### ISSUE TITLE
Best practice to include library into TA?

### ISSUE THREAD

**Issue by flottetotte** [OP-TEE/optee_os#1003]
Hello,

i would like to ask what's the best practice to add a library to a TA (note: cross compiling the library to be used in the user-space was not hard). As a naive start, i followed the discussion of this issue #901. However, i quickly noticed after cross compiling the lib (libgmp) and adding it like in the issues mentioned before, that when i try to actually compile the TA not all functions required (linking) by the library are there, for example (among others):
 
`/devel/optee/optee_os/out/arm/export-ta_arm64/lib/libgmp.a(printffuns.o):(.data.rel.ro+0x0): undefined reference to vfprintf
`

Of course one could adapt the library, but that seems to be a quite cumbersome task.
So is there some way to allow the TA to use user-space libraries directly?

Thanks!
Torsten

**Comment by jforissier** [comment]
You get an undefined reference to `vprintf` because `libutils.a` (which is more or less our C library for TAs) does not provide this function. The primary API that TAs are supposed to use it the _GobalPlatform TEE Core Internal API_. That is why we are not trying to provide a complete C library in `libutils.a`, although we do provide some well-known functions (you can see which ones with `$(CROSS_COMPILE)-nm libutils.a | grep " T "`). They are provided mainly to help implement the GP API.

A TA has to be fully statically linked, i.e., it can not use shared objects, let alone `.so` files from the normal world. But you might be able to use pre-compiled static libraries for your target.

Another option is to add the missing functions to `libutils`.

**Comment by vascoguita** [comment]
In the link bellow you may find a port of the GMP to OP-TEE:

https://github.com/vascoguita/optee_gmp

I know this issue was closed a long time ago but maybe this comment will help whoever comes across this issue looking for a way to include the GMP library into OP-TEE.

**Comment by jforissier** [comment]
@vascoguita thanks for posting the link :+1:

As a side note: the comment I made about shared libraries is no longer true; the GMP library could probably be compiled as a shared object if needed.
