### ISSUE TITLE
How to add dynamic 4k memory mapping for sg_table from REE side?

### ISSUE THREAD

**Issue by prime-zeng** [OP-TEE/optee_os#1004]
Here is our scenario：
1. Allocate the memory from the REE side(sg_table) using RPC from OP-TEE
2. Mark the returned sg_table memory blocks as Secure using the platform hardware.
3. Maping the sg_table in OP-TEE kernel space or TA memory space.

 Currently the op-tee memory are all fixed mapping and don't easily support the above scenario：
1. Add OP-TEE kernel VA space partition management.
2. Add kernel dynamic 4k page memory mapping.
3. Add TA dynamic 4k page memory mapping. 

So any suggestions?

**Comment by jenswi-linaro** [comment]
In order to understand the scenario better I have a few questions.
1. Why do you use an sg_table instead of plain virtual memory from `vmalloc()` or user space?
2. How will this memory be used, as a temporary parameter that will be unmapped when the call returns or some additional working memory or something else?
3. Why can't the memory be allocated with `tee_mm_alloc()` from `tee_mm_sec_ddr` instead?

**Comment by prime-zeng** [comment]
1. The component in the REE side use sg_table(dma_buf) , indeed , it maybe from vmalloc or user space, but it will turn to a chain of 4K pages from the physic memory view of point.

2. Additional working memory, for example, an encrypt video frame is passed to the  Secure Decoder TA in op-tee, the TA has to allocate secure buffer to process the video frame, on my platform, the secure is allocated from REE side using RPC, and marked as Secure in TEE side by platfrom hardware(TZASC etc). 

3. when we need memory in Secure side, we allocate from REE side,  and free after we have finished the secure task, when there is no secure task, the memory is used by REE side, it will save memory rather then reserve the secure needed memory at the right beginning.

**Comment by jforissier** [comment]
Typical use case for SMAF it would seem ;)

**Comment by prime-zeng** [comment]
I have also contacted with Benjamin, and he told me that SMAF is an allocation framework and don't cover the memory mapping, so i think we need more discussion about this case.

**Comment by jenswi-linaro** [comment]
When it comes to securing physically fragmented memory there will be some limitations from the TSASC with the number of available regions. The concept of carving out secure memory as it's needed looks interesting, but given limitations of TSASC and similar IPs I think it would be safer to use physically contiguous memory from for instance CMA.

Recently we added support for mapping user TAs with 4k page granularity, this includes the parameters. Due to some internal limitations of OP-TEE only physically contiguous memory is supported as parameters for a TA.

**Comment by prime-zeng** [comment]
We have got TZASC which can support none physically contiguous memory now.   So i 'd rather the OP-TEE support more flexible memory management, also the smmu tech may have to be introduced in the not far future, physically contiguous won't be a limit.

Of course ,it requires a lot of work to do that, but from my point of view, this is the right direction.

**Comment by jenswi-linaro** [comment]
I agree, that's the right direction. @lackan asked me some question related to physically non-contiguous memory in parameters a few weeks ago, it sounded like something he intended to work on.

**Comment by prime-zeng** [comment]
close it now, reopen when needed in the future.
