### ISSUE TITLE
Microbenchmark measurement

### ISSUE THREAD

**Issue by haleyyew** [OP-TEE/optee_os#1040]
Hi,
I'm currently developing an application and would want to know how well it performs. I would like to measure the time it takes to execute a program accurately without bias. Therefore I cannot include any C header files such as time.h to measure, because I do not know what exactly time.h measures. I am able to execute assembly instructions such as MRC and MCR to retrieve a value from performance counters, but I cannot convert the counter to seconds. 

I am emulating using QEMU. Has somebody who has done microbenchmarking before on QEMU tell me how to measure time in seconds?

Greatly appreciated.

**Comment by jforissier** [comment]
Hi @haleyyew,

Where do you want to take the measurements? In a linux application, in the linux kernel, in OP-TEE, in a trusted application...?

**Comment by haleyyew** [comment]
Hi @jforissier,

I'm currently measuring "world switching" time in the client side of the trusted application, in the normal world. Ideally, I also want to measure within the trusted application in the secure world.

Thanks.

**Comment by jbech-linaro** [comment]
@igoropaniuk , keep an eye on this discussion please.

**Comment by jforissier** [comment]
OK, so it's likely you will need a common reference between both worlds. I suggest reading CNTPCT and CNTFRQ.

**Comment by igoropaniuk** [comment]
Hi @haleyyew 
You can find example code of conversion  (values of CNTPCT/CNTFRQ timer registers, which @jforissier suggested to use) to seconds/milliseconds in  [tee_time_arm_cntpct.c](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/tee_time_arm_cntpct.c#L39 )

And, BTW, what exactly do you want to measure? The time of command passing through the overall chain
optee_client->linux kernel-> dispatcher -> optee_os->your Trusted Application ?

**Comment by haleyyew** [comment]
Thanks @igoropaniuk, I'm measuring in multiple granularities. The overall chain is one of the measurements, I also wanted to measure linux kernel-> dispatcher -> optee_os since we also built a kernel module. More specifically, we are measuring system calls, and how long it will take to perform a system call such as open() from a trusted application to the Supplicant, etc. 
I'll confirm whether CNTPCT/CNTFRQ is what we wanted.

**Comment by igoropaniuk** [comment]
I assume that measurements of latency for overall chain (optee_client->linux kernel-> dispatcher -> optee_os->your Trusted Application) could be affected by preemption, irq handling etc., so I'm not sure how much accurate and objective would such results be. Anyway it would be cool to research this.

BTW, we're already working on the benchmark framework for such measurements (I hope it will be released in OP-TEE 2.3.0), and I assume that we will also include some internal tests (that will run inside linux kernel/optee_os etc.) that will allow to measure latency for such operations like normal<->secured-world switches(performed by SMC call) etc.

**Comment by haleyyew** [comment]
Thank you for the update on OP-TEE 2.3.0, do you know when will it be released? We are aiming to finish our measurements within the next few weeks.

Thanks.

**Comment by igoropaniuk** [comment]
@haleyyew It will be released at the beginning of next year (to be more precise on 20 Jan 2017).

By the way, do you have any plans to share somewhere (on github in particular) details (ideas, code, measurement results etc., everything is valuable) of your research?
Because it seems that we are moving in the same direction, so it would be cool to collaborate ;)

**Comment by jbech-linaro** [comment]
And even though the release is that late in January, it will of course be merged as soon as it's ready. It's just that it won't get picked up by a stable tag until then. 2.2.0 will be released in about a month, but I'm not sure whether it's feasible to get this work done by then, that's why we're saying 2.3.0. But if it is done already this month, then we can of course tag the work with 2.2.0).

**Comment by igoropaniuk** [comment]
Hi @peterfeifanchen,
> 1) How do I measure the overhead (time) from operations launched in TA?

What exactly do you mean for the "overhead" here? A time of passing some cmd from linux_client to TA ?

> 2) How do I measure the world-switch + OP-TEE OS <-> Linux OS time? Does CNTPCT and CNTFRQ increment regardless of the world I am in, so that it can measure the time elapsed in OP-TEE from point of entry and exit from OP-TEE Linuxdriver? Is there some limitation I should be aware of?
Actually, we use this registers for getting timestamps in Secured World also.  

> 4) Is there a difference between using any of the four methods above? For example, I am assuming clock() would not good since it only measures cpu time and not the wall-clock delay?

Due to the man page for "clock_t clock(void)" this call based on clock_gettime, which uses the CLOCK_PROCESS_CPUTIME_ID clock by default, which represents the CPU-time clock of the calling process. I assume that this call is actual only if you want to measure a time in a context of some process, not system-wide. (see [clock_gettime.c)](http://git.musl-libc.org/cgit/musl/tree/src/time/clock_gettime.c) sources.

And by the way, for clock() we have a huge chain of calls with crossing the user-to-kernel-mode border back and forth.
time(libc)->clock_gettime(libc)->SYS_clock_gettime(syscall)-> __NR_clock_gettime->bunch amount of calls in kernelmode

By using directly CNTPCT and CNTFRQ you can avoid overhead for switches between usermode<->kernelmode (PL0 access to counters should be enabled in advance in kernel mode, "mcr p15, 0, 1, c14, 0") and will receive some kind of a common reference between both worlds (btw, I've already mentioned here that we use these registers for receiving timestamps in OP-TEE OS, see [tee_time_arm_cntpct.c](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/tee_time_arm_cntpct.c#L39) )

BTW, guys from ARM has already done similar basic testing [https://github.com/ARM-software/tf-issues/issues/354](https://github.com/ARM-software/tf-issues/issues/354), so I think you can also find some related information there.


> 5) In terms of interference, I am benchmarking this on QEMU32, so its single core and only my test program should be running. We were just going to run it couple of times and compute an average Is there anything else I should worry about?

SMC standard call can be preempted. The same applies to the code for both kernel/usemode of the normal world (optee_clien lib and optee kernel module). To avoid preemption of SMC you can use SMC fastcalls (they are atomic).

And, BTW, speaking about virtualized environments it's not clear to me how these timers(CNTPCT and CNTFRQ) are implemented in QEMU. I assume that CNTPCT timer will still run when QEMU is preempted by the host system (there is a strong possibility that its implementation is somehow based on the host hw clock). I need to refer QEMU sources to give you more comprehensible reply to this question.

**Comment by peterfeifanchen** [comment]
Hi @igoropaniuk. Thanks for the detailed reply. When I said overhead, I meant the time between a read/write/open/lseek/close operation for the system I built and the original read/write/open/lseek/close system calls. I was trying to see if I can get that overhead broken down into different components: (1) time spent in kernel, (2) world switch, (3) time spent in the OP-TEE OS, (4) time spent in my TA (breakdown the time cost of each policy evaluation that TA  can carry out). 

It sounds like the CNTPCT and CNTFRQ is the one that I should go for. But as an aside, would you recommend performance counters?

> BTW, guys from ARM has already done similar basic testing ARM-software/tf-issues#354, so I think you can also find some related information there.

I took a look at this and saw below.

> The test runs at EL2. It performs the following actions:
> 1. Take a first timestamp by reading the Counter-timer Physical Count register (i.e. CNTPCT_EL0).
> 2. Send the PSCI_VERSION SMC.
> 3. Get the result back.
> 4. Take a second timestamp.
> 5. Compute the time elapsed between the 2 timestamps.

Just wondering if I am understanding it correctly: 

(1) They performed this test from the optee-linuxdriver and because of the low amount of processing on the PSCI smc call, this can be a good proxy for world switch? 
(2) How did they send PSCI_VERSION SMC command through the optee-linuxdriver? In optee-linuxdriver, the smc call is launched from tee_smc_call() which takes a smc_param. When this goes into the ARM TF, it is handled by opteed_smc_handler(). But the PSCI_VERSION need to be directed to the psci_smc_handler(). The selection seems to be done in the assembly at smc_handler32() which finds the right RT_SVC. But it is not apparent to me, how when optee-linuxdriver calls tee_smc_call(), how it specifies the opteed_smc_handler vs. another service handler. Is this a question for OP-TEE people or better for the ARM-TF people?

**Comment by peterfeifanchen** [comment]
Also, does anyone know if the performance counter registers, specifically PMCCNTR,  PMCNTENSET, PMOVSR, PMCR are banked or are common to both Secure and Normal World?

**Comment by jforissier** [comment]
For all the registers you are mentioning, according to the ARM-v7A ARM: "In a VMSA implementation that includes the Security Extensions, this is a Common register."

**Comment by jbech-optee-adm** [comment]
We're working actively with benchmark implementation, please try to have a look and follow along with the pull requests related to this. Based on that, we're closing this issue since we feel that the question has been answered now. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.

**Comment by yilingxu** [comment]
Hi, I'm working on imx6q, and I want to know  the time it takes to boot optee os. Specifically, my boot sequence is uboot->optee os->linux os. From example, if uboot->linux os tasks 20ms, and uboot->optee os->linux os tasks 25ms, then I can can know it takes 5ms to boot optee os. 

I think there are two ways to get this time:
1. uboot print timestamp1 before it switch to optee os, and optee os print timestamp2 before it switch to linux os, then timestamps2-timestamp1 is the time it takes to boot optee os. By now I only find get_timer(0) in uboot to return the number of milliseconds since the Timer initializated, but not the number of millseconds since Epoch.
2. If optee os has similar faction like get_timer(0)  to return the number of milliseconds since optee os boot? If it has, I just need to call this function before optee os switch to linux os, then I can know the time it takes to boot optee os.

Thanks,
YIling Xu

**Comment by jbech-linaro** [comment]
@yilingxu , the [current benchmark framework](https://optee.readthedocs.io/debug/benchmark.html) can do things related to what you are looking for, however, we have never used it during boot. We've only used it when the system is fully up and running. OP-TEE doesn't have a function like the one you're asking for. Maybe you can use the Arm generic timers or PMU directly to get some numbers.
