### ISSUE TITLE
cache invalidate in CFG_PL310_LOCKED is wrong when used with CFG_WITH_PAGER

### ISSUE THREAD

**Issue by yanyan-wrs** [OP-TEE/optee_os#1045]
In generic_entry_a32.S:

```asm
    /*
     * In case we've touched memory that secondary CPUs will use before
     * they have turned on their D-cache, clean and invalidate the
     * D-cache before exiting to normal world.
     */
    ldr r0, =__text_start
#ifdef CFG_WITH_PAGER
    ldr r1, =__init_end
#else
    ldr r1, =_end
#endif
    sub r1, r1, #1
    bl  arm_cl1_d_cleaninvbyva

#ifdef CFG_PL310
    bl  pl310_base
    ldr r1, =__text_start
#ifdef CFG_WITH_PAGER
    ldr r2, =__init_end
#else
    ldr r2, =_end
#endif
    sub r2, r2, #1
    bl  arm_cl2_cleaninvbypa

#endif

#ifdef CFG_PL310_LOCKED
    bl  pl310_base
    bl  arm_cl2_lockallways
    bl  pl310_base
    bl  arm_cl2_invbyway
#endif
```

The last 'bl    arm_cl2_invbyway' should be 'bl arm_cl2_cleaninvbyway'. If configured with 'CFG_WITH_PAGER', it wrongly invalidates the pageable content.

**Comment by jenswi-linaro** [comment]
I agree, looks like to bug to me too.

**Comment by etienne-lms** [comment]
I don't think there is an effective bug.
I think `CFG_PL310_LOCKED` is required only on armv7 with an outer cache. optee/armv7 does not rely on another "secure" stack (as a-tf) that would use secure cache and provide runtime service. Hence, when optee boots, there is no other running SW stack that expects cache to be functional.

This "locked" think allows non-secure world to enable (resp. disable) the outer without invoking secure world, knowing that the PL310 cannot allow non-secure to write to the PL310 enable bit.
Nonsecure to enable (resp. disable) outer cache by unlocking all ways (resp. locking and invalidating all ways). Once "PL310 locked" sequence is done, the pl310 is expected to behave as if is was disable: all ways must be locked.

Current implementation invalidates all ways, after having locked them.
It could flush all ways instead of invalidating them.
A alternate implementation could lock the ways and not flush or invalidate them, only insure ways, once locked, are filled with secure tags before cpu switch to the non-secure boot sequence, where outer cache is expected default OFF (but that non-secure cannot enable itself).

**Comment by yanyan-wrs** [comment]
The problem here is not the lock operation itself, but the invalidate; to me invalidating cache without first cleaning the contents is always a dangerous operation.
As you can see, there is an `arm_cl2_cleaninvbypa' before, and when CFG_WITH_PAGER is not set, this clean and invalidate applies to `__text_start` to '_end', which is the whole executable, thus the subsequent invalidate would not cause any problem; however, when CFG_WITH_PAGER is set, the clean and invalidate only covers the init non-paged part, leaving the pageable part still in the cache. So, a subsequent cache invalidate would corrupt the paged part because valid data are in the cache and are discarded.

**Comment by etienne-lms** [comment]
optee is expected to be booted with cache off, no ?
Hence, on armv7, when optee is entered i would expect cache does not hold any useful content.
Then optee moves some 'unpaged' areas in RAM and flushes the cache.
Hence i would expect cache is "clean" when PL310 is locked in generic_entry_a32.S, and a 'invalidate all cache ways" is armless. The pagable content is expected already in the RAM, not in cache lines.

Yet, i think to prevent any later issues, maybe we should change the current code.

alternate#1: replace current sequence with:
```
 #ifdef CFG_PL310_LOCKED
     bl  pl310_base
     bl  arm_cl2_lockallways
     bl  pl310_base
+    bl  arm_cl2_cleaninvbyway
-    bl  arm_cl2_invbyway
 #endif
```

alternate#2: change outer cache enable sequence:

Before `core_init_mmu_map` is called, at `bl arm_cl2_enable`, we can a `arm_cl2_invbyway`+`arm_cl2_lockallways` (if `CFG_PL310_LOCKED`) to get cache enable/locked straight. This however would prevent the memory copy of pageable content (in `init_runtime()`) from benefiting of the outer cache.
