### ISSUE TITLE
With CFG_WITH_PAGER, if SRAM size is large enough, it is mapped using 1M page and conflicts with pager's requirement of 4K page

### ISSUE THREAD

**Issue by yanyan-wrs** [OP-TEE/optee_os#1049]
pager cannot use large page, so there is some special handling in `init_mem_map`:

```
#ifdef CFG_WITH_PAGER
    map->region_size = SMALL_PAGE_SIZE,
#else
    map->region_size = CORE_MMU_PGDIR_SIZE,
#endif
```

however, this is overwritten in `map_memarea`, which just uses large mapping if the area is well aligned and large enough.

It can be reproduced by setting the emulated SRAM area to 1M (for non-LPAE targe), and aligned at 1M boundary.

**Comment by etienne-lms** [comment]
true.
- reduce your SRAM by 4kB to loose alignment and benefit from... almost all SRAM ?
- change core_mmu.c to add a "force 4KB mapping" attribute to the TEE_RAM maparea ?
- change core_mmu.c to specifically force TEE_RAM to be mapped with 4KB pages ?

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered and we have no plans to change the current behavior (if you have a patch resolving this limitation, feel free to send it as a pull request). If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
