### ISSUE TITLE
Can i remove the limit that the optee driver only accepts one process ?

### ISSUE THREAD

**Issue by prime-zeng** [OP-TEE/optee_os#1051]
@jenswi-linaro   i want to add my own rpc, and process it in my own process, but i noticed that the optee driver only accepts one process from the your PATCH v10, any suggestion about this?

**Comment by jenswi-linaro** [comment]
Doesn't it work to modify tee-supplicant?

**Comment by prime-zeng** [comment]
The rpc is needed by the third party, so it is very complex to do it in tee-supplicant(process communication is needed, i think).

**Comment by jenswi-linaro** [comment]
Another option would be to support dynamically registered plugins (see `man 3 dlopen`) in tee-supplicant.

**Comment by jbech-optee-adm** [comment]
We have no plans on changing the current behavior as of now even though we recognize the limitation. If you have any design proposal or proof of concept code, we're more than willing to discuss it.

Based on this answer, we're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
