### ISSUE TITLE
Question - OPTEE performance?

### ISSUE THREAD

**Issue by marduino** [OP-TEE/optee_os#1061]
Hi,

I want to know how long does it take from a message is sent by android application to OPTEE response? As well as the opposite direction.

I would also would love to know other OPTEE related performance information. Is there any report for that? How can I find that?

Thanks!

**Comment by jbech-linaro** [comment]
Hi @marduino , I think what you're asking for is currently being discussed in #1040 . So, this is something we're working with as we're speaking. As an example, there went a performance tool for AES and SHA into xtest just a couple of days ago. With that done the next step is to look into what's been discussed in #1040.

**Comment by marduino** [comment]
Hi @jbech-linaro, thanks, that is really clost to my request. I would love to have a official benchmark as a reference, instead of having the testing tools or individually tested results.

**Comment by marduino** [comment]
Hi @jbech-linaro, sorry, I mean can we find official tested performance reports?

**Comment by jbech-linaro** [comment]
Hi @marduino, sorry we have no official test results yet. That's part of the ongoing work.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. Please try to follow along what is happening on master branch of OP-TEE gits. If everything goes according to the plan there will benchmark functionality coming in the near future . If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
