### ISSUE TITLE
On the issue of interruption

### ISSUE THREAD

**Issue by yymxx** [OP-TEE/optee_os#1074]
hello linaro：
         When the SMC call, TA did not process the end of the process, Linux was blocked, then Linux can respond to interruption? what should I do.

**Comment by jenswi-linaro** [comment]
You mean the TA execution was interrupted and the execution won't continue because the Linux kernel doesn't process the interrupt? If that's the case I suspect you're doing the SMC with IRQ masked. If it's not possible to unmask IRQ before doing the SMC you can't call a standard call at that place in the code. This is because standard calls unmasks IRQ while in secure mode.

Regards,
Jens

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
