### ISSUE TITLE
static TA question

### ISSUE THREAD

**Issue by ggao-inven** [OP-TEE/optee_os#1079]
Hi,
  Can I call TEEC_OpenSession TEEC_InvokeCommand etc. inside Linux Kernel? The idea is that we will receive interrupt to the normal world. Once we receive the interrupt, inside Linux Kernel, we want to send command to a static TA and ask it to do the processing, such read and write data to a hardware device.
  Is this possible? I checked the optee driver code, it seems does not like we have something do that. Maybe I missed something. So my question is do we have to call TA or static TA from the user space of the normal world. Can we call TA or static TA from kernel space? If we can, what is the corresponding API of doing that?
  Thanks.

Best Regards,

Ge Gao

**Comment by etienne-lms** [comment]
Hello Gao,

There is an API available in the [linaro-swg linux kernel](https://github.com/linaro-swg/linux) to invoke a TA from kernel land. As it is 'linux kernel' coding style, it does not conform to the GP TEE Client API specs, but it is functional.
!!! Be aware that this API is not yet official, not yet upstreamed, and it may change in the future !!!
You can find [here](https://github.com/etienne-lms/linux/commit/89e66efb27d927ba1f6f54f54a7274f5759e5b13) an example of a driver that uses this API to invoke a TA. You can use it as an example:
- get an optee context: ` tee_client_open_context()`
- open a session: `tee_client_open_session()`
- allocated shared memory: `tee_shm_alloc()`
- invoke a TA with parameters: `tee_client_invoke_func()`

That said, this implementation might not fit your needs: linux MUST unmasked IRQs before invoking a TA (see Jens' recent comment on https://github.com/OP-TEE/optee_os/issues/1074). Hence take care to invoke your TA from a kernel thread/work/whatever with IRQs unmasked.

Maybe you should rather configure your interrupt line as a secure interrupt so that it is fully trapped and handled in a secure interrupt handler. Note however that you will not be able to invoke a TA from such an op-tee interrupt handler.

Regards,
etienne

**Comment by ggao-inven** [comment]
Thanks. I will try it out.

Regards,

Ge

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
