### ISSUE TITLE
Config issue: conflicts with user ta address!

### ISSUE THREAD

**Issue by bafATsit** [OP-TEE/optee_os#1118]
Hello,

I need a little help for my `platform_config.h`.

When booting `optee_os` I get errors:
> ERROR:   TEE-CORE: va 0x100000 conflicts with user ta address!
> ERROR:   TEE-CORE: PANIC: map_memarea core/arch/arm/mm/core_mmu_v7.c:594

I don't see any overlapping in my memory config:

> /** platform_config.h **/
> #define DRAM0_BASE		0x00100000
> #define DRAM0_SIZE		0x1FEFFFFF
> 
> /* Location of trusted dram */
> #define TZDRAM_BASE		0x00100000
> #define TZDRAM_SIZE		0x04000000
> 
> #define CFG_SHMEM_START		0x04100000
> #define CFG_SHMEM_SIZE		0x04000000

Do I miss any important #define config?

Thank you

**Comment by jenswi-linaro** [comment]
When using the v7 legacy mapping the lower 32 MiB virtual memory is reserved for user space mapping. From your defines it looks like you need to map OP-TEE core somewhere in that range. There's basically two options, trying to have the secure memory at a different physical address or to use `CFG_WITH_LPAE=y`. With LPAE user space is mapped at some free memory range instead of this fixed range.
