### ISSUE TITLE
Installing apps on OP-TEE (QEMU)

### ISSUE THREAD

**Issue by jsherman3** [OP-TEE/optee_os#1129]
Hello,

I currently built the newest version of OPTEE and ran xtest and everything ran as expected. Next I compiled the hello_world example for 32 bit platforms. I'm just curious how do I actually install these files on QEMU?

**Comment by jbech-linaro** [comment]
Hi, it might look a bit complicated, but for the CPIO based root fs we're using in QEMU, you basically need to update the filelist.* files so that it pick up your host application and the TA also. In our helper makefiles this is done here for the Hello World TA:
https://github.com/OP-TEE/build/blob/master/common.mk#L280-L286

It's not any just "OP-TEE only magic", this is just we're using the CPIO archive/tool, so make a small and simple root fs.

**Comment by igoropaniuk** [comment]
Hi @jsherman3. It's also worth to mention that there are some limitations of the final CPIO size(out/bios-qemu/bios.bin, that consists of rootfs cpio+tee.bin+zImage), it should be less than 64mb, because you will face the issue described in https://github.com/OP-TEE/optee_os/issues/1094

It's just FYI, if you are going to store some huge files there

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
