### ISSUE TITLE
OP-TEE on Freescale Mars Board i.MX6

### ISSUE THREAD

**Issue by klemtax66** [OP-TEE/optee_os#1142]
Hey guys, 
what is the easy way to port OP-TEE to Freescale Mars Board i.MX6?
http://www.embest-tech.com/shop/star/marsboard.html

What I need is:
U-Boot (Secure Boot)
OP-TEE (Secure Wolrd/Normal World)

best regards
Michael K.

**Comment by jbech-linaro** [comment]
Hi Michael, 

So, even though I'm in Linaro I haven't explicitly worked with Freescale boards, but currently there are three IMX.6 devices already supported. So due to that I'd image it would be quite easy to get it up and running.
https://github.com/OP-TEE/optee_os#3-platforms-supported

Platform support is general not a big thing, as an example, here is the complete patch for porting OP-TEE to Raspberry Pi 3: https://github.com/OP-TEE/optee_os/commit/66d9cacf37e6bd4b0d86e7b32e4e5edefe8decfd

**Comment by jforissier** [comment]
+1 to what @jbech-linaro said.

For the things specific to your board, you may define your own "platform flavor" and adjust the content of the `plat-imx` directory. Let's say you call you flavor `mx6mars` for instance (we already have: `mx6ulevk`, `mx6qsabrelite`, `mx6qsabresd`). Then you would build with `make PLATFORM=imx-mx6mars`.
Assuming this:
- in C files, you can do: `#if defined(PLATFORM_FLAVOR_mx6mars)`
- in Makefiles: `$(PLATFORM_FLAVOR_mx6mars)` will be set to `y` and `$(PLATFORM_FLAVOR)` will be `mx6mars`.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
