### ISSUE TITLE
Interrupt behavior Question

### ISSUE THREAD

**Issue by acy54321** [OP-TEE/optee_os#1143]
Hi optee expert

In optee os if have any mechanism, when interrupt(Fiq) occur can notification each runing TA ??
Because I want to implement an alarm mechanism, but now I can't found method call  each runing TA .

**Comment by jenswi-linaro** [comment]
Hi,

No there's no standard way to notify a TA that an FIQ has fired.

Regards,
Jens

**Comment by jbech-optee-adm** [comment]
As Jens said, nothing like that currently exists in OP-TEE and as of now we have no plans adding that. I've you however have a design proposals or a proof of concept that you'd like to discuss, we're more than happy to be part of it. If so, please either re-open this issue or send a "[RFC"] pull request.

Basesd on this. I'm closing this issue since the question has been answered.
