### ISSUE TITLE
On elf file loading and optee the memory layout

### ISSUE THREAD

**Issue by yymxx** [OP-TEE/optee_os#1152]
hello
      I have two questions: The first is how to load elf into optee, is the use of the mmu mechanism? How the system function table is associated. The second question is also due to the first issue, should not find optee memory-related documents, do not know elf file loading time, data segment, code segment stored in that position. The dynamic loading of a ta has been bothering me a long time. Hope to get your help, look forward to your reply

**Comment by etienne-lms** [comment]
hello @yymxx,

Actually optee core cannot load any ELF as a Trusted Application. TA binary files are indeed ELF formatted file with an authentication header binary blob. The authentication blob is verified before TA is loaded, then it is dropped. Remains the TA ELF binary image.

Best to understand the TA section layout is the read the linker file `ta/arch/arm/ta.ld.S`.
Note the `.ta_head` section: it contains some TA function addresses so that TEE core knows where to go when it invokes TA code. TA entry point (from tee core view) is always `__utee_entry()`, see `ta/arch/arm/user_ta_header.c` and `lib/libutee/arch/arm/user_ta_entry.c`. TEE core use this entry point the call TA request: open/close session, invoke a command.

Regarding the load of the ELF segments of a TA, I think the best remains to check `core/arch/arm/kernel/elf_load.c`. It contains the sequence for ELF loading and post-processing. It is a bit specific and expects some segments ordering.

**Comment by yymxx** [comment]
Thank you very much for your reply. I do not understand how the translation is ta, I understand optee os as a dynamic library, each time will be compiled with optee_os together translated into. Otherwise, I can not understand how the procedure is aware of the system symbol table.

**Comment by etienne-lms** [comment]
optee_os is not a library.

optee_os is made of 2 things: the TEE 'core' and the resources to build Trusted Applications.

TEE 'core' operates in ARM CPU 'priviledge mode', and Tursted Applications execute in 'user mode'. Trusted Applications call TEE 'core' services through system calls (SVC, old SWI). No linkage.

When you build optee_os, you generate:
- a `tee.bin` file: the optee 'core' image, loaded/executed in secure RAM.
- a directory `export-ta_armXX/` with some prebuilt libraries.

When you compile your own Trusted Application(s), you compile your own code, you link it statically with the 'user TA libraries' (provided by  optee `export-ta_armXX/`) and then you post-process the generated ELF file to add signature info. At load time, the Trusted Application will NOT link with TEE 'core' or other libraries. The load Trusted Applications are each statically linked.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
