### ISSUE TITLE
How can i hold a tee mutex while executing in REE environment?

### ISSUE THREAD

**Issue by prime-zeng** [OP-TEE/optee_os#1176]
Hello:
I have the following usage of op-tee mutex;
------- CA-------------|--------------TA------------
  invoke command -------->mutex_lock(&xxxlock);
  ...............................
  invoke command--------->mutex_unlock(&xxxlock);
But now the op-tee will assert in the thread_state_free, i can fix it by removing the thread_add_mutex  and thread_rem_mutex.
And i don't quite understand the role of thread_add_mutex  and thread_rem_mutex, and can i just remove them?

**Comment by jenswi-linaro** [comment]
You should not exit from OP-TEE core (either to user TA or as a return from thread, exit for RPC is OK) with a mutex held. Compare with mutexes in the Linux kernel.

**Comment by prime-zeng** [comment]
I want to lock some TEE resource from REE side, so i can't do it if i release the mutex when exit the OP-TEE core,  can we attach the mutex to ta context instead of thread.   In linux side, i think user application can hold a kernel mutex  when exit the kernel space.

**Comment by jenswi-linaro** [comment]
No, you shouldn't return from a syscall in Linux with a mutex held. Using a mutex as you suggest could deadlock the system, that's why mutexes should be released before returning.

Let's assume that we can only support 2 threads in secure world:
CA 1 calls the TA to lock the mutex and returns.
CA 2 calls the TA to lock the mutex and blocks -> thread 1 busy.
CA 3 calls the TA to lock the mutex and blocks -> thread 2 busy.
CA 1 calls the TA to unlock the mutex, but fails as all threads are busy -> deadlock.

**Comment by prime-zeng** [comment]
Yes, you are right,  there are limited threads for TEE, but for syscalls in linux, i think no limit.

**Comment by jenswi-linaro** [comment]
OK, I may be wrong about the Linux case.
Any way we have a locking situation similar to what you have with `tee_ta_try_set_busy()` and friends.

**Comment by prime-zeng** [comment]
@jenswi-linaro thank you, tee_ta_try_set_busy is a good solution to work around.
