### ISSUE TITLE
About the TEE file renaming attack detection

### ISSUE THREAD

**Issue by lackan** [OP-TEE/optee_os#1177]
Hi,

In the secure storage future work, there offer a solution:
1,Use TEE filename as AAD when calculating the tag of meta file
so I think the completion may like this：
![image](https://cloud.githubusercontent.com/assets/14136466/20203864/dd2677f8-a805-11e6-823f-f81f265ad929.png)

And we think about the other two solution, and want to discuss which is best:
2,Add TEE filename in Meta Data like this:
![image](https://cloud.githubusercontent.com/assets/14136466/20203831/a96bf7bc-a805-11e6-8ddf-e782987a632d.png)

3,Add TEE filename in TSK:
Now the TSK is generate by `HMAC(SSK, TA_UUID)`, after adding the filename, it may be:
`TSK = HMAC(SSK, TA_UUID | filename)`, "|" means concatenate.

What do you think about this?  And I also find some little problem in secure_storage.md, the picture describe Meta Data Encryption Flow haven't yet change SSK to TSK, and Trusted Application Storage Key (TKS) have mistaken TSK to TKS.

Thanks.

**Comment by jbech-linaro** [comment]
@lackan , this will be taken care of in the already ongoing work by @jenswi-linaro. It will be solved in a different manner than what you proposed, but it will prevent people from making unnoticed name changes. Since I'm trying to clean up open issues and this seems to be covered I wonder if it would be OK for you if I close this issue?

**Comment by lackan** [comment]
@jbech-linaro Yes, sorry to reply late, I'm happy to see Jens work it well. I close it now.
