### ISSUE TITLE
How to flash the hikey on docker

### ISSUE THREAD

**Issue by Hackhao** [OP-TEE/optee_os#1191]
I want to flash the hikey board on docker, but I can't find the devices.

Docker configuration: `-v /dev:/dev`
Error occurred after running `make recovery` : `Device not detected under /dev/serial/by-id/. Please use -d.`

Please help me~ Many thanks!

**Comment by vchong** [comment]
First can you find it on your host OS? E.g. `/dev/ttyUSB0`?
If yes, then try running docker with `--device=/dev/ttyUSB0`.
You might also need to add `-d /dev/ttyUSB0` to https://github.com/OP-TEE/build/blob/master/hikey_debian.mk#L364, i.e.
`sudo python $(ROOT)/burn-boot/hisi-idt.py -d /dev/ttyUSB0 --img1=$(LLOADER_PATH)/l-loader.bin`

**Comment by Hackhao** [comment]
Many thanks for the prompt reply!
I can't find `/dev/ttyUSB0` on my host OS(Mac OS) after connecting my board. 
I used to flash my hikey board on Ubuntu 16.04 running in Parallels.
I think there should be a way to flash my board on Ubuntu 16.04 running in Docker. If not, Can I find a way to flash my board on Mac OS, directly.

**Comment by vchong** [comment]
You're welcome!
The Mac uses a slightly different notation, e.g. `/dev/tty.usbserial-ABCDE1FG`.
However, unfortunately, you'll not be able to do this on the Mac. This is not a Docker problem. The problem is that there are **no** drivers available for both Mac and Windows machines, so the device will not be recognized in the host. And if the host doesn't see the device, then it wouldn't be able to present it to the guest to instantiate.
If you insist on using a Mac for development, you'll have to transfer the necessary output files to a Linux machine and flash manually. Sorry.

**Comment by Hackhao** [comment]
This is exactly what I want to know. Thanks for the information！
