### ISSUE TITLE
OP-TEE Kernel Function Question

### ISSUE THREAD

**Issue by SimonWan** [OP-TEE/optee_os#1205]
Hi experts,

I'm using the Juno board and I want to know is there any kernel function of OP-TEE OS could work as the `printk`. If there is, how could I call it in a static TA and where I could check the output?

I'm also wondering is there any way for me to dynamic load a secure kernel program (with the same privilege as static TA) into OP-TEE when the entire system is working? 
If there is no developed solution, do you have any idea about what modification I need to do for achieving the dynamic load?

Thank you very much.

Simon

**Comment by jenswi-linaro** [comment]
Hi Simon,

By `printk` I guess you mean all those funny %-extensions it has? Then the answer is no. Otherwise use `EMSG/DMSG` etc.

Loadable static TAs is not a direction we'd like to take for a number reasons:
1. For a given platform you already which static TAs that platform requires so it can be compiled in in advance.
2. With dynamically loadable modules we would get added complexity. A bit weak argument as it's not that complicated. We've even had this capacity in the past in what later became OP-TEE.
3. I'm not sure a vendor can trust a third party enough to allow execution of arbitrary secure kernel code.
4. We'd need to deal with incompatible ABI in some way or the other, we would probably choose the Linux kernel route though.

Regards,
Jens

**Comment by SimonWan** [comment]
@jenswi-linaro thank you for answering my questions.

I'm also wondering where is the code about the page table of secure OS? Does the `pager `work as the page table? 
I found this root [mm](https://github.com/OP-TEE/optee_os/tree/master/core/arch/arm/mm) while I'm not really sure about it. 

Also if I write from the S-EL1, can I read/write the page table of OP-TEE?

Thanks.

**Comment by jenswi-linaro** [comment]
The pager is an optional component that implements demand paging into secure memory. It's only needed if the secure memory is too small to fit the entire OP-TEE.

`core/arch/arm/mm/core_mmu*` deals with most of the table updating.
