### ISSUE TITLE
fastboot needs administrator permission in Ubuntu

### ISSUE THREAD

**Issue by sylvainpelissier** [OP-TEE/optee_os#1211]
During installation, to flash images to the board using ```make flash ```, fastboot is called with the user permission making to wait indefinitely with the message:
```
< waiting for device >
```
But calling fastboot with sudo, make it flashes the device properly using Ubuntu distribution.

**Comment by jbech-linaro** [comment]
For flashing `make flash`, IIRC you should not need to run using sudo, it's been a while since did a workaround for that, have you checked that you have the correct udev rules on your machine?
https://github.com/OP-TEE/build/blob/master/hikey.mk#L391-L394

However, I think when you're making the `ptable` I still think you need to run using sudo, but that is a build step and not the flash step.

Start by trying to add the udev rule as described above.

**Comment by sylvainpelissier** [comment]
With the udev rule it worked fine. Thanks.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.

**Comment by Devil0308** [comment]
fastboot need user permission in windows
