### ISSUE TITLE
Trusted Application 

### ISSUE THREAD

**Issue by Hackhao** [OP-TEE/optee_os#1230]
I want to find out why there are two types of TA, I mean static TA and  dynamic TA.
I think making all TA as static ones is safer than loading them from the normal world.

Please help me~ Many thanks!

**Comment by jforissier** [comment]
Hi @Hackhao,

There are two types of TAs because they address different needs. Static TA run in "kernel" mode (secure PL1/EL1) in the same address space as the TEE core. They are statically linked with the TEE core binary (hence their name). They can access everything the TEE core can access, including the hardware. On the other hand, dynamic TAs are loaded at runtime. Since they are files in the normal world filesystem, they are in principle easier to upgrade.They run in user mode (secure PL0/EL0), each TA has its own VA space. They cannot access hardware resource directly, instead they must invoke the TEE Internal Core API. 

Dynamic TAs are signed so unless the private key is compromised or there is some weakness in the implementation, they should be safe.

**Comment by etienne-lms** [comment]
@Hackhao: one few words: "static TAs are not Trusted Application". They are not even applications.

A "static TA" is an "OP-TEE core" service hidden behind the GP TEE main interface API: 
* open a session
* invoke a command
* close the session

OP-TEE core services implemented as a "static TA" can be called from a Trusted Application, from the NonSecure world and from another "static TA". "Static TAs" are currently used in OP-TEE for embedded tests as well as for platform specific services.

**Comment by Hackhao** [comment]
I see. Many Thanks!
