### ISSUE TITLE
Using OP-TEE 

### ISSUE THREAD

**Issue by jonpe960** [OP-TEE/optee_os#1231]
I'm not sure if this is the correct place to ask questions about op-tee, I could not find any forum.

I've successfully tested op-tee on my custom, IMX6UL -based board, the xtest -tool reports that all test cases were successfull.

I have little experience with TrustZone/TEE etc. and I'm trying to wrap my head around what I need to do. What I want in the end is communicate with a server using openssl (or similar) and authenticate software components and updates on the system (Using a TEE).

My best guess is that I need the following:

 o a TA that manages the keys in OP-TEE, and possibly utilizes the CAAM -block of the IMX6UL
 o Encrypted keyring in the RPMB partition
 o openssl-engine to interface OP-TEE and the TA
 o tools to initialize the OP-TEE/TA environment, for example in production I would like that the TA generates the key pairs and program the secret part into fuses. The factory initialized key pair would then be used to sign hash'es and encrypt keychains that only the TA can open

Am I on the right track? Do I need to develop all of these things my self or are there already available setups that could solve my problem? 

//Jonas

**Comment by jforissier** [comment]
Hi Jonas,

First, a disclaimer: let me say I have no experience actually implementing the scenario you are describing. But, as far as I can tell, you are on the right track.

Using the hardware crypto engine is a good idea, especially if it supports one or more write-only key(s), i.e., keys that cannot be extracted by software. You will need to write a driver for that, however, because hardware cannot be accessed by a regular TA running at PL0 (well you could write a pseudo-TA, a.k.a. "static TA" and program the crypto block directly, but that's not recommended for several reasons). Then you can use the CAAM via your driver to secure the RPMB authentication key and the secure storage key (SSK).

As for your last question, I am not aware of sample code that would be publicly available.

**Comment by jonpe960** [comment]
Hello, thank you for the feedback :)

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
