### ISSUE TITLE
OPTEE 2.0 tee-supplicant issue

### ISSUE THREAD

**Issue by SimonWan** [OP-TEE/optee_os#1233]
Hi experts,

Today I was trying to use the latest OPTEE version to replace my previous one (v1.1.0) and I met one issue about tee-supplicant.

I used the initialization script from [ARM community](https://community.arm.com/docs/DOC-10804) with the choice "Juno, latest, openembedded".

Now I have booted up my board with the new system. 
I could successfully run the command `modprobe optee_armtz` while I got the error `-sh: tee-supplicant: command not found`  when I was trying to use the command `tee-supplicant &`.

Is there anything I missed? 

By the way, now I'm following the instruction of [optee_test](https://github.com/OP-TEE/optee_test) for running TA. 
If you have any other document about running a TA on latest OPTEE, please let me know so I could check the document by myself.

Thank you.

Simon

**Comment by jbech-linaro** [comment]
optee_test instructions? I'm sorry to say that the information there is a bit dated, you should not need to modprobe anything if you're running latest as described on our pages (optee_os/README.md). The driver will be built into the kernel in those setups.

Having that said, we're currently restructuring information in various pages, since some information unfortunately has become outdated. I've just a week ago or so updated the [FAQ](https://github.com/Linaro/website/blob/master/Linaro.org/initiatives/OP-TEE/faq.md#2-building) that should end up at optee.org any day. But the link I gave you will get a preview of that update, there you can find quite useful information about what devices, builds etc we're running. If tests are known to fail etc. Unfortunately OE builds are something we very seldom do in my team (mentioned in the FAQ too). But I happen to know that that team at Linaro (Builds & Baselines) successfully built OP-TEE on their OE builds just a week ago. How ARM are doing their builds I have no clue. By reading the link you gave I can tell that I don't recognize the scripts etc that they are using, so it's probably better so ask them in this case. Sorry for not being able to give better support this time.

**Comment by SimonWan** [comment]
@jbech-linaro thanks. I'll post my question at the ARM website.
