### ISSUE TITLE
Problems when reading memory in the normal world

### ISSUE THREAD

**Issue by holmastoo** [OP-TEE/optee_os#1249]
Merry Christmas!
I have a problem when I want to use a static ta to read memory in the normal world. The test program in the normal world  gives its address to the corresponding ta, and when the ta tries to access the address of the  program code in the normal world, it outputs "Error: TEE-core: Panic". My testing platform is qemu. Does anyone know the reason and how to solve it? 
Thanks,

**Comment by igoropaniuk** [comment]
Hi @holmastoo,
Merry Christmas to you too! :)

Could you please explain in details what's the problem you are trying to solve (just the whole picture)?

A bit of additional questions: 
1. What tasks your static ta is going to perform and why have you decided to use static TA instead of regular one? 
2. Why do you need access to "the program code" of the NW app?

Thanks

Best regards,
Igor

**Comment by vchong** [comment]
Also see previous related issues:
https://github.com/OP-TEE/optee_os/issues/803
https://github.com/OP-TEE/optee_os/issues/477

**Comment by holmastoo** [comment]
Hi, @igoropaniuk and @vchong 

Thank you so much for answering! 

1. The problem is that I'm trying to use the TA to monitor what code was running just now. The CA give its address to the TA and TA checks whether it executed the right code.

2. The reason why I use static TA is that I thought dynamic TA may not have authority to access all the memory in the normal world, and static TA has this ability. But obviously what I thought is wrong.

3. The reason why I need the access is I want to know exactly the running state, or in other words, know whether the code is same as what I expect.

4. I have read the related issues, and I think the solution may be this:
      a) Translate the virtual address in the NW to the physical address.
      b) Map the physical address to the SW, by adding an entry to the bootcfg_memory_map[ ] or changing  the function tee_mmu_kmap_helper().
      b) Translate the physical address to virtual address in the SW and TA can access it.
      Is my understand right? And another question, where is the translation table located? I think it is in the optee_os/core/arch/arm/mm/ directory but I still can't find it.

Best regards,

**Comment by etienne-lms** [comment]
@holmastoo, I see several issues in the setup you plan to use:
- each execution of your CA (in NW) is likely to be loaded at new unpredictable physical addresses. Hence such addresses cannot be statically defined in your TA.
- your CA is likely to be loaded in non-contiguous physical memory areas (pages), you will need to get and convert each of them, not a unique buffer.
- Main issue, I think, is that linux may decide to change your CA physical location during CA execution due to the linux kernel paging and swapping support, especially in case of high memory load in linux world. Physical page can be allocated, loaded and released at run-time even while an application is running. So it is quite hard for a non-linux-kernel component to verify the physical loading of an userland application.
(Note that you should crosscheck my assertion, I might be wrong).

About user TA versus static TA: it is true that, with current optee, a user TA cannot access nonsecure memory that is outside of the unique "TEE non secure shared memory" area in which linux kernel will never attempt to load an application.

**Comment by holmastoo** [comment]
@etienne-lms Thank you very much,

- I  think I have found a solution. I use core_mmu_add_mapping() to map the memory of the program to the SW after the CA is loaded and the TA can access it.

-  I test this solution in a simple case and it seems work. In this simple case, the program is really small and is in contiguous physical memory areas. I have no idea whether this solution still works when CA is loaded in non-contiguous areas. I think it will work if the areas which the program is loaded in are not too far from each other and can be covered by a large mapped region. 

- As for swapping, I think maybe it needs to add a linux-kernel component to manage the application reloading. I think it will be difficult to monitor the program if the physical address changes. Restricting the swapping out of the pages of the program may be an alternative solution. 

I will close this issue because my original problem has been solved.

Thank you for all your help and replies!
