### ISSUE TITLE
How to increase TA stack size

### ISSUE THREAD

**Issue by gaurav4dev** [OP-TEE/optee_os#1274]
Hi,
How much stack is available for a TA and how to increase it?
Regards,

**Comment by jforissier** [comment]
Hi @gaurav4dev 

The TA stack size is defined by the TA itself, at compile time. See for instance https://github.com/OP-TEE/optee_test/blob/master/ta/crypt/include/user_ta_header_defines.h#L36. This define is used in https://github.com/OP-TEE/optee_os/blob/master/ta/arch/arm/user_ta_header.c which is included in the TA SDK, and linked with the TA.

As for the maximum size that can be set, it depends on the OP-TEE OS configuration. As long as the TEE has enough memory to map the TA binary, it's OK.

**Comment by gaurav4dev** [comment]
Hi @jforissier  Thank you for your information. I am getting some strange issue on hikey, so had doubt if it might be stack size issue. Increased my TA stack size but it didn't help. Same TA when run on QEMU, it's now crashes in an RSAEncrypt API in our in-house crypto-lib, don't have much idea in debugging low level crashes, could anyone help in understanding below log, thank you very much
![crash_qemu](https://cloud.githubusercontent.com/assets/23352706/21718754/72ce324a-d43f-11e6-8e4c-9147f3596529.png)

**Comment by jforissier** [comment]
I would also think it looks like a stack size issue, because the invalid VA (0xffacc) is not very far from the bottom of the stack (0x100000), it may be that you have e.g., a 512-byte array and a few variables. Did you make sure the size of the stack actually changed when you increased it? (that's the 4096 in "- stack: 0x100000 4096". 2K for TA_STACK_SIZE plus 2K for TA_FRAMEWORK_STACK_SIZE).

**Comment by gaurav4dev** [comment]
Hi @jforissier, I increased the stack-size to 4k and data-size to 128k and it works properly. Thank you for your inputs.

**Comment by jforissier** [comment]
Closing this issue since it has been resolved.
