### ISSUE TITLE
API for reading 'efuse' values if platform supports them

### ISSUE THREAD

**Issue by msa2** [OP-TEE/optee_os#1294]
Secure monitor is supposed to be able to read efuse values (does rpi3 have them?).

If a TA wants to get the efuse value, how does it happen?

To clarify, some chips have a device specific random (burned once) read-only value somewhere, that can be used to derive device specific secrets. Thus I'm looking, if there is any generic API for accessing it or not.

**Comment by lws-team** [comment]
The API exists... indeed I sent a patch adding documentation for it in secure_storage.md

--->
In OP-TEE, there are apis for reading the keys generically from "One-Time
Programmable" memory, or OTP.  But there are no existing platform implementations.

To allow Secure Storage to operate securely on your platform, you must:

 - enable CFG_OTP_SUPPORT on your platform

 - In your platform code, define implementations for:

```
 void tee_otp_get_hw_unique_key(struct tee_hw_unique_key *hwkey);
 int tee_otp_get_die_id(uint8_t *buffer, size_t len);
```
<----

The point is no vendor has documented publicly how to read the e-fuses.  So OP-TEE provides the API but there are no existing implementations!  In turn it means the soi-disant "Secure Storage" is 100% insecure until you provide the (unknown) way to read the fuses on your platform, since the key is a constant the same on all builds and devices as it stands.

This isn't really OP-TEE's fault.  But clearly there ought to be a big list in bold at the top of the README listing the security deficits from the **capability** of OP-TEE, which is very good, and the rather more dismal reality out of the box, which is very insecure.  HWRNG is another case they support it, but many vendors did not document it (RPi3 is documented IIRC, but not Hikey).  Only having a PRNG in "Secure" World is a big problem if stuff like TLS wants to resist concerted attacks.

**Comment by msa2** [comment]
Thanks for the pointer. Good to know what to hack, if we ever get that far...

**Comment by lws-team** [comment]
If you are on Hikey, take a look at this PR

**Comment by msa2** [comment]
Looks nice. However, could use more than 32 bits? Might be useful, if someone actually could read the hardware unique key (or something) during boot and pass it to optee.

Another use for longer value could be scenario, where the boot code asks the user a password or pin code, and then could hash it together with device id, giving a device and user specific id?

**Comment by lws-team** [comment]
It's 32-bit because that's all I could find that has a "relatively unconditional" tie to the individual PCB, and it does not require any user config: it already has a random-looking set of 32-bit in it that should be different for "every" device with a very low chance of collisions.

For example if you completely wipe every sector the eMMC storage, this is still going to have the same 32-bit ID.  It's in a (slightly) different class than data taken from the eMMC storage as it is stored outside the main storage.  There are usually vendor commands to change it though so it's not perfect.

It could pass a PA for where to find the real key.  But if how to do that is known, OP-TEE can do it itself; OP-TEE will be the only guy still running who has the privilege to read the fuses anyway.

The reason for threading this through a-t-f is because he already touches the eMMC, and that way OP-TEE doesn't have a grow a possibly-conflicting eMMC driver (it requires commands sending to the eMMC to get the CID).

So it's not a replacement for the real SoC key.   But it is much better than every Hikey seems identical and has identical Secure Storage keys.

**Comment by MikeChou** [comment]
Does this help? 
https://github.com/raspberrypi/documentation/blob/master/hardware/industrial/README.md

**Comment by lws-team** [comment]
@MikeChou  yes, thanks, it helps somewhat if you have an RPi.

> Also, from 36 to 43 (inclusive), there are eight rows of 32 bits available for the customer

It explicitly says these are in OTP in the link you gave, and that you can set them from userland and permanently disable them from being written any more

```
Locking the OTP changes

It is possible to lock the OTP changes to avoid them being edited again. This can be done using a special argument with the OTP write mailbox:

pi@raspberrypi:~ $ /opt/vc/bin/vcmailbox 0x00038021 8 8 0xffffffff 0xaffe0000

Once locked, none of the customer OTP values can be accessed.
```

However what you ideally need from the whole TEE perspective are bits that can be written how you like, even from userland, but then **never read again** from outside of secure world and **never written again** from anywhere.  What the quote seems to be saying is that you simply permanently write-protected them, but you can still read them as a userland-accessible device ID.

This sounds like it's useful for doing as well (... or at 256 bits, better than) as the eMMC ID hack, in terms of getting a device-unique ID that can also be known by the untrusted world.

What would really be valuable is OTP that can only be read from secure world full stop, so you can put per-device secure keys there that userland can't trivially also know.  The RPi chips probably have that capability but what you pointed to doesn't document it.
