### ISSUE TITLE
Static TA cannot use TEE_* api -- a patch proposal for enabling "Static User TA" linked into optee

### ISSUE THREAD

**Issue by msa2** [OP-TEE/optee_os#1295]
Is this correct? Puts a serious damper, if you have a large TA and want to have an option to use it either as static TA (to make it available on early boot) or dynamic TA.

It would be perhaps nice, if the static TA compilation would have a light shim layer (#defines?) that map the TEE_*() functions to equivalent internal library calls? Anyone done that?

**Comment by etienne-lms** [comment]
I don't know such implementation.
`#define` won't be enough, the 'svc' layer must be emulated, and ther might be few library collisions between 'libutee' and the 'core'.

Trom current op-tee design, trusted applications are Applications. Hence they shall not crash the TEE integrity. Running TAs in userland is a safeguard for TEE integrity in case of TA failure, so that the failure remains in the scope of the TA secure abilities. A standard TA can also use crypto keys the TA cannot read (only optee 'core' will). That can protects the TA security domain against the TA itself.

Yet, i think it's possible the build a libutee integration layer for optee 'core'.

An alternate solution (not implemented neither in current optee) for invoking TAs before REE fs availability would be to store the prebuilt (standard)TA image (signed -or not- ELF) inside optee 'core' image (read-only part), and change the 'TA load' sequence in the 'core', to load such 'preloaded TAs' prior to look into the REE remote 'TA dynamic load' sequence.

**Comment by msa2** [comment]
Including the generated TA binary into optee os binary as is doesn't seem too difficult.
Just some clever use of linker options `--format=binary tafile.ta` and/or objcopy, which would generate `_binary_tafile_ta_start/_binary_tafile_end` symbols.

Then just generate of lookup table for TA's included this way to be looked up in user_ta.c:tee_ta_init_user_ta_session(). If found, skip rpc_load?

...but planning the build scripts into makefiles and finding all the necessary options for the correct result would need some thinking.

**Comment by msa2** [comment]
I poked around a bit and managed to get prebuilt TA blob included into optee.bin. However, it crashes inside "tee_vbuf_is_non_sec"

```
DEBUG:   [0x0] TEE-CORE:load_header:67: load_header
[   29.377490] Unable to handle kernel NULL pointer dereference at virtual address 00000044
[   29.386007] pgd = ffffffc033322000
[   29.389515] [00000044] *pgd=0000000000000000, *pud=0000000000000000
[   29.395990] Internal error: Oops: 96000005 [#1] SMP
```
I also have an eventual alignment problem: if I change the .data section into .rodata, the linker pretty much aligns the ta blob at any alignment (I now rename it into .userta, and with one TA it should be aligned, so this is not the cause the panic).

...appears that the trick is more tricky than I expected. Took some time get some idea of the build system ".mk" files and finding a place to put the hack in.

I had hoped to use the normal ta_load unchanged, but if I have to "disable checks like "tee_vbus_is_non_sec" (and whatever else comes up), the required changes are starting to pile up...

**Comment by etienne-lms** [comment]
you should change the load sequence of user_ta.c to loading a TA when its in a authorized location of the OP-TEE core binary. Current code expects the TA to come from NonSecure world, hence, it check that to provided buffer really complies with NonSecure domain.

**Comment by msa2** [comment]
Also running into byte order thingy on UUID. My TA UUID string (in Makefile, TA binary and as filename) starts with: ta_head->uuid=`12345678-8765-4321-...` but, the compare in ta_load expects uuid=`78563412-6587-2143-...`, verified with

`DMSG("   uuid=%pUl == %pUl", (void *)&ta_head->uuid, (void *)uuid);`

e.g. the 'uuid' parameter to 'ta_load' has different byte order than what exists in binary blob.

The exact same TA loads with tee-supplicant, so I assume someone is changing the uuid byte order somewhere in load logic.

**Comment by jforissier** [comment]
@msa2 UUID handling has changed recently. Now it's always native endianness [1] when manipulated as `TEE_UUID`, and big-endian when communicating between secure world and normal world.
Please make sure your optee_os and optee_client (tee-supplicant) are not mismatched!

[1] That is little endian for all platforms we support. Hence the '%pUl' format (l for little-endian).

**Comment by msa2** [comment]
So, when using the kernel API (patch), the uuid in tee_ioctl_open_session_arg should also be big endian...

...but, my point was that when TA is compiled, the TEE_UUID appears to be generated and stored into elf in native endiannes, and it seems to work -- someone modifies it before it gets to ta_load. But when I include the blob directly into optee_os.bin, it does not.

**Comment by msa2** [comment]
This is the current result that seems to work for. A very crude hack that needs cleaning and better integration into build system...

[patch.zip](https://github.com/OP-TEE/optee_os/files/729716/patch.zip)

For now I've to give up working more on this.

**Comment by msa2** [comment]
I had to tweak the patch to apply to latest rpi.xml repo, and little cleanup, but not much. This is still much of PoC. Lacks proper commenting and seriously need some way of running generate script, when directory content (core/user_ta/) has changed. Anyway, updated patch set:

[user_ta_patch.zip](https://github.com/OP-TEE/optee_os/files/735298/user_ta_patch.zip)

**Comment by etienne-lms** [comment]
hello @msa2, sorry i did not comment earlier and time goes by.

I found your proposal a nice clean start point. I did not try it but i think the basics are all there. i fear few discussions with multi-build requirements. let's seen then. Thanks for this.
Please do not hesitate to propose a "pull" if you have time, otherwise we/one may use your materials and keep you informed.

**Comment by jbech-linaro** [comment]
Looking up old and still open threads and found this one. I still think this is an interesting proposal, would you mind submitting a PR for it (if not already done and I've just missed this entirely).

**Comment by jforissier** [comment]
If the real need was "early TA", possibly in user mode, rather than the availability of TEE_* in kernel mode "pseudo-TAs" (as they are called now), then it's done here: https://github.com/OP-TEE/optee_os/pull/1733.

The `ld -b binary` trick mentioned [above](https://github.com/OP-TEE/optee_os/issues/1295#issuecomment-273757338) may probably be used to simplify the current implementation (get rid of the C file generation and build).

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.

**Comment by akbarsaleemt** [comment]
HI,
In TA side i wants to implement my own api before TA_Createentrypoin() for finding the OPTEE which is global platform OPTEE or any other secure world like QEE. Is there any way to find that platform(optee or qee ) in trusted world.

thank you

**Comment by jforissier** [comment]
@akbarsaleemt can you explain how your question is related to this PR?

**Comment by akbarsaleemt** [comment]
Hi,
I wants to display Secure OS name  when hello_world executing  which is OPTEE. where it is checking this is OPTEE OS or not (note: not in REE side only in Secure side(TEE)).
Thank you.
