### ISSUE TITLE
How to generate randomness for crypto reasons

### ISSUE THREAD

**Issue by booble89** [OP-TEE/optee_os#1308]
Is there any method equivalent  to /dev/urandom where I can generate random number for crypto purpose?

**Comment by lws-team** [comment]
`void TEE_GenerateRandom(void *randomBuffer, uint32_t randomBufferLen);`

**Comment by booble89** [comment]
Thanks for your answer. Is this generated from the environment noise like /dev/urandom ?

**Comment by lws-team** [comment]
Ehhh.... /dev/urandom is a pseudo-RNG.  /dev/random has real entropy.

It depends on your platform.  If the platform code in OP-TEE is wired up to a HWRNG on the SoC, then yes.  By default, no, it's also a PRNG.

OP-TEE security is a little bit like being pregnant, by default you are not but if you are, you are wholly.  To have any meaning from HWRNG in OP-TEE, you also need things like unique die serial number and Chain of Trust extending from BL1 in ROM.  Normal mortals cannot get any of those things without partnering with the SoC supplier.

**Comment by lws-team** [comment]
If you're on Hikey, take a look at this PR https://github.com/OP-TEE/optee_os/pull/1317

**Comment by jbech-linaro** [comment]
Just to add some more info related to RNG, [this](https://github.com/OP-TEE/optee_os/blob/09fc0424ec5ad8093864cd9959a1c539c10f0524/core/lib/libtomcrypt/src/tee_ltc_provider.c#L125-L143) is where we can select which RNG gets called when using the "random" API in OP-TEE. If you have the ability to use hardware, this is one place where you should add code. Since I think the question has been answer, I'm going to close the issue. If you have more questions, feel free to open the issue.
