### ISSUE TITLE
how to build SD card debian image

### ISSUE THREAD

**Issue by Valeri99** [OP-TEE/optee_os#1316]
Hello,
The nice building instructions at
https://github.com/OP-TEE/build 
tell in particular how to build debian images to be flashed to emmc.
That would be very helpful if you give an idea how to
build a bootable debian image to be flashed to SD card.
(like this one:
https://builds.96boards.org/releases/hikey/linaro/debian/latest/hikey-jessie_developer_20151130-387.img
)
Thanks a lot.

**Comment by lws-team** [comment]
I think the reason no comments are coming is this is unrelated to OP-TEE.  You may do better asking the same question at something with "96 boards" in the name... they have some repos on github if you look around.

**Comment by Valeri99** [comment]
Hello vchong, lws-team,
Thank you so much for giving me directions.
I am a very recent member (even have not still received needed hardware 
like USB-UART and USB-Ethernet) 
So, after I looked more attentively at the OPTEE Makefiles
I see now that my question was not quite correct.
The question was generated by my original desire to 
to have a debian os SD card flashable image with OPTEE things.
Now I see that I could do in the similar way like you do for emmc:
I.e. at first I could flash SD card with image like
https://builds.96boards.org/releases/hikey/linaro/debian/latest/hikey-jessie_developer_20151130-387.img
to install after that the optee_$(OPTEE_PKG_VERSION).deb and linux-image-*.deb.
However the hikey-jessie_developer_20151130-387.img and linux-image-*.deb may not live together
due to different kernel versions.
(I still can not play with *.deb installations due to lack of USB-UART hardware)
Thanks a lot.

**Comment by vchong** [comment]
I think if you first install something like a hikey-jessie_developer_20151130-387.img and then later a linux-image-.deb you'll just see a new boot entry based on linux-image-.deb in `/boot/grub/grub.cfg` that is available for you to select during bootup.

Also, you can replace the debian images in the optee build makefile [here](https://github.com/OP-TEE/build/blob/master/hikey_debian.mk#L29) with a newer version if you wish. It is still on 16.03 for some compatibility reason (https://github.com/OP-TEE/build/pull/100) but should be updated somewhere in the near future.

*.deb installation files are sent via IP/wifi. You don't really need the USB-UART adapter.
See https://github.com/OP-TEE/build/blob/master/hikey_debian.mk#L313

**Comment by Valeri99** [comment]
I appreciate your help very much.
However, it seems I do not understand something obvious:
In order to play with OS flashed onto emmc ( e.g. to install *.deb) I need to talk to OS
in some way.
In each way I got stuck mainly due to a lack of needed hardware.
(o) to talk via UART I need USB-UART hardware (did not come yet)  
(o) to talk via Wi-Fi I need to configure interface:
    https://github.com/OP-TEE/build/blob/master/hikey_debian.mk#L379
    (I belive I need USB-UART hardware to do that network configuration)
(o) there is a potential way to talk via HDMI/keyboard, but it seems it does not work for me.
    ( note: with OS flashed with hikey_debian.mk )
    
I also tried to communicate to OS:
https://builds.96boards.org/releases/hikey/linaro/debian/latest/hikey-jessie_developer_20151130-387.img
flashed onto SD card.

(o) in the case of SD card I can make wi-fi configuration right on SD card:
    https://github.com/OP-TEE/build/blob/master/hikey_debian.mk#L379
    I tried both dhcp and static -- both did not work for me
    (note: with image referred above: hikey-jessie_developer_20151130-387.img)
    
(o) in the case of SD card I can also make ethernet configuration right on SD card:
    But to do that I need USB-Ethernet adapter (did not come yet)

Thanks a lot.

**Comment by vchong** [comment]
> In order to play with OS flashed onto emmc ( e.g. to install *.deb) I need to talk to OS
in some way.

In order for install *.deb to work, the board must first be already be flashed with a reference platform image, i.e. from https://builds.96boards.org/releases/reference-platform/debian/hikey/.

> (o) to talk via UART I need USB-UART hardware (did not come yet)

Yes

> (o) to talk via Wi-Fi I need to configure interface:
https://github.com/OP-TEE/build/blob/master/hikey_debian.mk#L379
(I belive I need USB-UART hardware to do that network configuration)

Yes. Sorry if this confused you. The *.deb files themselves are sent via IP/wifi from the PC to the board and hence doesn't need the USB-UART hardware, but in order to setup wifi and install the *.deb files, you need it.

> (o) there is a potential way to talk via HDMI/keyboard, but it seems it does not work for me.
( note: with OS flashed with hikey_debian.mk )

Never really tried this so can't tell for sure. Sorry.

> (o) in the case of SD card I can make wi-fi configuration right on SD card:
https://github.com/OP-TEE/build/blob/master/hikey_debian.mk#L379
I tried both dhcp and static -- both did not work for me

Not sure what you mean by making wifi/ethernet config right on SD card? Can you please explain your procedures/steps in detail? The instructions on L379 are meant to be done on the board itself.

**Comment by Valeri99** [comment]
My previous post started from the point 
that emmc had been already flashed by "make flash" ("make all" is done too) 
( https://github.com/OP-TEE/build/blob/master/hikey_debian.mk#L350 )
So in my previous post I meant e.g. 
that I needed USB-UART hardware to configure network (wi-fi) 
in the "emmc" file /etc/network/interfaces )
in order to use that network to issue "make send" (for example).
Do you know another way?

Let me clarify what I meant by:
  (o) in the case of SD card I can make wi-fi configuration right on SD card:
  https://github.com/OP-TEE/build/blob/master/hikey_debian.mk#L379
  I tried both dhcp and static -- both did not work for me

Once an SD card has been flashed e.g. by
https://builds.96boards.org/releases/hikey/linaro/debian/latest/hikey-jessie_developer_20151130-387.img
(i.e. flashing has been done)
we can do as follows:

-plug and mount SD card on the host machine (SD card had been flashed before mounting)
-edit "sd card" file /etc/network/interfaces to configure network (wi-fi, ethernet)
-plug the SD card into HiKey and boot HiKey with SD card.
I.e. this way we can make network configuration without USB-UART hardware. 

Thank you.

**Comment by vchong** [comment]
> My previous post started from the point
that emmc had been already flashed by "make flash" ("make all" is done too)

Ok, that's good. That means your board is already flashed with a reference platform image, and you can install *.deb files.

Thanks for the clarification! I think I understand now, and it looks like making wifi config right on SD card should have worked. Not sure why it's not. Can you please double check your network config, especially your wifi ssid and password? Note that you should also be able to make wifi config right on emmc image file by mounting it on host machine, changing the /etc/network/interfaces file and unmounting it before flashing it to the board.

**Comment by lws-team** [comment]
The lack of Ethernet is really painful on Hikey.  You can get the wifi working on some kernel / rootfs combinations, but in all the versions I tried at best that was not wholly stable and at worst I couldn't apply power to the module.  There are some versions out there with a non-mainline kernel driver that has to be aligned with the exact kernel version... good luck with that.

Life is too short, the best solution is as @Valeri99 mentioned he has coming, a usb-ethernet adapter.  Even that has problems since they typically have no memory for MAC, they end up with a randomized MAC and if you are rebooting a lot, that ends up exhausting your DHCP server on ephemeral MACs that only exist once per boot.

If that bothers you here is a workaround to set the usb-ethernet mac to a unique enough permanent MAC early in your init

```bash
M=`cat /sys/block/mmcblk0/device/cid | tail -c 14`
A=`echo $M | head -c 2`
B=`echo $M | tail -c 12 | head -c 2`
C=`echo $M | tail -c 10 | head -c 2`
D=`echo $M | tail -c 8 | head -c 2`
MAC=02:01:$A:$B:$C:$D

echo "Setting eth0 MAC to $MAC"
/sbin/ifconfig eth0 hw ether $MAC
```

**Comment by Valeri99** [comment]
vchong, lws-team
Thank you both of you very much, I will follow your advices.

**Comment by jbech-linaro** [comment]
@Valeri99 , I'm trying to clean up open issues in general. This particular isn't that old, so no hurry here. But, after reading the discussion above it seems like you've gotten answers to the questions you had? Right? If yes, would it be OK for me to close the issue?

**Comment by Valeri99** [comment]
jbech-linaro, 
Just before closing I must confess that I did not understand the trick suggested by vchong namely:
>> Note that you should also be able to make wifi config right on emmc image file 
>> by mounting it on host machine, changing the /etc/network/interfaces
So my question to vchong is what did he mean by mounting an emmc image on host
(presumably an image of the file system?)
How could I do that mounting?
Thank you.

**Comment by jbech-linaro** [comment]
I think he meant that you can "loop back mount" the image on your regular machine, then just make the changes directly to the file (`/etc/network/interfaces`) and then unmount it and just use it the same way. Do you know how to loop back mount images?  If not let me know and we can probably guide you. If you succeed with that, then WiFi should work. But I second the other comments here, having a UART makes life much easier. So, try to gather a UART adapter board (or in worst case a 1.8V cable and solder the pins for the UART).

And, don't get me wrong with closing things. If you're still having issue, then no hurry to close it. It's just that the more issues we have, the harder it's to keep track of things.

**Comment by Valeri99** [comment]
I appreciate if you guide me on the  "loop back mount". I am still waiting USB-UART (with proper chipset) to come (I tried to use USB-UART with chipset cp2101 but it worked very unstable )
Thank you so much.

**Comment by jbech-linaro** [comment]
So, since that image seems to be a "sparse" image there is one more step than just mount it. I think this should work (all commands were OK, but I haven't tried to flash it the actual device).
```bash
$ cd <project>/out
$ mkdir mnt
$ simg2img debian_system.img tmp.img
$ sudo mount -t ext4 -o loop tmp.img mnt/
$ vim mnt/etc/network/interfaces
$ # Do the changes, i.e.,
$ # https://github.com/OP-TEE/build/blob/master/hikey_debian.mk#L380-L388
$ sudo umount mnt/
$ sudo ext2simg -v tmp.img debian_system.new.img
$ # Rename/overwrite the debian_system.new.img to debian_system.img and flash system image again (make flash)
```
Another thing that you should be aware of when not seeing what's happening during the boot is that, depending on how you've set the "boot pin" (see [page 7 here](https://github.com/96boards/documentation/raw/master/ConsumerEdition/HiKey/AdditionalDocs/HiKey_User_Guide_CircuitCo.pdf)) it will either stop at fastboot or if it will just continue into UEFI/Grub. IIRC I think it's `GPIO3_1` that you can try to put a jumper on if it seems like it's not booting. I hope this helps meanwhile you're waiting for the UART adapter.

**Comment by Valeri99** [comment]
jbech-linaro,
Thank you so much for your great help!

**Comment by Valeri99** [comment]
Please, close the issue. 
I appreciate very nice help of all.
