### ISSUE TITLE
Question: L2 control from rich OS

### ISSUE THREAD

**Issue by dryvenn** [OP-TEE/optee_os#1370]
Hi everybody!

I've got a question regarding OP-TEE and the Linux boot. If I'm not mistaken, it is a Linux requirement that the data caches are disabled at bootup. However, even though some platforms are implementing `arm_cl2_enable` (when CFG_PL310 is defined), none of them implement some sort of disabling. Moreover, when Linux boots and has to turn on the L2 cache, this needs to be done in secure mode (right?), but I don't see any platform implementing an SMC for that.

I believe this is taken care of by the ARM Trusted Firmware in ARMv8 architectures, but what about ARMv7 (I've got a Cortex A9)?

Does anyone have some insight on that?

**Comment by etienne-lms** [comment]
hello dryvenn,

Regarding Cortex-A9 and PL310 outer cache, it is true that some configurations can be loaded from the secure world only, including the PL310 enabling/disabling.

The OP-TEE approach for this is to play with the PL310 lockdown support for controlling PL310 activation from non-secure world. During OP-TEE core early boot (primary boot core early boot sequence, before non-secure world birth), the PL310 is enable, all cache lines are locked and invalidated and the PL310 is configured so that the non-secure world is allowed to act on PL310 lockdown registers.
This way, when non-secure world boots up, the PL310 behaves as if it is disable, yet being enable. Non secure world is then able to enable (respectively disable) the PL310 support by unlocking (respectively locking and invalidating) cache line. In OP-TEE, such support is enable through the configuration directive CFG_PL310_LOCKED.

From linux kernel view, the cache-l2x0.c driver lacks a change to support that. In `__l2c_init()`, one should change as following :
```
 	/*
 	 * Check if l2x0 controller is already enabled.  If we are booting
 	 * in non-secure mode accessing the below registers will fault.
 	 */
 	if (!(readl_relaxed(l2x0_base + L2X0_CTRL) & L2X0_CTRL_EN)) {
 		l2x0_saved_regs.aux_ctrl = aux;
 
 		data->enable(l2x0_base, data->num_lock);
-	}
+	} else
+		data->unlock(l2x0_base, data->num_lock);
 
 	outer_cache = fns;
 
```

**Comment by dryvenn** [comment]
Hi @etienne-lms,

Thanks for the reply!

If I understand correctly, this means that OP-TEE won't take advantage of the L2 during bootup, will it?

In that case copying bootloaders around and deciphering/authenticating them in software would be a huge penalty.

**Comment by etienne-lms** [comment]
Check **generic_entry_a32.S**. You will see some early memory copy before PL310 is enable, then OP-TEE core main inits are executed with PL310 enabled. Last, PL310 is locked/invalidated almost before non-secure boot entry point is reached (being a boot stage, the linux kernel or whatever).

That said, consider that pristine op-tee core is not responsible for loading any boot stage. OP-TEE core is not a bootloader. But, if a platform expects its OP-TEE core initializations to participate in some boot loading sequence(s), it should be able to execute such sequence while PL310 is enabled. Platforms are also free to not enable `CFG_PL310_LOCKED` in their OP-TEE configuration and handle such pseudo PL310 disabling (lock/inval) in their private non secure boot stage(s).

**Comment by dryvenn** [comment]
Allright thank you very much.

**Comment by dryvenn** [comment]
Hi @etienne-lms 

I noticed the OP-TEE related patches got merged into Linux (congrats 🎉 ), however I do not see the lines quoted above in the latest tree. Is lock+invalidate still the recommended way of managing the L2? Should this diff be applied manually?
