### ISSUE TITLE
Concurrent executions corrupt object storage

### ISSUE THREAD

**Issue by ds49** [OP-TEE/optee_os#1391]
Hello,
I'm developing an application that processes a small amount of information (matrices of floats) and produces a signature based on the input and output data.
The main goal is to divide a large set of data into smaller pieces and execute several instances of the program at the same time (each instance deals with one piece of the problem). After all the small outputs have been produced (and their signatures) another program produces the final result (by verifying all of the signatures). The signatures are generated by the private part of a RSA keypair object stored in the trusted side. On the client side the signatures are validated by the corresponding public key.

When I execute the program over each piece sequentially, everything works as expected and I am able to obtain the result for each piece of the problem.
However, when I execute the same program with several instances in parallel, some of the executions hang and the object gets corrupted.

Here's the log obtain on the trusted side when executing only two instances of the program at the same time:

[http://pastebin.com/xMK0KuQL](http://pastebin.com/xMK0KuQL)

(There are some messages I've inserted into the code in order to keep track of the operations)

As far as I can tell, when a second instance accesses the same object when it was already open (and/or performing an operation) the object gets corrupt.
As I said previously, the main goal is to execute these operations in parallel. I've tried to create a separate key for each execution (corresponding to several RSA keypair objects) but the problem persisted, which leads me to think the "problem" is from the storage itself (or in this case, the several parallel accesses to it).

Is there a way to overcome this problem? What do I need to include in the code to ensure these parallel accesses to the storage do not corrupt the objects?

Thanks in advance.

**Comment by jforissier** [comment]
Hi @ds49,

It looks like you're running out of TEE core heap memory -- see "Failed to allocate file data buffer" at line 114. Maybe you need to increase `CFG_CORE_HEAP_SIZE`. And/or use a more recent version of OP-TEE (the secure storage has been changed significantly in the past weeks).

The secure storage API is supposed to be safe regarding concurrent access. Which means, no internal (meta-data) corruption should ever occur due to concurrent access from multiple instance TAs. As for the actual object data, just make sure multiple instances of you TA do not read/write to the same area of the same persistent object and you should be safe.

**Comment by ds49** [comment]
Hello @jforissier,
Thank you for your quick answer.
I was able to build the most recent version of OP-TEE (with the other binaries need for my project) and the problem seems to be solved.
I'll close the issue. If something related to this problem pops up, I'll contact you.
Thanks again for your support!
