### ISSUE TITLE
setup_fvp_optee.sh optee_os build error

### ISSUE THREAD

**Issue by vchong** [OP-TEE/optee_os#148]
export CFG_TEE_CORE_LOG_LEVEL=5 in setup_fvp_optee.sh seems to be causing an error while building optee_os?

Should be 1-4?

optee_os/lib/libutils/ext/trace.c
# if (CFG_TRACE_LEVEL < TRACE_MIN) || (CFG_TRACE_LEVEL > TRACE_MAX)
# error "Invalid value of CFG_TRACE_LEVEL"
# endif

**Comment by leesagacious** [comment]
Not only these, Will also report an error when starting，
Too many bugs !!

**Comment by jbech-linaro** [comment]
I'm not sure if you are joking or just trolling. The issue is more than three years old and the mentioned files are not even in use anymore. If you fast forward 3-4 years in time and try the most current version, then things will work better. At least [it is working for ~10 people on the same amount of platforms](https://github.com/OP-TEE/optee_os/pull/2404), this includes [FVP](https://github.com/OP-TEE/optee_os/pull/2404#issuecomment-401049450) which you are referring to here.
