### ISSUE TITLE
Directly load files from storage in TA

### ISSUE THREAD

**Issue by str84ward** [OP-TEE/optee_os#1524]
Hello,

I am writing a Trusted Application for optee at the moment.
Therefore I want to load encrypted files from storage of my raspberry pi, decrypt and verify them and write them back to storage from the TA.
Is there a way to directly load files from storage in the secure world?

Thanks

**Comment by jforissier** [comment]
Hi @str84ward ,

No, you can't do that currently. TAs have their own secure storage space, they can't access the Linux file system directly. Why not deal with file access in the client application and only do the decryption stuff only in the TA?

**Comment by str84ward** [comment]
@jforissier 

Thanks for the answer. So i have to load the encrypted files on the client application. How do I pass the files to the secure world to be decrypted? How much space does this secure storage have? 
Would it be possible to store the files in the secure storage and pass them to the client application to write them to storage?

**Comment by jforissier** [comment]
> So i have to load the encrypted files on the client application. How do I pass the files to the secure world to be decrypted?

You can pass arbitrary data from non-secure to secure world (in/out) when you call `TEE_InvokeCommand()` -- but the size is limited because the shared memory is a fixed area of `CFG_SHMEM_SIZE` bytes, usually a few megabytes.

> How much space does this secure storage have? 

Maximum 4 GB per secure file (as per GlobalPlatform's `TEE_DATA_MAX_POSITION`). Other than that, the total size of the secure storage is limited by the kind of file system you have in normal world, because by default the secure storage is mapped to a normal world file. So it's hard to give a number but "pretty big" may be a reasonable answer ;)
If you're using RPMB however, chances are that the available size will be much smaller, typically some megabytes rather than gigabytes.

> Would it be possible to store the files in the secure storage and pass them to the client application to write them to storage?

Only the TA can read/write from/to secure storage, but as I said above you can exchange data buffer between normal and secure world.

**Comment by str84ward** [comment]
My original plan was to load a system image from the filesystem into the secure world and decrypt it and authenticate it there and then flash it to the respective part on the sdcard removing the previous installation. Like a reset switch.

I came to know that loading files directly from the secure world is not possible.
My question would be whether this is a security measure or just a missing feature.

So i implemented the image file to be loaded from the client side and decrypted an stored inside the secure world as a persistent file.
My second question would be, whether there is a way to write the image file directly to the sdcard from the secure world.

**Comment by str84ward** [comment]
@jforissier 
Another question.
Would it be possible to use optee_os/core/tee/tee_ree_fs.c through a pseudo TA to write arbitrary files to the REE file system without encryption?

**Comment by jforissier** [comment]
About loading normal world files from secure world: indeed, it can not be done directly (meaning: there is no API available to OP-TEE or TAs to read/write such files). It is not a security measure, it's just that it's not required by the GlobalPlatform APIs that we are implementing for TAs, and it's not something we have been requested to do or that someone contributed to the upstream code. But as you said, it can easily be accomplished by a client application.

About writing data to the SD card from normal world: again, not possible currently. In order to do that you would need to write a MMC/SD driver, making sure sharing with normal world is taken care of (might not be trivial). Or you could involve normal world to perform the actual write (but that may be problematic if you can't trust normal world, which by definition you shouldn't).

About `tee_ree_fs.c`: actually, in older versions of OP-TEE we had a POSIX-like interface between secure world and normal world (implemented in tee-supplicant), which would allow secure world to open, create, read, write files etc. (but this was restricted to some path under `/data/tee`). This was done to implement secure storage ; the files were simply containers for encrypted and authenticated persistent objects. In the current code, this interface has been removed in favor of a more efficient (and more secure) implementation. You can check the file history in Git and you'll see what was done.

**Comment by str84ward** [comment]
@jforissier 
Thank you for you help.

I have a question that is not directly related to the issue.
I have op-tee running on a raspberry pi 3.
I made 3 partitions on the sdcard, boot partiton and 2 rootfs partitions.
How can i switch between those partitions on boot time.
I already tried to change the env in u-boot with the command setenv bootargs root=/dev/mmcblk0p3 but it is still loading the rootfs from partition 2.

**Comment by str84ward** [comment]
Another question came up when examining the TEE_GenerateRandom function.
I traced it back to TEE_SCN_CRYP_RANDOM_NUMBER_GENERATE	sys call.

The questions is, how is this random value created ?

**Comment by jforissier** [comment]
> The questions is, how is this random value created ?

The syscal body is here: https://github.com/OP-TEE/optee_os/blob/master/core/tee/tee_svc_cryp.c#L2899-L2920.
The implementation depends on the platform. The default is a Fortuna software implementation in LibTomCrypt (see here https://github.com/OP-TEE/optee_os/blob/master/core/lib/libtomcrypt/src/tee_ltc_provider.c#L129). Entropy is added at a few locations in the code (search for `plat_prng_add_jitter_entropy()`).
Wether the default software implementation is used or a custom one is controlled by `CFG_WITH_SOFTWARE_PRNG ?= y` here: https://github.com/OP-TEE/optee_os/blob/master/mk/config.mk#L83-L87.

**Comment by jforissier** [comment]
And, for an example of hardware-based RNG, see https://github.com/OP-TEE/optee_os/blob/master/core/drivers/hi16xx_rng.c.

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins

**Comment by zineb-creator** [comment]
> @jforissier
> 
> My original plan was to load a system image from the filesystem into the secure world and decrypt it and authenticate it there and then flash it to the respective part on the sdcard removing the previous installation. Like a reset switch.
> 
> I came to know that loading files directly from the secure world is not possible.
> My question would be whether this is a security measure or just a missing feature.
> 
> So i implemented the image file to be loaded from the client side and decrypted an stored inside the secure world as a persistent file.
> My second question would be, whether there is a way to write the image file directly to the sdcard from the secure world.

@str84ward can you share the code please ?

**Comment by srinivasbollaboyena** [comment]
hi @jforissier ,I want to store a sample text in the trusty os it possible ,and how?

**Comment by jforissier** [comment]
Hi @srinivasbollaboyena, please open a new issue and give more details on your use case. Thanks.
