### ISSUE TITLE
Performance problem: Normal world vs Trusted Application

### ISSUE THREAD

**Issue by doanquangviet** [OP-TEE/optee_os#1566]
Hi Experts,

I am working on PLATFORM=imx and got a problem in performance:

With the same task:
- Run In Linux (Normal world): ~ 0.19 seconds
- Run In Trusted Application: ~ 2.933 seconds = The duration between SENDING command (TEEC_InvokeCommand) and RECEIVE the result.

Has somebody met the same problem? Please tell me how to increase the performance when running in trusted application?

My setting:

1. In **user_ta_header_defines.h**:
```
#define TA_STACK_SIZE               (256 * 1024)
#define TA_DATA_SIZE                (5 * 1024 * 1024)
```

I also disable the log:
`CFG_TEE_TA_LOG_LEVEL ?= 0`

2.  **core/arch/arm/include/mm/pgt_cache.h**
Line 67: 
`#define PGT_CACHE_SIZE	ROUNDUP(CFG_NUM_THREADS * 3, PGT_NUM_PGT_PER_PAGE)`

3. **core/arch/arm/plat-imx/platform_config.h**
Line 325
`#define CFG_PUB_RAM_SIZE		(3 * 1024 * 1024)`

4. **core/arch/arm/plat-imx/conf.mk**
`CFG_NUM_THREADS ?= 4`

Greatly appreciated,

**Comment by etienne-lms** [comment]
hello @doanquangviet,

What kind of task are you running ?
- Do you use a very big buffer of non-secure shared memory ?
- Does the task implies some generation of an asymmetric key pair ?
- Does this task require the TA to access some "persistent object" (secure storage) ?

Regarding the overall system:
- Are there any other trusted application invoked at the same time ?
- Is the OP-TEE pager enabled (`CFG_WITH_PAGER=y`) ?
- Check the value of `CFG_TEE_CORE_LOG_LEVEL`, it should be lower or equal to 2 (INFO level) in case of performance expectation. I doubt it is high than 2 otherwise you would see quite a lot a traces you would probably already have tried to disable.

**Comment by doanquangviet** [comment]
Thank @etienne-lms  for your comment.

I just use 300KB buffer of non-secure shared memory. (tmpref)

CFG_TEE_CORE_LOG_LEVEL = 1. It does not affect performance.

When I enable OP-TEE pager by set CFG_WITH_PAGER=y and rebuild OPTEE, I can not boot. Hanging at "Starting kernel ..."

**Comment by etienne-lms** [comment]
> I just use 300KB buffer of non-secure shared memory. (tmpref)

300kB of copy per invocation (twice in in/out), at high rated invokes that makes a lot. Can't improve ? 

> CFG_TEE_CORE_LOG_LEVEL = 1. It does not affect performance.

agree

> When I enable OP-TEE pager by set CFG_WITH_PAGER=y and rebuild OPTEE, I can not boot. Hanging at "Starting kernel ..."

I apologies but I don't practice on a imx board. Most seem to support the pager.

**Comment by jeffy1009** [comment]
It's weird. I tested with simple code that sets and adds up the `int a[15]` array, looping 5,000,000 times.

Running in TA is 5x time slower than running in Linux.

Some possible reasons I can think of
- Cache is not working in TA
Maybe related to [this](https://github.com/OP-TEE/optee_os/issues/1284#issuecomment-277913299)
- TA is frequently preempted by Linux OS

I think the problem might be specific to our board - freescale imx sabrelite. (because when I tested with hikey board I don't remember having this issue)

@MrVan Do you have any ideas?

**Comment by MrVan** [comment]
@jeffy1009 would you mind share your test program? Then I could debug. You are using 6qsdb board, right?

**Comment by jeffy1009** [comment]
@MrVan Attached is the test program.

[perf_test.tar.gz](https://github.com/OP-TEE/optee_os/files/1071516/perf_test.tar.gz)

I checked the optimization flags and generated assembly and I think it is not an issue.

I'm using 192cd5688293ff32779ed6d5e5861169ffe0b109 version of op-tee, and linux 3.14.

I'm using sabrelite board (but with 2G RAM instead of 1), so changed `DRAM0_SIZE` in `platform_config.h`

**Comment by jeffy1009** [comment]
@MrVan 
I tested with another code that have almost no load/stores, and the TA is still significantly slower.
Following is the code and the results.

[perf_test_no_mem.tar.gz](https://github.com/OP-TEE/optee_os/files/1074078/perf_test_no_mem.tar.gz)
![perf_test](https://user-images.githubusercontent.com/14091654/27124571-7623bf90-512c-11e7-97b0-f2aa45e9baef.PNG)

Following is the generated assembly in host. (the assembly in TA is almost the same)
```
;; r2 = n
L1: mov r3, #1000000
L2: subs r3, #1
     bne.n L2
     adds r2, #1
     cmp r2, r0
     bne.n L1
```

So it seems like the cache is not the problem, but I don't know what else could be the problem.

Can it be that TA is being interrupted constantly (by linux scheduling etc..) ?

**Comment by jenswi-linaro** [comment]
To rule out scheduling try commenting out the line:
https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/tee/entry_std.c#L373

**Comment by jeffy1009** [comment]
@jenswi-linaro 
Tried changing `thread_set_irq(true)` to `thread_set_irq(false)`

Also tried removing `CFG_BOOT_SECONDARY_CPU=y CFG_PSCI_ARM32=y CFG_BOOT_SYNC_CPU=y`

Still no difference  😢

**Comment by jeffy1009** [comment]
@MrVan @jenswi-linaro 

I did some more tests. 
I put a bunch of nops in the loop like the following, and the TA performance gets closer to the host performance.

```
L1: mov r3, #1000000
L2: subs r3, #1
     nop
     nop
     nop
     nop
     nop
     nop
     nop
     nop
     nop

     bne L2
     adds r2, #1
     cmp r2, r0
     bne L1
```

[perf_test_nop.tar.gz](https://github.com/OP-TEE/optee_os/files/1076902/perf_test_nop.tar.gz)

Could `bne` be the problem? Right now it seems to be the only possible problem.
Maybe branch predictor is not working in TrustZone??

**Comment by jeffy1009** [comment]
@MrVan @jenswi-linaro 

I found that by default ARM branch predictor (11th bit in system control register) is off.

The bit was indeed off in TrustZone (When checked with `read_sctlr` in `arm32.h`)

For imx, I see the code in `plat-imx/a9_plat_init.S` do not enable the bit for the branch prediction.

After enabling the branch prediction bit, TrustZone is as fast as Normal world.
I wonder if there is going to be any side effects in enabling branch prediction.

I don't exactly remember if this issue is applied to the other platforms.

**Comment by MrVan** [comment]
@jeffy1009 From ARMv7 RM, "In an implementation that includes the Security Extensions, this bit is Banked between the Secure and Non-secure copies of the register.", This bit should be enabled in tz secure world. other platforms that based on ARMv7, also needs this bit set, I think.

**Comment by jforissier** [comment]
@MrVan I agree that most ARMv7 platforms would probably benefit from having this bit (SCTLR.Z) set in `plat_cpu_reset_early()`. But note that some implementations may not support branch prediction, or on the contrary may not support disabling it. In both cases setting the bit is ignored. So, although it would not hurt to set it always, it might not make sense for some platforms. Since we have no common code for SCTLR initialization of ARMv7 CPUs, I think it's best to just fix platforms one by one, as needed.

@jeffy1009 would you please create a pull request to fix this issue for `plat-imx`?

**Comment by jeffy1009** [comment]
@jforissier I've created a pull request.

Also recently we tried to build TA with `-O2` flag put manually in the makefile in ta but we found that `-Os` flag which is set by default in `core/arch/arm/arm.mk` overrides it.

We see at most 2x slowdown for `-Os` compared to `-O2` in extreme cases.

Anyone who really need the performance might want to check this.

**Comment by etienne-lms** [comment]
Hi @jeffy1009.

Note that the directive `platform-cflags-optimization` can be overridden by platforms since in **arm.mk** script implements `platform-cflags-optimization ?=  ...`.

The usual way to do so is to add `platform-cflags-optimization = -O2` in your **.../plat-xxx/conf.mk**.

**Comment by jforissier** [comment]
In addition to what @etienne-lms said, also note that C flags may be added to the TA build step only with e.g., `CFLAGS_ta_arm32=-O2` or `CFLAGS_ta_arm64=-O2` (depending on whether your are building a 32-bit or 64-bit TA). Those flags appear *after* `platform-cflags-optimization`, this way you can override the optimization level.

**Comment by ghost11235** [comment]
Hello @jenswi-linaro ,
My primary goal is to find where overhead and bottle necks are in the system. 
I have also been utilizing the information from here to accelerate the system which has brought a significant performance boost using the -O2 option. 
On ultra96 ECDSA timing in seconds original_sign: 0.207 original_verify:0.141 optimized_sign:0.096 optimized_verify:0.064 where Linux and bear metal are about the same with sign:0.04 and verify at 0.047 using LibTomCrypt statically. 
On the RPI the performance numbers are approximately doubled as the running processor frequency is half that of the ultra96, both are A-53 processors that do not support out of order execution.

I am tying to trace down the causes of the overhead it possibly being abstraction, scheduling, or even other security features like rollback.
I have also been trying to get benchmark framework running to get more detailed timing info, [https://github.com/OP-TEE/optee_os/issues/3073](url).  

Any help you could provide to trace down the culprit of the performance overhead would be greatly appreciated.

Thanks in advance

**Comment by jenswi-linaro** [comment]
Hi @ghost11235,

This is a closed issue which I think addressed the original issue properly before being closed. Would you mind creating a new issue instead? By the way, make sure that you're using the same bignum library in both cases or that's another lose string.

**Comment by ghost11235** [comment]
@jenswi-linaro 
I have created a new [ticket](https://github.com/OP-TEE/optee_os/issues/3156)
Thanks
