### ISSUE TITLE
Client application with openssl on rpi3 and hikey

### ISSUE THREAD

**Issue by nikoskoutr** [OP-TEE/optee_os#1568]
Hello,
I understand that the rpi3 OP-TEE port runs on busybox, is there a way to have the openssl library to be used by a CA?

I also have the hikey board, as i can see openssl is pre-installed on the board, when i build my application, i define the flags:
`
-I$(TEEC_EXPORT)/include
-L$(TEEC_EXPORT)/lib
`
And i get an undefined function error when using openssl in my code. Is there a flag i can add to find the location of the openssl library that is used inside the board?

Thank you,
-Nick

**Comment by jforissier** [comment]
Hi @nikoskoutr,

> I understand that the rpi3 OP-TEE port runs on busybox, is there a way to have the openssl library to be used by a CA?

Assuming you're using https://github.com/OP-TEE/manifest/blob/master/rpi3.xml and https://github.com/OP-TEE/build/blob/master/rpi3.mk, one option is to add the OpenSSL git to manifest and to the build. Then you can build your CA with `-Ipath/to/openssl/include` and `-Lpath/to/openssl/lib -lcrypto` or similar. Don't forget to update the rootfs and add the OpenSSL shared libraries to `/lib` so that you CA can find them at runtime.

> I also have the hikey board, as i can see openssl is pre-installed on the board, 
> [...]
> And i get an undefined function error when using openssl in my code. Is there a flag i can add to find the location of the openssl library that is used inside the board?

What you can do is copy the required files (includes and libraries) to your build environment, then you can use the proper `-I...` and `-L... -l...` when compiling/linking your CA.

**Comment by nikoskoutr** [comment]
Thank you for your help once again!
I followed your instructions and everything works fine. I was afraid there were gonna be dependency issues with the openssl in the rpi3.
