### ISSUE TITLE
Booting optee - how to I do this?

### ISSUE THREAD

**Issue by ursus-the-bear** [OP-TEE/optee_os#1599]
Hi.

I have a security question. I would like to make sure that a file that makes calls to the secure world, that itself is in the normal world, has not been tampered with (lets use /bin/hello_world as an example). I was thinking of adding the hash value of the file as a parameter during runtime that gets passed to the TA. The TA could then check the hash value against a saved hash I have in a secure persistent storage. That way I could be sure that hello_world has not been tampered with. This leaves me with the problem of getting the hash value INTO the secure persistent storage.

I have heard about "golden values" and "platform configuration registers"  in TPM, is there something similar in optee?

Thanking you in advance
Ursus

**Comment by jforissier** [comment]
Hi @ursus-the-bear ,

Have you heard about Linux IMA/EVM? As far as I can tell, it does exactly what you're asking for (and more). See for instance https://wiki.gentoo.org/wiki/Integrity_Measurement_Architecture and https://wiki.gentoo.org/wiki/Extended_Verification_Module.

A TPM can indeed be used by IMA/EVM. And, it is possible to implement a TPM in software, see for instance https://www.microsoft.com/en-us/research/publication/ftpm-a-firmware-based-tpm-2-0-implementation/. With OP-TEE that would be a pseudo-TA and a linux driver, for instance. Probably not an easy thing to do, but should be doable.

Hopefully you can use a simpler ad hoc solution. To answer your question:
> This leaves me with the problem of getting the hash value INTO the secure persistent storage.

It has to be the same TA (same UUID) that writes and reads the hash, because a TA cannot access the secure storage that belongs to another TA. You could add a command to the TA to store the hash, with proper authentication of course (using public key signature for instance).

**Comment by ursus-the-bear** [comment]
Hi Jérôme. 

Thank you very much for your pointers. 

I hadn't heard of IMA/EVN yet but will look into it. It does seem like a lot of trouble to "just" check the integrity of one file... I do think I will try and find a simpler solution - I was thinking of adding the hash value as a #define to the TA. That way I wouldn't need to do anything to my environment (I am currently testing in QEMU but will be moving to a Pi3) other than compiling twice - once to get the runnable hello_world file and then again after adding the hash value on TA. 

I'll report back here so others will know if it works :o)

Cheers
Ursus
