### ISSUE TITLE
Travis CI. Pull request. Optimization consideration.

### ISSUE THREAD

**Issue by P1119r1m** [OP-TEE/optee_os#1615]
While providing several pull requests I found some inconvenience while submitting...
For example, while the change from pull request affects some predefined platform, Travis CI system builds  proposed version for a full bunch of platforms and it takes a lot of time and probably of CPU time of build machine.
The question is directed to the maintainers of continuous integration system.
Is it possible to modify rules to make only necessary set of rules from Makefile?

Thanks!

**Comment by jforissier** [comment]
Well, not really, because the purpose of CI tests is to test on as much configurations as possible. The reason being, there is no way to tell which platform/configurations are affected by a given change. It is not that uncommon that some change that "should not change anything" does actually break stuff...

That being said, we (Linaro) are working on setting up a different CI loop for OP-TEE. It will probably be based on Jenkins running on Linaro servers. It will hopefully be faster and have no time limit that we can't control. Stay tuned!

**Comment by P1119r1m** [comment]
@jforissier Ok. I got it! Thanks! That was just a consideration :)
