### ISSUE TITLE
News: Trust Issues: Exploiting TrustZone TEEs

### ISSUE THREAD

**Issue by lordqwerty** [OP-TEE/optee_os#1716]
https://googleprojectzero.blogspot.co.uk/2017/07/trust-issues-exploiting-trustzone-tees.html

Not sure if you have seen this but thought it might be of interest to you all. 
Sorry didn't know best way to get in touch.
Best,
Jorden

**Comment by jforissier** [comment]
Hi @lordqwerty,

Thanks for sharing. Just a quick comment about the relevance of the the issues to OP-TEE. The blog post essentially focuses on TA revocation, for which there is no mechanism in place in upstream OP-TEE. We do however provide an interface for loading and validating the TAs, so that TEEs based on OP-TEE can easily insert their own code and leverage RPMB and eFuses, or even use OP-TEE's own secure storage to store TAs (secure storage is authenticated and protected against rollback if the device has an RPMB partition).
