### ISSUE TITLE
General Question about scheduling

### ISSUE THREAD

**Issue by ursus-the-bear** [OP-TEE/optee_os#1721]
I was wondering if it could be possible to add a scheduler to the optee OS. The reason I am asking this is that I would like to have a daemon running in the secure world that starts when the OS boots. I was thinking that I could either write a scheduler for optee or maybe add pTA scheduling to the rich os (in my case Linux). Any ideas?

**Comment by etienne-lms** [comment]
The idea is nice but the context must be clarified. Mainly considering the TEE scheduling versus the REE scheduling.

In current optee design (linux and TEE sides), when the REE invokes the TEE, the TEE saves the caller REE thread state (non-secure context, saved/restored by atf or sm). While TEE (and TA) execution, REE ticks (actually all REE interrupts) that are trapped are forwarded straight to the REE, using the saved 'caller REE thread state' as REE execution context. Optee saves TEE execution state through means of the optee 'thread' support. When REE invokes the TEE through SMC 'return from foreign interrupt forward' sequence, optee resumes execution of the interrupted optee thread.

By adding some scheduling to optee, you could design something that use a secure timer (tick) to schedule a secure sequence, like a background task. Current optee design does not allow such a task to be interrupted by REE interrupts (foreign interrupts in OPTEE scope). But if foreign interrupts are masked, one could set some scheduling support on TEE side. Yet not easy. Synchro, rescheduling the REE, ...

I think the basics would be to create a 'task thread' object in optee_os/core that would handle a secure execution context. Task threads must be able to interrupt a running optee execution thread.

Since (if) foreign interrupts are masked during TEE scheduling, unexpected delays on REE side may be reported by REE (i.e linux warnings).

Just a note about pTAs. A pTA is only an API, it is not a optee entity. A pTA is the easy API for one to add services in optee_os 'core' accessible from REE and/or TAs (easy sine reusing the generic GP TEE API open/invoke/close). Hence I would rather talk of scheduling optee 'secure tasks' rather than 'pTAs'.

**Comment by ursus-the-bear** [comment]
@etienne-lms thank you for the detailed explanation :o)
