### ISSUE TITLE
Do we need to add the fno-builtin compile option?

### ISSUE THREAD

**Issue by prime-zeng** [OP-TEE/optee_os#1722]
We can't use gcc builtin function in OP-TEE(TAs)， so if we don't have the fno-builtin option, an linker error will be reported if we use the builtin functions by mistake, but i 'd rather to have this option and then report a compile error instead,  any idea?

**Comment by jforissier** [comment]
Hi @prime-zeng,

What do you mean? Do you have an example? (I suspect `-fno-builtin` is not the option you need but I want to make sure what problem you're trying to fix).

**Comment by jforissier** [comment]
I realize my answer above may sound a bit mysterious ;-) so let me explain a bit more.
I don't think `fno-builtin` is desirable for TAs because, although TAs are supposed to use the GP API i.e., `TEE_Malloc()` rather than `malloc()` etc., we do provide `libutils` which is a partial implementation of the standard C library, so any assumption that the compiler could do about the standard functions should be valid, hence no need to disable those assumptions with `-fno-builtin`. Unless I'm missing something, which is why I'm asking for an example of a problem that is fixed with `-fno-builtin`.

**Comment by prime-zeng** [comment]
For example,  if the have the code` printf("x")  `in the ta source,  it will report undefined reference to `putchar`.

**Comment by jforissier** [comment]
Ah, I see. So, builtins may generate calls to other standard functions that we may not have in our own libc (`libutils`). It makes sense, indeed.

Then I think what we need is `-ffreestanding` (which implies -fno-builtin`). Can you test it please?

**Comment by prime-zeng** [comment]
I jsut tried and it works, can you help to add it to the default cflags for TAs.

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_os/pull/1723

Thanks.

**Comment by prime-zeng** [comment]
https://github.com/OP-TEE/optee_os/pull/1754  resolve this problem, close it
