### ISSUE TITLE
How to print thread ID of TEE thread

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#1736]
I want to ask how can the thread ID of a TEE thread be printed in a TA.
I used the API `trace_ext_get_thread_id()` and I always get -1 as the id. 
Is there any other API that can be used ? Thanks

**Comment by jforissier** [comment]
Hi @a2t2,

What do you expect to do with a thread ID? TAs are single threaded.

**Comment by igoropaniuk** [comment]
@a2t2,
`trace_ext_get_thread_id` implementation for SW usermode is just a stub (check https://github.com/OP-TEE/optee_os/blob/master/lib/libutee/trace_ext.c#L43), because of the reason @jforissier has already mentioned

`trace_ext_get_thread_id` provides actual thread id when used in OP-TEE OS core (https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/trace_ext.c#L66)

**Comment by a2t2** [comment]
I was just trying to do a simple experiment where I wanted to see how a TA instance for which a session is not closed is handled by different TEE threads when the TA is invoked twice. If there is no API for thread ID, then it's fine. I will close the issue. Thanks.
