### ISSUE TITLE
QUERY - Need SPI reference sources for SPI bus driver, SPI controller and SPI application

### ISSUE THREAD

**Issue by ajithpv** [OP-TEE/optee_os#1741]
Hi,
I would like to implement SPI (including the bus driver, controller and test application for the validation) on OP-TEE.
So far, the only reference I have seen is the HiKey implementation and I have following doubts on the same.
1) The `SPI_BASE` is registered as `MEM_AREA_IO_NSEC` in the _"core/arch/arm/plat-hikey/main.c"_.
Whether this SPI implementation is secure or sharing with the normal world SPI? 
2) Whether HiKey SPI implementation using SPI bus driver (I'm referring this to Linux SPI source files)? If yes, which source file is the bus driver in HiKey SPI implementation? I'm assuming spi_init() is using only the SPI controller but no generic SPI bus register methods.
3) Whether `spi_test()` using any normal world to TA side application flow? I have seen all loop back tests are carryout in the same _"core/arch/arm/plat-hikey/spi_test.c"_ file itself. Is there any host to TA application available for SPI to test.

If any other SPI implementation is available with secure path, then I would like to get that also.
Thank you in advance.

**Comment by vchong** [comment]
1. Shared, so if both try to use it at the same time, collision will happen. There's not a mechanism mature enough right now to sync access to shared io (not just spi) between NW and SW.
2. This is a relatively simple/direct implementation, and not as advanced or similar in any way, shape or form to the Linux implementation. I'm not sure if the terminologies match 1:1 directly per se, but I suppose you can assume that `spi.h` 'is' the (simple) bus/protocol driver, and `pl022_spi.c` as the controller driver (that implements/registers the functions required/specified by `spi_ops` in `spi.h`. There are no other controller drivers implemented atm afaik. `spi_init()` is just to init some registers to enable SPI operations on the HiKey board.
3. No. Everything is confined to SW atm. If you want to 'connect' the spi functions from NW, you need to write a pseudo-TA to call those functions.

**Comment by ajithpv** [comment]
Thank you very much @vchong for the detailed explanation. This gives me a better understanding on the OP-TEE side SPI functionalities. I will check this out and try to implement mine corresponding to the references.

**Comment by ajithpv** [comment]
I would like to know how I can add a SPI client driver to access the controller driver. I'm assuming that the pl022_spi.c as a SPI master in this case and I have a SPI client driver (slave/device which is connected external) for doing the operations.
@vchong could you please clarify this?

**Comment by vchong** [comment]
Sorry but I don't get it. It would help to explain your master-slave connection/setup and the SW components running on each of them. In any case, only the HiKey board uses SPI/pl022 atm. Are you saying that you want to use the HiKey board as an SPI slave? If that's the case, I've not really tried it myself since it's not a common case, but I suppose you can try setting the pl022 to slave mode (https://github.com/OP-TEE/optee_os/blob/master/core/drivers/pl022_spi.c#L480) and see if it works.

**Comment by ajithpv** [comment]
@vchong Sorry, let me put it in this way for better understanding.
First of all, I'm trying to implement SPI on another platform but, not on HIkey (Hikey is the reference for me to implement it). When compared to the Hikey, then in my case, Hikey board is SPI master (in other words pl022 is master). What I would like to know is how to connect a slave SPI device (another chip which works based on SPI data) to hikey board SPI master. The Hikey board SPI master will trigger all the SPI read and write and SPI slave device actually perform the operation based on that.
Is this connection involves just to make the chip select to the correct device or any other configuration (to hook up the slave SPI device to SPI Master) needed to implement in OP-TEE side?

**Comment by vchong** [comment]
Does your platform use PL022 as well? If not, the code can be different to varying degrees. Even if it does, your platform will still be different wrt how you need to configure the mux-ed io pins to work as gpio pins or spi pins.

In the case of spi on hikey op-tee, all you have to do is to just physically connect the client device to the hikey master and call the functions you see in `spi_test.c` along with the proper settings, e.g. clock, speed, mode, data size, etc. If you use the `spi_test_with_builtin_cs_control()` example, then the pl022 driver will take care of toggling the CS pin for you so you don't even have to worry about it.

There's no need to "make the chip select to the correct device" because, unlike i2c, spi doesn't use any addressing or device id scheme, so all slave devices will react to the same chip select signal.

There's also no need to add a client driver to the hikey board. At this point, again, it's not like linux where you have to specify the client device in the device tree in order to select the proper controller driver.

HTH

**Comment by ajithpv** [comment]
@vchong Thank you again for your wonderful support. My platform is not based on PL022 and I have understood that the corresponding changes have to be made in-order to make it work on my platform.
Let me try with the available resources and see how it going forward.
Currently, my concerns are already answered and I think we can close this thread.
