### ISSUE TITLE
Code for interrupt list for OPTEE on Hikey

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#1762]
I am looking for the code that shows list of interrupts that trigger a world switch from secure world to normal world when OPTEE is run on the hikey 620 board. I am interested in understanding the scheduling done by linux kernel when TEE is invoked.

Based on a previous [question](https://github.com/OP-TEE/optee_os/issues/1724), and searching online, I find that there can be a timer interrupt that can be used to periodically switch from secure world to normal world via the secure monitor. I want to see the list of interrupts that are configured for OPTEE on the hikey board. I want to request if you could point me to the code (either on optee github or on arm-tf github), where list of interrupt exist to show whether on hikey there is a secure timer being used to help linux schedule time for threads made calls to TEE.

Thanks.

**Comment by etienne-lms** [comment]
Considers the Linux timers. They are used by Linux for some scheduling purposes, whatever if there is an TZ secure world (optee?) or not. The scheme is something like:
- Linux schedules in a Linux thread.
- A timer interrupt occurs: from the irq handler of Linux, Linux can schedule out the active thread and schedule in another thread. 
- Later on, Linux can  schedule back the former Linux thread , on the same cpu or on another cpu.

When using an optee, the same happens. For each non secure interrupt trapped while TEE is executing, TEE suspends the execution, invokes back the REE into the REE caller Linux thread which is simply asked to return back to TEE: https://github.com/linaro-swg/linux/blob/optee/drivers/tee/optee/rpc.c#L423. If the REE handling of the interrupt schedules out the active Linux thread, then TEE must wait Linux to schedule back the previously active Linux thread so that REE returns to TEE and resume the TEE thread execution.

**Comment by a2t2** [comment]
Thank you for your response.
