### ISSUE TITLE
Query: About TEE_Panic()

### ISSUE THREAD

**Issue by airbak** [OP-TEE/optee_os#1765]
TEE_Panic() is called anywhere, when panic, it just print the information of the function which call TEE_Panic(), but it is hard to find who and where call this function.
Sample:
ERROR:   USER-TA:TEE_WriteObjectData:716: Panic 0xffff0006
ERROR:   [0x0] TEE-CORE:tee_svc_sys_return_helper:258: TA panicked with code 0xffff0006 usr_sp 0x130530 usr_lr 0x159983

From the log, only know TEE_WriteObjectData panic, but can not find who call TEE_WriteObjectData from usr_lr.

Cound you dump function call trace in TEE_Panic(), thanks.

**Comment by jforissier** [comment]
Hi @airbak,

That would be quite helpful indeed.

The problem is, we don't have stack unwinding code in the user libraries, so we can't do much in the `TEE_Panic()` function itself. But we do have unwinding code in the TEE core (`__print_stack_unwind_arm32()`, `__print_stack_unwind_arm64()`). So perhaps we can re-use it after `syscall_panic()` is entered. We don't have a `struct abort_info` at this point however, so maybe we need to fake one.

@jenswi-linaro do you think it is a reasonable approach?

**Comment by airbak** [comment]
Thanks, it have been solve by https://github.com/OP-TEE/optee_os/commit/0e1c6e8e35c64fde0c31a34a68ca349240604c86
