### ISSUE TITLE
malloc() error in optee os

### ISSUE THREAD

**Issue by FormerBuckeye** [OP-TEE/optee_os#1792]
Hi all,

I am trying to allocate an array of type of char in optee os like:

str = (unsigned char *)malloc(strlen((const char *)str1)+100);

But it shows one error called:

ERROR:   TEE-CORE: Assertion 'ct != -1 && threads[ct].state == THREAD_STATE_ACTIVE' failed at core/arch/arm/kernel/thread.c:1068

Could you help me with that? Thanks!

**Comment by igoropaniuk** [comment]
Hi @FormerBuckeye,

I guess this assertion failure occurs not exactly while calling `malloc`. (as `malloc` implementation in the TEE core is using spilocks for syncronization, but assertion fails inside `void thread_add_mutex(struct mutex *m)`), 

I suppose that problem is in some another line, where your are trying to lock a mutex. If it's true (that you are using mutexes), then seems that you are trying to lock it inside interrupt/abort handler.

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
