### ISSUE TITLE
OP-TEE hangs when pager is enabled on  i.mx6q sabresd board

### ISSUE THREAD

**Issue by TEE-OS** [OP-TEE/optee_os#1795]
I enable the pager on i.mx6q sabresd board, and I config the platform_config.h as follow:

```
#define CFG_TEE_RAM_START		TZSRAM_BASE
#define CFG_TEE_LOAD_ADDR		TZSRAM_BASE
```

However, OP-TEE stops at:
```
DEBUG:   [0x0] TEE-CORE:core_mmu_alloc_l2:249: L2 table used: 1/4
INFO:    TEE-CORE:
INFO:    TEE-CORE: Pager is enabled. Hashes: 1504 bytes
```

Could anybody tell me on which board the pager can run?

**Comment by jenswi-linaro** [comment]
Physical boards Hikey and Juno
Emulators/simulators QEMU and FVP

**Comment by TEE-OS** [comment]
It seems that I should set CFG_PAGEABLE_ADDR in the command line. What does this address mean? 
When I set it to be TZ_DRAM_BASE (0x4E100000), it goes further, and stops at hash verification.
What should I set CFG_PAGEABLE_ADDR to be?
```
DEBUG:   [0x0] TEE-CORE:init_runtime:245: hash pg_idx 5 hash 0x4e02cab8 page 0x50f05000
DEBUG:   [0x0] TEE-CORE:init_runtime:245: hash pg_idx 6 hash 0x4e02cad8 page 0x50f06000
ERROR:   [0x0] TEE-CORE:init_runtime:249: Hash failed for page 6 at 0x50f06000: res 0xffff000f
ERROR:   [0x0] TEE-CORE: Panic at core/arch/arm/kernel/generic_boot.c:250 <init_runtime>
ERROR:   [0x0] TEE-CORE: Call stack:
ERROR:   [0x0] TEE-CORE:  0x4e0029adx
ERROR:   [0x0] TEE-CORE:  0x4e006119x
ERROR:   [0x0] TEE-CORE:  0x4e02d55bx
ERROR:   [0x0] TEE-CORE:  0x4e000158x
```

**Comment by jenswi-linaro** [comment]
@TEE-OS, check the boot loader source hopefully we can find where it copies the pageable part of OP-TEE. It has obviously once been at the address `0x4E100000` but appears to have been partially overwritten.
@yanyan-wrs, any advice?

**Comment by TEE-OS** [comment]
@jenswi-linaro my uboot doesn't config the CFG_PAGEABLE_ADDR, and I configure it in the command line by setting CFG_PAGEABLE_ADDR=0x4E100000 in command line:
`make PLATFORM=imx-mx6qsabresd ARCH=arm CFG_BUILT_IN_ARGS=y CFG_PAGEABLE_ADDR=0x4E100000 CFG_NS_ENTRY_ADDR=0x12000000 CFG_DT_ADDR=0x18000000 CFG_DT=y CFG_PSCI_ARM32=y DEBUG=y CFG_TEE_CORE_LOG_LEVEL=4 CFG_BOOT_SYNC_CPU=n CFG_BOOT_SECONDARY_REQUEST=y`

From the logic of init_runtime(), I think the CFG_PAGEABLE_ADDR should be set `__pageable_part_start` (I print it in the log, and it is 0x4E033000). However, OP-TEE still hangs at hash verification. So I think it is not the CFG_PAGEABLE_ADDR that causes the problem.

**Comment by etienne-lms** [comment]
Hi, `CFG_PAGEABLE_ADDR` should be set to where the bootloader loads the "pageable" image of optee_os: the generated binary file **tee-pageable.bin** or **tee-pageable_v2.bin** (they are the same).

If your bootloader loads a regular **tee.bin** , the "pageable" image is likely the address passed to optee_os as boot argument: the last part of the single loaded image.

**Comment by TEE-OS** [comment]
Up to now, I locate the place where the hash verification fails: the area of pageable_part. The verification of the init area passes flawlessly, but even the first page of the pageable_part doesn't pass. It seems that the back store area for pageable_part is not overwritten, and I don't know why its verification is not ok.

**Comment by TEE-OS** [comment]
Hi @etienne-lms @jenswi-linaro , the memory address of the tee.bin (after generated by `gen_hashed_bin.py`) is as follows. 
```
pageable_part: 0x4E03_3600 - xxxxxx
temp_hash: 0x4E03_3000 - 0x4E03_3600
init: 0x4E02_D000 - 0x4E03_3000
unpaged: 0x4E00_0000 - 0x4E02_D000
```
Although the `__pageable_part_start` in kern.ld is set to be `0x4E03_3000`, the `gen_hashed_bin.py` appends the hash values to `tee.bin` between `init `area and `pageable `area, and the hash values occupy `0x600 `bytes, so actually the pageable_part area starts from `0x4E03_3600`. 
Then should I set `CFG_PAGEABLE_ADDR ` to be `0x4E03_3600`?

**Comment by etienne-lms** [comment]
>The following code copies init and pageable_part areas to paged_store, and I'm confused that why they use different mem functions for init and pageable_part area?
```
	memmove(paged_store + init_size,
		phys_to_virt(pageable_part,
			     core_mmu_get_type_by_pa(pageable_part)),
		__pageable_part_end - __pageable_part_start);
	memcpy(paged_store, __init_start, init_size);
```
The `memmove()` copies (moves) the `pagestore_part` (loaded by bootloader) from DDR to its final location in DDR. We use `memmove()` since loader may have loaded pagerstore at a location that overlaps the final pagestore location allocated in DDR by optee inits.
The `memcpy()` copies the 'init' sections from internal RAM (as loaded by bootloader) to the pagestore in DDR.

> (...) so actually the pageable_part area starts from 0x4E03_3600.
> Then should I set CFG_PAGEABLE_ADDR to be 0x4E03_3600?

**tee.bin** stores 3 images:
- the formatted header structure: meta data only used by the bootloader.
- the _boot image_: unpaged + init (paged content) + temp_hash (paged sections hash table)
- the _pageable_part_: paged content excluding paged content used at init (before pager is enabled).

The optee boot/init scheme is:
- Bootloader is expected to loaded the _boot image_ in internal RAM and the _pageable_part_ in external RAM.
- At early optee init, from **generic_entry_aXX.S**, the hash value table is moved to another target location (in internal RAM).
- Then, in **generic_boot.c**, the full pagestore is stored in DDR at a target location: paged init data (_init_, copied from internal RAM) + non-init pagestore data (_pageable_part_, loaded by bootloader).

From these scheme, you can see that _pageable_part_ from **tee.bin** should not be loaded at 0x4E03_3600 (see above) but should be loaded in secure external RAM at any location:
- bootloader can tell optee where it has been loaded through boot argument `r0`/`x0`.
- or optee can hardcode this load address using `CFG_PAGEABLE_ADDR`.
Optee inits will take care of moving _pageable_part_ to the right location (allocated at runtime).

**Comment by TEE-OS** [comment]
@etienne-lms Thanks for your reply. 

I use uboot to load _**tee.bin**_, and don't load **_tee-pageable.bin_** as I thought it was included in tee.bin. From your explanation, it seems that I also need to manually load _**tee-pageable.bin**_ to some place of secure DRAM, such as using such command in uboot:` tftp tee-pageable.bin 0Xxxxxxxxx`, and then set `CFG_PAGEABLE_ADDR `to that address. Is my understanding right?

**Comment by etienne-lms** [comment]
> I use uboot to load tee.bin, and don't load tee-pageable.bin as I thought it was included in tee.bin. 

You are right, **tee-pageable.bin** is included in **tee.bin**.

> (...)  it seems that I also need to manually load tee-pageable.bin to some place (...)

No, you should not need to.


I have understood your use u-boot loads **tee.bin** at some place. As state before, **tee.bin** is a formatted file and u-boot must read the image header structure to know where the unpaged sub-image is (inside the loaded **tee.bin**) and where this sub-image must be loaded in memory before u-boot can branches into (unpaged load address = optee entry point).
(note: 'unpaged sub-image' in **tee.bin** contains _unpaged_, _init_ and _temp_hash_.)

The same way, u-boot should use the **tee.bin** header structure to find where the _pageable_part_ sub-image is inside the loaded **tee.bin**. Then u-boot should copy the _pageable_part_ image to the target `CFG_PAGEABLE_ADDR`.

This description above assumes optee_os was built with `CFG_PAGEABLE_ADDR` set to some RAM physical address. Note that there are alternate ways to load the optee_os into memory.

**Comment by jforissier** [comment]
It would be good if we had some platform using uboot in https://github.com/OP-TEE/manifest.git. And later perhaps, upstream OP-TEE loader code to uboot?

**Comment by TEE-OS** [comment]
Hi @etienne-lms Thanks, I get it.  It seems that I need to  1) modify my uboot to load the _**pageable_part**_ to some secure DRAM place, or 2) modify the **_generic_boot_a32.S_** (at the same place when _init_ and _hash_ are relocated) to load _pageable_part_ to some secure DRAM place.

**Comment by etienne-lms** [comment]
If you are using an optee 2.5.0, here is an alternate way. Binary file **tee.bin** stores a header + 2 images. The 2 images are already generated as separated files: **tee-pager_v2.bin** and **tee-pageable_v2.bin**.

I assume you statically know the target internal RAM location (as set in `CFG_TEE_LOAD_ADDR`), call it _myloadaddr_. And I assume you statically know the secure DRAM start address, call it _tzdrambase_.

First build optee with `CFG_PAGEABLE_ADDR=`_tzdrambase_.

Then change u-boot boot sequence. Instead of loading **tee.bin** at some place, load **tee-pager_v2.bin** at _myloadaddr_ and **tee-pageable_v2.bin** at _tzdrambase_. Then u-boot can branch into _myloadaddr_. This should boot ok.

As @jforissier stated, a better way would be to have native optee support in u-boot: some piece of code to parse optee header structures and allow boot commands to inherit from optee header structure directives.

**Comment by TEE-OS** [comment]
Hi @etienne-lms , Thanks for your help. I can run pager on i.mx6q now.

**Comment by etienne-lms** [comment]
Great.
