### ISSUE TITLE
Query regarding condvar usage

### ISSUE THREAD

**Issue by surendran90** [OP-TEE/optee_os#1798]
Hi all,

I tried to use condvar inside GPIO driver (usage in IRQ mechanism).
 
**getvalue API in gpio driver:**
```
mx_gpio_get_value (unsigned int gpio_pin)
{
...
...
...
#ifdef     INTERRUPT_MODE
           mutex_lock(&pd.mu);
           condvar_wait(&pd.cv, &pd.mu);
           mutex_unlock(&pd.mu);
#endif
`...`
...
}
```
**In Interrupt service routine:**

```
itr_return gpio_itr_cb(struct itr_handler *h)
{
        pd = *(struct imx_gpio_data*)(h->data);        
        condvar_signal(&pd.cv);
	...
	...
        return ITRR_HANDLED;
}
KEEP_PAGER(gpio_itr_cb);
```

Current thread is waiting and not waking-up ,even though it is signaled from ISR.

As per code, we call __condvar_wait , which calls wq_wait_final() and flow goes till thread rpc and waits.
How does the condvar_signal unlocks and resume the condvar_wait?

**Comment by jenswi-linaro** [comment]
`condvar_signal()` can only be called from a thread context as it may need to do RPC in order to wake up a waiting thread. An interrupt handler is not in a thread context.

This is an issue I've also faced when testing stuff and I don't have a good solution to that. We need a way to signal (without leaving secure world) to normal world that a thread can be unblocked. An non-secure SGI would fill this purpose, unfortunately are all 8 non-secure SGIs already used for other purposes in Linux. We'll need to fix this sooner or later, but it will be difficult as it likely means changing the SGI allocation in Linux.

**Comment by surendran90** [comment]
Thanks Jen

I'm trying to implement interrupt mode in OPTEE gpio driver.
Is there any-other methods that can be used in interrupt mode other than condvar ? To my understanding mutex also cannot be used in handler.

**Comment by jforissier** [comment]
Correct, mutexes may need to RPC into NS world, too, so they cannot be used either.
Polling and spinlocks look like the only viable option currently :(

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
