### ISSUE TITLE
Error TEEC_ERROR_ITEM_NOT_FOUND on TEEC_InitializeContext

### ISSUE THREAD

**Issue by Makht916** [OP-TEE/optee_os#1806]
Hi,

I have downloaded AOSP "https://source.android.com/source/devices" and OPTEE "https://github.com/linaro-swg/optee_android_manifest/tree/hikey-n-4.9-master" and put it on the hikey620 board. After that I make an application that access the tee_client_api function like TEEC_InitializeContext(NULL, &ctx). I build the application and put in onto the board but when I run the app it throws the error "**TEEC_ERROR_ITEM_NOT_FOUND**".  Why I am getting this error and how to resolve it?

Second, this might be very lame question but I don't understand where to run xtest command? What it is mean by command prompt, which command prompt is it? And how to access this command prompt?

Many thanks in advance.

Regards,

**Comment by vchong** [comment]
> I have downloaded AOSP "https://source.android.com/source/devices" and OPTEE "https://github.com/linaro-swg/optee_android_manifest/tree/hikey-n-4.9-master" and put it on the hikey620 board.

You mean you've followed the instructions in https://github.com/linaro-swg/optee_android_manifest/tree/hikey-n-4.9-master to download and build the source, and then flashed the built images onto the hikey board? Are you sure you've followed the instructions properly, because they don't use https://source.android.com/source/devices. It would be helpful if you list the steps you took and include error logs.

> After that I make an application that access the tee_client_api function like TEEC_InitializeContext(NULL, &ctx). I build the application and put in onto the board but when I run the app it throws the error "TEEC_ERROR_ITEM_NOT_FOUND". Why I am getting this error and how to resolve it?

Is your app an android app, or regular linux executable?
What is the output of `dmesg | grep tee`? If it returns empty, then you probably don't have the TEE driver in your kernel build.
If the driver is ok, then is the `tee-supplicant` service up and running? If not, can you manually start it?
If the `tee-supplicant` is ok, can you verify that `tee_helloworld` works? That would verify somewhat the running condition of your board before trying to run your own app.

>  What it is mean by command prompt, which command prompt is it? And how to access this command prompt?

The same place where you run your app. It's probably not advisable to run `xtest` yet, because at this point it sounds like you might not have a good build/images.

**Comment by vchong** [comment]
>> What it is mean by command prompt, which command prompt is it? And how to access this command prompt?

> The same place where you run your app. It's probably not advisable to run xtest yet, because at this point it sounds like you might not have a good build/images.

Are you maybe launching your app by clicking/tapping at the app icon on your home screen instead of executing it from a command (line) prompt like below?

```
root@HiKey:/ hello
Hello, world!
```

**Comment by Makht916** [comment]
Hi,

Thanks for your quick response.

First, I downloaded the AOSP from "https://source.android.com/source/devices" and flash it onto my hikey620 board. It works properly. After that, I downloaded OP-TEE from "https://github.com/linaro-swg/optee_android_manifest/tree/hikey-n-4.9-master", it builds and then I flash it onto hikey board. Flashing was successful and it get no error there.

I make an android app which uses tee_client_api function to initialize TEE on board like TEEC_InitializeContext(NULL, &ctx). I put this app onto the hikey and there I get error "TEEC_ERROR_ITEM_NOT_FOUND".

This dmesg | grep tee command should be run on the console of hikey board? Right? 

App will launch like a normal android app on board? Do I need to execute it via console?

I am new to this board :)

Regards,

**Comment by vchong** [comment]
Yes, run `dmesg | grep tee` from the console (aka command (line) prompt) or adb shell of hikey board. We only build command line or non graphical linux executables here, no android apps, which is why you had to do the integration to the android app part yourself, but it shouldn't matter whether you launch your android app via the home screen or console.

Just remembered something - maybe SELinux is blocking your app from accessing the TEE driver, causing the error. If that's the case, disable SELinux (`setenforce 0`) to see if it helps. See https://github.com/OP-TEE/optee_os/issues/903 for details.

**Comment by Makht916** [comment]
Hi @vchong 

I have ordered UART cable from https://www.seeedstudio.com/96Boards-UART-p-2525.html and I don't know how much time it will take to come. In the meanwhile, I want to know that do we have any workaround to set selinux to permissive without using console?

Function fd = open(devname, O_RDWR) is returning -1 and I have re-installed OP-TEE "https://github.com/linaro-swg/optee_android_manifest/tree/hikey-n-4.9-master" on two different boards, both of which produce same error. So, I am coming to point that this may be due to selinux.

Many thanks in advance.

Regards,

**Comment by vchong** [comment]
If you're using `boot_fat.uefi.img`:
In `device/linaro/hikey/bootloader/EFI/BOOT/grub.cfg`, add `androidboot.selinux=permissive` to the end of lines that start with `linux /kernel.
The full line should look something like:
`linux /kernel console=ttyFIQ0 androidboot.console=ttyFIQ0 androidboot.hardware=hikey firmware_class.path=/system/etc/firmware efi=noruntime androidboot.selinux=permissive`

If you're using `boot.img`, add `androidboot.selinux=permissive` to `BOARD_KERNEL_CMDLINE` defined in `device/linaro/hikey/hikey/BoardConfig.mk`.

**Comment by Makht916** [comment]
Thanks for your quick response.

Still facing the same issue, do we have any other way to open /dev/tee0 without having a root permission? 

Regards,

**Comment by vchong** [comment]
If you'd disabled SELinux and are still having the same issue then there's probably no point messing with permission issues anymore.

Best wait for the uart to check the stuffs mentioned in https://github.com/OP-TEE/optee_os/issues/1806#issuecomment-329055067.

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
