### ISSUE TITLE
Is it ok to make optee position independent?

### ISSUE THREAD

**Issue by MrVan** [OP-TEE/optee_os#1825]
Just have such an idea to make optee could be position independent. I would like to hear more comments before implementing it.

Thanks,
Peng

**Comment by jenswi-linaro** [comment]
What do you mean by position independent, compiled with -pic/-pie?

**Comment by MrVan** [comment]
Compiled with pie and modify the asm code

**Comment by jenswi-linaro** [comment]
So that means that before the c-code can be called some assembly routine need to update the binary according to the relocation entries?

When it comes to how to make the assembly code position independent I think we should start with small pieces to make sure that we can agree on the method you use before you put too much work into it.

**Comment by MrVan** [comment]
Thanks.
