### ISSUE TITLE
Can i invoke a TA using an interrupt?

### ISSUE THREAD

**Issue by Matombo** [OP-TEE/optee_os#1847]
I want to periodically invoke a TA and ofc it should not be interceptable by the normal world. I therefore use a hardware timer with secure only access that sends interrupts catched by OP-TEE. However is there any functionality to open a TA from the interrupt handler? I tried using the functions of tee_ta_manager directly, however there is a mutex involved which is forbidden during an interrupt.

**Comment by jbech-linaro** [comment]
I don't think that is possible in the current implementation and I'm not sure if that is how you would like to implement/use it. I would instead suggest to implement APIs where a TA could register for certain interrupts. One use case I've been thinking about is if you have any peripheral connected which you are using from a TA (neither is that implemented yet). That TA should be able to register for interrupts coming from that peripheral to be able to avoid polling etc.

We have discussed all this, but we haven't had time to look into it yet. Eventually we will do it in the future, but when that happens I don't dare to say, since we are a bit short on engineers compared to the big wish list. If you have time and are willing to prototype something, then we would not say no and we would of course help out as much as we can.

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again.

// OP-TEE admins
