### ISSUE TITLE
Booting OP-TEE in RPi3

### ISSUE THREAD

**Issue by atm849** [OP-TEE/optee_os#1855]
I have done the steps to boot the OPTEE on RPI3. The problem is that I faced this message "sh: can't access tty; job control turned off" and I can't use sh to run my program.

**Comment by jbech-linaro** [comment]
Since it's been a long time since I had my RPi3 running I did a setup from scratch today and I had no issues at all, it worked just fine. Both with the uSD-card (default) and with NFS-boot.

Is it based on some old setup? If yes, have you updated everything?

Are you using the [UART-cable|https://github.com/OP-TEE/build/blob/master/docs/rpi3.md#61-debug-cable--uart-cable]? If not I guess that is the issue. Using HDMI doesn't work by default in this setup, there is more information about that in #1505 and #1367 .

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
