### ISSUE TITLE
Issue:  Load TA is blocked by libmpa

### ISSUE THREAD

**Issue by airbak** [OP-TEE/optee_os#1862]
xtest gp_7507 generate RSA key spent a long time. 
Load another TA is blocked at ecc_make_key_ex(), it wait for the gp_7507 RSA key finish.
It could be caused by the get_pool() and put_pool() in tee_ltc_provider.c.
I think the libmpa may use dynamic malloc instead of static memory pool.
Load TA should not be blocked, please help to solve it, thanks!

LOG:
FLOW:    [0x0] TEE-CORE:plat_prng_add_jitter_entropy:97: plat_prng_add_jitter_entropy: 0x9D
FLOW:    [0x0] TEE-CORE:plat_prng_add_jitter_entropy:97: plat_prng_add_jitter_entropy: 0x84
FLOW:    [0x0] TEE-CORE:plat_prng_add_jitter_entropy:97: plat_prng_add_jitter_entropy: 0xCE
FLOW:    [0x0] TEE-CORE:trace_syscall:161: syscall #27 (syscall_cryp_obj_alloc)
FLOW:    [0x0] TEE-CORE:trace_syscall:161: syscall #54 (syscall_obj_generate_key)                                                 ------------ thread[0] generate RSA key spent a long time
DEBUG:   [0x1] TEE-CORE:tee_ta_init_pseudo_ta_session:259: Lookup pseudo TA 8f194022-c9a2-11e6-9d9d-cec0c932ce01                  ------------ thread[1] CA open a new TA 8f194022-c9a2-11e6-9d9d-cec0c932ce01
DEBUG:   [0x1] TEE-CORE:tee_ta_init_user_ta_session:632: Lookup user TA 8f194022-c9a2-11e6-9d9d-cec0c932ce01 (early TA)
DEBUG:   [0x1] TEE-CORE:tee_ta_init_user_ta_session:632: Lookup user TA 8f194022-c9a2-11e6-9d9d-cec0c932ce01 (REE)
FLOW:    [0x1] TEE-CORE:plat_prng_add_jitter_entropy:97: plat_prng_add_jitter_entropy: 0xD6
DEBUG:   [0x1] TEE-CORE:__wq_rpc:60: sleep thread 1 0x3e0ad9f8 -2 core/lib/libtomcrypt/src/tee_ltc_provider.c:586                 ------------- thread[1] get_pool,   load_elf->ta_open->ecc_populate_ltc_public_key->fortuna_reseed->ecc_make_key_ex  
FLOW:    [0x0] TEE-CORE:wq_promote_condvar:173: promote thread 1 0x3e0ad9f8 core/lib/libtomcrypt/src/tee_ltc_provider.c:608            ------------ thread[0] put_pool()
DEBUG:   [0x0] TEE-CORE:__wq_rpc:60: wake  thread 1 0x3e0ad9f8 -3 core/lib/libtomcrypt/src/tee_ltc_provider.c:612
FLOW:    [0x0] TEE-CORE:trace_syscall:161: syscall #24 (syscall_cryp_obj_get_info)
FLOW:    [0x0] TEE-CORE:trace_syscall:161: syscall #26 (syscall_cryp_obj_get_attr)
FLOW:    [0x0] TEE-CORE:trace_syscall:161: syscall #24 (syscall_cryp_obj_get_info)
*DEBUG:   [0x1] TEE-CORE:ta_load:317: ELF load address 0x101000

**Comment by jenswi-linaro** [comment]
The problem with asymmetrical crypto operations is that they requires much memory, but we must at the same time guarantee that a asymmetrical crypto operation doesn't fail due to out of memory. That's what why we have a memory pool dedicated to this.

If we where to allocate this from the heap instead it would have to be much larger. But we'd have two problems left:
1. we can't guarantee that a asymmetrical crypto operation will not fail due to out of memory
2. it would have very bad impact on paging as quite a few additional physical pages will be permanently allocated by the heap

Long term we'll get rid of the asymmetrical crypto operation when loading a TA by installing it in an earlier step where it's encrypted and protected with a symmetrical crypt instead.

**Comment by airbak** [comment]
Thanks for your reply.
