### ISSUE TITLE
TUI implementation

### ISSUE THREAD

**Issue by tesmnorth** [OP-TEE/optee_os#1898]
Hello everyone, 

I am interested in OP-TEE and developed Trusted App. I am learning about OPTEE structed what I need. So, I am wondering about TUI. But, I dont know some technical details like graphic interface, drm etc. Can you give me an advice how can I started this and what kind of documentation can I read about that (except GP TUI specification)

**Comment by vchong** [comment]
@tesmnorth TUI code has been removed due to lack of usage, although you can study the removed code here: https://github.com/OP-TEE/optee_os/pull/1842/files. Also, as mentioned in https://discuss.96boards.org/t/optee-android-in-hikey960/2850/87https://github.com/jforissier/secvideo_demo is a good proof of concept for secure image display despite being a bit old and having a couple of issues as discussed in https://github.com/jforissier/secvideo_demo/issues/2. Other than that, there isn't really any other graphic interface or drm related details available.
