### ISSUE TITLE
What will happen if Secure Group 1 irq triggered which affinity routing to another core not in Secure world?

### ISSUE THREAD

**Issue by Yanjiong** [OP-TEE/optee_os#1930]
Hi Expert,

What will happen if Secure Group 1 irq triggered which affinity routing to another core running in Non-Secure world?

It seems the irq lost in my case.

BR.
Wang Yanjiong

**Comment by jenswi-linaro** [comment]
Please give a bit more context. Are you using GIC v2 or GIC v3? How is interrupt routing configured? Armv7 or v8?

**Comment by Yanjiong** [comment]
Thanks Jens.

It's ARM V8 core with GIC v3. Since ITARGET just support 8 cores, we use Affinity Routing instead. 
The irq was configured as Secure Group 1 by IGROUP and IGRPMOD and it's affinity routing was set to any core.

**Comment by jenswi-linaro** [comment]
I'm not that familiar with all the ways GICv3 can be configured. When it comes to OP-TEE and ARMv8, most of the GIC configuration is done outside OP-TEE, in ARM-TF. Perhaps checking with the ARM-TF guys or if @davwan01 can advice here.

**Comment by Yanjiong** [comment]
Thanks.

From ATF docs:
1.3.1.   Secure-EL1 interrupts
...
    CSS=1, TEL3=0. Interrupt is routed to the FEL when execution is in non-secure state. This is an invalid routing model as a secure interrupt is not visible to the secure software which violates the motivation behind the ARM Security Extensions.

I don't understand this clearly. Why it's invalid? How it's handled in ATF? @davwan01

**Comment by davwan01** [comment]
@Yanjiong @jenswi-linaro , Sorry, I didn't notice this thread.

> What will happen if Secure Group 1 irq triggered which affinity routing to another core running in Non-Secure world?

(Assume you're using aarch64 mode with GICv3 affinity mode)
If the SG1 (Secure Group 1) interrupt targets to other core(s), then the core which successfully responded this interrupt (coreA) will handle it. It's nothing to do with the core running optee.
For coreA, if it's running in non-secure world, then for affinity mode, this interrupt will be triggered by FIQ not IRQ. The idea behind this is that the core knows you want to handle the interrupt which targets another secure world, so a "secure world switch" is required anyway. So FIQ will take the core to EL3 to do that switch (you should configure FIQ trapped to EL3 correctly). In EL3, arm-tf will check the reason of FIQ by reading the ID of the interrupt. The ID 1020 is reserved for the case "An interrupt for the Trusted OS was signalled while the core was executing in Non-secure state." (please check the spec of GIC architecture). The arm-tf knows it should forward the interrupt to S-EL1.

If this interrupt targets a group of cores, then if the core(s) running optee enables IRQ (because the target is secure world and it's running in secure world, so IRQ is used to trigger the interrupt not FIQ), it can try to acknowledge the interrupt. (but maybe not the first one who can get the "real" ID. The later coming cores can just get ID 1023 which means "somebody already took that, please ignore that.")

The key point:

- For GICv3 affinity mode, if the group1 interrupt targets the secure state which is not the same one the core is running, then trigger FIQ. (we want arm-tf in EL3 to handle the secure world switch.)
- If target secure state is same as running secure state then it's IRQ. (Just for group1 because group 0 will trigger FIQ anyway)
- Let EL3 trap FIQ in this case. (EL3 may not trap FIQ if running in optee. see [arm-tf interrupt framework design](https://github.com/ARM-software/arm-trusted-firmware/blob/master/docs/interrupt-framework-design.rst#133el3-interrupts), CSS=0, TEL3=0)
- The masks of FIQ/IRQ are independent of the cores.

> CSS=1, TEL3=0. Interrupt is routed to the FEL when execution is in non-secure state. This is an invalid routing model as a secure interrupt is not visible to the secure software which violates the motivation behind the ARM Security Extensions.

I think you may get the answer from above. :)
If it's running in non-secure world, then the secure interrupt will be triggered by FIQ. If EL3 doesn't trap FIQ, then non-secure world will intercept the secure interrupts (although it can't do anything but it prevents the secure world from handling the interrupt).
The principle of interrupt handling:
- Secure world can intercept non-secure interrupt
- Non-secure world can never disturb secure interrupt

Hope these answered your question.
Please let me know if you have further questions.
