### ISSUE TITLE
Pseudo TA compilation error

### ISSUE THREAD

**Issue by anwaymukherjee** [OP-TEE/optee_os#1948]
Hello, I am trying to mimic stats.c to model a pseudo TA which performs floating point multiplication. The compilation process, however, generates an error "-mgeneral-regs-only incompatible with floating point code". On further exploration, I found that the above mentioned flag is passed as part of arch-64 compilation setup. I have added a screen shot of the relevant code snippet (src/optee_os/core/arch/arm/arm.mk). Why does both "hard" and "no-hard" float flags are passed for rpi3 build? My knowledge says that rpi3 comes with an on-chip hardware fpu support.
![opteeos_vfp](https://user-images.githubusercontent.com/7190917/32922782-fd052d6a-cb01-11e7-8098-5f81e8f60494.png)

**Comment by jforissier** [comment]
Hi @anwaymukherjee,

Which version of OP-TEE are you using? Did you modify `arm.mk` locally? `$(arm64-platform-cflags-hard-float)` is not supposed to be passed here. See the master branch [1].

Floating point is disabled in the TEE core (and therefore in pseudo-TAs) because the FP registers are generally not preserved by OP-TEE. There is one exception: when `CFG_WITH_VFP = y` the FP registers may be preserved manually thanks to functions in `thread.h` [2] but this is meant for NEON and Cryptographic Extension (CE) instructions currently. Perhaps it would be OK to enable hard float for the pseudo-TA only and make sure the `*_vfp()` functions are used consistently there.

[1] https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/arm.mk#L98
[2] https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/include/kernel/thread.h#L383-L420
