### ISSUE TITLE
How to use benchmark in QEMU?

### ISSUE THREAD

**Issue by neuzm** [OP-TEE/optee_os#1979]
I am studying about virtualization of secure world.Now,I want to test the overhead of world switch(CA->Linux kernel->Monitor->secure os->TA).I know op-tee provides the process of benchmark and want to learn the method of how to use PMU.I have run the process of benchmark,and it tells I should input the "host_app" and "host_app arguments",then I try to appoint a CA like "optee_example_hello_world".But it still doesn't work,the log of secure world and normal world are shown as following.
in secure world:there are many errors after tee_ta_init_session.I think the most important log is like:
TEE-CORE:Panic 'unhandled pageable abort' at core/arch/arm/kernel/abort.c:687
in normal world,it is stopped at the log:
INFO : 2. Allocationg per-core buffers, cores detected=1.

so ,it will not generate the <client_app>.ts which is introduced in Document.I have two questions:
1.Is there a basic CA that can be appointed as "host_app"?
2.Now,I use QEMU to emulate the hardware,can I test the overhead in QEMU?Is it support PMU now?

I just want to use PMU to get the cycles of world-switch.

Greatly appreciated.

**Comment by igoropaniuk** [comment]
Hi @neuzm,

Sorry for the late reply (I hope it's still actual), I simply missed your message. 

Frankly, I was a bit out of the loop for a while regarding all this benchmark stuff, so I needed to spent some time to refresh all details and investigate what causes this issue (btw, I'm facing the same behavior on the latest master).

There were some changes introduced, that changed the way how SHM are allocated and handled in OP-TEE os core. In case if timestamp buffer is allocated in userspace and new register
user memory API is used for its registering in OP-TEE OS (introduced in
https://github.com/OP-TEE/optee_client/commit/27888d73d156d4862c07effce7c8c2455774768b),
there is no possibility to keep this mapping permanent among different
TEEC_InvokeCommand invocations. All all SHM are automatically unmapped from
OP-TEE VA space after TEEC_InvokeCommand is handled by OP-TEE.

I've created https://github.com/OP-TEE/optee_os/pull/2049 that fixes this, also will create PR in `optee_benchmark` (another part of this fix) tomorrow.

> 1.Is there a basic CA that can be appointed as "host_app"?
you can just start with `hello_world` in `optee_examples`.

> 2.Now,I use QEMU to emulate the hardware,can I test the overhead in QEMU?Is it support PMU now?
Frankly, QEMU isn't considered a good platform for performing any type of measurements (because of virtualization of PMU sand huge impact of host OS and its scheduler). I'd rather suggest to use real hardware (btw, it works on RPi3).

Hope it helps,
Igor

**Comment by neuzm** [comment]
Thank you for your answer @igoropaniuk .
