### ISSUE TITLE
Update the current LibTomCrypt version in optee_os to support novel ecc curves

### ISSUE THREAD

**Issue by matzedav** [OP-TEE/optee_os#1988]
Hey,

I want to replace the libtomcrypt version in optee os. For a cryptographic operation I need the "SECP256K1" curve but the current version of optee_os libtomcrypt does not support this curve. The "pr/ecc-asn1-part branch" of libtomcrypt supports the curve. Has anybody integrated a newer version of libtomcrypt in optee_os (maybe the current pr/ecc-asn1-part branch) or any libtomcrypt version with support for novel ecc curves like SECP256K1? 

If not does anybody have experiences in changing the crypto-api with least efforts?

Thanks

**Comment by jforissier** [comment]
Hi @xnadO ,


I have no ready-to-use code to share, but IMO what you are trying to do can be accomplished in a couple of steps:
1. Import the patches you need into `core/lib/libtomcrypt`. The tree structure is almost the same as upstream LTC, except that headers are in `core/lib/libtomcrypt/include` and not under `core/lib/libtomcrypt/src` like all other files. I suppose a good way to do that is to download the patches one by one, edit them to adjust the paths if needed, and apply them. Just copying the source files might work but you might also cause problems if you're missing other changes. If there are new `.c` files, add them to the proper `sub.mk`.
2. Decide how you want to access the new algorithm(s). The simplest way is probably to write a pseudo-TA which would directly access the LibTomCrypt routines. Otherwise you will need to extend the GlobalPlatform API, i.e., define new identifiers and integrate the new algorithms in `core/lib/libtomcrypt/src/tee_ltc_provider.c` and probably also in the `libutee` user-mode library (`lib/libutee/tee_api_operations.c`). This second option may be cleaner and easier to call, however.

**Comment by jbech-linaro** [comment]
The only downside with `SECP256K1` is that it is not considered as a secure curve (even though it is used in Bitcoin protocols). If there is no strong reason for using that I'd rather add/implement support for curve 25519 instead.
