### ISSUE TITLE
Can TA be used dynamically?

### ISSUE THREAD

**Issue by jenkin233** [OP-TEE/optee_os#2015]
Hi,all
I have built OP-TEE on the HiKey Board, but I have a doubt whether TA can be complied and used without  rebuilding the whole system. I have seen a way somewhere that put the .ta file into /system/lib/optee_armtz/ and put CA in /system/bin/ , but it seems doesn't work.  Can anyone help?
Thanking you for any help given.

**Comment by lorc** [comment]
Hi @jenkin233,

Yes, this is perfectly fine. Most TAs are loaded dynamically. As an example, you can take a look at https://github.com/OP-TEE/optee_test 

BTW, are you using Android? Because, on my linux system, all TAs reside in `/lib/optee_armtz/`.

Also, don't forget to run `tee-supplicant`, because it responsible for loading TAs (among many other things).
