### ISSUE TITLE
Confuse about SDP initialization checking

### ISSUE THREAD

**Issue by ken08liu14** [OP-TEE/optee_os#2017]
Hi,
Still something about SDP :)

While we got CFG_DT enabled, SDP memory regions in DT will be parsed in:
```
init_fdt()
{
    ...
    config_nsmem(fdt);
    ...
}
```
And finally, SDP and SHM in non secure memory get parsed and holes made for them. Check comments:
```
	/*
	 * Non-secure shared memory and also secure data
	 * path memory are supposed to reside inside
	 * non-secure memory. Since NSEC_SHM and SDP_MEM
	 * are used for a specific purpose make holes for
	 * those memory in the normal non-secure memory.
	 *
	 * This has to be done since for instance QEMU
	 * isn't aware of which memory range in the
	 * non-secure memory is used for NSEC_SHM.
	 */
```
Question is, since we enabled parsing DT for making SDP holes; why check_sdp_intersection_with_nsec_ddr() is necessary for checking intersection ? It get triggered always while SDP is defined within non secure memory area. Since core_init_mmu_map() get called earlier than init_primary_helper();

This question stands for PR:
https://github.com/OP-TEE/optee_os/pull/1987

BR.

-Ken

**Comment by etienne-lms** [comment]
Hi, thanks for the ref to #1987. I could have given feedback since a while...

Regarding your question:

> While we got CFG_DT enabled, SDP memory regions in DT will be parsed in

SDP memory is not defined in the DT. OP-TEE currently reads the DT to get the memory address ranges that DT defines for the dear Linux kernel (or any REE). TEE carves out from these ranges the address ranges internally defined as SDP memory (as well as the TEE memory address ranges).

SDP memory definition needs to be trustful. DT it not trustful as currently accessed by TEE. Hence SDP memory is currently hard coded inside TEE. Op-tee current make the non secure DT content flexible by allowing it to take into account the secure memory regions. This is allowed at the cost that Op-tee modifies the DT content before REE gets booted.

Check  also the comment i (lately) made in [#1987](https://github.com/OP-TEE/optee_os/pull/1987#issuecomment-353087757). The idea of carving out SDP memory from "register DDR" is fine, but we would need some `registered_ddr()` macro, not use a `registered_nsec_ddr()` to register memory/ies that gets redefined from memory defined by `registered_sdp_mem()`.
Hmmm, I hope I am not too confusing...

**Comment by ken08liu14** [comment]
Hi, since we move comment into PR #1987 , let's close this issue and discuss there.
