### ISSUE TITLE
Overly zealous panic on ECDSA TEE_AsymmetricVerifyDigest

### ISSUE THREAD

**Issue by jgrangethales** [OP-TEE/optee_os#2021]
I'm trying to verify signatures in a trusted application and wrote a number of standard test cases, which involve the following combinations of digest/signature/public key from a successful signing operation:
original/original/original
modified/original/original
original/modified/original
original/original/modified

The first 2 test cases work as expected (valid signature; invalid signature).  The second two test cases cause a TA panic.

This seems like very odd behaviour as the signature and public key are very likely to be passed to an application from the outside world (e.g. a certificate) and an application really ***must*** have a way of detecting bad inputs and discarding them ***without*** altering its internal state.  The GP apis do not provide a way for an application to determine whether a signature or public key is mathematically valid, so the TEE_AsymmetricVerifyDigest should really return a TEE_ERROR_INVALID_SIGNATURE in these cases (as the signature ***is*** invalid).

Note my optee_os repo is currently at c4a17553f77d7a4fc035475498a10dd718f9a9ce

**Comment by jgrangethales** [comment]
Does anybody have any thoughts on this, or is it something I should create a fix for and submit?

Does anybody object particularly?

**Comment by jforissier** [comment]
Hi @jgrangethales,

I think you're right. TEE_ERROR_INVALID_SIGNATURE seems valid for the cases you mentioned. There is also a GP test in the TEE Initial Configuration Test Suite ("Invoke_Crypto_AsymmetricVerifyDigest_invalid_signature (50-31-23)") that checks that TEE_ERROR_INVALID_SIGNATURE is returned when one bit is changed in an otherwise valid signature (so that is your third case). I'm not sure we're ever running it in `xtest`, it might be in the excluded list, I'd have to check. And the test is using DSA anyway, not ECDSA.

So yes, please submit a fix and we'll review it. Thanks!
