### ISSUE TITLE
GlobalPlatform’s Trusted UI

### ISSUE THREAD

**Issue by Marwen10** [OP-TEE/optee_os#2034]
Hello everyone,
I'm attempting to have some login TA, in OP-TEE website they mention that Trusted UI implementation is not complete. I have few questions:
1) is there a way to know what has been implemented or not
2) Trusted UI would work from command line interface ? I'm using linaro as rootfs
3) Is it easier to implement it as TA application that only prompt user for username and password without using Trusted UI specification ?
Thank you

**Comment by vchong** [comment]
1. There was a PoC implementation that was removed. See https://github.com/OP-TEE/optee_os/pull/1842 for details. Original tree is here: https://github.com/jenswi-linaro/optee_os/tree/tui-old2. The code didn't support rpi3 though, just FVP and QEMU iirc. See https://www.op-tee.org/blog/op-tee-qa/ (Q: Currently is there any work on Trusted User Interface support?)
2. Don't think so in this implementation. It's mainly a GUI implemented via a pseudo-TA.
3. Without TUI, which APIs/functions would you use to prompt for user entry?

**Comment by Marwen10** [comment]
Hello Victor thanks for the reply.
Thanks for the informations.
For 3 I was thinking about standard I/O operations in C.

**Comment by vchong** [comment]
You're welcome. There's no 'standard' IO ops in C for TAs, only a minimal/limited implementation (https://github.com/OP-TEE/optee_os/blob/master/lib/libutils/isoc/include/stdio.h) so if you're thinking of things like `scanf()` and `gets()`, they're not available.

**Comment by Marwen10** [comment]
ok, do you think there's a way to achieve this without TUI ?

**Comment by vchong** [comment]
Afaik, not without a whole lot of effort. First you need an interface for secure user input. For CLI, that means you need a way to access (using drivers, interrupts, etc) and secure/protect your keyboard from normal world so that it can't 'see' what you're typing. One of the difficult things would probably be how do you share/switch the keyboard between the 2 worlds properly. Not even sure if TUI addresses this properly or at all.

Even if you don't care about security for now, both secure and normal world probably shares the same uart/console right now so you need a way to determine whether what you type should go to secure or normal world? If another uart/console is available on the rpi3, then you can probably separate them out to 2 terminals.

**Comment by Marwen10** [comment]
Thank you for the explanation.
