### ISSUE TITLE
How to alloc 10M memory by TEE_Malloc()？

### ISSUE THREAD

**Issue by YumingMa** [OP-TEE/optee_os#2090]
Dear,

Thanks in advanced!
I  want to send an encryto file from a CA and its size is 10M to a TA.  
I have two questions:
1.The CA must send it multiple times and the buffer can't be more than 4M?
2. How to alloc more than 10M memory by TEE_Malloc()？

**Comment by rangewang** [comment]
I think your CA is in the non-secure world, and maybe you can use the shared memory between the two world. Because shared memory is a non-secure memory and secure world also can access it. You can put your encrypt file 10M here. Using CA to send the pointer of your file to TA. After that you can directly use this data.

Ref: https://github.com/OP-TEE/optee_os/blob/master/documentation/optee_design.md#7-shared-memory

**Comment by YumingMa** [comment]
Thanks！
I used the TEEC_AllocateSharedMemory(&ctx, &shm) to alloc shared memory. the shm.size can't be more than 1028095.

**Comment by lorc** [comment]
Hi, @YumingMa.

In default configuration OP-TEE can't map 10M of shared memory into TA address space. You can increase `PGT_CACHE_SIZE`  which  is defined in `pgt_cache.h`.
10M is equivalent to 2560 4k pages, so you need at least 5 pagetables. Try 6:

`#define PGT_CACHE_SIZE	ROUNDUP(CFG_NUM_THREADS * 6, PGT_NUM_PGT_PER_PAGE)`

**Comment by YumingMa** [comment]
Hi, @lorc 
Thanks very much! I will try to modify as your said.
