### ISSUE TITLE
error: required section '.rel.plt' not found in the linker script

### ISSUE THREAD

**Issue by j824737450** [OP-TEE/optee_os#2114]
Hi,
I got the u-boot from  https://github.com/MrVan/u-boot.git –b imx_v2016.03_4.1.15_2.0.0_ga, but when I compile the u-boot (I use mx6qsabrelite):
$export CROSS_COMPILE=arm-linux-gnueabi-
$make ARCH=arm mx6qsabrelite_defconfig
$make ARCH=arm
then there is an error:
![1](https://user-images.githubusercontent.com/33032927/35678725-6813af4a-078f-11e8-8168-1cf8744a65a1.jpg)
Does anyone know what caused this?
What's wrong with the compiler?Or something else?

Thank you!

**Comment by jforissier** [comment]
Hi @j824737450,

There is clearly something wrong with the compiler, since the build triggers an assertion in the linker itself. Now, it's hard to tell if this is caused by something else being wrong already although the 'undefined reference' message certainly looks suspicious at this point! Where is `ldo_mode_set` supposed to be defined?

**Comment by j824737450** [comment]
Hi @jforissier ,
Thank you for your reply! It's very strange that compiling mx6qsabresd is ok , and I get anything useful from google. So I don't know what to do next. Do you have any ideas?

**Comment by jforissier** [comment]
> Do you have any ideas?

No, sorry, I don't use this board. Maybe @MrVan can help.

**Comment by j824737450** [comment]
@jforissier 
Also thank yo,I have left a message at https://github.com/MrVan/u-boot. And  I will close this one.
