### ISSUE TITLE
Leaving a core in TEE

### ISSUE THREAD

**Issue by a2t2** [OP-TEE/optee_os#2161]
Hello,

I am working on a project where I require TEE to run a long task, and so TEE cannot return to normal world for a while.  If we assume that there are 8 cores, if normal world asks TEE to initiate such a task, then one core should be left in TEE to run this task (it would be a command code in a TA); the other 7 cores can be in normal world. Also I want the normal world to be able to instruct the TEE to stop its long operation on that one core, so that all 8 cores can be in normal world.

I wanted to ask how can one go about achieving this. 

Thanks

**Comment by lorc** [comment]
Hi @a2t2,

Do you really don't want OP-TEE return to NW? Right now OP-TEE can run very long tasks without any problem, because it periodically returns to NW  (thanks to interrupts or to RPCs). You just want to be sure, that you don't mask any exceptions.

**Comment by a2t2** [comment]
Hi @lorc  

The concern I have is the switching time between normal world and TEE. My project requires NW to get real time results from TA code in TEE; and the task the TA has to run will go on for long duration. Each switch to NW and back will incur time loss. I want to ask how can I achieve this real time requirement.

**Comment by lorc** [comment]
Ah, I see. 

This would require serious hacking, because OP-TEE does not  have primitives that you will need. You see, OP-TEE is externally scheduled and most IPC primitives in OP-TEE work with Normal World support. It wasn't intended to run on its own.

The easiest way to achieve this is  to disable external exceptions during TA invocation. You can do this by hacking `user_ta.c` (if you want to use user TA). But linux kernel will be very unhappy in this case. It will complain that one of the processor cores is stuck somewhere. If, of course, this is really long-lasting operation. E.g. longer than couple of seconds. But in this case you will not be able to terminate this long operation. 

The right way to do this is either give OP-TEE one of the cores (so this core will never leave Secure World and Linux will not know about it at all), or to use processors hotplug mechanism in linux disable core and then switch it into Secure World. And the switch it back on. 

But, any case you will need some way  to communicate with this dedicated core. You will either need to use one of  the Secure PPIs or just poll some shared variable. You will need some mechanism to manage this dedicated core: give it tasks, receive results, interrupt it, etc.

**Comment by jenswi-linaro** [comment]
Using real time scheduling in Linux is perhaps an option.

**Comment by jforissier** [comment]
+1 with what has been said and also define what is "real time" and do some experiments with the current code to see if the expectations are met already, or if you need to investigate the above suggestions.
