### ISSUE TITLE
Porting SQLite to Secure World

### ISSUE THREAD

**Issue by Bolvach-BVM** [OP-TEE/optee_os#2167]
Salutations.

I am trying to port SQLite to use its functions in the secure world. I've already compiled the program for ARM following this tutorial, https://vicente-hernando.appspot.com/sqlite3-cross-compile-arm-howto, and have the libraries. My question then is where to put these libraries and how to configure the makefiles so that SQLite can be accessed from a TA. I would appreciate if you could point me in the right direction.

Best regards,
Bolvach

**Comment by jforissier** [comment]
Hi @Bolvach-BVM ,

- To link your TA against your SQLite library, you need to set `CFLAGS` and `LDADD` in the TA's Makefile (I'm assuming the library name is `libsqlite.a`):
```make
CFLAGS = -Ipath/to/sqlite/include
LDADD = -Lpath/to/sqlite -lsqlite
```

- For examples on how to build TAs, please refer to https://github.com/linaro-swg/optee_examples and especially the TA for the "Hello World" example: https://github.com/linaro-swg/optee_examples/tree/master/hello_world/ta

- You also need to make sure your library is built with the proper flags. One way is to use the OP-TEE build environment, the same used to build TAs, except that you would set `LIBNAME = libsqlite` instead of `BINARY= <some UUID>` in the Makefile, to indicate you want to build a static library, not an application.

- What worries me a bit in your request is the lower-level API(s) used by SQLite. I mean: POSIX file functions essentially (`open()` or `fopen()`, etc.). Those are **not** available to a TA. So you will need to implemented them on top of the persistent object API (`TEE_OpenPersistentObject()`, etc.).

HTH.

**Comment by Bolvach-BVM** [comment]
Hello @jforissier, and thank you very much for your answer. I have some doubts though:

Regarding the first point, I have the compiled library libsqlite3.a. I'm not sure I understood correctly the paths that I should add to the Makefile. Regarding point number three, I do not want to create a static TA that is essentially SQLite; instead I want an existing TA to use the SQLite library. Is this not possible?

Thanks again,
Bolvach

**Comment by jforissier** [comment]
Unless you modify it, `libsqlite3.a` won't run in secure world. It's like trying to run a Windows library on Linux. Therefore, a TA cannot use the SQLite library unless you port the library code to the OP-TEE OS environment.

**Comment by Bolvach-BVM** [comment]
@jforissier I think I understand. So I need to alter sqlite3.c (namely the POSIX functions as you described) and build it as a TA. Then I link this build library with my true TA.

**Comment by jforissier** [comment]
Exactly.

**Comment by Bolvach-BVM** [comment]
Thank you very much for the support.
