### ISSUE TITLE
Fast and std calls question

### ISSUE THREAD

**Issue by nikoskoutr** [OP-TEE/optee_os#2170]
Hello,

I would like to make a quick question.
Where is the type of SMC to be made defined? Is it defined by the client or the ARM-TF / Secure Monitor ?

Thank you for your time.
Nick

**Comment by lorc** [comment]
Hi @nikoskoutr,

type of SMC call is deducted from its function number as described in ARM SMC Calling Convention (ARM DEN 0028B, pages 7-8).

**Comment by nikoskoutr** [comment]
Thank you @lorc,

after reviewing the document you mentioned and the linux kernel code from linaro, i find the following code that along with others, sets the function id:
```
#define OPTEE_SMC_STD_CALL_VAL(func_num) \
        ARM_SMCCC_CALL_VAL(ARM_SMCCC_STD_CALL, ARM_SMCCC_SMC_32, \
                           ARM_SMCCC_OWNER_TRUSTED_OS, (func_num))

#define OPTEE_SMC_FAST_CALL_VAL(func_num) \
        ARM_SMCCC_CALL_VAL(ARM_SMCCC_FAST_CALL, ARM_SMCCC_SMC_32, \
                           ARM_SMCCC_OWNER_TRUSTED_OS, (func_num))
```
I have a follow up question, why is  ARM_SMCCC_SMC_32 used by default. In an 64 bit implementation, what will happen? I cannot find any code using the 64 bit convention for optee.

Thank you for your time,
Nick

**Comment by lorc** [comment]
`ARM_SMCCC_SMC_32` works both on 32 bit and 64 bit ARM cores, while `ARM_SMCCC_SMC_64` will work only on 64-bit cores. You need to use `ARM_SMCCC_SMC_64`  only when you are sure that your service will be used only on 64 bit core. 

PSCI is a good example. There are 32-bit only call `CPU_OFF`, because  it works in the same way on both types of  cores. But `CPU_ON` call has 32-bit and 64-bit variants, because it uses different encoding for parameters. You can find details on page 29 of ARM DEN 0022D. But this is just an example.

**Comment by nikoskoutr** [comment]
Thank you very much for your time @lorc, you have been of great help.
I am closing the issue since you have answered all my questions.
