### ISSUE TITLE
mutex_destroy(...) wrong panic condition

### ISSUE THREAD

**Issue by MHesham** [OP-TEE/optee_os#2205]
From `mutex` struct definition:
`short state;		/* -1: write, 0: unlocked, > 0: readers */`

`mutex_destroy` first intention is to make sure no one is holding the lock here:
https://github.com/OP-TEE/optee_os/blob/b1d7375c01ec8bcbf3561d27425d320afed23bce/core/arch/arm/kernel/mutex.c#L255

However, the condition seem to be wrong. It should be `if (m->state)` instead of `if (!m->state)`.

**Comment by etienne-lms** [comment]
Looks like you're right. Issue introduced by faulty commit https://github.com/OP-TEE/optee_os/commit/bdc1c51e9d3c2828bd5dfaa2e599b7a5ec601ac3.
However, this routine is never used and has never been used since introduced. We should better get rid of it. Dear maintainers, what's you're feeling, fix or remove?
