### ISSUE TITLE
Role of Public Key in OP-TEE

### ISSUE THREAD

**Issue by Atomar25** [OP-TEE/optee_os#2265]
As per this Document[1], TEE contains a public Key that can be used to sign the
Trusted application.

But I didn't get how TA is signed using Public key, for instance we just simply compile this Hello world 
application[2] and run it on hardware.

Also, how OP-TEE make sure that it is running *only* Trusted apps, for example one can write an Application using TEE Global API and run it from normal non secure root filesystem?

[1]https://elinux.org/images/e/e6/OP-TEE-Using_TrustZone_to_Protect_Our_Own_Secrets-20171023-2.pdf
[2]https://github.com/linaro-swg/optee_examples

**Comment by jforissier** [comment]
Hi @Atomar25 ,

Trusted Applications are signed using a *private* key ([defaut_ta.pem](https://github.com/OP-TEE/optee_os/blob/master/keys/default_ta.pem)) and the public key in OP-TEE ([extracted](https://github.com/OP-TEE/optee_os/blob/master/core/sub.mk#L6-L13) by the makefiles) is used to authenticate them.

If you write an application using the GlobalPlatform API, you will need OP-TEE to run it (because the API calls the secure world via the libteec.so library which in turn calls the OP-TEE driver in the kernel, which ultimately invokes secure world). And OP-TEE will verify it is authorized to run it thanks to the signature.
