### ISSUE TITLE
Do you have schedule for DDK(Driver Develop Kit) or dynamic loading mechanism of Secure Driver?

### ISSUE THREAD

**Issue by ljmblueday** [OP-TEE/optee_os#227]
Hello, 
I want to load TUI(Trusted User Interface) or other peripheral device dynamicaly at secure OS.
Do you have schedule about loading mechanism of hardware device driver?

**Comment by jbech-linaro** [comment]
Hi @ljmblueday, we plan to look into TUI as soon as GlobalPlatform have released the Trusted UI v1.1 spec. I haven't got any detailed date when GP plan to do so. DDK is something we have started to discuss, but I don't think we will actually start working with it before we start look into Trusted UI, basically since that is the first use case that really require something like that.

In case you have some ideas or already ongoing work, please feel free to submit a patch for it and we can review it. Beware that as of today we cannot merge anything until you have signed the CLA (this is a restriction that we are trying to get rid of, but as of now, it is needed).

// Joakim
