### ISSUE TITLE
TEEC_RegisterSharedMemory performance impact

### ISSUE THREAD

**Issue by sahilnxp** [OP-TEE/optee_os#2285]
Hi All,

We are working on a solution in which we are using the OPTEE as secure storage for our keys.
These keys will be accessed when a connection is made to the system and there can be a number of connections to this system at same time so these keys can be accessed simultaneously.

Connections are being handled in non-secure world and make a call to OPTEE only when this connection needs the key.

Currently we have configured the system to have static shared memory between Secure and Non-Secure World, which is getting exhausted when we are making even 20 connections to the system.
In this case we are using TEEC_AllocateSharedMemory for allocating shared memory.

So we are now planning to move to TEEC_RegisterSharedMemory to resolve this memory crunch.
Since we are Registering the memory at run time with OPTEE, it needs to create a mapping in MMU for this memory so that it can access the shared memory.

Before we move to the TEEC_RegisterSharedMemory, I just want to get the inputs that if anybody has tested this TEEC_RegisterSharedMemory with OPTEE rigorously to handle a lot of requests ??

Or If OPTEE MMU table will gets so much stress, that we are Registering/deregistring new memory again and again and leads to a significant performance delay ??

Thanks
Sahil

**Comment by etienne-lms** [comment]
About mapping and shm registering.

If you are working with dynamic shared memory (check patches present in optee linux driver + activation in optee_os), then you can register a big chunk of allocated memory from Linux/OS once, and use it without any perf penalty. If you register/release a Shm buffer before/after each access then of course you'll get some overhead. In this case, consider preallocating a big buffer and registering it once and check the balance between buffer registering/release and data copying perfs.

If you don't use dynamic SHM, then `RegisteringSharedMemory()` uses data copy in buffers allocated in the static SHM. It is tested and reliable up to our best knowledge. If such conditions, `Regsiter/ReleaseShm` or `Alloc/Copy/ReleaseShm` should be the same. In this case, best is also to preallocate a big buffer and use it for several transfers if possible.

**Comment by etienne-lms** [comment]
> (...) Or If OPTEE MMU table will gets so much stress, that we are (...)

Note that optee will not map the memory when you register it.
The memory references (physical pages) are stored no TEE side.
It is only when a TA is invoked (or a core service) that registered shm will be mapped. It is unmapped on completion of the TA/service invocation, and remapped at next invocation if required.

**Comment by sahilnxp** [comment]
Thanks @lorc and @etienne-lms  for quick reply.

@lorc 
> And sidenote: are you sure that is a good idea to transfer keys from secure world to non-secure? This defeats the very idea of a secure storage.

We are not moving the private part of keys between secure/ non-secure world.
Only Public part and the data to be encrypted/decrypted is moved between the Secure and Non-Secure World.

> Also, note that virtual address space for registered buffers is also limited.

What is the limit on this space ?

> How many times per second you want to register memory?

I'm not having any specific number, but number can be more than 20.

@etienne-lms 
> In this case, consider preallocating a big buffer and registering it once.

Yes, this is a good option to do, but I think in this case we need to write some sort of memory manager for managing this pre-allocated memory.

> If you don't use dynamic SHM, then RegisteringSharedMemory() uses data copy in buffers allocated in the static SHM. 

Maybe I didn't understood this correctly, I got a doubt here.
Why in case of static SHM, there will be data copy, Can we not allocate the static shared memory via TEEC_AllocateSharedMemory and what Non-Secure world writes on this memory will directly be used by the Secure World and vice-versa ??

Thanks
Sahil

**Comment by lorc** [comment]
> Only Public part and the data to be encrypted/decrypted is moved between the Secure and Non-Secure World.

I see. This is perfectly fine then

> What is the limit on this space ?

As @etienne-lms pointed out, registered buffer gets mapped into TA address space only during TA invocation. So number of registered buffers basically is limited by size of OP-TEE heap, where information about registered  buffers is stored.

> I'm not having any specific number, but number can be more than 20.

I think, it is achievable. Register/UnregisterSHM() actually operates only with heap, no MMU operations there. On other hand, heap is locked with spinlock, so there can be problems with concurrency. 

Maybe it is worth to implement some cache on non-secure world side?

> Why in case of static SHM, there will be data copy, Can we not allocate the static shared memory via TEEC_AllocateSharedMemory and what Non-Secure world writes on this memory will directly be used by the Secure World and vice-versa

Yes, you can allocate memory with `TEEC_AllocateSharedMemory`. And this buffer will be shared between SW and NW. But `TEEC_RegisterSharedMemory` asks to register a user-provided buffer. 

In case of static SHM, client library allocates memory with `TEEC_AllocateSharedMemory` and uses it to communicate with TA. Because, this new buffer is different from that user has provided, client library is forced to copy memory back and forth between this two buffers. So for user it looks like it TA works with theirs buffer, while for OP-TEE it looks like it works with static SHM.

Dynamic SHM eliminates this problem by registering user provided buffer right into OP-TEE.

**Comment by sahilnxp** [comment]
Thanks @lorc for clariying the things.
Will study this more and write back again if any doubt. :)

**Comment by sahilnxp** [comment]
What I see from OPTEE code, it is having 64K heap and what I understand from here is that we cannot register shared memory more than OPTEE heap size.

I think TEEC_RegisterSharedMemory() should be used when user wants to share something big with OPTEE.(e.g. Hash of a big file) to work upon.

But in this case we cannot share more than 64K b/w NW and SW, which in my opinion is conflicting with the purpose of TEEC_RegisterSharedMemory().

Please check if my understanding is correct, I am still in learning phase :)

Thanks
Sahil

**Comment by jenswi-linaro** [comment]
The limits on shared memory imposed by the secure heap is just the bookkeeping of the shared memory addresses etc.

**Comment by sahilnxp** [comment]
So we can't map more than 64K memory via TEEC_RegisterSharedMemory() ??

Sorry, I am not able to understand what following line means.
> bookkeeping of the shared memory addresses etc.

Thanks
Sahil

**Comment by lorc** [comment]
@sahilnxp heap is used to store information about shared memory. OP-TEE does not maps anything into heap.

As page address takes 4/8 (depending on LPAE present) bytes to store, you can say that every 4kb of shared memory requires 4/8 bytes of heap. This is very rough calculation, because there is also additional metadata for every shared buffer. I don't remember exact numbers, but you can assume that you need about 32-64 bytes of metadata + 4/8 bytes * `number of shared pages` of heap per one shared buffer.

**Comment by sahilnxp** [comment]
Thanks all.
Closing this ticket.
