### ISSUE TITLE
Board that supports trusted boot

### ISSUE THREAD

**Issue by Marwen10** [OP-TEE/optee_os#2309]
Hello,
I have experimented OP-TEE on the raspberry pi 3. But as it's not secure, we want to have a secure board on which we can run a secure application. By secure, I mean principally secure boot and hardware mechanisms to separte the ram of the two worlds. So what would be the best solution available ?

Thank you

**Comment by gitfineon** [comment]
Hi @Marwen10 ,
I guess you are aware of the README section [Supported Platforms](../blob/ecb1e1546bbd38cb78dd5bca5ce539fbb1889238/README.md#3-platforms-supported) listing?
If you want to build it by your own, take a look at [Platforms supported by build.git](../../build/blob/d790b504a378f68814f15849b7890c56b3663f97/README.md#5-platforms-supported-by-buildgit)

Be aware of the difference between Trusted Board Boot (TBB) and UEFI Secure Boot. To verify OP-TEE you need TBB or a comparable proprietary mechanism from the board vendor. Trusted Firmware is responsible to establish non-secure world. 

A good development platform to start is the HiKey Board, supported by OP-TEE, ARM-TF but TBB is not ported, yet. The only platforms with TBB support public available in ARM-TF are ARM Juno and Socionext Unipher (not listed by OP-TEE). Additionally there are virtual platforms like QEMU and FVP, which can be used to develop without hardware.

All platforms are not designed for products (like the RPi  :no_mouth:) and have multiple lacks of security you should be aware of, e.g. hardware unique key (HUK), which is a requirement for [secure storage](../blob/master/documentation/secure_storage.md#important-caveats), is zero for all devices because SoC vendors do not publish code or documents on how to get HUK or use crypto engine. For more details have a look at the [porting guidelines](../blob/master/documentation/porting_guidelines.md).

**Comment by Marwen10** [comment]
Thank you for the response. It's very clear. I have another (independent) question. The implementation of secure input is not finished yet. Is there plans to finish it ? is there a hardware problems preventing it ? 
Thanks again

**Comment by gitfineon** [comment]
Are you talking about OP-TEE or TEEs in general? Where have you got this information from? I'm also interested to see some progress here. 

My understanding of secure input is an interface hard-wired or configured to be only accessible in Secure World and the TEE does forwarding, if input is not considered as sensitive.

The only development platform I know is Juno with its Secure Keyboard (I2C) port. http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.100113_0000_06_en/bri1378914845916.html

Samsung claims in their KNOX documents that they have secure input implemented.

**Comment by Marwen10** [comment]
I'm talking about OP-TEE specifically. There was an unfinished work about a secure input API according to GlobalPlatform specifications. As I understood the I/O interfaces should be virtually disconnected from the normal world and connected to the secure world when secure input is called.
