### ISSUE TITLE
Store encryption keys at build time

### ISSUE THREAD

**Issue by pokitoz** [OP-TEE/optee_os#2314]
Hello,

For a project, I need to generate 1 RSA key pair for each board I have. Each of the boards needs to share their RSA public keys for authentication purposes.

Currently, I have created a TA with a header file containing the RSA key pair of the device and all the other public keys of the devices authenticated. Then I use TEE_AllocateTransientObject, TEE_PopulateTransientObject and finally create the handles.

However, I would like to avoid having this header file and am wondering how to embed the different public keys in Optee-OS so that I can directly use them in my TA. I also want to embed the private key in Optee-OS.

In brief, can I add a RSA key pair into the Optee-OS build to use it in the TA?

Is there any way to achieve that?
Thanks

**Comment by jbech-linaro** [comment]
Hi @pokitoz ,

So, you have multiple devices and needs to have control of both public and private keys unique to each device. This is more of a manufacturing and provisioning problem. Having all public keys in headers doesn't scale as you've already figured out.

And the way to do this depends a bit on how it will live in an ecosystem. In general you do key generation for this on the first boot in factory (and the generation there typically uses a hardware unique key or identifier to make it different from other devices). One should be able to read the public key from the device, preferably in a certificate (to prove its authenticity).

You are asking about areas where we are doing work as we are speaking. We are working with both AOSP Keymaster/Gatekeeper as well as a PKCS#11 implementation. With that we are going to need to use and create similar functionality. But as that is work being developed there isn't much you can use for the moment.

If you're not involved in the factory setup, then the best you can do is some kind of late provision. Be aware that doing so is always risky, since by doing so, you are adding "trust anchors" on a device that you don't know whether it is compromised or not (it is probably not, but you can't really know). The principles are similar though and then you typically derive/generate whatever keys you need the first time a TA launches (@jenswi-linaro please remind me here, is it possible to run some TA code at the same time as your are installing a TA in secure storage? I don't think so, right?)

For the moment, the best place to store the keys are in secure storage, more or less what you've been playing with (but you should probably use the "Persistent" + "Read-/WriteObject" functions instead of "Transient", since the latter is a temporary thing). But drop the idea with having it in header files, instead look at how you can derive hardware unique keys instead and again if you check back here in a couple of months there might be more in OP-TEE that could help you out.

**Comment by jenswi-linaro** [comment]
>(@jenswi-linaro please remind me here, is it possible to run some TA code at the same time as your are installing a TA in secure storage? I don't think so, right?)

For the moment, that's correct. With proper security domains that will be different, but I don't know when that will happen.

**Comment by pokitoz** [comment]
Thanks a lot for your comments. I will wait for the new functionalities you are developing.

As I am not in the factory setup, I will put the trust anchor as suggested. It is only a prototype so it should be fine :D
