### ISSUE TITLE
How does OP-TEE deal with the scenario of parallel invokes from different clients

### ISSUE THREAD

**Issue by Tigerly** [OP-TEE/optee_os#2343]
when I check the GPD TEE spec, I found there are several internal APIs are implemented as atomic operations (e.g., TEE_WriteObjectData). However, lots of APIs are not atomic. 

I was wondering how does OP-TEE handle the parallel invokes from different clients?
For example, "secure_func" is the function in TA. Now, two CAs parallelly invoke "secure_func" from the normal world via TEEC_InvokeCommand(...). Then, how should TA do for ensuring the correctness of the execution?  

Does OP-TEE support to handle the similar scenarios? or should TA handle that case (e.g., lock the "TA_InvokeCommandEntryPoint" and "secure_func") ?

Thanks in advance!

**Comment by jenswi-linaro** [comment]
The APIs are implemented to be atomic from the TA point of view. Mutexes are used internally in OP-TEE to ensure that. The TA doesn't need to do anything extra for the operations to be atomic. Unless the TA is a single instance TA it will still need to be a bit careful since it's only the individual API calls that are atomic.
