### ISSUE TITLE
Access to NW kernel memory space from OPTEE os

### ISSUE THREAD

**Issue by wonn1e** [OP-TEE/optee_os#2373]
I'm passing a pointer defined in kernel of normal world to optee. 
A simple SMC call is newly defined to pass the pointer as one of the variables/registers. 
I would like to dereference the pointer on OPTEE os side. 
Currently, I'm not defining shared memory in kernel. Is it possible to dereference and access the normal world memory directly?

Thank you in advance!

**Comment by lorc** [comment]
Hi @wonn1e, generally speaking - no, because non-secure memory is not mapped to OP-TEE. 

To overcome this, mechanism of dynamic shared memory was implemented.

If you want to experiment with this, you can try `core_mmu_map_pages()` (this is a lowest level) or `mobj_reg_shm_alloc()` + `mobj_reg_shm_map()` (this is a higher level).

**Comment by yilingxu** [comment]
Hi,
in core_mmu_map_pages(vaddr_t vstart, paddr_t *pages, size_t num_pages,  enum teecore_memtypes memtype)

I suppose the parameter "pages" as the physical address in NW which needs to be mapped. Is it right?

How can I get the value of "vstart"?

**Comment by jenswi-linaro** [comment]
No, `pages` is a pointer to a list of physical addresses.
