### ISSUE TITLE
Malloc fails to allocate 74k of memory

### ISSUE THREAD

**Issue by ademyankov** [OP-TEE/optee_os#2395]
I have an extensive test application interacting with TA DRM Engine, which internally allocates, re- and de-allocates a whole bunch of memory. Finally, I hit the wall when malloc or realloc cannot allocate 74k block of memory.

Q1. Is tee_os memory allocator fragments the memory? Does it mean, that in my case, TA eventually finds itself in the state where it is impossible to find 74k of a free consecutive block of memory?

Q2. How can I increase TA heap memory for the emulator (qemu v8)? For example:
If I #define TA_DATA_SIZE (0x400000) // 4Mb then OS fails to load TA at all.

Q3. I use CFG_TEE_TA_MALLOC_DEBUG ?= y to get the memory stats. How difficult is to have a free memory left for TA information?

![image](https://user-images.githubusercontent.com/13845895/41376529-54e2b6aa-6f0e-11e8-8f04-fa588733bc2a.png)

**Comment by jenswi-linaro** [comment]
Q1: Yes

Q2: There's some upper limit, but the method looks OK. Did you try with slightly smaller sizes?

Q3: I'm not sure that would help much, fragmentation of the heap is expected especially when allocating such large chunks.

It could also be worth considering doing your own memory management for large buffers since generic memory management has its limitations (it is generic after all :-) ).

**Comment by ademyankov** [comment]
Ok, I got it. Thanks @jenswi-linaro 

And yes, I tried with smaller sizes. Code works even with 1.5Mb of memory designated for TA's heap.

One more question though. How generic is it? ))) Does it at least merge consecutive free blocks?

**Comment by lorc** [comment]
OP-TEE uses [bget](http://www.fourmilab.ch/bget/) as allocator. Originally it was written in 1972, based on algorithm from 1966 :) It was rewritten a couple time of times since then, thought. Very interesting piece of code, written in K&R C. 

But yes,  it knows how to merge free blocks.  Basically it maintains list of free blocks and it allocates memory from first free block of appropriate size. So it can fragment heap very badly. But otherwise, it is small and memory-effective.

**Comment by ademyankov** [comment]
Yeah, I know bget! I see, ok then... Thanks guys for clarification.
