### ISSUE TITLE
vfp optee_os core problem

### ISSUE THREAD

**Issue by zatkh** [OP-TEE/optee_os#2396]
I am porting a library as one of optee_os libs(not TA side). for the core sources hard float is not supported and I am getting (error: '-mgeneral-regs-only' is incompatible with floating-point "func_name"). So I was wondering if you have any suggestion for that?

**Comment by jforissier** [comment]
I think one option may be to remove the `-mgeneral-regs-only` option for the library (add `cflags-remove-y += -mgeneral-regs-only` to `sub.mk`) and make sure the calls into your library are wrapped with `thread_kernel_enable_vfp`/`thread_kernel_disable_vfp()`. Similar to what is done for LibTomCrypt when crypto acceleration is enabled. The CE instructions make use of the floating-point registers, too, so that is a similar use case.
@jenswi-linaro correct me if I'm wrong ;)

**Comment by jenswi-linaro** [comment]
For privileged mode (kernel mode) floating point (VFP) isn't directly supported. There's an exception to that rule, see for instance:

 https://github.com/OP-TEE/optee_os/blob/e77020396508fc086d7a4d6137388b116e4a662f/core/arch/arm/crypto/aes-gcm-ce.c#L62-L69

where VFP is temporarily enabled for an assembly routine.

**Comment by zatkh** [comment]
thanks. Just to make sure, this way (temporaly vfp enabling) still can't have C function definitions with floating-point arguments in kernel mode.

**Comment by jenswi-linaro** [comment]
Correct

**Comment by zatkh** [comment]
last question,  libraries in optee_os/lib/* are not running in kernel mode as I understand, and I tried porting my lib there. have the same problem, why the hard float is not supported here?

**Comment by jforissier** [comment]
Some libs in `optee_os/lib` are running in kernel mode: libutils and libmpa, see here: https://github.com/OP-TEE/optee_os/blob/master/core/core.mk#L82-L88

**Comment by zatkh** [comment]
thanks, make sense now.
