### ISSUE TITLE
Dynamic shared memory translation fault on Juno

### ISSUE THREAD

**Issue by Emantor** [OP-TEE/optee_os#2402]
After fixing dynamic shared memory on Juno, if the kernel driver tries to use the dynamic shared memory, i get a translation fault in optee.

This is on optee_os master and a v4.17 kernel with the necessary device tree patches cherry-picked.
Starting optee_test triggers the translation fault  on juno r0.

A complete symbolized optee log is available [here](https://paste.stratum0.org/?91d7efbe42d0e163#wmR7U66ZsdgD7DH61w87+JohWRsmZGi2o9ZjJw2Rylg=)

OPTEE Make variables:
PLATFORM=vexpress-juno CFG_ARM64_core=y DEBUG=1 CFG_TEE_CORE_DEBUG=y CFG_TEE_TA_LOG_LEVEL=4 CFG_TEE_CORE_LOG_LEVEL=4

**Comment by jenswi-linaro** [comment]
Thanks for the report. I can't find anything obvious in the log. I'll take a closer look later when I have access to a Juno myself.

**Comment by fractalclone** [comment]
Hi,
I have the same issue on the fvp platform, since dynamic shared memory from normal-world has been enabled in optee. I have done some investigation and found that the issue arises whenever the normal-world shares a memory of address > 32 bits, like 0x8f9568000

Hence, I've checked how TCR_EL1 register is configured for fvp and found that the IPS (Physical AddressSize) is set to 0x000 (32 bits, 4GB), which IMHO is wrong, since fvp have two DRAMs (with second DRAM address > 32 bits)
1) 0x80000000, size 0x80000000
2) 0x880000000, size 0x180000000

Within optee, the TCR_EL1 IPS bits are set via the tcr_ps_bits, which is calculated based on the MAX PA obtained from the get_nsec_ddr_max_pa() function. This function does the computation by looping through the core_mmu_phys_mem structures defined within the phys_nsec_ddr_section section (between variables __start_phys_nsec_ddr_section and __end_phys_nsec_ddr_section). But in plat-vexpress there are no core_mmu_phys_mem structures within that section, instead the fvp DRAM0
and DRAM1 core_mmu_phys_mem structures are defined within the phys_ddr_overall_section section (defined via the register_ddr macro).

By replacing the following in core/arch/arm/plat-vexpress/main.c:
```
register_ddr(DRAM0_BASE, DRAM0_SIZE);
register_ddr(DRAM1_BASE, DRAM1_SIZE);
```

by

```
register_dynamic_shm(DRAM0_BASE, DRAM0_SIZE);
register_dynamic_shm(DRAM1_BASE, DRAM1_SIZE);
```

TCR IPS bits are computed correctly to 36 bits (64GB), which fixes the translation fault.

I've made a pull request for the patch at https://github.com/OP-TEE/optee_os/pull/2421

@Emantor  can you check at your end and confirm that it works for you too?

**Comment by Emantor** [comment]
Yes that works for me, thanks. However I do not think that this is the proper fix for the problem. 2f82082fada310cd58bcb8145d677144e9bfccaa explicitly changed the `register_dynamic_shm` to `register_ddr`, with changes related to SDP memory. 

However changing the `max_pa` calculation function will probably break other platforms which actually use `register_dynamic_shm` and not `register_ddr`.

@edison-ai what are your thoughts on this?

**Comment by fractalclone** [comment]
@Emantor I think that one solution would be to update the `get_nsec_ddr_max_pa` to obtain the MAX PA following the core_mmu_phys_mem structures found within both the `phys_nsec_ddr_section` and `phys_ddr_overall_section` sections. 

Anyway, following the `discover_nsec_memory` function a platform cannot have core_mmu_phys_mem structures defined within both `phys_nsec_ddr_section` and `phys_ddr_overall_section` sections. Code except below:
```
	nelems = (&__end_phys_ddr_overall_section -
		  &__start_phys_ddr_overall_section);
	if (!nelems)
		return;

	/* Platform cannot define nsec_ddr && overall_ddr */
	assert(&__start_phys_nsec_ddr_section == &__end_phys_nsec_ddr_section);
```

**Comment by jenswi-linaro** [comment]
Here's another fix https://github.com/OP-TEE/optee_os/pull/2427

**Comment by fractalclone** [comment]
@jenswi-linaro thanks, working for me. I'll abandon my pull request
