### ISSUE TITLE
Why not add const  for function parameter do not use const modification ?

### ISSUE THREAD

**Issue by leesagacious** [OP-TEE/optee_os#2433]
hi :
   the following code, 
   why does the function parameter do not use const modification ?

    static void __print_stack_unwind_arm32(struct abort_info *ai) // the struct 
   {
	.....
 

@ jbech-linaro  , 

Please reply to the trouble

**Comment by jbech-linaro** [comment]
The one creating the function did probably not think about that when writing the code. I'm pretty sure you can find lots of places in the code base where it would make sense to add `const`. We fix things like this when we stumble upon it. When you find things like this, may I kindly ask you to just submit a fix for it (as pull request) instead of submitting it as a question? In either case you will get answer to the question, but if it's clear that it is an issue, then it will be fixed and merged very quick.

**Comment by leesagacious** [comment]
hi @jbech-linaro  : 
 there are a large number of such code in optee,
 in the struct, i must add const,
 what do you mean is that this is also a solution ?

**Comment by jbech-linaro** [comment]
Since it seems like you have looked into this recently, may I ask you to create a pull request that you could name "Add missing const" or something like that. Then we can get this reviewed and sorted.

**Comment by leesagacious** [comment]
what are your rules for reviewing structs and const ?

**Comment by jbech-linaro** [comment]
There are no explicit rules. It's just try to adhere to good coding practice. Everyone knows it's good practice to try to use `const`, but many of us still forget to add it (and quite often abuse it by casting it anyways further down). Submit a pull request and you will get feedback whether we agree or disagree with you.

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
