### ISSUE TITLE
Virtualization Security Error issue

### ISSUE THREAD

**Issue by casionwoo** [OP-TEE/optee_os#2451]
Hello,

I'm working on virtualization for OPTEE.
And here's my situation.

linux + android   |           TAs
ㅡㅡㅡㅡㅡㅡㅡㅡ   | ㅡㅡㅡㅡㅡㅡㅡㅡㅡ
   hypervisor        |       OPTEE-OS
ㅡㅡㅡㅡㅡㅡㅡㅡ   | ㅡㅡㅡㅡㅡㅡㅡㅡㅡ
             Monitor mode firmware 

this optee-os is built from linux yocto build environment. 
so whenever I want to execute the TA (for example, keymaster and gatekeeper) which is built from android build environment, there's a error code of TEE_ERROR_SECURITY.

and here's my question that do i have to specify the path of optee-os from yocto when I build TA which is belongs to android environment.

or is it something else problem?

**Comment by lorc** [comment]
Hi @casionwoo ,

In the simplest situation, when there is only one guest and android memory is mapped 1:1 to real memory, all should  work out of the box. Just ensure that  hypervisor passess all SMC calss to OP-TEE as is.

**Comment by MrVan** [comment]
@Iorc  You mean Android as Dom0 on XEN? And no DomU?

**Comment by lorc** [comment]
Dom0 is good because it (almost) always is 1:1 mapped. But if you want to run Android as DomU, then you need to do memory address translation, as I did [here](https://github.com/lorc/xen/commit/06f463a799b2bfc64b0290d9a9e37b4f6f49e6be). Also it is advisable to disable static SHM at all in this case. And will be good to ensure at XEN level that only one domain can work with OP-TEE.

**Comment by casionwoo** [comment]
@lorc Thank you for your reply. However I don't get your explanation fully. My problem is following:

I have two VMs: Linux and Android
Linux is built from Yocto project and Android is Android repo project. Each project includes optee-os as a sub-project, and I chose Yocto optee-os as a secure OS on the platform(hikey).

I have executed optee-test (xtest), it worked perfectly(TAs are built from Yocto).
When I execute gatekeeper and keymaster which are Android Applications (of course they are built from android workspace.), there's a error message **TEE_ERROR_SECURITY**

My assumption is when I build those android applications(especially TAs), should I specify the path of optee-os from Yocto not Android repo project? 
Am I correct?

**Comment by vchong** [comment]
Is optee-os built the same way, i.e. same make command and options/flags?

In Linux/Yocto, you're probably running as root, right?

Sounds like an SELinux issue maybe. Which line give you the TEE_ERROR_SECURITY? Maybe try again running as root, or disable SELinux (`setenforce 0`), or both.

**Comment by lorc** [comment]
@casionwoo,

So you want to use OP-TEE from two virtual guest simultaneously? This is not possible with current mainline OP-TEE. This is the first problem. I have a patch series that enables virtualization in OP-TEE, but it is not upstreamed and it supports only one platform - qemu_v8.

You are getting  `TEE_ERROR_SECURITY` because physical memory address as seen by Android are not real physical memory address. They are IPAs (intermediate physical address). But OP-TEE does know nothing about this and it expect real PAs. This is the second problem. 

In this case you need special code in XEN to do address translation inside op-tee command buffers. I call this part of code "TEE mediator". I have written such patch for XEN, and it relies on OP-TEE virtualization support. But you can try it, thou. You need this XEN branch: https://github.com/lorc/xen/commits/optee_buildroot
don't forget to enable op-tee support in your domU cfg file with `optee=1`.

**Comment by casionwoo** [comment]
@lorc 

As you mentioned one of VM(this VM is linux, among linux + android two VMs) have a identical mapping (1:1 mapping) and I have implemented to emulate even both guest request, only one VM(linux) invoke that request which makes OPTEE-OS aware only one VM only. which makes easy that unnecessary to modify any code of optee-os including stack and thread etc..

I confirmed xtest from both VMs are working well.(TA files are built in linux workspace environment) but not gatekeeper and keymaster (which are built from android workspace).
So I think 
1. I have worked on hikey
2. IPA and PA mapping is already done that the  TEE_ERROR_SECURITY error is not caused by memory related but it seems from verifying the signature of TA right before execute them.
3. Hypervisor is company property that I can't open but I would read your xen code.

**Comment by lorc** [comment]
@casionwoo,

Ah, I see. So, if xtest works well in Android, then problem in keymaster TA itself.

**Comment by casionwoo** [comment]
@lorc 

then does it seems from the reason keymaster and gatekeeper is built with the path of android optee-os?

as far as i know they build ta, the path of optee-os toolchain should be specified.
and when i build keymaster and gatekeepr, it build ta with the path of optee-os from android.

**Comment by lorc** [comment]
Maybe @vchong  can help you there.

I would recommend you to find which code exactly returns `TEE_ERROR_SECURITY`. E.g. is this does ta_loader? Or TA gets successfully loaded and then TA itself returns this error. Does it originate from secure storage subsystem? It will be helpful if you build  op-tee with FLOW log enabled and share logs somewhere.

**Comment by casionwoo** [comment]
@lorc @vchong 
I have a question for signature verification.

I have two VMs.(Linux from Yocto and Android this two VM have same version for optee stuff)
and OPTEE-OS (secure os) is built from Yocto.

TAs which are built from android workspace. when they are loaded by tee-supplicant and before trying run them, optee-os verify the signature.

I'm considering in this case, TA could be used?

**Comment by vchong** [comment]
@casionwoo I think you should be able to use the TAs although I don't really have your build environment to try.

1. Have you tried running xtest using TAs built in from android workspace?

2. I still think it might be permission issue. See previous comments/questions here: https://github.com/OP-TEE/optee_os/issues/2451#issuecomment-404045693. Maybe also compare the file permissions of the xtest TAs (built in linux workspace env) and the keymaster/gatekeeper TAs on your board.

**Comment by gchww** [comment]
@casionwoo
I have encountered a similar permission issue  as yours.
It seems that in your case TAs have not been loaded by tee-supplicant and libteec returns error.
Check whether  your tee-supplicant and libteec.so are built by android toolchain, these two run in android runtime, so they are needed being built by android toolchain. I fix my issue just by clean build environment and rebuild optee client by android toolchain.
Maybe your issue is a different case, just for your information.
