### ISSUE TITLE
OPTEE version with vanila Linux upstream

### ISSUE THREAD

**Issue by casionwoo** [OP-TEE/optee_os#2504]
I'm trying to use linux from upstream not linaro-swg/linux because of company policy.
linux commit ID is 102b97d6241d938ac153193504a5936fc0be27ed and it's version is 4.14.44
and here is git log for optee in $(linux_root)/driver/tee
![image](https://user-images.githubusercontent.com/3404383/44534694-aa0ed880-a6f8-11e8-98ab-7ea00b0c65e8.png)

this is the only commit for optee.
does anybody knows which version I have to use for optee-client optee-os?
Thank you

**Comment by jenswi-linaro** [comment]
The latest and greatest should work. You may want to use a more recent kernel though, most of the stuff we have on the stuff we have in the SWG branch went into 4.16. If you've noticed any problems I'd be interested in hearing that.

So far I think that any upstream kernel since 4.12 will work with anything since the kernel API is supposed to be compatible. I wouldn't recommend using such an old kernel of course.

Speaking of upstream commits, it seems you already have a few that aren't upstream.

**Comment by casionwoo** [comment]
@jenswi-linaro 
Thanks for your reply. this kernel git log is only for /driver/tee 
such as **git tree driver/tee** command

I will let you know the result after trying with recent optee projects (optee-client, optee-os, optee-test)
