### ISSUE TITLE
Abnormaly slow I/O times

### ISSUE THREAD

**Issue by PedroRibeiro95** [OP-TEE/optee_os#2530]
Hello.

I developed a prototype (NA and TA), and initially tested it via QEMU. Now I want to run it on a development board. Everything works just as it did on QEMU, except the I/O, which takes a very long time to write files (between 5-10 seconds). This is troublesome for me, as I want to measure the execution time of the prototype.

How can I solve this problem?

Thank you.

**Comment by jenswi-linaro** [comment]
Which files? Secure storage objects? How large are they? In what manner are they written? Where are they stored, REE FS or RPMB FS?

**Comment by jbech-linaro** [comment]
So you're facing two problems? Slow I/O and you don't know how to measure the execution time? For the first one it's hard to say anything about it since you haven't provided any information about the hardware, not what kind of operations you are trying to do. To measure execution / running time, you could give our (crude) [benchmark framework](https://github.com/OP-TEE/optee_os/blob/master/documentation/benchmark.md) a try.

**Comment by PedroRibeiro95** [comment]
Hello @jenswi-linaro and @jbech-linaro, and sorry for the lack of details.

I'm currently using the IMX Nitrogen6x board. Everything runs as smoothly as it did on QEMU, except the I/O. I'm trying to use the secure storage (REE FS) to write relatively small files (mainly AES keys). I write them using the secure storage API.
