### ISSUE TITLE
GPIO pin only accessible from OP-TEE

### ISSUE THREAD

**Issue by Rusack** [OP-TEE/optee_os#2615]
I'm using a PineA64+ board and I'd like to be able to reserve certain GPIO pins to be used only in OP-TEE (can I do this the TrustZone memory controller ? ), but I'd like to be able to use the other GPIOs from linux as well.
Is it possible to achieve this ?

**Comment by jforissier** [comment]
@Amit-Radur do you have any information about this?

**Comment by Rusack** [comment]
Any news on this ?

**Comment by vivinamartins16** [comment]
+1! I also would like to know this!

**Comment by Andre-ARM** [comment]
You can only switch a whole GPIO controller to secure world on Allwinner. There are two of those on the A64, one covering ports B-H, the other dealing with PortL. There is *no* pin granularity for secure/non-secure. If you switch ports B-H to secure, Linux would not work (given you have burnt the secure fuse, which is required to actually enable the Secure Peripherals controller). If you switch PortL to secure, you might get away with it and be able to control all those pins from secure world only. You might need to remove the PMIC from Linux' DTB though, since this relies on using two PortL pins.
