### ISSUE TITLE
Get CA infomation in TA

### ISSUE THREAD

**Issue by s0r4syl** [OP-TEE/optee_os#2622]
Hi All,

There are two things I want to do.
The first is the implementation of CA authentication.
The second one is to connect TA and CA one to one.
Therefore, I want to acquire CA information in TA.
How can I obtain the TEEC_LOGIN_ * specified by the argument of TEEC_OpenSession on the TA side?

**Comment by jenswi-linaro** [comment]
You can't, because the driver doesn't copy that information. The reason for that is that the specifications aren't very clear on what the information means and who's guaranteeing what. Until that's clear it doesn't make sense for the driver to pass on that information. However, if you have designed a scheme that you think would be useful for others, feel free to supply patches. I'll look at them.

**Comment by s0r4syl** [comment]
Hi, jenswi.
Thank you for your reply.
Pardon my broken English.
That means that I need to create an environment which from CA to TA to pass CA's information from 1
because I can not use TEEC_LOGIN_* defined in tee_client_api.h under the present environment, right ?
I will do my best to make patches.
