### ISSUE TITLE
How to share global variables among different TA callbacks?

### ISSUE THREAD

**Issue by tiger20081015** [OP-TEE/optee_os#2624]
Hi, we have below requirements:
1. CA1 -> TA1 -> TA2: CA1 calls TA1, TA1 calls TA2 and when TA2 is called, it sets a variable A to a specific value;
2. CA2->TA2: CA2 calls TA2, when TA2 is called, it wants to read the value of A set by item 1. 

However, each time CA2->TA2 is called, it can't read the value of A set by item 1. Instead, it always gets the inital value of A, just like A never changes. Is there any method to share the changed value of A between item 1 and item 2? Thanks.

**Comment by jbech-linaro** [comment]
Hi  @tiger20081015,

In this case I believe you have to set the `gpd.ta.instanceKeepAlive` property on CA2. Since otherwise, when CA2 is done it clears all resources. To use that property, you should also set `gpd.ta.singleInstance`. You can set that in the `user_ta_header_definies.h` file, like [here](https://github.com/linaro-swg/optee_examples/blob/master/hello_world/ta/user_ta_header_defines.h#L53-L56) for example. For more details about the properties, please have a look at the GP spec (Internal Core API).

**Comment by tiger20081015** [comment]
@jbech-linaro ,
thanks, it works!
