### ISSUE TITLE
Plans to support keymaster4.0

### ISSUE THREAD

**Issue by mozoko** [OP-TEE/optee_os#2625]
Android 9 uses Keymaster 4.0.
Do you have plans to update OP-TEE to support all services of Keymaster 4.0 ?
If yes, how long does it take ?

thanks.

**Comment by jbech-linaro** [comment]
> Android 9 uses Keymaster 4.0.
> Do you have plans to update OP-TEE to support all services of Keymaster 4.0 ?

Probably yes, but we have just put together a [KM 3.0 setup](https://github.com/linaro-swg/optee_android_manifest/tree/optee_kmgk_3.3.0). We are going to work a bit more with 3.0 also, we since we have some re-factoring being planned. 

> If yes, how long does it take ?

Cannot say, but what I **can** say is that it is not on any plans in our current development cycle (Oct 2018 to  April 2019). We're not many developers in the core team so we have to carefully pick various things to work with each cycle. But as usual, if someone outside the core team volunteers to champion some work, then that is of course also welcome.

**Comment by mozoko** [comment]
I got it. Thanks.

**Comment by mozoko** [comment]
Related keymaster, let me ask more question.

https://s3.amazonaws.com/connect.linaro.org/yvr18/presentations/yvr18-414.pdf
This slide says(page10):
> After upgrading to a new AOSP version we have two regressions

Are you going to fix these regressions ?

**Comment by vchong** [comment]
> Are you going to fix these regressions ?
>

They're fixed.
