### ISSUE TITLE
Support/Document offline signing of TAs

### ISSUE THREAD

**Issue by wamserma** [OP-TEE/optee_os#2657]
First off: Yes, I read https://www.op-tee.org/faq/#how-are-trusted-applications-verified

Currently, https://github.com/OP-TEE/optee_os/blob/master/scripts/sign.py uses a local .pem file to sign the TAs. As far as I understand, this file can not be protected with a password and the signing process can not be delegated.
Yes, there is the possibility to include a TA via `CFG_EARLY_TA` and in my setting I can delegate signing the OS-blob. However, I am worried that `keys/default_ta.pem` might leak (and the public part of it goes still into the OS-blob), which opens a door for rogue TAs.

IMO, a more elegant way would be to make https://github.com/OP-TEE/optee_os/blob/master/scripts/sign.py "smarter". In case the key read here https://github.com/OP-TEE/optee_os/blob/a3a309a8637a3a819c48aaca16a70ca7fc2dc7ce/scripts/sign.py#L40 is a pure public key, then `h` from https://github.com/OP-TEE/optee_os/blob/a3a309a8637a3a819c48aaca16a70ca7fc2dc7ce/scripts/sign.py#L65 is output to a file `$img.hash`.
This hash can subsequently be signed offline (using OpenSSL, a SmartCard, a HSM, a TPM,...).
If `sign.py` is then (re)invoked and given a signature as additonal argument, the signature is verified (for sanity) and the Image is constructed as in the remainder of the script.

What is your take on this proposal? It should not break existing workflows as far as I can judge.

**Comment by jbech-linaro** [comment]
> First off: Yes, I read https://www.op-tee.org/faq/#how-are-trusted-applications-verified
> 

:1st_place_medal:  for doing that before open an issue!

> Currently, https://github.com/OP-TEE/optee_os/blob/master/scripts/sign.py uses a local .pem file to sign the TAs. As far as I understand, this file can not be protected with a password and the signing process can not be delegated. However, I am worried that keys/default_ta.pem might leak

The private key must be handled with great care within a company. Usually only one or two person will have access to a private key.

> (and the public part of it goes still into the OS-blob), which opens a door for rogue TAs.

It's no problem to have a public key in the OS blob as long as it is immutable. I.e, part of chain of trust is to also verify that the public key is what it is supposed to be. That is why you typically make a hash of the public key and store that in OTP memory or similar. During boot you compute the hash of the public key and compare it with the hash in OTP. If they are the same, then you know that that public key is "**your**" public key and not any other rouge public key. I.e., from that point it's safe to you that public key to verify the signature.

> What is your take on this proposal? It should not break existing workflows as far as I can judge.

I'm not sure I follow your proposal here. Are you saying that instead of using the private key to sign the image, we shall use the public key to sign the image? If that is the case, how can you prevent anyone from signing any image? (the public key is public knowledge). I've probably misunderstood what you're after.

**Comment by wamserma** [comment]
@jbech-linaro I guess I need to clarify my rambling.
The first point was about using CFG_EARLY_TA. If I read the doc correctly, then default_ta.pem will not be used if there are no other TAs that need signing. The public part will still be anchored in the OS, but the private part will be unused. Currently, the public part is extracted from the private key .pem during the build process. My issue was, that a developer who puts all his TAs into CFG_EARLY_TA may leave the private key in his source repo as it seems to be unused. Now, if someone gets hold of the private key, it might be possible to create a malicious TA, sign it, inject it into the deployed OS and invoke it from the REE. This could be mitigated by an `ALLOW_ONLY_EARLY_TAS` option or sth. like that.
But this was not the main cause for opening this issue.

The main cause was, as you rightly noted,
> The private key must be handled with great care within a company. Usually only one or two person will have access to a private key.

Ideally, this key is generated inside an HSM, which it will never leave. All signing operations are done with this HSM. The current implementation of `sign.py`, however, expects the private key to be readable by the script. My proposal was to modify `sign.py` to optionaly offload the actual RSA operation to such a HSM or some other environment thats more trustworthy than a developers machine. (Yes, I know about Ken Thompsons classic paper, but let's just assume the toolchain is not corrupted, but keys may be exfiltrated by an attacker.)

**Comment by jbech-linaro** [comment]
> Ideally, this key is generated inside an HSM, which it will never leave. All signing operations are done with this HSM. The current implementation of `sign.py`, however, expects the private key to be readable by the script.

Ah, I get the point. Yes, that would work, in that case you'd fully ignore using the key in the script. I.e. you can calculate everything in the script, but you sign the hash offline. This means that the script would be a two step thing:
1. Created header with magic, size etc.
2. Do `SHA256(h)`.
3. Sign output from '2' with HSM or similar.
4. "Continue"/re-run the script with the signed signature.

I kind of like the idea, but it would require us to change the script so that they current way still works (for regular developers and other people who cannot and do not want to use external signature). So one could change the script to take some more parameters.

```
--offline_signing   <Don't do any signing in script, outputs SHA256 hash>
--signature         <Signature to be written, outputs a signed TA, just as normally>
```

So with something like that you'd run the script twice:
```bash
$ sign.py --offline_signing
b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
```
Go offline, sign this hash
```bash
$ sign.py --signature HSM/RSA(b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c)
signed_ta.ta
```

Another alternative is to create a new and separate "sign_offline.py" script that does this and leaves the current one intact. If you feel for creating a proposal, I'm all ears.

**Comment by wamserma** [comment]
> Yes, that would work, in that case you'd fully ignore using the key in the script.

I'd not ignore the key but rather check whether it is a public key and use it for checking the signature before merging the sig with the TA.

I'd also rather make the script "smarter" in a way that it checks whether the key is a full key or a public key only and in the latter case maybe even looks for a file carrying the signature, reducing the developers work to
```
make
sign_offline
make
```
I'll put this on my list and eventually a PR for this will pop up.

**Comment by jforissier** [comment]
Clearly related: https://github.com/Microsoft/ms-tpm-20-ref/tree/master/Samples/ARM32-FirmwareTPM/ta_prod_signing_scripts

**Comment by wamserma** [comment]
> 
> 
> Clearly related: https://github.com/Microsoft/ms-tpm-20-ref/tree/master/Samples/ARM32-FirmwareTPM/ta_prod_signing_scripts

Yes, definitely. I'll try to head for as much compatibility as possible withou breaking the current process.

**Comment by jbech-linaro** [comment]
@wamserma have you had any time to look into a PR proposal yet?

**Comment by wamserma** [comment]
@jbech-linaro Unfortunately not yet as project priorities were shuffled around. But the issue has moved closer to the top of my list.

**Comment by wamserma** [comment]
@jbech-linaro PR is here: https://github.com/OP-TEE/optee_os/pull/2832

**Comment by jbech-optee-adm** [comment]
Cool, thanks! I'll have a look at the PR also.

**Comment by wamserma** [comment]
Closing this issue as resolved since functionality is merged with https://github.com/OP-TEE/optee_os/pull/2832 and the update of documentation is tracked through https://github.com/OP-TEE/optee_docs/pull/11.

**Comment by jbech-linaro** [comment]
> ... the update of documentation is tracked through [OP-TEE/optee_docs#11](https://github.com/OP-TEE/optee_docs/pull/11).

Thanks for reminding me about that docs PR, is it ready? Seems like there is a pending comment between you and @jforissier in that PR. Anyhow, let's continue the discussion in the doc PR instead of this PR. Thanks for closing!
