### ISSUE TITLE
x509 API mbedTLS

### ISSUE THREAD

**Issue by pokitoz** [OP-TEE/optee_os#2658]
Hello,

I would like to use the x509 API which is available through the mbedTLS library. Hence, in my TA, I included the mbedTLS header file:

`#include <mbedtls/x509.h>`

And I can call the mbedTLS functions from the TA. However, I was wondering if there is a plan to add a layer so I call a generic OPTEE-OS API, or maybe a Global Platform API.  

Instead of calling: 
`mbedtls_x509_crt_parse_path(...)`
I would call a function similar to:
`tee_x509_parse_path(...)`
Which will be redirected to mbedTLS or another library to handle x509 certificates.

Another question I have is about the handling of the stored certificates using mbdedTLS. The function 
`mbedtls_x509_crt_parse_path` needs to be given a path in argument. The function is not available in OPTEE-OS as `MBEDTLS_FS_IO` is unset. However, if I stored a x509 certificate using `TEE_CreatePersistentObject`, and I read it using `TEE_ReadObjectData`, could I achieve the same result?

Thanks!

**Comment by jenswi-linaro** [comment]
Hi,

I'm not aware of any GP specified API:s for X.509 and there's not really any clean defacto standard for it either. So we chose to expose the mbedtls API directly instead of inventing anything new ourselves.

Storing and reading certificates in secure storage should work well. Note that mbedtls isn't aware of the GP secure storage so that part would need to be handled by the TA.

**Comment by pokitoz** [comment]
Thanks ! I will keep using the mbedTLS API then.
