### ISSUE TITLE
Is DRM support in OP-TEE open source for windvine ?

### ISSUE THREAD

**Issue by aansari2408** [OP-TEE/optee_os#2681]
Is DRM support in OP-TEE open source for windvine ?

**Comment by jbech-linaro** [comment]
@aansari2408 , it is the same answer as in the other thread:
For Widevine the answer is no, since Google mandates that people should have signed the Widevine Master License Agreement (WMLA) to be able to work with that. That is basically a NDA. We (Linaro) would be happy to open source it, but the decision is not in our hands.

**Comment by aansari2408** [comment]
Thanks @jbech-linaro 
Is any cost involved to have signed the Windvine master license agreement(WMLA) ?

**Comment by jbech-linaro** [comment]
@aansari2408 I'm "just" a technical guy (even though I for sure now the guys working with membership etc), but if you want to explore membership, then it's best to go here: https://www.linaro.org/membership/ scroll down to the bottom and press the "Apply to join" button, that will take you to the correct people for a discussion like this.

**Comment by aansari2408** [comment]
@jbech-linaro  Thank you very much and really appreciated for your help!
