### ISSUE TITLE
Overrunning array tmp of 32 bytes by passing it to a function which accesses it at byte offset 63

### ISSUE THREAD

**Issue by alezzdiki** [OP-TEE/optee_os#2716]
Hello there,

Coverity complains about a possible overrunning of the array tmp by calling the function:
https://github.com/OP-TEE/optee_os/blob/d8265859f026e7bbdadcbf1e4f25cf281623d927/lib/libmbedtls/mbedtls/library/md.c#L392

Actually, in case MBEDTLS_SHA512_C is not defined,  MBEDTLS_MD_MAX_SIZE is 32
https://github.com/OP-TEE/optee_os/blob/d8265859f026e7bbdadcbf1e4f25cf281623d927/lib/libmbedtls/mbedtls/include/mbedtls/md.h#L52

https://github.com/OP-TEE/optee_os/blob/d8265859f026e7bbdadcbf1e4f25cf281623d927/lib/libmbedtls/mbedtls/library/md5.c#L112

so, in mbedtls_md5_process, tmp will be accesses up to byte 63, isn'it?

**Comment by jbech-linaro** [comment]
I haven't digged deeply into this, but I can't spot any error. If `MBEDTLS_MD_MAX_SIZE` (which seems to be a generic define for all hash operations) is set to 64 byte output, then there is no problem. If it's set to 32 byte output, then MD5 still fits, since the output from MD5 is less than this (16 bytes). In the end the process function does a memcpy into a buffer which has size 64 (https://github.com/OP-TEE/optee_os/blob/beb065df6ee53d014366068a138ccdb780b733d0/lib/libmbedtls/mbedtls/library/md5.c#L258).

Yes, the the MD5 algorithm works with 512 bit blocks in the compression function, but is for an internal state and not for the actual output.
