### ISSUE TITLE
TEE_GetPropertyAsBinaryBlock() is not returning base64 encoded buffer

### ISSUE THREAD

**Issue by ncpsa** [OP-TEE/optee_os#2726]
Hi All,

As per the spec, the API TEE_GetPropertyAsBinaryBlock() should always return binary block,whihc should be encoded to base64.
But When I try to get TAs extended property, the value of the property is encoded string, then the buffer will be decoded into UTF-8 string in the API propget_get_ext_prop() and it will be returned by TEE_GetPropertyAsBinaryBlock(), which is wrong as per specification.
Could someone please explain why the implementation is contradicting with spec?

Thanks in Advance.

Regards,

**Comment by ncpsa** [comment]
Hi @jbech-linaro,
Since the input buffer is encoded buffer to the API TEE_GetPropertyAsBinaryBlock(), it should not be decoded and should return the buffer as it is. But decoding is happening in the API propget_get_ext_prop() for USER_TA_PROP_TYPE_BINARY_BLOCK case.
So do we need to encode it again in TEE_GetPropertyAsBinaryBlock() before return?.
If yes, then why decoding is happening, which is unnecessary in this case?.
Still I am trying to understand.

**Comment by jenswi-linaro** [comment]
It's not clear (at least in the 1.1 spec) that `TEE_GetPropertyAsBinaryBlock()` should return the value base64 encoded.

It says:
*The function TEE_GetPropertyAsBinaryBlock retrieves an individual property and converts its value
into a binary block.*

So I guess that was interpreted literally.

Taking section 4.4 Property Access Functions into account I agree that it's more likely that the `TEE_GetPropertyAsBinaryBlock()` is supposed to return a base64 encoded binary block.

If we change the behavior of `TEE_GetPropertyAsBinaryBlock()` we have to make sure that the GP tests still passes.

**Comment by jforissier** [comment]
I can run the GP tests but it seems we're filtering out the only test that checks the value returned by `TEE_GetPropertyAsBinaryBlock()` :( It is test `a7-85-e1` a.k.a. `xtest_tee_8025`.

What the test does is configure a TA with a predefined property in a manifest file:
```
smc.ta.testbinaryblock: VGhpcyBpcyBhIHRleHQgYmluYXJ5IGJsb2Nr
```
...then it makes sure `TEE_GetPropertyAsBinaryBlock()` returns this exact value. Since I could not find any information on how the manifest file is supposed to be interpreted, we cannot conclude with 100% confidence, but given that the test data represent the string "This is a text binary block" with base64 encoding, it is a strong hint that `TEE_GetPropertyAsBinaryBlock()` should always base64-encode the data.

**Comment by ncpsa** [comment]
Since the reading the data from manifest file  is  also as binary block data, we can say it is binary block data and it is base64 encoded.  xtest_tee_8025 should pass if do not do **base64_dec** in **propget_get_ext_prop**

**Comment by jforissier** [comment]
I looked into this more deeply, and I think we're doing the right thing.
- The TA declares a binary property by providing its base64-encoded string -- quite convenient because the value has to be given via a `void *` pointer and nothing else, no length in particular (see `struct user_ta_property`).
- `TEE_GetPropertyAsBinaryBlock()` will return the binary value (i.e., after base64 decoding)
- `TEE_GetPropertyAsString()` will return the base64 encoded value, which does fit the GP requirement "the implementation SHALL convert the property into a printable string" and more specifically the sentence "Binary block is converted into a string that is consistent with a Base64 encoding" in section 4.4.

@jenswi-linaro 
>Taking section 4.4 Property Access Functions into account I agree that it's more likely that the TEE_GetPropertyAsBinaryBlock() is supposed to return a base64 encoded binary block.

No, it is `TEE_GetPropertyAsString()` that is supposed to return a base64 encoded block.

**Comment by jenswi-linaro** [comment]
@jforissier , thanks for looking into this.

**Comment by jbech-linaro** [comment]
@jforissier I read this as it's actually not a bug? Should we close the ticket?

**Comment by jforissier** [comment]
> I read this as it's actually not a bug? Should we close the ticket?

Correct.

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
