### ISSUE TITLE
Rainbow screen on rpi3 with optee

### ISSUE THREAD

**Issue by dkarnikis** [OP-TEE/optee_os#2783]
Hello,
I have built successfully optee os for qemu and write some custom TA's without any problems. 
My next step was to boot optee into rpi3.
I followed the guide https://github.com/OP-TEE/build/blob/master/docs/rpi3.md, flashed the image to the sd card, booted the rpi but a rainbow screen pop's up.
(usb devices are not getting any power. I have managed to boot other OS).
I am using hdmi ouput (following this guide https://github.com/OP-TEE/optee_os/issues/1367) 
Am i doing something wrong?
Thanks a lot,
Dimitris

**Comment by jbech-linaro** [comment]
Hi,

Feels like I'm repeating in each and every ticket about RPi3 but anyways ...

1. We're updating the documentation. A snapshot of the work in progress can be found here for RPi3: https://optee.readthedocs.io/building/devices/rpi3.html. Even though not fully ready, please use those for general RPi3 information as well as for standard setup with SD-card  (NFS, JTAG has not been verified yet on the new updated instructions). There are many clarifications on that page about what is supposed to work and what's not, what version of RPi hardware and what not etc. ETA for updated instructions are ~April 2019.

2. Today 2019-01-31 I've created a video clip while I was verifying the instructions. I.e., a full setup from scratch, you will find that here (I'm going add narrative audio later on to describe more what's going on): 
[![OP TEE on Raspberry Pi 3 with SD card](https://img.youtube.com/vi/-IcC2b3AJdA/0.jpg)](https://youtu.be/-IcC2b3AJdA)

Since I did "2" today and it is from scratch, it should be fairly easy to follow along if you use the upcoming documentation + look at (and pause) the video.

// Joakim

**Comment by dkarnikis** [comment]
Hello again,
thanks for the video and for the guide.
I have found that my rpi3 flashes the red light 4 times which means that start.elf is corrupted.
I replaced it with an other start.elf (just to check the  flash sequence) and the flash sequence was different(still no output on UART). 
Do you know what would be the case? Could you provide me with your stalf.elf or your whole /boot directory?

**Comment by jbech-linaro** [comment]
> > 1. We're updating the documentation. A snapshot of the work in progress can be found here for RPi3: https://optee.readthedocs.io/building/devices/rpi3.html.

> Few minor comments on u-boot environment

That has not been changed/updated/covered yet and that's what I tried to indicate with the comment "``(
NFS, JTAG has not been verified yet on the new updated instructions)``"in my comment. My intention is to spend some time with that today. Anyhow, thanks for the additional feedback, I'll have that in mind/use this when doing the updates. Thanks!

**Comment by jbech-linaro** [comment]
@msa2 , I've looked into this as mentioned earlier today and I think I'm with you on the two first bullets, but the ones about `dhcp` I'm a bit more skeptical to. To replace dhcp with the IP of the PI, then you need to figure out that on your own. It's not really hard and will stay the same for the lease time of your router. But, it's a bit inconvenient I think if dchp can do it for you. Your last bullet about "*get address and network that cannot reach the NFS server*". Is that likely to happen? To me it feels like for that to happen you have misconfigured you router, /etc/exports etc. I.e., I'm in favor of keeping `ip=dhcp`. What do you say?

**Comment by jbech-linaro** [comment]
> * you configure your nfs server as 192.168.1.100
> ...
> * when rpi3 tries to connect to your nfs server on 192.168.1.100,

That's not really a surprise, shouldn't the NFS server have a 10.2.2... IP  and also said in its exports file tell that the share is located at its own IP, i.e., also a 10.2.2.x in that case? Maybe I'm a bit into deep water here, I'm no network guru.

**Comment by jforissier** [comment]
@msa2 why would the NFS server not have an address in the 10.2.2.0/24 network?

Anyway, not sure it can help, but I found PyPXE to be a very useful tool when you have to deal with a local test environment including DHCP/TFTP/NFS and you are already on a network with a DHCP server. It can act as a DHCP proxy.

**Comment by msa2** [comment]
> @msa2 why would the NFS server not have an address in the 10.2.2.0/24 network?

Because in my case the NFS server is my laptop sitting on same desk and rpi3. If "NFS" server gets address from 10.2.2.0/24 dia DHCP, it can get different addresses on different boots, and then I would again need to edit the uboot.env...

My setup is simply

```
192.168.1.200 rpi3 ----|
                       |bridge ----- internal net --- internet
192.168.1.1.100 laptop-|
+ internal DHCP address
```
e.g. laptop has two addresses (if do `ifconfig eth0:1 192.168.1.100`). This way boot.env is stable, regardless of my internal address on corporate net.

However, no big deal. I guess anyone setting up NFS server, is capable of figuring out best option for himself.

**Comment by dkarnikis** [comment]
well,
I have solved my issue, the start* files were the problem(was working on rpi3b+) and the dtb.
I am having hdmi support aswell. TEE is working as expected. Might upload my solution and a guide for rpi3b+ with hdmi support(no uart needed) as soon as I find some time.
Cheers

**Comment by jforissier** [comment]
@dkarnikis glad it's working for you.

> Might upload my solution and a guide for rpi3b+ with hdmi support(no uart needed)

Would be awesome.

**Comment by dkarnikis** [comment]
@Hacklog24 
Hello, i will try to upload my guide in the upcoming days. Still have to clean it up and verify the steps.
Cheers

**Comment by Hacklog24** [comment]
@dkarnikis 
Thanks a lot for the answer. When it's ready, can you notify me? 

Thank you so much,
Cheers

**Comment by dkarnikis** [comment]
i will ping you first, don't worry(have a couple stuff do to)

**Comment by Hacklog24** [comment]
@dkarnikis 
Of course!
Thank you again, I'll wait.

**Comment by dkarnikis** [comment]
@Hacklog24 
hello,
I have uploaded a rushed 'guide' that  you can find here https://github.com/dkarnikis/rpi3bplus-optee
It is still quite ugly, I am not very good with this part.
Feel free to contact me :)

**Comment by Hacklog24** [comment]
@dkarnikis 
Hi and thank you very much for the timely help!

The guide is fantastic, clearly explained and if the previous steps are correct, it will work great. Congratulations and well done! Tested with both UART and HDMI cables.

Cheers

**Comment by jbech-linaro** [comment]
> I have uploaded a rushed 'guide' that you can find here https://github.com/dkarnikis/rpi3bplus-optee

@dkarnikis , thanks! I'll update our official docs in the future in one or another way to reflect this (I should probably buy a 3b+ myself at some point).

**Comment by Hacklog24** [comment]
@dkarnikis 
Hello again,
did you solve the network problem? You would be a great help, thanks!

**Comment by johnphilby** [comment]
> I have uploaded a rushed 'guide' that you can find here https://github.com/dkarnikis/rpi3bplus-optee

@dkarnikis Your boot files for RPi3 b+ works, thanks. But it isn't clear from your instructions the files that you replaced to get it to boot. Your instructions say "so I swapped some files from the latest ubuntu core ..." -- could you provide the details of the exact files you swapped and the original location from where it was copied from?
