### ISSUE TITLE
Docs sources are hard to find and don't encourage contribution of board HOWTOs

### ISSUE THREAD

**Issue by daniel-thompson** [OP-TEE/optee_os#2793]
Currently documentation for OP-TEE is split between:

https://github.com/OP-TEE/optee_os/tree/master/documentation (OS internals)
https://github.com/OP-TEE/optee_website/tree/master/documentation (documentation tab on website)
https://github.com/OP-TEE/optee_website/tree/master/docs (board ports)

This has the effect of completely burying to board port documentation (AFAICT there is no click trail that leads to the board port documentation... not even a cross link from optee_website/documentation and to optee_website/docs).

Arguably the biggest problem here is that board port authors are not encouraged to (or perhaps even aware that they could) contribute a basic guide describing how to build and load optee_os for the platform they have ported to. I think we could curate much better board documentation simply by managing the board docs in optee_os rather than optee_website so that port authors are more likely to include documentation on how to load optee_os on their platform.

Likewise moving the list of supported platforms from _website to _os would help ensure it is better maintained (I think this table still describes the state of optee_os rather than the wider OP-TEE family of repos).

PS If there is agreement on migrating these to optee_os it would also be good to ping @kylekirkby and get the resulting optee_os/documentation through the static generator and made prominent on op-tee.org .

**Comment by jbech-linaro** [comment]
@daniel-thompson , this is well known to us, I had it up for discussion at Connect (see [doc](https://docs.google.com/presentation/d/1qRJb-04kB7n9O_8o4NmLrBAu2wrkiB3r-yEr3343GGY/edit#slide=id.p4)). We decided to create a new **optee_docs** folder alongside with the other gits, this is tracked in [SWG-355](https://projects.linaro.org/browse/SWG-355) (require Linaro login to view).

So, I have an task with ETA OP-TEE 3.5.0 which is about gather all docs at a single location. I.e., no longer spread across a) different gits b) Google drive docs c) optee.org etc. A snapshot of WIP can be found here: https://optee.readthedocs.io . I'd say that it's about ~80% complete and many of the pages are much more up-to-date, than the official ones, since I've re-read them all and tested all instructions etc.

optee.org will still be there, but it will be more of a landing page which then just re-direct to the optee.readthedocs.io will be the official page in the future. Hopefully this will help board port authors also in the future (make it easier and more understandable to to contributions).
