### ISSUE TITLE
Global variables inside TA

### ISSUE THREAD

**Issue by AlessandroVisintin** [OP-TEE/optee_os#2796]
Hi all,

I need to store some data while a Trusted Context is alive. Is it secure to use global variables inside the TA code? Or is it better to use Temporary objects? The data I am storing must be visible only inside the TA and should disappear after the context is closed.

Thank you very much!

**Comment by jbech-linaro** [comment]
Hi @AlessandroVisintin , TA's are sandboxed from each other, so the global variable is mapped into memory currently only accessible by your TA. I.e, a global variable in a TA is only seen/available by the TA it self (not other TA's).

**Comment by AlessandroVisintin** [comment]
Ok thanks a lot, as always quick and informative answer.

**Comment by dsimmoAnyVision** [comment]
@jbech-linaro I understand your comment. What still confuses me though is that each trusted application has a corresponding file stored in the non trusted OS. Can this file not be reverse engineered to reveal the global variable, or is the global variable stored somewhere else (in a secure potion of the devices memory)?

I have some other questions:
**1.** If I was to provide a firmware image (i.e., the underlying file used to flash the chip) with trust zone enabled through optee, how secure would the global variable be that I had stored in my TA be?
**2.** Could the firmware image itself be reverse engineered to reveal the global variable?
**3.** If the above would pose a security risk, are these risks removed by personally flashing the chip myself and releasing the chip (rather than the image) to a third party?

**Comment by jbech-linaro** [comment]
> @jbech-linaro I understand your comment. What still confuses me though is that each trusted application has a corresponding file stored in the non trusted OS. Can this file not be reverse engineered to reveal the global variable, 

It can, but you're not supposed to store secrets in the binary itself. If you do that, then you're toast.

> or is the global variable stored somewhere else (in a secure potion of the devices memory)?
> 

An initialized (global) constant can be found in the ELF (in `.data`, `.text`, `.rodata` or similar). If it's an uninitialized, then it'll get the value zero and found in `.bss`. But again, you shouldn't set global variable to a secret value.

> I have some other questions:
> **1.** If I was to provide a firmware image (i.e., the underlying file used to flash the chip) with trust zone enabled through optee, how secure would the global variable be that I had stored in my TA be?

Initialized to a secret value, then **not** secure at all. Initialized and used in run-time, then you're safe.

> **2.** Could the firmware image itself be reverse engineered to reveal the global variable?

Yes, if initialized to with a secure value, otherwise no.

> **3.** If the above would pose a security risk, are these risks removed by personally flashing the chip myself and releasing the chip (rather than the image) to a third party?

With the current solution, my advice is that you should definitely avoid putting known secrets into the binary itself. Instead generate the secrets runtime and then store those in secure storage. If we implement support of loading encrypted TA's (from flash in normal world), then one might argue that it's OK to store secrets in it (I'd still recommend to avoid it). But we haven't got such a solution as of today ... maybe in the future.

**Comment by jenswi-linaro** [comment]
> But we haven't got such a solution as of today ... maybe in the future.

Not entirely correct, there's "Secure Storage TA" which does that already. How the TAs are transferred into that storage is another story.

**Comment by jbech-linaro** [comment]
> > But we haven't got such a solution as of today ... maybe in the future.
> 
> Not entirely correct, there's "Secure Storage TA" which does that already. How the TAs are transferred into that storage is another story.

With my comment `...  (from flash in normal world)` in parenthesis I referred to the TA's loaded from NW flash, i.e., under `/lib/optee_armtz` and we have no solution for getting (pre-)encrypted TA's into OP-TEE.

**Comment by jenswi-linaro** [comment]
`/data/tee` is also a path in flash in normal world. So what's actually missing is another way that what's used in xtest to install the TAs.

**Comment by jbech-linaro** [comment]
> `/data/tee` is also a path in flash in normal world.

I know. Reading out the "TA" from `/data/tee` isn't easy (it's a bunch of garbled data), At least I don't know how to do it (seems like that'd be a security issue if one could figure out what the data is mapped to). Likewise if that still would be possible I don't know how to encrypt and put a TA into the correct location and keeping the integrity of the Merkle tree.

So sorry for repeating, but I still argue that we have no solution for getting (pre-)encrypted TA's into OP-TEE, but .. maybe in the future.

**Comment by jenswi-linaro** [comment]
I think you're misunderstanding me. The encrypted TAs are not stored in a Merkle tree (which has all payload data encrypted, not garbled, by the way), they are just AES-GCM encrypted with a key which is stored in secure storage. The only link missing in the chain is how to supply the data which is then stored as an encrypted TA (the input to `tee_tadb_ta_write()`).

So the TA itself is stored encrypted in normal world FS, only meta data and encryption key is stored in secure storage.

**Comment by jbech-linaro** [comment]
> I think you're misunderstanding me.

I think that is in both directions :) Anyhow, to avoid more confusion, let's wrap it up with this statement. A vendor cannot install or update using an already encrypted TA, that is future work, agree?

**Comment by jenswi-linaro** [comment]
Yes, I agree that some pieces are missing. My point is that if this is something someone really wants, it's not that big thing to implement since storage and loading already is in place.

**Comment by jbech-linaro** [comment]
Thanks!
