### ISSUE TITLE
About hardware support

### ISSUE THREAD

**Issue by Tigerly** [OP-TEE/optee_os#2813]
Hello op-tee team,

I was wondering:
Is there a simple way to check whether my device (hardware) supports op-tee?
(For example, whether the hardware has the TEE, and whether op-tee can be installed into it? )

Thanks in advance!

**Comment by jbech-linaro** [comment]
More or less every Arm-chip since many years back have TrustZone on them. The questions is whether you can use it or not. Some vendors lock it down, others don't. Luckily there seems to be many who doesn't. For those that aren't locked down, it's up to you to decide what kind of TEE you want to run. There are both proprietary as well as open source (OP-TEE is one of them).

We have gather a list of all the devices that are officially supported in OP-TEE. That list can currently be found [here](https://github.com/OP-TEE/optee_os#3-platforms-supported). That is an always growing list. So far it seems like it has been pretty straight forward to add support for new boards. The current FAQ lists a couple of examples [here](https://github.com/OP-TEE/optee_website/blob/master/faq/README.md#how-do-i-port-op-tee-to-another-platform).

> Is there a simple way to check whether my device (hardware) supports op-tee?

Probably easiest to check the list above. 

> (For example, whether the hardware has the TEE, and whether op-tee can be installed into it? )

As said, all your devices will likely have TrustZone support and if open, then OP-TEE can be ported if not already supported.

**Comment by casionwoo** [comment]
I usually use DTS file if there's a device information on OPTEE.
