### ISSUE TITLE
force CA terminated,then system crash.

### ISSUE THREAD

**Issue by benhaz1024** [OP-TEE/optee_os#2826]
When I used Ctrl+C terminate CA(linux app)，I found that the system maybe crash sometimes.
I tested it on two hardware platform:

1.  Raspberry Pi 3B+
~~2.  NXP LS1012A~~

I guess the reason maybe when the code in Secure world（Optee-os or Monitor) switch back to Non-S
ecure world, the Linux kernel process context has disappeared due to linux app terminated.

Or something else I missed?

Thanks.

**Comment by benhaha** [comment]
Can any developers give me some help？
Thanks.

**Comment by jenswi-linaro** [comment]
That's unexpected. I can't recall having seen this myself, but I have to admit that I don't terminate applications with Ctrl-C very often. Do you have more details? Is it reproducible on a standard build with QEMU?

**Comment by benhaha** [comment]
@jenswi-linaro  thank you.

I have resolved this issue.

Before  envirenmont:

I used OpenWrt with OPTEE-OS and Arm Trusted Firmware.
With default build only 1 CPU core can be recognized(cat /proc/cpuinfo) and this issue present.

How I resolved:
Patch linux device tree. So that all 4 CPU cores works, and this issus also resolved.

I will test again, and close this issue if no errors.

**Comment by jbech-linaro** [comment]
@benhaha , if you have a patch for it, feel free to send it to us so get can get this fixed in the upstream tree(s).

**Comment by amelroua** [comment]
@benhaz1024 can you tell me please how to build op-tee with openwrt (using Qemu or Rasspberry Pi) and which patch you used?
