### ISSUE TITLE
HUK for ARM32 i.MX6 without hardware key derivation

### ISSUE THREAD

**Issue by Emantor** [OP-TEE/optee_os#2892]
Hello,

the i.MX6 processor I am currently working on has no hardware unique key to use for secure storage key generation. The CAAM hardware module also includes no mode to generate a hardware unique key only accessible to the secure world. It does however contain a mechanism to encrypt and decrypt information which is hardware unique (BLOB/DEBLOB) and can only be used in the secure world.
Me and a colleague did some brain storming and came up with the following solutions:
1. Have the early bootloader load the blob into memory, OP-TEE deblobs it and uses this information for the hardware unique key. If no blob address is supplied, OP-TEE uses an RNG and the Linux supplicant to save the blob to persistent storage.

2. Support lazy generation of the secure storage key. The blob is saved on the linux file system and on the first access to the ree fs, OP-TEE requests the blob via RPC, decrypts it and generates the secure storage key.

3. Implement a new ree fs driver which uses BLOB/DEBLOB for individual files and saves the blobs using the RPC.

Each of the approaches has advantages and disadvantages, e.g. 1 requires boot loader support, 3 requires the implementation of a ree fs driver specific to i.MX6, etc.

My primary questions are:
- Does anybody have a better solution to the HUK problem?
- Which of the approaches is most likely to be included mainline?

Thanks for your input.

**Comment by jenswi-linaro** [comment]
The hardware unique encrypt/decrypt looks interesting. Perhaps that can be used to generate the key?
Would it be possible to encrypt the string "hardware unique key" (padded to a complete block)?

**Comment by Emantor** [comment]
Using the BLOB/DEBLOB functionality in this way is unfortunately not possible, since the CAAM generates a key for each blob which is encrypted together with the payload. Therefore subsequent encryptions of the same payload will generate different blobs, since each blob contains a newly generated key for the payload.

**Comment by jenswi-linaro** [comment]
That's unfortunate indeed, I have to admit I'm a bit surprised that it's not possible. The feature is there, it's just that it's then explicitly hidden inside the BLOB/DEBLOB scheme.

If that road is closed I think I'd prefer option 1, perhaps with a twist where the HUK-BLOB is part of the DTB passed to OP-TEE.

**Comment by jluebbe** [comment]
@jenswi-linaro Actually, for our use-case we'd prefer option 2. We want to load OP-TEE early to reduce the amount of code running in the secure world.

So we could load OP-TEE from the first bootloader stage (barebox PBL in this case, similar to u-boot's SPL), but we would need to enable drivers to load the per-device blob from storage (NAND, eMMC or EEPROM). As the i.MX6 ROM can already load the full image (PBL, OP-TEE, main barebox) into RAM, storage drivers are not needed otherwise. We also don't have code for DTB manipulation in the early stage.

What are your doubts about option 2, where the HUK wouldn't be available until a supplicant is available? As far as I can see, OP-TEE doesn't need it until requests from the normal world come in, but by then a supplicant is already available.

**Comment by jenswi-linaro** [comment]
With option 1 all special tweaks needed are contained in the early boot, after that everything is as usual. This option is also least complicated in OP-TEE OS.

Option 2 is more complicated. How is RPMB handled with this option? Interaction with RPMB while still in U-Boot will be impossible, I guess.

Note, I'm not against option 2 I just want to make sure we get the best solution possible.

**Comment by jluebbe** [comment]
I agree that option 1 is less complex in OP-TEE. The PBL is still part of the trusted base, as it runs in the secure world before OP-TEE, so I'd prefer to avoid additional complexity there as well.

According to https://github.com/OP-TEE/optee_docs/blob/master/architecture/secure_storage.rst#rpmb-secure-storage, a supplicant is needed for RPBM. So interacting with RPMB in the bootloader would require a supplicant implementation there, which could also provide the initial key blob to OP-TEE.

Using OP-TEE from the main bootloader is something we want to have later, as well.

**Comment by jenswi-linaro** [comment]
There's already supplicant support in U-Boot to use RPMB, but there's not support to use any file system. That's not a problem since OP-TEE itself manages the file system inside RPMB.

With option 2 we'd need a way for U-Boot to load the HUK-blob. From OP-TEE point of view there shouldn't be any difference if we're currently in U-Boot or the kernel.

**Comment by jluebbe** [comment]
> There's already supplicant support in U-Boot to use RPMB, but there's not support to use any file system. That's not a problem since OP-TEE itself manages the file system inside RPMB.

We can't store the HUK-blob in the RBMP, as we can't send authenticated read commands without having the HUK. So it needs to be stored somewhere else (EEPROM, main eMMC partition).

I tought about using efuses to store the HUK-blob, but that's no general solution: On the i.MX6 Solo-Quad, we have only ~64bit free, while the blob would be 640bit. On the i.MX6UL, there are many more general purpose efuses, so it would be a nice solution there, as the efuses could be read directly by OP-TEE.

> With option 2 we'd need a way for U-Boot to load the HUK-blob. From OP-TEE point of view there shouldn't be any difference if we're currently in U-Boot or the kernel.

I agree that OP-TEE shouldn't see any difference between kernel or bootloader.
U-Boot can load from filesystems with fs-/ext4-/fatload, in barebox filesystems can be mounted. So it shouldn't be too complex to hook that up with the supplicant implementation.

**Comment by sdininno** [comment]
@Emantor , 
your statement "The CAAM hardware module also includes no mode to generate a hardware unique key only accessible to the secure world"
is not entirely true.
As you have rightfully stated that the hardware supports (BLOB/DEBLOB) mechanism, this same functionality can be used to generate (or derived ) the SSK without the need to actually store any data on persistent storage.
As you may know the Blob mechanism uses a Key encryption Key (KEK)that is derived from the OTP Master key. This KEK is not usually an output of the CAAM but instead diretly use by it to encapsulate (or decapsulate) the blob.
however there is a command that can be sent to the CAAM to output this KEK, by creating a Master key verification descriptor.
this KEK can then be used to create the SSK for secure storage. a similar mechanism can also be used for the RPMB key.

this functionality shoud be available at the end of April on code aurora 
https://source.codeaurora.org/external/imx/imx-optee-os/
our plan is to upstream the HUK support (as well as the CAAM support) on github as well.

**Comment by jluebbe** [comment]
@sdininno I had noticed the Master Key Verification Blob format as well. But: according to the docs, the master key is used for key derivation, *regardless of security mode*. I read that as meaning that the BKEK is the identical for accesses from secure and normal worlds. It looks like it would also be available even when not booted via HAB. We've not tried that, though.

If it was the same BKEK value in all modes, we couldn't be sure that it has not been copied before HAB is setup, making it less secure than loading a blob with a random key. (As that's only possible after HAB was enabled.)

**Comment by jluebbe** [comment]
@sdininno Do did you have a chance to check if we see different Master Key Verification Blobs from different contexts?

**Comment by jluebbe** [comment]
@sdininno Is https://github.com/ms-iot/optee_os/commit/ab616627d2ef6c2dc9a1be4eb05a3bd35edb5e2c#diff-58e965cf33d42d72f00a3ced99ec876eR122 the approach you are suggesting?

**Comment by sdininno** [comment]
@jluebbe , 
sorry for the late reply. 
yes this looks like a similar approach, although not the same code.
from the Master Key Verification blobs from different context, i has been a while since we have done those tests.  Also please note that on i.MX6Q, DL, SX TZ is not taken into account in the derivation of the key. As an alternative you can increment PRIBLOB after generating the SSK and before the siwtch to non-secure world the first time.
As stated earlier, the code will land on code aurora later this month. But we are also actively working on upstreaming CAAM support on github (will be incremental thoug hand will probably start with hash support first). We will at that time redo some of the test.
regards, 
Silvano

**Comment by Emantor** [comment]
I have fused an i.MX6Q board today and verified that incrementing the `PRIBLOB` indeed also changes the master key verification blob. This means that it is fit to be used for SSK derivation. I'll create a minimal possible CAAM implementation from your current CAAM pull request and implement my BLOB support on top of it.
