### ISSUE TITLE
i.MX8 Support

### ISSUE THREAD

**Issue by SimonWan** [OP-TEE/optee_os#2906]
Hi there,

I set up my i.MX8 board with OPTEE option by following the [instruction](https://www.nxp.com/docs/en/user-guide/i.MX_Yocto_Project_User's_Guide_Linux.pdf). However, by reviewing the [OPTEE documents](https://optee.readthedocs.io/building/gits/build.html), it looks like imx8 is not a support platform yet.

I'm just wondering what's the current states and is that possible for me to build TA to run on the imx8 board?

Thanks.

**Comment by jbech-linaro** [comment]
Hi Simon,

Since OP-TEE is an open source project, it's impossible to who has forked it and how they are using it. I.e., beside what you find here on the official forum/pages etc, there are many forks that is not maintained by us. The instructions you are referring to is one such example.

Our repo manifest + build.git doesn't support the I.MX8 as of today. So you're probably best of giving NXP's instructions a try.

**Comment by SimonWan** [comment]
@jbech-linaro got you, thanks.

**Comment by 21212124** [comment]
Hi @SimonWan,
 
Could you tell me the steps you took to start with OPTEE?

Thanks

**Comment by SimonWan** [comment]
@21212124 just updated the question with the document name and link.
