### ISSUE TITLE
optee_examples build[raspberry pi 3B]

### ISSUE THREAD

**Issue by Xinyao90** [OP-TEE/optee_os#2934]
Hi, 

I'm trying to build optee_example on raspberry pi 3B.

I followed the optee_example build instruction 
https://optee.readthedocs.io/building/gits/optee_examples/optee_examples.html

For the host application build using GNU Make,
No matter I use 32-bit build or 64-bit build, they all give me errors(my raspberry pi 3B is 64bit).
For 32-bit build, the error is:
$ make \
> CROSS_COMPILE=arm-linux-gnueabihf- \
> TEEC_EXPORT=/home/tj/rpi3/optee_client/out/export \
> --no-builtin-variables
arm-linux-gnueabihf-gcc -o optee_example_hello_world main.o -lteec -L/home/tj/rpi3/optee_client/out/export/lib
main.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
Makefile:21: recipe for target 'optee_example_hello_world' failed
make: *** [optee_example_hello_world] Error 1

For 64-bit build, the error is:
$ make CROSS_COMPILE=aarch64-linux-gnu- TEEC_EXPORT=/home/tj/rpi3/optee_client/out/export --no-builtin-variables
aarch64-linux-gnu-gcc -Wall -I../ta/include -I/home/tj/rpi3/optee_client/out/export/include -I./include -c main.c -o main.o
aarch64-linux-gnu-gcc -o optee_example_hello_world main.o -lteec -L/home/tj/rpi3/optee_client/out/export/lib
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: cannot find -lteec
collect2: error: ld returned 1 exit status
Makefile:21: recipe for target 'optee_example_hello_world' failed
make: *** [optee_example_hello_world] Error 1

Any suggestion will be thankful.

**Comment by jbech-linaro** [comment]
Hi,

I believe this is because there was a patch (https://github.com/OP-TEE/optee_client/commit/3f28557f972b9840cf4453665d0f2f3240a5eca8) in optee_client not that long ago (in [this](https://github.com/OP-TEE/optee_client/pull/143) pull request) that change the path. You can try change 
```bash
TEEC_EXPORT=/home/tj/rpi3/optee_client/out/export --no-builtin-variables
```
to
```bash
TEEC_EXPORT=/home/tj/rpi3/optee_client/out/export/usr --no-builtin-variables
```
and I think it should work. In any case, we have a release around the corner, so we are going to do regression tests for everything in the coming two weeks. Issues like this should be fixed before making a new stable release. Having that said, here I think it is fixed upstream on master, it's "just" the documentation that is wrong. I'll check that and fix it if needed.

**Comment by underflag** [comment]
i just think you use the uncorrest the xml to downlording the source code. NOT the default.xml and the rpi3.xml and then repo sync. And I also make the problem

**Comment by Xinyao90** [comment]
@jbech-linaro Thanks, it solves my problem.
