### ISSUE TITLE
Broadcom e-mail address bounces

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#2938]
`bcm-optee-feedback-list.pdl@broadcom.com` (in MAINTAINERS) bounces, at least for me.

@sandeepbrcm is there anything wrong with this address?

(and BTW, the list should probably be a L: entry not R:).

**Comment by sandeepbrcm** [comment]
Thanks @jforissier.  Post permission for the list was by default for within the Broadcom domain. 
It is corrected now.

The intention was to have reviewers as a list instead of single person so that we do not have to change this file ever for internal changes. 
 However if it has to be an L: entry, can I have R:  and L:  both the entries  for example:   
R: sandeep.tripathy@broadcom.com 
L: bcm-optee-feedback-list.pdl@broadcom.com

**Comment by jforissier** [comment]
Hi Sandeep,

> However if it has to be an L: entry, can I have R: and L: both the entries

Yeah, having a list as a reviewer is a bit of a problem IMO, because we will never accept a Reviewed-by: with a list address, so it is a bit inconsistent. L: is better for a list, obviously.
Actually I like your suggestion. May I append your full name and GitHub nickname, too? Like so:
```
R:      Sandeep Tripathy <sandeep.tripathy@broadcom.com> [@sandeepbrcm]
L:      bcm-optee-feedback-list.pdl@broadcom.com
```

If you're OK with this I will create a PR.

**Comment by sandeepbrcm** [comment]
Thanks @jforissier  Created the PR  #2940 .
