### ISSUE TITLE
TEE InitializeContext if failing

### ISSUE THREAD

**Issue by jiwonjoung** [OP-TEE/optee_os#2950]
Hello I am getting the error 
`ERR [726] LT:TEEC_OpenSession:522: TEE_IOC_OPEN_SESSION failed` in my QEMUv7  program.

However, the function that invokes the trusted world is called several times before this without fail and the function args have not changed. The trusted world's terminal does not display any error so it appears to be a problem with the normal world. 

I gdb'd my app and the bug disappears into a library and there is no viewable stack. 

Questions are twofold: 
1. What are the reasons why I might get  `TEE_IOC_OPEN_SESSION` failed after successfully calling the same TA_Invoke command before? 
2. How can I follow dynamic library calls in the OPTEE gdb setup?

**Comment by jiwonjoung** [comment]
is there a way I can make gdb break on `tee_ioctl_open_session`?

**Comment by jbech-linaro** [comment]
Yes, in GDB:
```
symbol-file <linux>/vmlinux
b tee_ioctl_open_session
```
Eventually you have to disable optimization in `linux/drivers/tee/Makefile` in case you cannot see the symbol.
```
CFLAGS_tee_core.o = -O0
```

**Comment by jiwonjoung** [comment]
thanks I'll try that -- also is there a diff between <qemu-v7-project>/out-br/host/bin/arm-buildroot-linux-gnueabihf-gdb and  <qemu-v7-project>/toolchains/aarch32/bin/arm-linux-gnueabihf-gdb?

**Comment by jiwonjoung** [comment]
I tried this and got 'cannot access memory" 
-- any advice?

**Comment by jbech-linaro** [comment]
Regarding `/out-br/host/bin/arm-buildroot-linux-gnueabihf-gdb` and `/toolchains/aarch32/bin/arm-linux-gnueabihf-gdb` I suppose both will work, I use the latter one, i.e., the one in the toolchain-folder.

> I tried this and got 'cannot access memory"

Load the symbols and set the breakpoint **before** starting the simulation in QEMU, i.e. don't press 'c' in QEMU. Instead do that from GDB after loading the symbols and setting the breakpoint. Basically do the same as suggested [here](https://optee.readthedocs.io/building/devices/qemu.html#gdb-secure-world), but instead of loading OP-TEE secure side symbols etc, you load Linux kernel symbols.

**Comment by jiwonjoung** [comment]
yes I did connect the remote GDB  
-- thanks I'll give that a shot 

Furthermore, do you have any ideas about how to fix failed calls to TEEC_InitializeContext?
