### ISSUE TITLE
TEE_ALG_RSA_NOPAD for Sign/Verify

### ISSUE THREAD

**Issue by Emantor** [OP-TEE/optee_os#2979]
I am working with the SKS patch set from @etienne-lms. I coupled libsks with the pkcs#11 openssl engine, generated a RSA private public keypair inside SKS and used this to create a certificate.
When using the openssl s_server with the certificate, the pkcs#11 mechanism CKM_RSA_X_509 is not implemented by SKS.
This corresponds to TEE_ALG_RSA_NOPAD, however to use this with the openssl engine, sign/verify support needs to be supported. The GPD TEE API specifies only Encrypt/Decrypt for this function.
Since this is raw RSA, the decrypt and encrypt functions can also be used to implement sign/verify.
I have a branch which adds the necessary couple of definitions and checks, but I am not sure how this should be exposed to the build system, since this is an extension to the API.
With these definitions and a patched SKS the openssl s_server works.

**Comment by vchong** [comment]
Just want to find out, to what extent does your branch overlap with the patches in https://github.com/OP-TEE/optee_os/compare/3.3.0...kmgk_pta_3.3.0, e.g. https://github.com/OP-TEE/optee_os/commit/962d00403a0fe4db482bd2eaf8e95548ecfd6218?

**Comment by Emantor** [comment]
Yep, thats pretty much it. I also had to touch `tee_svc_cryp.c`, since the `cs->mode` is checked there as well and add `op->info.operationClass = TEE_OPERATION_ASYMMETRIC_SIGNATURE` for TEE_ALG_RSA_NOPAD.
I'm not sure about the last change.

**Comment by vchong** [comment]
@etienne-lms The patches in https://github.com/OP-TEE/optee_os/compare/3.3.0...kmgk_pta_3.3.0 might not be needed anymore once the refactoring [1] is done, so not sure if you want to discuss/work with @Emantor wrt any patches required here (for SKS)? The patches from https://github.com/OP-TEE/optee_os/compare/3.3.0...kmgk_pta_3.3.0 can be used as a reference or starting point if useful, although they're a bit outdated with the introduction of crypto ops [2]. I have the updated patches on my personal fork and can provide links if necessary.

[1] SWG-360: move keymaster PTA to regular TA and use TA libmbedtls instead of core libtomcrypt (no ETA atm)
[2] https://github.com/OP-TEE/optee_os/pull/2868

**Comment by vchong** [comment]
> I have the updated patches on my personal fork and can provide links if necessary.

Might as well do it, even if not necessary: https://github.com/vchong/optee_os/compare/2976273f390e0654fb95928838ed0e251be8451f...kmgk_pta_rebase

**Comment by etienne-lms** [comment]
@Emantor, if you have changes to propose in optee related to SKS, even if changes are in OP-TEE core (not in the TA itself), do not hesitate to push P-Rs on the sks branch of my repos (os, client and/or test).

If some changes looks nice to be merged in the OP-TEE mainline, we can create a P-R on OP-TEE.

**Comment by etienne-lms** [comment]
@vchong, indeed the work made for keymaster can be reused here but obviously needs adaptation. SKS TA should use mbedTLS library for certificate manipulation. 

@Emantor, sorry I don't think I'll have time to work on that in the short term. I would be please to but likely later. Forks and contributions are welcome. If you want me to review P-Rs on your own github repo (always helps), please feel free to ask.

**Comment by Emantor** [comment]
@etienne-lms I'll open a PR on your repo and we can discuss the upstream approach there.
