### ISSUE TITLE
How to have a shared memory between TA and hypervisor

### ISSUE THREAD

**Issue by saeedm92** [OP-TEE/optee_os#3085]
Hi,

I have OPTEE and Xen running on my development board. I have a working TA in OPTEE. I would like to have a small (4 byte) shared memory between my trusted application (TA) and hypervisor kernel. Also, I don't want to register any shared buffer for my TA from my userspace application. How would that be possible? I'm fine with using of pseudo-TA (pta) rather than a normal TA too.

Thanks,

**Comment by jenswi-linaro** [comment]
The you need to share at least 4kB as that's the smallest page size. The easiest path here is to use a PTA. You can share memory via a static mapping, so if you can say that a certain physical page is to be shared you can have it mapped at boot with help of:
``` C
register_phys_mem(MEM_AREA_NSEC_SHM, start, size);
```

You may need to define a new `enum teecore_memtypes` to be used instead of `MEM_AREA_NSEC_SHM` or the guest could fool OP-TEE into reading/writing something into that memory.
