### ISSUE TITLE
MMU intialization in optee

### ISSUE THREAD

**Issue by mrajsingh** [OP-TEE/optee_os#3097]
Hi, I am working to port optee and am new to this area. Specifically I am looking into MMU initialization. Below are my doubts and am looking forward for help to correct my understanding.

1. If TZDRAM used lies in 40-bit address space with LPAE enabled, then should CFG_LPAE_ADDR_SPACE_SIZE be (1ull <<40) for my configuration?

2. If yes, then, there is below compile time assertion  in core_mmu_lpae.c
    ```
COMPILE_TIME_ASSERT(CORE_MMU_L1_TBL_OFFSET ==
               sizeof(l1_xlation_table) / 2);
```
   Specifically, when CFG_WITH_LPAE is enabled, then, CORE_MMU_L1_TBL_OFFSET becomes much smaller. 
     ```
 #ifdef CFG_WITH_LPAE 
      #define CORE_MMU_L1_TBL_OFFSET      (CFG_TEE_CORE_NB_CORE * 4 * 8)
       #else

```
Am I missing something here? 

3. Going ahead, with 40-bit address TZDRAM and LPAE enabled, I get through all xlate table but when MMU is enabled,  `msr sctlr_el1, x0 ` , then there is synchronous exception after `isb` instruction. Any pointers ??

Thanks in advance.

**Comment by jenswi-linaro** [comment]
1. Yes, if you're executing from that memory then it needs to be 1-to-1 mapped. This requirement may be removed in future releases, but this is what we have currently.

2. The compile time assert is a real time saver here. Because `CORE_MMU_L1_TBL_OFFSET` is wrong in your configuration (large `CFG_LPAE_ADDR_SPACE_SIZE` and `CFG_CORE_UNMAP_CORE_AT_EL0` set to `y`). `CORE_MMU_L1_TBL_OFFSET` needs to be updated to take `CFG_LPAE_ADDR_SPACE_SIZE` into account.

3. Are you able to read any registers, like ESR? If not, perhaps it's easier to start with QEMU for AArch64 to see if it works there.

**Comment by mrajsingh** [comment]
Thanks a lot for the reply, Jens.

1. I realised that the address range is 37 bits for my system
   instead of 40 bits. So, with CFG_LPAE_ADDR_SPACE_SIZE being (1ull <<37)
   and CORE_MMU_L1_TBL_OFFSET being (4*4096) Optee worked fine.

2. From the comments about CFG_CORE_UNMAP_CORE_AT_EL0 
   looks like it is to addresses CVE-2017-5715. And the fix is, 
   enabling CFG_CORE_UNMAP_CORE_AT_EL0 creates 2 tables one for user mode 
   and another for kernel mode. 

3. So, does it mean that while using CFG_LPAE_ADDR_SPACE_SIZE
   (more than 32 bits range) CFG_CORE_UNMAP_CORE_AT_EL0 should be disabled?
   
4. Also, I did not fully understand the below lines from core/arch/arm/include/mm/core_mmu.h

  ```
 #ifdef CFG_WITH_LPAE  
   #define CORE_MMU_L1_TBL_OFFSET      (CFG_TEE_CORE_NB_CORE * 4 * 8)
```
   
   How does CORE_MMU_L1_TBL_OFFSET is (4*8) times number of TEE cores?
  and why CORE_MMU_L1_TBL_OFFSET is 4 * 4K without LPAE?

   Could you please help me correct my understanding here?

Thanks Again Jens!!

**Comment by jenswi-linaro** [comment]
1. I can't make sense of this.

2. Correct.

3. Only if you don't care about `CVE-2017-5715`, I'd prefer fixing the problem than brushing it under the carpet.

4. With `CFG_CORE_UNMAP_CORE_AT_EL0` the number of L1 translation tables are two instead of just one. `CORE_MMU_L1_TBL_OFFSET` is used to switch back and forth between them. Check the compile time asserts in `core_mmu_lpae.c` and `core_mmu_v7.c` and I hope it's a bit more clear.
