### ISSUE TITLE
Allocating aligned memory

### ISSUE THREAD

**Issue by Emantor** [OP-TEE/optee_os#3116]
Working with the CAAM requires memory alignement on cacheline size. Currently the NXP pull request implements their own aligned memory tracking by overallocating, wrapping the memory into a struct and returning the aligned pointer. However I expect that eventually more drivers will have alignement requirements and each driver implementing their own aligned allocation function won't scale
The existing memalign function was removed in 8cd8a629697499bd2b497818964944e277b3360b because it was broken. I think the fundamental problem in this case is that bget does not implement aligned allocation itself, making all wrappers fundamentally problematic. While investigating a switch to dlmalloc I noticed that OP-TEE switched from dlmalloc to bget before, see 074ba9b23d8a550fa8d8f23d673e4b6984de10ba.
This raises two questions:
1. Why did OP-TEE switch from bget to dlmalloc initially?
2. Is another switch of the allocator something that is even in scope and would be mergeable?

Thanks,
Rouven

**Comment by jforissier** [comment]
Hi @Emantor,

> 1. Why did OP-TEE switch from bget to dlmalloc initially?

You mean from dlmalloc to bget, right? (dlmalloc was present since OP-TEE was open sourced).
In fact, prior to 074ba9b, libutee had bget, libutils built for core had dlmalloc, and libutils built for user space had no malloc function. After this commit, libutee has no malloc, and libutils has bget. 

So, IIRC it was purely a matter of code consolidation (removing redundant code, moving malloc to libutils where it makes more sense since libutils is kind of OP-TEE's libc), and bget was preferred over dlmalloc but I don't know if there is a specific reason. @jenswi-linaro do you remember?

> 2. Is another switch of the allocator something that is even in scope and would be mergeable?

Well, if it brings useful functionality, I would say why not.

**Comment by jenswi-linaro** [comment]
> So, IIRC it was purely a matter of code consolidation (removing redundant code, moving malloc to libutils where it makes more sense since libutils is kind of OP-TEE's libc), and bget was preferred over dlmalloc but I don't know if there is a specific reason.

I guess we chose bget since it was perceived to be smaller and more suitable for embedded bare metal software. The main target for dlmalloc is user space which compared to secure world has more memory to manage by several magnitudes. So perhaps dlmalloc doesn't scale low enough, expected size of the heap is in the ballpark of 64 KiB.

If we're to switch from bget to something else we need to make sure that the parameters we care about still are acceptable or improved. Here's a few to consider:
- Fragmentation avoidance
- Overhead in terms on wasted memory
- Overhead in terms of CPU cycles, this is a bit complicated so I guess we could settle with "not obviously bad"
- Code size

An interesting memory allocator I've run across lately is umm_malloc, described at  https://dmitryfrank.com/articles/heap_on_embedded_devices

**Comment by jbech-linaro** [comment]
I'm closing the ticket, either because it has already been answered or that it is no longer relevant or it could be lack of response from the author. Having that said, feel free to re-open the ticket if you have more to add to the ticket.
