### ISSUE TITLE
imx6ul Fastinterrupts with optee

### ISSUE THREAD

**Issue by alekarasma** [OP-TEE/optee_os#3144]
Hello All,

I am implementing  imx6ul keypad driver as trusted application, I want to enable FIQ interrupts on it. Can anybody help me how to enable FIQ interrupt on keypad driver. 
I have enable keypad driver in imx6 device tree as follows:
pinctrl_kpp: kppgrp {
			fsl,pins = <
				MX6UL_PAD_KEY_ROW0__KEY_ROW0    0x1b010
				MX6UL_PAD_KEY_ROW1__KEY_ROW1    0x1b010
				MX6UL_PAD_KEY_ROW2__KEY_ROW2    0x1b0b0
				MX6UL_PAD_KEY_COL0__KEY_COL0    0x110b0
				MX6UL_PAD_KEY_COL1__KEY_COL1    0x110b0
				MX6UL_PAD_KEY_COL2__KEY_COL2    0x110b0
			>;
		}; 

I have written trusted application for keypad.
I am not getting how to enable FIQ interrupts as my driver will be implemented in secure zone.
Will itr_add() & itr_enable is enough for this?

Regards,
Asma

**Comment by vchong** [comment]
There's no interrupt related GP Internal API for user mode TA, so you'll have to use/write a pseudo TA. You can refer to https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/pta/interrupt_tests.c as an example, but do you really need to this in a TA? If not, you can just do it in `main.c`. See https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-synquacer/main.c#L97 for references.

**NOTE**: It's summer time and many people in the core team is on vacation, so expect delayed answers to both questions as well as feedback in pull requests!

**Comment by alekarasma** [comment]
Thank you @vchong for quick reply.
Could you please help me in understanding this.
I am working on payment application in imx6ul. I am writing 4x4 keypad driver, which I will be writing in optee driver and I will add interrupt handler which will be called whenever key is pressed.

Whenever the key is pressed, I have to send the key pressed value{"1","2",..."f"} to normal world in encoded format{"*","@"....}.

But what I dont understand is how will I send it?
1. Can optee driver call secure world? I believe, No.
2. If I write Pseudo TA, how will Pseudo TA come to know about key press? Will optee driver would be able to call Pseudo TA?
and again after that the same question, How will i notify to Normal world?

It would be very helpful, if you could explain if its possible to implement keypad driver as above requirement and if yes, How?

Thanks &  Regards,
Asma

**Comment by vchong** [comment]
> Can optee driver call secure world?

Yes since it runs in secure world too.

> how will Pseudo TA come to know about key press? Will optee driver would be able to call Pseudo TA? How will i notify to Normal world?

I assume that, roughly, the 'communication' path would be CA <-> PTA <-> op-tee driver. The CA will call into the PTA, PTA waits [1] for a key press from the driver, receives it and sends it back to the CA. In this case, the driver now would be the one handling the interrupts, not the PTA. I suppose either the driver or PTA can do the encoding.

[1] Not sure what implications there might be if you wait too long in secure world without returning to normal world (e.g. Linux watchdogs) but since OP-TEE is scheduled by Normal World, there's no way for it to be in standby at all time to suddenly receive an interrupt and notify Normal World about it. You might have to time out your wait, return to normal world and come back into secure world to wait again - some sort of polling I guess. See #3147 for a similar issue.

Here are more references that'll be useful:
https://optee.readthedocs.io/architecture/core.html?#interrupt-handling
https://github.com/jenswi-linaro/optee_os/blob/tui-old/core/drivers/ps2mouse.c

**Comment by alekarasma** [comment]
Thank you @ vchong,

I need one suggestion, if you could suggest me please.
As I am writing keypad driver in optee core. IMX6UL has definition of its Keypad port module in device tree as follows:

kpp: kpp@20b8000 {
				compatible = "fsl,imx6ul-kpp", "fsl,imx6q-kpp", "fsl,imx21-kpp";
				reg = <0x020b8000 0x4000>;
				interrupts = <GIC_SPI 82 IRQ_TYPE_LEVEL_HIGH>;
				clocks = <&clks IMX6UL_CLK_KPP>;
				status = "disabled";
			};

&kpp {
    pinctrl-names = "default";
    pinctrl-0 = <&pinctrl_kpp_1>;
    keypad,num-rows = <5>;
    keypad,num-columns = <4>;
    linux,keymap = <
           0X00040031
           0X00010032 
          ............
         .............
>;   
    status = "okay";
};

Do you think should its is a good idea to keep definition in device tree or I should delete from device tree and defined it in optee core for my application?

Regards,
Asma

**Comment by vchong** [comment]
I don't know exactly the interactions of the keypad with normal world but I suppose generally if it'll interfere with what you need it to do in secure world then you'd need to delete or at least disable it. This also assumes that removing the node doesn't affect boot in any way.

**Comment by alekarasma** [comment]
There is no interaction of keypad with normal world. whenever the key is pressed, secure world sends its value to normal world. thats it.

In this case, where should be my keypad definition?

**Comment by jenswi-linaro** [comment]
The pressed keys are passed to normal world I understand it correctly. Why not read them directly in normal world instead? Impossible to configure non-secure access to keypad?

**Comment by alekarasma** [comment]
`Impossible to configure non-secure access to keypad?`
Dint understand what do you meant by this.

I am working on payment application which require keypressed values to be catched in secure world.
For this reason I am implementing keypad driver in secure world.

So for this I am asking if I am implementing keypad driver in secure world, is it also required to define keypad pins to be implemented in secure world or implementing it in device tree would be okay?

**Comment by jenswi-linaro** [comment]
My point is that if you just pass on the received keys to normal world then there's no value in processing it in secure world at all.

**Comment by jbech-linaro** [comment]
I have the same considerations as @jenswi-linaro . I'd buy it if you read the key presses in secure world and process them in secure world, since in that case you do everything in a secure domain. But if you read them in secure world and send them to non-secure side. What's really the point of reading it out from secure side? As soon as it is on non-secure side, the data is susceptible to normal Linux root attacks etc.

**Comment by alekarasma** [comment]
@jenswi-linaro @jbech-linaro 

I am going to process keypad values in secure world. The pressed key value and the value of Entered PIN from keypad will undergo crypto services and then will be send to Normal world, as this is for payment EFTPOS application.

**Comment by alekarasma** [comment]
Thank you @vchong  @jenswi-linaro @jbech-linaro  for help.

I am able to solve the above issue. I deleted keypad node from device tree and added pin definition through IOMUX controller in optee core and it worked.

Cheers,
Asma
