### ISSUE TITLE
Installing OP-TEE OS alongside Debian

### ISSUE THREAD

**Issue by sheepNo** [OP-TEE/optee_os#3165]
I'm trying to use OP-TEE OS with Debian in the normal world. I'm not sure if my question is within the scope of your project but I've seen someone do the same thing on the Hikey [here](https://github.com/OP-TEE/optee_os/issues/1234).

I've successfully build and used OP-TEE on Qemu, changing the kernel I want in normal world is also fairly easy. However I can't find how to boot with a full-fledged Debian in the documentation.

The current process uses buildroot, obviously I'm not going to try to replicate Debian using buildroot. Is there anything I've missed in the doc ?

**Comment by jbech-linaro** [comment]
I used to maintain the Debian/Hikey setup that we had enabled a couple of years ago. However, we had not enough time to maintain and test that build, so we decided to drop it. But in short, you can replace the Buildroot fs and replace it with an Debian fs for Arm. Then you need to put the necessary OP-TEE files in that Debian fs, i.e., libteec.*, xtest, *.ta etc. If done correctly it should just work.

I'm still using a Debian based fs when doing NFS boot from time to time (RPi3), but that is a local hack on my side.

**Comment by sheepNo** [comment]
Thanks for your time and quick reply. Just to be sure, you compile everything with buildroot and then swap the resulting fs with a Debian one (then add a few optee files back in) ? And then I guess `make run-only` should work for QEMU.

I'm not sure which `rootfs` is actually used and which one I'm supposed to swap out. `find . -name "rootfs*"` returns quite a few `rootfs.cpio.gz`, `rootfs.cpio`, `rootfs.tar` in `out/` and `out-br/`.
I suppose swaping out the `*.tar`is no sufficient.

**Comment by jbech-linaro** [comment]
Right, everything from Buildroot are gathered in `out-br/images/rootfs.cpio.gz`. If you find a Debian rootfs for Arm, then you can just as well replace the `out-br/images/rootfs.cpio.gz` with that instead. But you for course have to add all the files I mentioned in one or another way. So, if Buildroot is of no interest, then there is not much point in compiling stuff for that. In theory it should be possible to just disable that make target. But since we unfortunately have managed to create quite hard dependencies, you'll have a hard time building `optee_test` standalone (`optee_os`, `optee_client` is easy).
