### ISSUE TITLE
Run two static (or user) TAs on two different CPU cores

### ISSUE THREAD

**Issue by TEE-OS** [OP-TEE/optee_os#3177]
Is there any way to locate two TAs (no matter static TAs or User TAs) to run on two different CPU cores? I'm using i.mx6q develepment board, and using OP-TEE version 2.5. I see that the [issue 496](https://github.com/OP-TEE/optee_os/issues/496) says OP-TEE support running TAs simultaneously. But I find that my version does not have that patch. 

If I use the latest version of OP-TEE, how can I specify two TAs to run on two different CPU cores?

**Comment by jbech-linaro** [comment]
It'll happen automatically for you. Example, if core 1 has entered secure world and at the same time core 2 gets another request for some secure service. Then it'll enter secure side on this second core. I.e, both 1 and 2 will be running in secure world simultaneous.

If you want to strictly run a certain TA on a certain core, then you're out of luck, since that particular use case isn't supported.

**Comment by TEE-OS** [comment]
Dear @jbech-linaro Thank you for your reply. Do all the versions of OP-TEE support this feature or only the versions after the issue 496 patch has this feature? Thanks.

**Comment by jbech-linaro** [comment]
My memory is a big vague, but most likely starting from #496 and later.

**Comment by TEE-OS** [comment]
@jbech-linaro Thanks.
