### ISSUE TITLE
How can  I use SPI  to get Hardware Data in TA?

### ISSUE THREAD

**Issue by fengleichn** [OP-TEE/optee_os#3184]
Hi team,

I want to get hardware data  by SPI  in Op-tee TA,  can you help me? I can't find SPI config and SPI read and write function.

**Comment by vchong** [comment]
There's no SPI related functions available for TAs. You'll have to use a pseudo TA and call the driver functions directly.

**Comment by jbech-linaro** [comment]
We've never really sorted out multiple access to SPI things (and peripheral in general for that matter). So as long as you're the "only one" on the system providing TA's, you're good to go with @vchong's proposal.

**Comment by fengleichn** [comment]
you mean SPI is mounted to NW in OP-tee, not in tee?  I can access SPI  in NW?

**Comment by jbech-linaro** [comment]
> you mean SPI is mounted to NW in OP-tee, not in tee?

No, SPI is connected to the TEE. I imagine that using SPI from a TA is achieved by this:

![image](https://user-images.githubusercontent.com/6168937/62681668-83ee5100-b9ba-11e9-93dd-04092299e16a.png)

With that image you probably also understand what I meant with the challenges with multiple accesses. I.e., if you have 2 TA's trying to use SPI at the same time, then the "SPI PTA" needs to acts as an arbiter deciding where SPI traffic should go.

> I can access SPI in NW?

Of course!

**Comment by fengleichn** [comment]
According to my understanding， SPI can configured NW side or secure side;
I want to know where is the  SPI configured default on hikey960, my test code is
get from [optee_android](https://github.com/linaro-swg/optee_android_manifest)

**Comment by fengleichn** [comment]
I can not understanding PTA， Can you explain in detail?

**Comment by jbech-linaro** [comment]
> I want to know where is the SPI configured default on hikey960, my test code is
> get from [optee_android](https://github.com/linaro-swg/optee_android_manifest)

I haven't played with that myself, so I cannot help you with that.



> I can not understanding PTA， Can you explain in detail?

https://optee.readthedocs.io/architecture/trusted_applications.html#pseudo-trusted-applications

**Comment by fengleichn** [comment]
thanks for you help

**Comment by vchong** [comment]
Another thing about multiple access is NW and SW both using SPI at the same time. That'll cause collisions as well I believe although I've never really tested.

In any case, support for SPI operations on SW isn't enabled for the hikey960, only the hikey620. Looking at the manual, they both use the same PL022 IP so technically the existing driver should/could work but I don't know of anyone who's tried.

If you want to try, you can try rebuilding after removing the `ifeq ($(PLATFORM_FLAVOR),hikey)` and its corresponding `endif` in https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-hikey/conf.mk#L22 and https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-hikey/conf.mk#L39, but I advise trying it out on our regular Linux build first [1] because Android with its SELinux rules and whatnots makes it hard to get it to work. See https://github.com/OP-TEE/optee_os/issues/1461 for what the original poster had to go through to finally get it to work on the hikey620.

[1] https://optee.readthedocs.io/building/devices/hikey960.html

**Comment by vchong** [comment]
@fengleichn Sorry but I rechecked the code and it looks like trying to get SPI to work on the hikey960 will be a bit more involved than just removing the `ifeq` above. E.g. if you look at https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-hikey/main.c you'll see more code guarded by `#if defined(PLATFORM_FLAVOR_hikey)`, i.e. only compiled for hikey620. Also, the SPI and related pin pinouts and register base addresses (https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-hikey/hikey_peripherals.h) will all be different as well.

**Comment by vchong** [comment]
> Can we access SPI Device from OPTEE on platforms other than Hikey. Is it possible to access it on Platform Aspeed.

I've no idea what Platform Aspeed is. The Hikey uses the Arm PL022 IP as its SPI controller. If your platform uses the same IP then there's a good chance it will work. Otherwise you'll have to implement the drivers required for your platform.

> Also I am trying to invoke Pseudo TA from User TA. But no success. Is there any available to access Pseudo TA from User TA.

You can see `seed_rng_pool()` in https://github.com/OP-TEE/optee_os/blob/master/ta/pkcs11/src/pkcs11_token.c for example. It uses Internal Client API. See `Internal Client API` section of GlobalPlatform TEE Internal Core API Specification v1.1.
