### ISSUE TITLE
Out Of Tree TA

### ISSUE THREAD

**Issue by foreverska** [OP-TEE/optee_os#3188]
Is there a reference for creating a TA which is compiled "Out of Tree" or at least installed to the guest file system rather than installed to secure world by default?

I have attempted to change the O variable in the makefile for my TA but nothing seems to be created there even though the build process completes successfully.

**Comment by Emantor** [comment]
Take a look at how OP-TE/optee_test compiles it's TAs.

**Comment by jbech-linaro** [comment]
> I have attempted to change the O variable in the makefile for my TA but nothing seems to be created there even though the build process completes successfully.

It's unfortunately a bit messy when it comes to plain GNU make vs CMake (which is the default), I've added a comment about that [here](https://optee.readthedocs.io/building/gits/optee_test.html#build-instructions) for xtest for example. In short, in the default setup, `optee_os` uses the plain old makefile, but the rest are using CMake. So it's in CMake files you need to make the changes in case you're using the default setup (which you actually are more or less forced to use, since the old Makefiles in the other gits doesn't work for all cases anymore).

I created a playground for building standalone a while ago, this is the closest I got: https://github.com/jbech-linaro/optee_standalone

**Comment by jbech-linaro** [comment]
Speaking about that, [this](https://github.com/jbech-linaro/optee_examples/blob/aes-gcm/build.sh) is how I typically build **just** TA's "standalone", as you can see, there is some magic. I haven't tried, but I suppose that there is a chance that the `O=` flag actually would work there.

**Comment by foreverska** [comment]
Okay so I think there have been some misunderstandings which led to this question.  TAs by default are stored in the REE Filesystem.  After Secure Storage is setup (first boot) they may be installed there.  At which point the REE Filesystem copies can be deleted.  Is this correct?

**Comment by etienne-lms** [comment]
Yes, this is correct. Once a TA is installed in the secure storage, it will be loaded from there and its binary file can be removed from the REE fs.

You can experience that on your favorite platform:
- Boot then install TAs in secure storage, i.e `xtest --install-ta /lib/optee_armtz`.
- Once done, remove all TAs from the REE fs, i.e `mv /lib/optee_armtz /lib/optee_armtz-BKP`.
- Then run `xtest`, it should successfully complete as TAs are all found and loaded from secure storage.

**Comment by foreverska** [comment]
Yea, that was basically the test procedure that lead to that hypothesis.  Thanks for the confirmation.

As to the original issue, the build system is still a very scary proposition but I recognize the given examples.  I'll call this closed.

**Comment by etienne-lms** [comment]
@foreverska, as for building TAs, maybe the [doc](https://optee.readthedocs.io/building/trusted_applications.html#ta-makefile-basics) can help or clarify.
