### ISSUE TITLE
Raspberry Pi 4 TrustZone Support

### ISSUE THREAD

**Issue by HernanGatta** [OP-TEE/optee_os#3205]
While OP-TEE has been ported to run on the Raspberry Pi 3, [it is known](https://www.slideshare.net/linaroorg/las16111-easing-access-to-arm-trustzone-optee-and-raspberry-pi-3) (slides 6 & 7) that the platform is missing components for it to be fully secure.

Would anyone know if this has changed with the Raspberry Pi 4?

Thank you.

**Comment by vivinamartins16** [comment]
Anyone?

**Comment by jbech-linaro** [comment]
I don't think anyone in the @OP-TEE/linaro team knows, since we have no direct collaboration with Broadcom and so far none of us have given the RPi4 a try. My gut feeling says that it's probably the same, since RPi devices are created without TrustZone in mind.

**Comment by kunmukh** [comment]
Hi admins and fellow collaborators, 
I am recently starting to work with OP-TEE, so if my question is answered previously, pointing to the issue would really help.

The device I am using is RPi 4. I followed the instruction to install the OP-TEE from [https://optee.readthedocs.io/en/latest/building/devices/rpi3.html](url). I also watched the video made by Joakim Bech, [https://www.youtube.com/watch?v=-IcC2b3AJdA&t=246s](url) . During installation, all my installation results followed the same results as shown in the youtube video, except the last step, where you plugged your TTL cable and after sometime the terminal appeared on picocom. For my installation, I waited for 20 mins and did not see any terminal. 

That being said, my installation steps was done using Ubuntu 18 on a virtual machine using VirtualBox. And I was using Putty to listen on the COM port to see if the shell appeared (picocom step). I have used Putty and USB-to-TTL cable to get access to Raspbian Buster Lite's command prompt, before. Thats why I do not think that these will cause any issue as to why OPTEE is not booting up on RPi4.

Currently, I am following this issue thread, [https://github.com/OP-TEE/build/issues/276](url),  and tomorrow morning I am going to try to use the binary that jbech-linaro created to see if it works, [http://people.linaro.org/~joakim.bech/jdeus/](url). Any help would be really appreciated?

Also, I have ordered a RPi3 just to sure that it is not a device dependent problem. I will update this thread as I find out more.

I also saw that the support for RPi 3+ was added according to this pull request, [https://github.com/OP-TEE/build/pull/358](url), but in the official documentation page, it says that RPi3+ is not supported [https://optee.readthedocs.io/en/latest/building/devices/rpi3.html](url). Why this discrepancy? And does it means that by making the same modification made in the pull request to add support for RPi3+, the support for RPi4  can be added?

Thank you.

**Comment by jbech-linaro** [comment]
> I waited for 20 mins and did not see any terminal.

That tells that it's probably stuck in early boot stages. Next time, stop waiting after 30 seconds. If you see nothing after that, then it will not be any better.

> ... Thats why I do not think that these will cause any issue as to why OPTEE is not booting up on RPi4.

I think you're right, the serial connection is probably OK, it's probably early boot stages that gets stuck.

> I am going to try to use the binary that jbech-linaro created to see if it works, 

That is probably pointless, since that was built for the RPi3 and even without trying/checking RPi4, I'm almost 100% sure that there are differences that one need to take into account.

> I also saw that the support for RPi 3+ was added according to this pull request, https://github.com/OP-TEE/build/pull/358, but in the official documentation page, it says that RPi3+ is not supported https://optee.readthedocs.io/en/latest/building/devices/rpi3.html. Why this discrepancy?

We've forgotten to update the documentation. Thanks for the reminder.

> And does it means that by making the same modification made in the pull request to add support for RPi3+, the support for RPi4 can be added?

Maybe, I guess the differences aren't too big. If you have the time and are willing to give it a try, please go a head. Seems like RPi devices are popular for OP-TEE development also, so you'd make lots of people happy! :+1:

**Comment by kunmukh** [comment]
> We've forgotten to update the documentation. Thanks for the reminder.
> 
Okay, that makes sense.

> Maybe, I guess the differences aren't too big. If you have the time and are willing to give it a try, please go a head. Seems like RPi devices are popular for OP-TEE development also, so you'd make lots of people happy! 👍
>
Alright, I will give it a try. I will update this thread if I make some progress.

Now, for the big reveal as to is it device specific problem. My preliminary answer is, kinda YES. Today, after I got my RPi3, I just inserted the SD card from the RPi4 to RPi3, and OPTEE booted up within 10 secs. I did not have to change anything. The installation took a long time after this stage, `[4.495762] random: crng init done`. 

I think it will be nice to update the documentation with an extra column, for RPi4 and saying that it is not supported.

**Comment by jbech-linaro** [comment]
> Now, for the big reveal as to is it device specific problem. My preliminary answer is, kinda YES. Today, after I got my RPi3, I just inserted the SD card from the RPi4 to RPi3, and OPTEE booted up within 10 secs. I did not have to change anything. The installation took a long time after this stage, `[4.495762] random: crng init done`.
> 

Please see OP-TEE/build#390 which I found yesterday when doing regression testing for OP-TEE 3.7.0 

> I think it will be nice to update the documentation with an extra row, for RPi4 and saying that it is not supported.

Sure, that should also be updated. I'll put it on the todo list. Btw, the documentation is also open, i.e., anyone can contribute :wink:

**Comment by kunmukh** [comment]
> > Please see [OP-TEE/build#390](https://github.com/OP-TEE/build/pull/390) which I found yesterday when doing regression testing for OP-TEE 3.7.0
> 
I have updated my previous comment, as I did not realize that the installation actually did not complete. but rather got stuck after this command. ` [4.495762] random: crng init done` . Therefore, I am currently following this issue: https://github.com/OP-TEE/build/issues/296 and https://github.com/OP-TEE/build/issues/306 to see if anything helps. Also, if anyone can point me towards a fix for this from a previous issue, it will be really helpful.

> > Sure, that should also be updated. I'll put it on the todo list. Btw, the documentation is also open, i.e., anyone can contribute 😉
> 
Okay, will do, once I actually get OPTEE to run on RPi3 without any issue :)

**Comment by kunmukh** [comment]
>> Okay, will do, once I actually get OPTEE to run on RPi3 without any issue :)
>
 Created a pull request with the updated documentation, https://github.com/OP-TEE/optee_docs/pull/44. 

But, still have not able to figure out why I cant move past the crng init stage. Currently, using RPi3 Model B. Any help would be appreciated.

**Comment by kunmukh** [comment]
>> But, still have not able to figure out why I cant move past the crng init stage. Currently, using RPi3 Model B. Any help would be appreciated.
>

I finally got it to work. I re-did the entire sequence of installation steps all the way from the beginning. Something was changed yesterday, I think that is what jbech-linaro was pointing towards me, 
>>Please see OP-TEE/build#390 which I found yesterday when doing regression testing for OP-TEE 3.7.0
>

Thank you, so I can confirm with the latest build RPi3 is working fine.

**Comment by vivinamartins16** [comment]
Think this should help you on Rpi4 support: https://git.trustedfirmware.org/TF-A/trusted-firmware-a.git/commit/?id=17b0bb6cf53cd9cd904ac6551f3552bd884e8159

**Comment by kunmukh** [comment]
> Hey, @kunmukh !
> Think this may help you on Rpi4 support: https://git.trustedfirmware.org/TF-A/trusted-firmware-a.git/commit/?id=17b0bb6cf53cd9cd904ac6551f3552bd884e8159
>
 Thank you, will take a look it.

**Comment by 21212124** [comment]
Hi @kunmukh, 
Did you get it to work with rpi4?

**Comment by kunmukh** [comment]
> Hi @kunmukh,
> Did you get it to work with rpi4?

Unfortunately, no.

**Comment by rafagameiro** [comment]
Hi admins and fellow collaborators,
I have recently started working with OP-TEE, and since it as been an year since the close of this issue, and if in the meantime my problem has already been solved, I would appreciate if someone could point me out to the issue in question.

As this issue suggests, I have also been trying to run optee on rpi4, following the same steps as kunmukh in this comment (https://github.com/OP-TEE/optee_os/issues/3205#issuecomment-538828953), where I followed the documentations instructions to install optee in raspberry pi 3, since I assumed that most of the building process would be the same.
The problem I'm currently facing is the same as the previous referred comment, in the documentation guide last step, after plugging my rpi4 to my computer and turning it on, the screen does not display anything.

I assume some system file modification might be needed as I already verified that some boot files changed from the rpi3 to rpi4. Also, I have tried to do changes with regard to Trusted Firmware Raspberry pi 4 support (https://git.trustedfirmware.org/TF-A/trusted-firmware-a.git/commit/?id=17b0bb6cf53cd9cd904ac6551f3552bd884e8159) but so far, with no success.

If someone already succeeded in running optee in rpi4, or if the Admins are already working on a port, would it be possible to provide some guide or instructions on how to successfully run optee, so that I could also do it?

Thank you.

**Comment by jbech-linaro** [comment]
> I'd be also interested to know if there is planned support for Raspberry Pi 4.

Not right now, but your timing is good. I did purchase a RPi400 last week. Since then I have investigated various things. The RPi4 TF-A BL31 setup booting Linux is working. But to make a proper boot we'd need to update BL2 as well to load both BL31 and BL32 (OP-TEE). Then of course OP-TEE would need to be updated. But I believe there is more work on the TF-A side than the actual OP-TEE side of this.

Having said that, I've spent most of my time on the TFTP boot. I.e., to speed the turn-around time (I don't enjoy swapping uSD-card all the time), I first would like to get the TFTP (the RPi4 eeprom supported TFTP) to work. I haven't done that successfully, I can see that it pulls files, but it doesn't boot up. Probably `config.txt` related. But, this is very much a side task for me, so I don't dare to promise anything.

**Comment by hughsheehy** [comment]
Curious if there's been any movement/update .

**Comment by jbech-linaro** [comment]
I haven't had time to do more work since ~May on this. So no progress on my end.

**Comment by peter-nebe** [comment]
The issue is closed but doesn't want to die.
> If someone already succeeded in running optee in rpi4, or if the Admins are already working on a port, would it be possible to provide some guide or instructions on how to successfully run optee, so that I could also do it?

I tried it and thanks to @jbech-linaro 's help I succeeded. But this is more of a gimmick because as far as I understand the RPi4, like the RPi3, lacks the hardware characteristics to be a secure device.
https://github.com/peter-nebe/optee_os

**Comment by kunmukh** [comment]
@peter-nebe did you create a PR with your changes? And which hardware does the RPi4 lacks to make OPTEE practical?

**Comment by peter-nebe** [comment]
> @peter-nebe did you create a PR with your changes? 

No, because extensions in [ARM trusted firmware](https://github.com/ARM-software/arm-trusted-firmware) are also required. And a clean solution in optee_os would be to convert platform rpi3 to rpi with flavors rpi3 and rpi4. That would have to be agreed with the maintainers and would be a bit much work for a beginner like me.
> And which hardware does the RPi4 lacks to make OPTEE practical?

I'm not a hardware expert, but I believe the RPi doesn't have secure RAM.

**Comment by mlhh1103** [comment]
hi, @jbech-linaro I have followed same procedure as mentioned in your video，but I can not find the directory "out-br" after running the "make -j `nproc`", so I can not do the next step about the SD card, If you have any advice, thank you.

**Comment by jbech-linaro** [comment]
> hi, @jbech-linaro I have followed same procedure as mentioned in your video，but I can not find the directory "out-br" after running the "make -j `nproc`", so I can not do the next step about the SD card, If you have any advice, thank you.

Hi, recently I made a change, so the old way of making partitions etc isn't necessary any longer. With recent changes you should be able to just simply "dd" the image to an SD-card. Please cross check that. The make 'make img-help' should still tell you what you need to do.

**Comment by mlhh1103** [comment]
> > hi, @jbech-linaro I have followed same procedure as mentioned in your video，but I can not find the directory "out-br" after running the "make -j `nproc`", so I can not do the next step about the SD card, If you have any advice, thank you.
> 
> Hi, recently I made a change, so the old way of making partitions etc isn't necessary any longer. With recent changes you should be able to just simply "dd" the image to an SD-card. Please cross check that. The make 'make img-help' should still tell you what you need to do.

yes, I can see the command "$ sudo dd if=/home/mlh/optee/build/../out/rpi3-sdcard.img of=/dev/<name-of-my-sd-card> bs=1024k conv=fsync status=progress", but the "rpi3-sdcard.img" file does not exist in the "out" directory. What went wrong？(my machine version is Ubuntu22.04, I followed the instruction in the OP-TEE documentation)

**Comment by vschiavoni** [comment]
@TephrocactusMYC i'd be interested to see such repositories explaining how to launch OP-TEE on RaPi4. Can you share?

**Comment by minminlittleshrimp** [comment]
Hello @jbech-linaro
Is there any chance we can have a doc for rpi4 based on successful setup with proof-of-concept? I believe RaspPi4 is, saying, a very common and popular Board for education and optee learning. I am just on my way for flashing optee on rpi4 for my paper (still there are few setup and configurations), so if that is possible and I can get optee maintainers' approval, I can go ahead upload a PR for that document.

Hi @vschiavoni 
Thannks to **joaopeixoto13** and **DiogoRoseira** from University of Minho I am trying his approaching. In fact buildroot already support optee in GUI option setup 💯 
Here is the repo:
https://github.com/joaopeixoto13/OPTEE-RPI4

Regards

**Comment by abhi9280** [comment]
Hi experts. For my Masters work, I need to setup OPTEE on Pi4, so can just anyone let me know, where are we standing currently? Does Pi4 support OPTEE or not? Any answers would be greatly appreciated.
