### ISSUE TITLE
TEE -> REE custom service

### ISSUE THREAD

**Issue by divneil** [OP-TEE/optee_os#3266]
Hi,

I have a requirement in UTA to get custom service from REE (similar to socket PTA). So, I had developed a patch which generically allows any custom service.

I would like to get it merged. Can you please help with the process.

It's a work for earlier ticket: https://github.com/OP-TEE/optee_os/issues/2333. I am generating a new ticket as that was not intended for contribution.

Thanks,
Divneil

**Comment by jforissier** [comment]
Hi @divneil,

> I have a requirement in UTA to get custom service from REE (similar to socket PTA). So, I had developed a patch which generically allows any custom service.

Sound good.

> I would like to get it merged. Can you please help with the process.

I suggest you create a RFC ("Request For Comments") pull request, so that we can see what you have come up with. To create a RFC PR, simply mention `[RFC]` in the title (I think Github has a RFC checkbox too, check it if you have the opportunity). If you have patches for `optee_client` and/or `optee_examples` and/or `optee_test`, please create RFC PRs for them too. This will allow anyone to better understand the code and experiment with it.

General instructions on how to contribute are here: https://optee.readthedocs.io/general/contribute.html.

Thanks!

**Comment by divneil** [comment]
Hi @jforissier 

> I suggest you create a RFC ("Request For Comments") pull request, so that we can see what you have come up with. 

Thanks for your sharing the process. I have created https://github.com/OP-TEE/optee_os/pull/3270 for review. There are some things I wanted to have opinion on, so, I will post comments on the PR.

Thanks,
Divneil
