### ISSUE TITLE
File not found when building OP-TEE for RPI3 on Ubuntu

### ISSUE THREAD

**Issue by MaBejadi** [OP-TEE/optee_os#3342]
I am trying to build OP-TEE for RPI3 on Ubuntu

I am following the guide
https://optee.readthedocs.io/en/latest/building/devices/rpi3.html

However, when I try to flash the drive, I constantly get this error (File not found)

![index](https://user-images.githubusercontent.com/56938079/67431159-6198c680-f5ec-11e9-8459-658346e4d405.jpg)

And I don't seem to be able to find the file anywhere as well 

What am I missing here?

**Comment by agangal93** [comment]
Yes. I am also seeing the same issue with the latest stable release 3.7.0. After the build, out-br directory is not generated, which the SD card mounting procedure expects for flashing the root file system. I went back to using the 3.4.0 branch which I could see in https://optee.readthedocs.io/en/latest/building/devices/rpi3.html
I am thinking if the build procedure has changed post 3.4.0 but hasn't been updated in the docs?

**Comment by jbech-linaro** [comment]
> What am I missing here?

You are literally doing `mkfs.vfat ..... /dev/sdx1`, which is a device that doesn't exist on your computer. `/dev/sdx1` is just an example, since it is impossible to write instructions that works for everyone, since disks can have any name `/dev/sda1`, `/dev/sdb1`, `/dev/sdc1`, ... `/dev/sdy1`.

There is even a big note on the instruction page that you linked to that highlights that, i.e.
```
The mention of /dev/sdx1 and /dev/sdx2 when running the command above are just examples.
You need to figure out and replace that with the correct name(s) for your computer and 
SD-card (typically run dmesg and look for the device name matching your SD-card).
```

So find the `/dev/sd<whatever_letter_your_SD_card_mounts_to>` and substitute that and I'm sure it'll work for you.

Also, I did test RPI3 for the 3.7.0 release myself last week, no regression found on standard setup (RPi3 instructions) and also NFS passed with no regressions (see platforms that were tested successfully [here](https://github.com/OP-TEE/optee_os/commit/a2fa5018cb595a9cd9ab62e82c7485ca57a62084)).

> I am thinking if the build procedure has changed post 3.4.0 but hasn't been updated in the docs?

No, it hasn't changed it's still the same.

**Comment by MaBejadi** [comment]
> You are literally doing `mkfs.vfat ..... /dev/sdx1`, which is a device that doesn't exist on your computer. `/dev/sdx1` is just an example, since it is impossible to write instructions that works for everyone, since disks can have any name `/dev/sda1`, `/dev/sdb1`, `/dev/sdc1`, ... `/dev/sdy1`.

Noted, I edited to its name "sdc1" and I still got the problem

![index](https://user-images.githubusercontent.com/56938079/67433315-927afa80-f5f0-11e9-827c-6bf5131b3549.jpg)

**Comment by agangal93** [comment]
Hi @jbech-linaro 

Yes I agree that @MaBejadi has not used the SD card flashing steps correctly for the device, but the command that has failed is gzip which is failing because I cannot see a out-br directory or rootfs.cpio.gz generated after the build for the this release. Following are the contents of my directory

![optee1](https://user-images.githubusercontent.com/43253458/67433437-211e5600-f5b6-11e9-9bfb-bca0885a13b5.png)

Have I missed something in the build?

**Comment by jbech-linaro** [comment]
> Have I missed something in the build?

There is no `out-br` folder at all, which seems wrong. Everything built by buildroot and some of the optee_* gits will put its built files there. I'll turn on a build here on my side and will check it tomorrow morning when I wake up. Meanwhile can you run (from build.git)
```bash
$ make 2>&1 | tee build.log
```
and upload `build.log` to some pastebin service? http://ix.io/ or https://0bin.net/ or ... to give two examples. Please avoid using any `-j` flag since that makes it harder to read the log file.

**Comment by agangal93** [comment]
Thanks a lot @jbech-linaro 

After using this command,
```
make 2>&1 | tee build.log
```
I was able to build successfully and can now see the out-br directory. The only additional thing needed was to install python3-pyelftools before which the make was failing. I am not sure if installing python3-pyelftools fixed the issue or running a clean build without threads. 

Regards,
Akshay Gangal

**Comment by jbech-linaro** [comment]
> I was able to build successfully and can now see the out-br directory.

Good and likewise, my build here on my side went fine, no build errors etc.

**Comment by MaBejadi** [comment]
> ```
> make 2>&1 | tee build.log
> ```

> I was able to build successfully and can now see the out-br directory. The only additional thing needed was to install python3-pyelftools before which the make was failing. I am not sure if installing python3-pyelftools fixed the issue or running a clean build without threads.

This worked for me, Thank you
