### ISSUE TITLE
how to add another openssl  module  

### ISSUE THREAD

**Issue by wtxiao1984** [OP-TEE/optee_os#340]
in the openssl branch ,how to add bio pkcs7 x509 module to libopensslcrypto.a

**Comment by jforissier** [comment]
Hello @wtxiao1984,

To add code to libopensslcrypto.a, you need to edit the `sub.mk` files in `core/lib/openssl/crypto/*` and add the source files you need to the variable `srcs-y`. You will also need to add other `sub.mk` files such as in `core/lib/openssl/crypto/pkcs7`, and then update the `subdirs-y` variables so that the new `sub.mk` are used by the build step. You may also need to add C flags, this can be done at the file level or for a whole directory (please check out the existing `sub.mk` files).
This will likely bring in lots of dependencies. I would suggest to start by identifying the top-level functions you need, add the files that implement them to the build, then proceed by adding more files to resolve the missing symbols you see at link time. This can be a time-consuming process but by doing this you will likely identify some build options which you could set to disable some unneeded code, or you may add such `#ifdef`'s yourself.
Another approach would be to always add whole sub-directories to the build but as I found out in the past it can cause unnecessary trouble, like requiring some function from the C library which does not exist in OP-TEE and that you would therefore need to add, although it may not really be needed for your use case. BTW, libC is in `lib/libutils/isoc` and `lib/libutils/ext`.

HTH.

**Comment by wtxiao1984** [comment]
Thanks for your help
