### ISSUE TITLE
TEEC_InvokeCommand returned TARGET_DEAD (rc 0xffff3024) from TEE

### ISSUE THREAD

**Issue by vikaspot** [OP-TEE/optee_os#3410]
While doing any operation which involves buffer to pass from CA to TA app.
Any kind of access to a buffer passed from ca is causing TARGET DEAD.
Any idea while doing any operation as per OPTEE Samples also causes this issue.
random no generation 
Creating storage 
Writing to storage 
Pls suggest i think its some simple config or setting or some pre-initialization steps missing ..

**Comment by jforissier** [comment]
Hi @vikaspot,

Have you enabled debug traces in secure world? In order to so you need to set `CFG_TEE_CORE_LOG_LEVEL=3` when building `optee_os`. Then you should hopefully obtain a call stack on the secure console.

Perhaps there is a problem with dynamic shared memory registration. Try the same tests with `CFG_CORE_DYN_SHM=n`, and see if it works or fails differently.

**Comment by vikaspot** [comment]
CFG_CORE_DYN_SHM disabled only registered shared memory reference-based buffer operation.
But in my case, temp memory reference-based buffer operation causes TARGET_DEAD.

**Comment by vikaspot** [comment]
Thanks Solved !!
