### ISSUE TITLE
TA to Host communication 

### ISSUE THREAD

**Issue by deekshith565** [OP-TEE/optee_os#3413]
Is there anyway that I can call or invoke host APIs from TA?

@jbech-linaro @jenswi-linaro @jforissier

**Comment by jbech-linaro** [comment]
It has been discussed recently in other threads here, I cannot find the thread after doing a quick search, but spending a bit more time on searching will for sure find it.

**Comment by jforissier** [comment]
If by "host APIs" you mean invoke code in Normal World, then see https://github.com/OP-TEE/optee_os/issues/3303 (@jbech-linaro I think it is what you were looking for).

If you mean using some "standard" APIs such as pthreads etc. then the general answer is no but you need to give us more details ;-)

**Comment by deekshith565** [comment]
@jbech-linaro, @jforissier  Thanks for quick reply.
I used #3292 (Generic RPC Support) and it worked thanks @HernanGatta, now my question is there a plan to merge this to OPTEE master branch and if so by when or which next OPTEE release is it planned for?

**Comment by HernanGatta** [comment]
@deekshith565 Glad it worked for you.

Priorities have shifted somewhat on our end, which is why I haven't been active lately. However, I _do_ want to get this functionality merged in. Both Jens and Jérôme seem OK with the feature.

We're coming up on a long weekend around here, so I should be able to make some time to rework the PRs according to what's been discussed in #3303.
