### ISSUE TITLE
optee-os build failed in Android 10 due to python Crytpo library import error.

### ISSUE THREAD

**Issue by angelina-zhao** [OP-TEE/optee_os#3455]
I built the optee-os using aosp_optee.mk in Android 10, and met the errors that python Crypto library cannot be imported, such as:
Traceback (most recent call last):
  File "scripts/sign.py", line 79, in <module>
    main()
  File "scripts/sign.py", line 32, in main
    from Crypto.Signature import PKCS1_v1_5
ImportError: No module named Crypto.Signature

Although the Crypto library is installed by pip, Android 10 build system does not refer to it, and still reports import error.

I have tried to use PYTHONPATH to direct the Android build system to use the Crypto library installed by pip, but still meet errors.  The reason is that my OS (Ubuntu 16.04) has python version 2.7.12, but Android's python is 2.7.25, thus when importing the Crypto library, the "undefined symbol: PyExc_ValueError" is reported.

My current approach is to modify optee Android makefile to use the system pre-installed python (under /usr/bin), rather than the Android prebuilt python.  I would like to get recommendations on other better approachs.  Thanks.

**Comment by gitgonewithwind** [comment]
try to look at here:

https://github.com/OP-TEE/optee_os/issues/3441

**Comment by vchong** [comment]
@angelina-zhao Sorry for the late reply. Yes, this is a known issue and we're using the same approach as you. The recommendation workaround (from an AOSP engineer) is as below although we haven't managed to try any of it yet. Please do let us know if you're able to get any of the alternatives to work. Thanks.

"Normally I'd have you use python_library_host / python_binary_host Android.bp modules so that you can check in your dependencies, then build a binary that includes those libraries as a self-contained executable. But it looks like pycrypto includes a C extension for python, which is something that we haven't had to try as of yet (I suspect it would work if you rewrite exec_prefix in your script to the directory containing the shared library extensions, which should be able to build with cc_library_host).

It looks like external/avb/avbtool ran into this before and switched to using subprocess to call out into openssl -- I don't know if that's an alternative for you or not."

**Comment by angelina-zhao** [comment]
Thanks for your suggestions.
