### ISSUE TITLE
Timer value in microseconds in OPTEE

### ISSUE THREAD

**Issue by alekarasma** [OP-TEE/optee_os#3513]
Hello Everyone,

Is there a way I can get current time in microseconds in OPTEE?

Or if I do following,

uint64_t cntpct = read_cntpct();
uint32_t cntfrq = read_cntfrq();

time_in_us = (cntpct % cntfrq) / (cntfrq / 1000000);

Will this be the correct microsecond value?

Thanks,
Asma

**Comment by jbech-linaro** [comment]
If I'm not wrong we're from a TA point of view (S-EL1) at least limited to milliseconds.

```c
// GP TEE Internal Core API, section 7.1.1 TEE_Time
typedef struct
{
uint32_t seconds;
uint32_t millis;
} TEE_Time;
```

From TEE core I believe that you can read counters directly (generic timers). Have a look at [this post](https://developer.arm.com/architectures/learn-the-architecture/generic-timer/single-page) and you can read what is possible to do from various exception levels.

**Comment by jforissier** [comment]
@jbech-linaro correct, let me add that since commit 4486d5866e23 ("libutee: add headers for user-space to access sysregs"), TAs may also use `read_cntpct()` and `read_cntfrq()`.

@alekarasma be careful with integer division/multiplication order. You may get reduced precision or division by zero exceptions. I would recommend to multiply first, then divide. Use 64-bit types if needed. In other words: `uint64_t time_in_us = (cntpct * 1000000) / cntfrq;`.

**Comment by alekarasma** [comment]
Thank you @jbech-linaro and @jforissier . 

@jforissier , The above code was taken from tee_time_arm_cntpct.c and modified to get the value in microseconds.

Do you think, it also need to be taken care of?

> static TEE_Result arm_cntpct_get_sys_time(TEE_Time *time)
> {
> 	uint64_t cntpct = read_cntpct();
> 	uint32_t cntfrq = read_cntfrq();
> 
> 	time->seconds = cntpct / cntfrq;
> 	time->millis = (cntpct % cntfrq) / (cntfrq / TEE_TIME_MILLIS_BASE);
> 
> 	return TEE_SUCCESS;
> }

Regards,
Asma

**Comment by jforissier** [comment]
cntfrq is typically in the MHz range so if it is, say 1.9 MHz, and you divide by 1M, you get 1 instead of 1.9 which is a big difference. In the above code we divide by 1000.

**Comment by alekarasma** [comment]
Ok got it.

Thank you @jforissier
