### ISSUE TITLE
DMSG and MSG in Optee

### ISSUE THREAD

**Issue by alekarasma** [OP-TEE/optee_os#3520]
Hello Everyone,

I am trying to understand about Trace levels in Optee.
My trace level is set to TRACE_LEVEL -- TRACE_FLOW

In config.mk , config is as set below

> CFG_TEE_CORE_DEBUG ?= y
> 
> CFG_TEE_CORE_LOG_LEVEL ?= 1
> CFG_TEE_TA_LOG_LEVEL ?= 1
> 
> CFG_TEE_CORE_TA_TRACE ?= y

I have written driver in Optee. So , when I use MSG - the output prints to uart console. When I use DMSG there is no output printed on console. 

Why is the output of DMSG not printed on console? 
how can I enable it to print it on console for Optee drivers?

Regards,
Asma

**Comment by Emantor** [comment]
This is because you `CFG_TEE_CORE_LOG_LEVEL` is set to `1`, the default. This is passed to the compiler as the `TRACE_LEVEL` for core files:
https://github.com/OP-TEE/optee_os/blob/2d8d7e280db5cee94bd6ed7dbf40325e10b4e057/core/core.mk#L51-L51

the trace levels are set in `trace_level.h`:
https://github.com/OP-TEE/optee_os/blob/3f58e4ec10c5df57bad1296bb9a5cbc7bfacaef1/lib/libutils/ext/include/trace_levels.h#L26-L31

and interpretation happens in `trace.h`:
https://github.com/OP-TEE/optee_os/blob/9348a85a6425b2b88c6d5c200dc1b1a65eedcb80/lib/libutils/ext/include/trace.h#L70-L75

The result is that you want `CFG_TEE_CORE_LOG_LEVEL=4` in your configuration to see `TRACE_FLOW` debugging messages.

**Comment by alekarasma** [comment]
@Emantor Thanks for detailed explanation.
