### ISSUE TITLE
Question: How can an OP-TEE TA restrict commands to PreBoot environment?

### ISSUE THREAD

**Issue by thiruan** [OP-TEE/optee_os#3527]
Hi,

Is there a global milepost signal in OPTEE to know whether the system is in OS run-time or in PreBoot (BL33)?  

Context: We have an OPTEE TA and we would like to restrict it's interface usage to BL33 (U-boot or UEFI).  In other words, we would like to prevent the OS clients from using the TA interface.  

I see two possible options: 
1. We can accomplish this in a TA specific manner by exposing a new command in the TA and it can get called in ExitBootServices in UEFI or board_preboot_os in u-boot . TA can look at the flag set by this command and deny handling commands from OS clients. 

2. The other possible option is that OP-TEE already has a signal to know the system is already in OS run time. TA can query the state of this signal and deny handling commands from OS clients.

If OP-TEE already has this signal, we would like to leverage this signal. 

Best Regards,
Thiru

**Comment by jenswi-linaro** [comment]
There's no such signal in OP-TEE.

**Comment by jbech-linaro** [comment]
@thiruan , I think what you've described in "1" might work, but it'd be important to make sure that there actually is someone doing the calls to the TA before the main OS has been loaded, otherwise there is a chance that someone from the OS context might call it once. You might need to configure your TA as a singleinstance TA with the keepalive flag set (see [here](https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html#globalplatform-properties)), alternatively backup the flag in secure storage for example.

Otherwise I agree, it could be quite useful to have the possibility from TA point of view to be able query the TEE itself to understand at what stage the boot is in.

**Comment by wamserma** [comment]
> Otherwise I agree, it could be quite useful to have the possibility from TA point of view to be able query the TEE itself to understand at what stage the boot is in.

But that means making every piece of bootloader/firmware aware of OP-TEE, requiring them first to check whether OP-TEE is present and so on. I doubt this would get upstreamed e.g. by U-Boot.
Plus the TA can not trust signal that is set by such an external call, as it never knows when such a call has been maliciously omitted/blocked, due to its passive nature.
So a flag provided by OP-TEE is pretty much out-of-scope.

Assuming you have a proper secure boot something like your first solution sounds reasonable, along with Joakim's suggestions.
