### ISSUE TITLE
rcar-m3: enable RPMB

### ISSUE THREAD

**Issue by foreverska** [OP-TEE/optee_os#3538]
Hello all,

I am attempting to use RPMB and I have an m3ulcb at my disposal.  I have previously shown (emulated) RPMB working on QEMU, by changing CFG_RPMB_FS and CFG_RPMB_WRITE_KEY to y.  I attempted the same with this platform and it complained about needing a HW crypto engine so I enabled CFG_CRYPT_HW_CRYPTOENGINE.  But for some reason `libcrypto_engine_secure.a` is not being generated.
`cp: cannot stat 'core/lib/libcryptoengine/libcrypto_engine_secure.a': No such file or directory`
and then the build fails.  What gets me is in core.mk that library doesn't appear to be a conditional build after you've enabled HW_CRYPTOENGINE.  This is part of a yocto build so I guess it's possible buildroot is suppressing build errors for libcrypto_engine_secure.a but I've never seen that before.  Also for reference I'm enabling these features using EXTRA_OEMAKE in optee-os_git.bb... not sure if that's how it's supposed to be done.  Still pretty new to yocto/buildroot.

Does anyone have any clue what is happening?  Or maybe can correct what I'm doing wrong in trying to enable RPMB.

**Comment by lorc** [comment]
Hi @foreverska,

It depends on which OP-TEE you are using. If it is Renesas flavor (i.e. built with Renesas Yocto), then you probably should ask them at https://github.com/renesas-rcar/optee_os/issues or by writing to theirs customer support.

If I remember right, you don't need `CFG_CRYPT_HW_CRYPTOENGINE`. Moreover, you can't use it without signing NDA, because it uses some sort of proprietary code. On other hand on Renesas flavor you can user Hyperflash for storage. This is special flash chip embedded inside the SIP. It is accessed directly by OP-TEE, so no support from NW is needed and replay-back attack is almost  impossible without SIP disassembly.

If you are using vanilla OP-TEE (i.e. from this very GH account - https://github.com/OP-TEE/optee_os/), then I believe, you can use RPMB. IIRC, m3ulcb have eMMC, so theoretically you can use its RPMB facilities. Problem is that Renesas uses somewhat outdated Linux kernel, so there is no RPMB support in it. But I'm sure it is possible to backport RPMB patches. I never tried this, but I don't see why it should not work.

Also, I think, RPMB can be used on Renesas flavor as well. You just don't need to enable that `CFG_CRYPT_HW_CRYPTOENGINE` thing. But, anyways, you need to backport RPMB patches for  the Linux.

**Comment by foreverska** [comment]
The yocto layer is doing something funny because it downloads both.  I think the only thing it copies over from OP-TEE is libtomcrypt though.  I didn't know how divergent the renesas branch was or if RPMB guidance would apply to both.

If I don't turn on `CFG_CRYPT_HW_CRYPTOENGINE` I get:
`#error "RPMB requires Crypto Engine."`
from tee_rpmb_fs.c:71.  Which I now realize is a Renesas branch thing.

For the record though, I've had the yocto built sans Optee-RPMB support and I saw that rpmb showed up as a device in Linux and responds to requests from mmc-utils.  So they apparently have brought up the version of Linux.

But none of this is your problem.
