### ISSUE TITLE
How to implement execution of ELF .init_array and .fini_array?

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#3584]
The ELF standard defines special sections (and corresponding entries in the dynamic segment) to hold pointers to initialization and finalization functions. They are typically used by compilers to register constructors/destructors for instance, but may also be used in C thanks to  `__attribute__((constructor))` and `__attribute__((destructor))`. 

OP-TEE currently ignores these functions, and I'm wondering how we could support them. It could be a first step towards C++ support for TAs. The obvious place is ldelf, because it is where the ELF processing occurs. The problem is, ldelf does not always run in the same execution state as the TA (AArch32, AArch64). When the TEE core is AArch64, so is ldelf, but the rest of the TA code may be Aarch32. In this case it is impossible to branch directly from ldelf to the initialization functions -- a transition via EL1 is required.

I see two options:
1. Invoke constructors / destructors via libutee, in a similar way the TEE core would trigger a "create session" or "invoke" etc. that is: `user_ta_enter(..., UTEE_ENTRY_FUNC_CALL_FN_ARRAY)` or similar. The ugly part is passing the .init_array / .fini_array information from ldelf to the TEE core and then to libutee. Has to be done also when dynamically loading a shared library (`dlopen()`).
2. Have two versions of ldelf, one for Aarch32 and one for Aarch64. This is more or less the Linux model. What were the arguments to have a single one? "Simplicity, no need for two at this point" perhaps?

Comments welcome.

**Comment by jenswi-linaro** [comment]
There's pros and cons with two versions of ldelf.
Pro:
A. .init_array can be handled directly by ldelf
B. The dumping and backtrace stuff in ldelf can be moved into libutee
C. TAs can access the data structures initialized by ldelf without too much trouble, overlaps a bit with [A] above
D. init_instance() can be executed directly by ldelf, simplifying TA initialization a little
E. dlopen() can be handled in libutee by direct calls into ldelf simplifying stuff a little

Con:
a. Takes up more memory in OP-TEE
b. .fini_array will still need to be handled by the TA unless we add another entry for tearing down the TA
c. OP-TEE and ldelf cannot share data structures easily, `struct ldelf_arg` must only use fixed width elements etc
d. a bit more work is needed to have two variants of ldelf

[b] seems to cancel out whatever advantage with [A].
[C] and [D] are rather weak
[B] would require some additional work.
[E] is not bad, but we'll still be stuck with the old interface since we need to be backwards compatible
[a] is a bit annoying, but not a disaster

Based on this I'd say that we should stick with a single ldelf. Unless we chose to break backwards compatibility, but then we should clean a lot more.

**Comment by jforissier** [comment]
Thanks for the valuable feedback :+1:

So, I went ahead with the current single option, and it turned out better than I thought :wink: see https://github.com/OP-TEE/optee_os/pull/3620.
