### ISSUE TITLE
Test optee on raspberry pi; How to project on LCD monitor?

### ISSUE THREAD

**Issue by aliamal** [OP-TEE/optee_os#3606]
Hi, I have tested **optee** with **qemu v8** on **ubuntu**, and I'm going to test **optee** on a **raspberry pi 3 b**, but I got confused about buying a **monitor / LCD** for **rpi** ! I know the **HDMI** port is not supported, but i don't have any knowledge about **UART** and **TFT** monitors, Please provide me a help on buying a proper monitor for my project; (`If provide me a link such as on _amazon.com_, I'll be grateful`)

**Comment by Raincode** [comment]
Hi there,

since nobody has replied to you thus far, I will give you my view: When I work with my carrier board, it is simply connected via USB to a host machine running a Linux VM (Debug UART) and I can run minicom to get a shell on the target board and see console output.

I don't think TF-A or OP-TEE support any video display or graphics drivers. So you should somehow be able to connect via UART. See also this link: [https://optee.readthedocs.io/en/latest/building/devices/rpi3.html](https://optee.readthedocs.io/en/latest/building/devices/rpi3.html) which shows in the table HDMI is not supported.
