### ISSUE TITLE
Is there CVE-2019-16910 in optee os

### ISSUE THREAD

**Issue by NiuTree** [OP-TEE/optee_os#3630]
We find the software Mbedtls-2.16.0 has this vulnerablity, and optee os include Mbedtls-2.16.0.
Is there CVE-2019-16910 in optee os?

**Comment by jbech-linaro** [comment]
Without checking, I'd say yes, since the last (re-)base branch we used is a https://github.com/OP-TEE/optee_os/tree/import/mbedtls-2.16.0. @jforissier @jenswi-linaro , seems like there is need for yet another update.

**Comment by jforissier** [comment]
@jbech-linaro you're right about the version currently used by OP-TEE, it is 2.16.0 indeed.

But I don't think [CVE-2019-16910](https://nvd.nist.gov/vuln/detail/CVE-2019-16910) applies, because we're not using "deterministic ECDSA" (`MBEDTLS_ECDSA_DETERMINISTIC` config flag or `mbedtls_ecdsa_sign_det()` function). See https://github.com/ARMmbed/mbedtls/commit/298a43a77ec0ed2c19a8c924ddd8571ef3e65dfd for details.

Instead, the ECDSA verification function in OP-TEE uses the TEE RNG ([here](https://github.com/OP-TEE/optee_os/blob/3.8.0/lib/libmbedtls/core/ecc.c#L248-L249)). `mbd_rand()` calls `crypto_rng_read()` which is the OP-TEE RNG so no repeated value for identical keys or whatever.

**Comment by jbech-linaro** [comment]
Ok, then it's a less urgent thing to do. But since we expose mbed TLS to TA's we should update it, better sooner than later, since we never now what the users of TA's are doing.

**Comment by jforissier** [comment]
> Ok, then it's a less urgent thing to do. But since we expose mbed TLS to TA's we should update it, better sooner than later, since we never now what the users of TA's are doing.

Fair point. Added to my TODO list!

**Comment by jforissier** [comment]
https://github.com/OP-TEE/optee_os/issues/3699
