### ISSUE TITLE
about ip core

### ISSUE THREAD

**Issue by angusmart** [OP-TEE/optee_os#364]
when controllers, such as mmc controller, keyboard controller, display card controller, enter secure world,my understanding was that we must change the security state of these controllers through writing the corresponding controller registers.
but how these are represented in optee-os code. i haven't found the corresponding code in optee-os.

**Comment by jbech-linaro** [comment]
Hi @angusmart , we don't have any support for that as of today. But we have realized that this is something that we need to support sooner or later. We have been touching this area when discussing Trusted UI (and some people have suggested some kind of device driver kit). We are going to rely on TZPC when configuring peripherals, but that will probably not be enough, since we also need to add support for some bus protocols also (I2C, SPI etc...) which also has to be handled securely. We don't have any date when this will be implemented, it is still open.
