### ISSUE TITLE
How to run OP-TEE OS on special cores  like core0 or core1

### ISSUE THREAD

**Issue by chenlifu2015** [OP-TEE/optee_os#3643]
hi experts,
    I want to know how to run optee-os on the special core when cpu has more than one cores, let`s say it has four cores, I want optee-os only runs on core 0, and Linux runs on core0-3, when Linux want to use services in optee-os, core1-3 send IPI (Inter-process interrupt) to core0, then core0 send smc to switch to secure world
   So are there  some ways to do that? Thanks

**Comment by vchong** [comment]
@chenlifu2015 You can disable any of the CPUs using `echo 0 >/sys/devices/system/cpu/cpuX/online`, but since optee_os doesn't have its own scheduler, it’s up to the kernel to decide which core it runs on, i.e, it will be the same core as the one initiating the SMC in Linux. See https://optee.readthedocs.io/en/latest/faq/faq.html#q-can-i-limit-what-cpus-cores-op-tee-runs-on and https://optee.readthedocs.io/en/latest/faq/faq.html#q-how-is-op-tee-being-scheduled.

**Comment by chenlifu2015** [comment]
hi, vchong 
    Thanks for your apply，I have another questions：
    1.Can I open the device：/dev/tee  more than once？such as，CA1 open the decive for open a session，then CA2 try to open the /dev/tee，in this time, CA2 will open device succeed or failed?
    2.If CA2 open device succeed, and OP-TEE OS can create four secure threads, Does  it means there are four different TAs can run on the same time?

**Comment by chenlifu2015** [comment]
hi, vchong 
    Thanks for your apply，I have another questions：
    1.Can I open the device：/dev/tee  more than once？such as，CA1 open the decive for open a session，then CA2 try to open the /dev/tee，in this time, CA2 will open device succeed or failed?
    2.If CA2 open device succeed, and OP-TEE OS can create four secure threads, Does  it means there are four different TAs can run on the same time?

**Comment by vchong** [comment]
@chenlifu2015 you're welcome.
1. Yes. It should succeed.
2. This depends somewhat on the TA FLAG settings. See below references:
https://optee.readthedocs.io/en/latest/faq/faq.html#q-is-multi-core-ta-supported
https://optee.readthedocs.io/en/latest/search.html?q=thread
https://github.com/OP-TEE/optee_os/issues/1590
https://github.com/OP-TEE/optee_os/issues/751
https://github.com/OP-TEE/optee_os/issues/2791

**Comment by vchong** [comment]
Found another old thread with the same question: https://github.com/OP-TEE/optee_os/issues/926

**Comment by chenlifu2015** [comment]
Hi，vchong
    Thanks a lot，I have read those issues, and the questions above is cleared, but another question come out:
    Let`s say the CPU has 4 cores, and my op-tee os build with CFG_ NUM_THREADS = 2 and  CFG_TEE_CORE_NB_CORE = 4, in such configuration
   Question 1 :I can run 2 * 4 = 8 threads (or TAs)or only 2 threads(TAs) in op-tee os at the same time？
   Question 2:And issue 1194  [https://github.com/OP-TEE/optee_os/issues/1194](url) said that optee-os can occupy any cores, then, when rich os on core0 send a smc, core0 will enter the  secure world,right?but core1~3 are still run with REE, how can the optee-os use the core1~3?

**Comment by chenlifu2015** [comment]
Hi，vchong
   Add another situation, if  CFG_TEE_CORE_NB_CORE =1 and  CFG_ NUM_THREADS = 2,in this time, How many threads optee-os can create and run at the same time?

**Comment by vchong** [comment]
@chenlifu2015 You're welcome. I'm not totally sure of the answers so hopefully @jforissier or @jenswi-linaro can confirm or elaborate.

For Q1 and 3, although these aren't common configurations a platform would normally have, I think you take the lesser of the 2 configs.

For Q2, when secure world on core0 is done or interrupted, the task returns to normal world and if it later gets rescheduled to a different core and sends another smc, then that core will enter secure world instead. Or in a different scenario, core0 is in secure world and another core sends another smc then that core will enter secure world too. Of course CFG_TEE_CORE_NB_CORE has to be more than 1 in this case.

**Comment by chenlifu2015** [comment]
Hi，vchong
   Your answer is very helpful to me, last question:If cpu has only one core, but my optee-os build with CFG_ NUM_THREADS = 2,then CA1 send smc and thread1 will deal with it,but the operation with this smc will take some times to finish,so REE send a time slice interrupt, thread1 is suspend, core 0 switch back to normal world, in this time, CA2 send smc, will optee-os use thread2 to handle this smc or return some error code.?

**Comment by jforissier** [comment]
Careful about changing `CFG_TEE_CORE_NB_CORE`: its value must be consistent with the values returned by `get_core_pos()`. For instance, if you set `CFG_TEE_CORE_NB_CORE=1`, you need to make sure that `get_core_pos()` can only return `0`. Which means, OP-TEE running on a dedicated core.

**Comment by jenswi-linaro** [comment]
OP-TEE is scheduled by normal world and is normally only active during a request from normal world. Fastcalls (and secure interrupts) are processed with a small cpu specific stack, so we have one for each CPU in the system that OP-TEE can run on.

More complex requests are processed as yielding (aka standard) calls. These calls uses a larger thread specific stack. A yielding call can be interrupted and even rescheduled to a different CPU. A yielding call may also do RPC into normal world when loading a TA for instance.

So the number of threads and CPUs are quite independent. With only one CPU it may still make sense to have 2 or 3 threads. With 32 CPUs it may make sense to have fewer threads than 32 in order to save some memory.

The maximum concurrency possible for yielding calls is `MIN(number of threads, number of CPUs)`. But the perceived concurrency can still be the number of threads if some thread is waiting for I/O when loading a TA for instance.

**Comment by bzhu5** [comment]
> Hi，vchong
> Your answer is very helpful to me, last question:If cpu has only one core, but my optee-os build with CFG_ NUM_THREADS = 2,then CA1 send smc and thread1 will deal with it,but the operation with this smc will take some times to finish,so REE send a time slice interrupt, thread1 is suspend, core 0 switch back to normal world, in this time, CA2 send smc, will optee-os use thread2 to handle this smc or return some error code.?

it seems that this particular question has not been explicitly answered yet.  

To the best of my knowledge, i think OPTEE would **not** return error code but handle it appropriately in thread2.  

please correct me if i'm wrong!
