### ISSUE TITLE
fastboot problem on Hikey960 rk3399

### ISSUE THREAD

**Issue by dkarnikis** [OP-TEE/optee_os#3743]
Hello,
I have recently bough a Rock 960 Board Rk3399 solution 2G version in order to flash OPTEE on it.
I have followed the guide to build the source from scratch and it succeeds. The real problem resides in make flash command, where fastboot is not able to find ptable partition and I cannot proceed. Is there a way to flash OPTEE on an sd card and boot from there, similar to raspberry pi method? 

Thanks in advance,
Dimitris

**Comment by jbech-linaro** [comment]
> I have recently bough a Rock 960 Board Rk3399 solution 2G version in order to flash OPTEE on it.
> I have followed the guide to build the source from scratch and it succeeds. 
What guide are you referring to? Is it HiKey 960 (Hisilicon board) you're testing or is it a Rockchip board? They are two different devices from different vendors with different software?

**Comment by ychen96** [comment]
Hi i'm also suffering from this issue. @jbech-linaro @dkarnikis 

My board is Rockchip rk3399, and i followed the instructions on the [official document ](https://optee.readthedocs.io/en/latest/building/gits/index.html). As it says currently rockchip is not supported by the build.git so i just manually build toolchains, optee_os and optee_client respectively.

The question is i don't know how to "make flash" in order to flash it onto my board. Any help would be greatly appreciated!

**Comment by jbech-linaro** [comment]
> Any help would be greatly appreciated!

I'd be happy to help, but since we have no official support in `build.git` (however device is support in `optee_os.git`), I'm in the same situation as you are, i.e., I if I'd give the Rockchip device a try, then I'd have to dig up all that information from other sources to start with, i.e., I would have start to read on Rockchip documentation pages trying to figure out how to build and deploy software on their devices. When I know how to do that, then next step would be to try to figure out how to enable OP-TEE, that is at least building it with  `PLATFORM=rockchip-rk3399`.

**Comment by ychen96** [comment]
> I'd have to dig up all that information from other sources to start with
Thanks for your reply!
I've decided to have a try using u-boot based on the [rockship wiki document](http://opensource.rock-chips.com/wiki_U-Boot). Share it with you in case you're interested.

**Comment by jbech-linaro** [comment]
I also found [this](https://www.96boards.org/documentation/consumer/rock/installation/linux-mac-rkdeveloptool.md.html) at the 96Boards pages, that might also give some ideas how to flash a Rockchip device.

**Comment by dkarnikis** [comment]
Hello, i have managed to flush Debian, Android and ubuntu on my board using GPT. On Optee situation, we have to use fastboot command instead of the flashing tools provided by rockchip. I have managed to boot on fastboot, but i was unable to flash any of the partition make flush executes. So that's why I am asking if i can flush optee on sd card without modifying the eMMC
