### ISSUE TITLE
Question: Android and OP-TEE(Trusty TEE)

### ISSUE THREAD

**Issue by saddy-muchu** [OP-TEE/optee_os#3774]
Hello all,

I wanted to know since which OP-TEE version do we have support for Android?
What are the corresponding release versions for optee-client and optee-test?

**Comment by jbech-linaro** [comment]
Hi,

I think you find answers to this here: https://optee.readthedocs.io/en/latest/building/aosp/aosp.html. I believe it's Android P(ie) for the moment (@vchong can confirm).

For the individual OP-TEE components they run tagged versions according to the OP-TEE releases if you're using a stable manifest (which is recommended) or otherwise the top of master on all optee_xyz.git if running a manifest tracking branches instead of stable.

**Comment by saddy-muchu** [comment]
Thank you.

**Comment by vchong** [comment]
@saddy-muchu Yes, P(ie) is the only supported, i.e. actively maintained, version at the moment. There are plans to upgrade to Q but no ETA atm. Once Q is up, P will be dropped.

For the currently maintained Android version, we 'put on top' of it each version of OP-TEE after it's released, so you might see for e.g. '3.8.0 on P', '3.7.0 on P' and so on so forth. Basically, what @jbech-linaro  said above.

Please note that manifests that track (master) branches are basically for internal development only due to the fact that they're constantly changing and as such not as stable as the stable ones, obviously. Also, the only platforms publicly supported right now are the HiKey 620 and 960 boards.

Please also note that Trusty is Google's TEE solution and doesn't really have anything to do with OP-TEE.
