### ISSUE TITLE
Compiling TA applications 

### ISSUE THREAD

**Issue by zacchaeusliang** [OP-TEE/optee_os#3788]
How do i compile a TA file? I've been only modifying the example code that has been given in the source tree.  I tried to clone the github example and build the but it says that optee_client is not found.  Do i need the toolchain and to build the optee_client. where do you put it? How do you sign the application once i sign it? Do i have to put the public key in the source tree to verify it?  So sorry for the questions really new and would love to do embedded development for a living

Thanks 
Zack

**Comment by gagachang** [comment]
Since the CA utilizes TEE Client API, you need to [include the libteec.so* libraries](https://github.com/linaro-swg/optee_examples/blob/master/hello_world/host/Makefile#L11) when CA is compiled.
You also need to [include TEE Internal Core API libraries](https://github.com/linaro-swg/optee_examples/blob/master/hello_world/ta/Makefile#L7) when the TA is compiled.
In brief, the optee_os and optee_client must be compiled first, then we can compile CAs and TAs.
Also, to compile them you need toolchains from [here](https://github.com/OP-TEE/build/blob/master/toolchain.mk).
Just clone the OP-TEE/build repository and `make toolchains` to download them.

BTW, I have already tried two ways to compile my applications successfully :
(1) Treat your project as another optee_examples' applications and compiled together with it.
Copy another `optee_examples/hello_world` into optee_examples directory and modify the dir's name, Makefiles, CA and TA to what you want. Then recompile the whole OP-TEE project.
(2) Treat your project as another optee_examples. Copy the `optee_examples` into your OP-TEE directory and modify the dir's name, Makefiles, CA and TA to what you want. 
Then add and modify buildroot parameters like optee_examples [here](https://github.com/OP-TEE/build/blob/master/common.mk#L217).
You also need to add the configurations and package related to your project [here](https://github.com/OP-TEE/build/tree/master/br-ext).
Then recompile the whole OP-TEE project.

**Comment by zacchaeusliang** [comment]
Currently I've just copied the hello world app. it's sitting on my desktop and I'm hoping to compile it without the source tree. i don't know how to include the api libaries.

**Comment by zacchaeusliang** [comment]
i'm now having difficulty with building the gcc toolchain for arm. I tried to clone the git repo and it only downloaded the repos. I tried using curl but don't know what to do next once i have extracted the package

**Comment by jforissier** [comment]
@zacchaeusliang have you tried to follow the "quick start" instructions at https://optee.readthedocs.io/en/latest/faq/faq.html#q-what-is-the-quickest-and-easiest-way-to-try-op-tee? (the commands in the green rectangle)

**Comment by zacchaeusliang** [comment]
yes i have but that's for building the whole os.

**Comment by zacchaeusliang** [comment]
i want to build a development environment

**Comment by gagachang** [comment]
@zacchaeusliang, the QEMU version @jforissier mentioned is the best development environment for OP-TEE. I usually use QEMU to debug CA and TA that I developed. It's very efficient.

Besides, TA is not a common application we develop on Linux.
Since TEE's TA is designed to execute in TEE only, it can't run in general OS such as Linux.
Actually you must build the whole OP-TEE project to develop your own CA and TA in QEMU.
You just need to recompile the **buildroot** when you add new CA and TA into OP-TEE.

**Comment by zacchaeusliang** [comment]
I"m developing on a **linaro** hikey

**Comment by etienne-lms** [comment]
Despite you may need to build the whole **optee_os**, you should still be able to build only the TA SDK with `make -C .../optee_os PLATFORM=... [O=out/...] (...) ta_devkit`.
Find SDK at `.../optee_os/out/.../export-ta_*` or any `O=` provided base path.
