### ISSUE TITLE
Query: Standard GPIO framework in OPTEE 

### ISSUE THREAD

**Issue by vahidd1** [OP-TEE/optee_os#3817]
Hi,

I am trying to understand if there is any general GPIO framework in optee. I can see gpio.h has a APIs which can be implemented by the soc verndors or users.
However currently gpio.h ask to implement following APIs
get_direction
set_direction
get_value
set_value
gpio_interrupt
set_interrupt

But there are various other electrical properties for a given GPIO which we generally needed (more common are pull-ups & pull down  - I am aware that few SOC might not support all or any of the electrical properties).

But I just wanted to check is this under development or someone has tried it before?
Or are there any concerns for this implementation?

Thanks

**Comment by vchong** [comment]
@vahidd1 There was an earlier attempt to add a framework [1], but it was sort of put off due to its invasive nature in that all affected platform code also have to be changed at the same time.

Afaik, the pull ups and downs (and other electrical properties) were left off the API list as these are commonly done only once during setup. E.g. for the hikey platform, these are done in [2].

[1] https://github.com/OP-TEE/optee_os/pull/2926
[2] https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-hikey/main.c#L119-L129
