### ISSUE TITLE
clang aarch64 --print-libgcc-file-name doesn't work on aarch64

### ISSUE THREAD

**Issue by PeikanTsai** [OP-TEE/optee_os#3880]
I use llvm 9.0.1 to compile the lastest optee os and fail at the following error.
```
ld.lld: error: cannot open libgcc.a: No such file or directory
make: *** [out/arm/core/all_objs.o] Error 1
```
And I found the error is caused by 8287cbcf8a because the there's no aarch64 libgcc is specified of the toolchain.

```
$ clang --target=aarch64-linux-gnu --print-libgcc-file-name
libgcc.a
```
Should I build compiler-rt in llvm project or use an external aarch64 libgcc.a?

I build the llvm toolchain by follwing the optee document.
https://optee.readthedocs.io/en/latest/building/toolchains.html#llvm-clang

**Comment by vchong** [comment]
@PeikanTsai Fix is here [1] but I still need to address the review comments.
Note that you'll need to build the compiler-rt for aarch64 and arm in llvm project, which might not be trivial. It might be easier to just grab them from [2] and [3] and copy them to your toolchain path under lib/clang/10.0.0/lib/linux/. Note that the current release version at https://releases.llvm.org so you might want to upgrade your build too from 9.0.1 to 10.0.0.

[1] https://github.com/OP-TEE/optee_os/pull/3844
[2] https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang+llvm-10.0.0-aarch64-linux-gnu.tar.xz
[3] https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang+llvm-10.0.0-armv7a-linux-gnueabihf.tar.xz

**Comment by jforissier** [comment]
> Note that the current release version at https://releases.llvm.org is 10.0.0 so you might want to upgrade your build too from 9.0.1 to 10.0.0.

There is an issue with LLVM/Clang 10: https://github.com/OP-TEE/optee_os/issues/3802

IMO the easiest solution for now is to install `ligcc.a`. In my environment (Ubuntu 19.10) it comes with package `libgcc-9-arm64-cross-dev`.

**Comment by vchong** [comment]
> There is an issue with LLVM/Clang 10: #3802

Can the prebuilts from [4] be used instead then? Usually the reason for using clang is to not use gcc for whatever reason. I'd assume this includes the rt libraries as well.

[4] https://releases.llvm.org/download.html#9.0.1

**Comment by jforissier** [comment]
> > There is an issue with LLVM/Clang 10: #3802
> 
> Can the prebuilts from [4] be used until the 10.0.0 issue is fixed? Usually the reason for using clang is to not use gcc for whatever reason. I'd assume this includes the rt libraries as well.
> 
> [4] https://releases.llvm.org/download.html#9.0.1

Worth a try indeed. I seem to remember that 9.0.0 does not come with the compiler-rt libraries but the 9.0.1 archive has a file called `lib/clang/9.0.1/lib/linux/libclang_rt.builtins-aarch64.a` and a bunch of others, so it looks promising at least ;-)

**Comment by PeikanTsai** [comment]
Thanks for your comments!
#3844 and https://releases.llvm.org/download.html#9.0.1 is work for me.

And I think the documentation need to be updated.
Maybe add some commands to build compiler-rt lib in llvm-project 9.0.1?
https://optee.readthedocs.io/en/latest/building/toolchains.html#llvm-clang

**Comment by jforissier** [comment]
@PeikanTsai glad it worked for you!

Since we're heading towards a full LLVM/clang setup, i.e., *without* libgcc and *with* compiler-rt, which makes sense indeed, I propose we update the documentation to recommend getting the compiler(s) from the GitHub release page. The alternative methods (OS packages and re-compiling) risk being incomplete. For example, the Ubuntu `clang` package does not install `ld.lld`, you need the `lld` package; the packages do not contain the cross-compiled compiler-rt libraries; building by yourself is hard for the same reason (no cross-compiled compiler-rt libraries are generated)...

Here is a little script I've put together that we could recommend or even rewrite in the toolchains Makefile in `build.git`: [get_clang.sh](https://github.com/OP-TEE/optee_os/files/4668251/get_clang.sh.txt).

**Comment by vchong** [comment]
https://github.com/OP-TEE/optee_docs/pull/75
