### ISSUE TITLE
Question: Debugging TA code and OP-TEE Kernel code

### ISSUE THREAD

**Issue by saddy-muchu** [OP-TEE/optee_os#3935]
Is it possible to use GDB for debugging TA code and KGDB for debugging OP-TEE kernel code?
If not, what are the best ways to debug them?

**Comment by jenswi-linaro** [comment]
This depends on the platform. When running everything inside QEMU remote GDB debugging is quite convenient. You need to specify the correct load address for the TA though.

**Comment by saddy-muchu** [comment]
What about a non-QEMU platform?

**Comment by Emantor** [comment]
I did some testing with JTAG on i.MX6 using OpenOCD, this worked somewhat fine. Most of the difficulties were down to OpenOCD.

**Comment by jforissier** [comment]
I also used OpenOCD occasionally on HiKey960. The JTAG connection was not very reliable, but it was good enough to troubleshoot some nasty exception at the time.

If you have a good JTAG debugger for your platform I see no reason it would not work with OP-TEE.

**Comment by jbech-linaro** [comment]
I wrote [this](https://optee.readthedocs.io/en/latest/building/devices/rpi3.html#jtag) JTAG guide for OP-TEE debugging on Raspberry Pi 3 a long time ago. Haven't tried it in a while. But just as @jforissier mentioned about HiKey960, the same was true with Rpi3, it was a bit flaky to use.

I tend to go with QEMU, since debugging is rock-solid on all levels. Regarding finding the correct load addresses for TA's I have a [Python GDB script](https://github.com/Jyx/configs/blob/gdb-optee/gdb-optee.py#L323-L350) that takes care of that, I just need to have gdb-helper functions merged into optee_os (https://github.com/OP-TEE/optee_os/pull/3847#issuecomment-634571739).

**Comment by saddy-muchu** [comment]
OK.
Thank you all for your inputs.
I'll try as suggested.
