### ISSUE TITLE
QEMU fails for "write to buffer emulation is flawed"

### ISSUE THREAD

**Issue by cloverpop** [OP-TEE/optee_os#3939]
Hi,
I followed the OP-TEE guide to download OP-TEE source code based on the qemu_v8.xml manifest.
So far it can pass build and launch the QEMU.

However, once I start to execute QEMU, one error occurs.

<quote>
:~/workspace/optee_qemuv8/build$ make run-only
ln -sf /home/zhiyan01/workspace/optee_qemuv8/build/../out-br/images/rootfs.cpio.gz /home/zhiyan01/workspace/optee_qemuv8/build/../out/bin/

* QEMU is now waiting to start the execution
* Start execution with either a 'c' followed by <enter> in the QEMU console or
* attach a debugger and continue from there.
*
* To run OP-TEE tests, use the xtest command in the 'Normal World' terminal
* Enter 'xtest -h' for help.

cd /home/zhiyan01/workspace/optee_qemuv8/build/../out/bin && /home/zhiyan01/workspace/optee_qemuv8/build/../qemu/aarch64-softmmu/qemu-system-aarch64 \
        -nographic \
        -serial tcp:localhost:54320 -serial tcp:localhost:54321 \
        -smp 2 \
        -s -S -machine virt,secure=on -cpu cortex-a57 \
        -d unimp -semihosting-config enable,target=native \
        -m 1057 \
        -bios bl1.bin \
        -initrd rootfs.cpio.gz \
        -kernel Image -no-acpi \
        -append 'console=ttyAMA0,38400 keep_bootcon root=/dev/vda2' \
        -object rng-random,filename=/dev/urandom,id=rng0 -device virtio-rng-pci,rng=rng0,max-bytes=1024,period=1000 -netdev user,id=vmnic -device virtio-net-device,netdev=vmnic
QEMU 5.0.0 monitor - type 'help' for more information
(qemu) c
(qemu) pflash_write: Write to buffer emulation is flawed
pflash_write: Write to buffer emulation is flawed

(qemu)

</quote>

Any suggestions to resolve this issue? Thanks.
I ever tried to add QEMU parameters "-pflash flash0.img -pflash flash1.img", it doesn't work.

**Comment by jforissier** [comment]
I have noticed this error too with recent versions of QEMU. v3.1.0-rc3 (as specified in the manifest) does not show this error, and in any case everything seems to be working fine. That's why I have not spent more time on this yet.

**Comment by jforissier** [comment]
More info on this.

1. The messages are warnings inserted in QEMU commit [4dbda935e054](https://git.qemu.org/?p=qemu.git;a=commit;h=4dbda935e054) ("pflash_cfi01: Log use of flawed "write to buffer""). The latest QEMU release to date (v5.0.0) has this message, and I found no sign of a fix being merged or worked on.
2. The messages are triggered by the UEFI (EDK2) module NorFlashDxe, which is clearly needed since the platform will not boot without.
3. Upgrading EDK2 to the tip of the master branch at commit 20286e168b6b ("BaseTools: Add external definitions for RISC-V assembly build") results in a working setup, but with the message logged 364 times instead of just 2 (!).

My conclusion is, we should not worry about that for the moment and hope for QEMU to eventually remove the messages.
