### ISSUE TITLE
the difference between register_ddr() and register_dynamic_shm()

### ISSUE THREAD

**Issue by chenlifu2015** [OP-TEE/optee_os#3948]
hi.experts
    I want to know the the difference between register_ddr() and register_dynamic_shm(), recently, I am working on imx8qm(Armv8-a) with ddr address ranges: 0x80000000~0xFFFFFFFF  0x880000000~0xBFFFFFFFF, I want to use the dynamic shared memory features, so I need to map the ddr address range to optee os mmu.Usually, I should use the macro register_dynamic_shm, but the mem type is MEM_AREA_RAM_NSEC, and when I see the defination of the MEM_AREA_DDR_OVERALL:
   MEM_AREA_DDR_OVERALL: Overall DDR address range, candidate to dynamic shm
   I think the macro register_ddr() is ok, too.So, which macro I should use, and what the difference between them.
   And if I want to map more than 20MB(10MB for param in, 10MB for param out) size memory to optee os in each smc call, what should I do with the mmu/page size config,

**Comment by etienne-lms** [comment]
Regarding 1st question:
* `register_dynamic_shm()` defines an address range that can be used as shared memory.
* `register_ddr()` defines an address range that can include secure memory and shared memory. At boot time, OP-TEE carves out from this address range the ranges that are defined as secure (i.e. through `CFG_TZDRAM_*`) so that remaining address range(s) can be used as shared memory.

Regarding 2nd question, it is a bit unclear to me. Could you repharse it? Do you need more than 20MB of secure memory or of shared memory? Which issue do you currently face?

**Comment by chenlifu2015** [comment]
@etienne-lms 
     Thanks for your fast answer, I have understand the  difference, about question 2, I want to implement a feature:use aes algo to encrypt/decrypt a file in optee os core with big size(like 1GB),I enc/dec 10MB data in each smc call(means that I have malloced a buffer with size 10MB as temp input buffer, at the same time 10MB size for temp output buffer), so I need register 20MB address range to optee os mmu, but I get the error code: 0xFFFF000C（means TEE_ERROR_OUT_OF_MEMORY） ，so I guess the reason is optee os core do not have enough pages to map the buffer(my ta is a pta), so I want to change some macro to make optee core can map more dynamic shared memory in each smc call

**Comment by niehaokang** [comment]
@chenlifu2015 
You may need to increase PGT_CACHE_SIZE which is define  in core/arch/arm/include/mm/mm/pgt_cache.h. See[https://github.com/OP-TEE/optee_os/issues/1523](url) and [https://github.com/OP-TEE/optee_os/issues/2090](url).
