### ISSUE TITLE
Status of Secure Storage and Hardware Unique Key

### ISSUE THREAD

**Issue by sto-vec** [OP-TEE/optee_os#3978]
Hello all,
I am a bit confused about the status of the Secure Storage and the Hardware Unique Key. In the documentation there is written that the secure storage can be decrypted on other devices because a constant key is used. I found several merged pull requests which i think addresses the issue on i.mx6 devices which I am using (for example https://github.com/OP-TEE/optee_os/pull/3608). 
When I using the current master do I still have to implement the two function named in the documentation, when i want a secure storage? Maybe you can help @Emantor ?
Thank you very much. 
Best regards,
Tobias

**Comment by jenswi-linaro** [comment]
> In the documentation there is written that the secure storage can be decrypted on other devices because a constant key is used.

It would help with a link. Perhaps the documentation needs to be updated?

**Comment by sto-vec** [comment]
> > In the documentation there is written that the secure storage can be decrypted on other devices because a constant key is used.
> 
> It would help with a link. Perhaps the documentation needs to be updated?

Of course.  https://optee.readthedocs.io/en/latest/architecture/secure_storage.html?highlight=secure%20storage#important-caveats

**Comment by Emantor** [comment]
Yes, for i.MX6 with additional compile options (per default the CAAM driver is disabled and the i.MX maintainters didn't want to enable it for the HUK), the HUK is generated from the per device OTPMK (One time programmable master key) fused into the board during manufacturing by NXP.
I still have to update the documentation for this. The required compile flags are `CFG_NXP_CAAM=y` to enable the CAAM driver and `CFG_NXP_CAAM_RUNTIME_JR=n` to disable runtime access of the CAAM due to CLK disabling issues with the mainline linux driver. AFAIK NXP is looking into a fix for this.

**Comment by sto-vec** [comment]
thanks @Emantor 
Did i understand it correct: I set the compile flags and then my storage is encrypted with a key derived from HUK without further settings?

**Comment by Emantor** [comment]
Your device will also need to be configured for High Assurance Boot (HAB) since the SoC otherwise uses a test key instead of the fused OTPMK.

**Comment by sto-vec** [comment]
Thank you @Emantor also for the interesting talk. 
I close the issue since the question is answered.
