### ISSUE TITLE
OS related capabilities of OP-TEE

### ISSUE THREAD

**Issue by saddy-muchu** [OP-TEE/optee_os#4057]
Hello all,

I am aware that OP-TEE is a parallel OS that provides better security than linux.
I was curious to know about the OS related capabilities of OP-TEE. Things like scheduling algorithms, process/thread synchronization (mutex, semaphores), deadlock handling, memory management( handling of internal/external fragmentation),  paging etc.

Does OP-TEE have these capabilities similar to linux and other operating systems?
Is there documentation available regarding this?

**Comment by sunnybird** [comment]
i find some explanation at https://optee.readthedocs.io/en/latest/faq/faq.html#q-how-is-op-tee-being-scheduled

**Comment by saddy-muchu** [comment]
Thank you @sunnybird .
But, i was more interested in the internals of OP-TEE as mentioned above.

**Comment by etienne-lms** [comment]
Hello @saddy-muchu,

I don't think we can say OP-TEE is an OS, mostly because it lacks scheduling support and many features one may expect from an OS (filesystem, mutlmedia, shell terminal, ...). OP-TEE offers better security than Linux in the sense that it is designed to expose services to the Linux OS for when such service relies on secrets one does not want to expose in any of the Linux OS layers (kernel, user app, files, ...). One could say it is more secure than Linux but that's because it is designed for security and because it provides a million far less features than a Linux based OS can provide, which helps focusing on security matters.

As mentioned by @sunnybird, OP-TEE docs are here: https://optee.readthedocs.io/en/latest. Have a look at the several [architecture articles](https://optee.readthedocs.io/en/latest/architecture/index.html). If you think some information is not accurate of not understandable, feel free to point at it (docs sources are in [optee_docs](https://github.com/OP-TEE/optee_docs)) so that 
 contributors can help improving it.

**Comment by saddy-muchu** [comment]
I guess i could get some insights through the architecture articles.
Thanks :)
