### ISSUE TITLE
TSL support in OPTEE

### ISSUE THREAD

**Issue by xiangmingyuan** [OP-TEE/optee_os#4075]
Hi OPTEE group,

We are developing an application that requires TSL support, but I read from [here](https://optee.readthedocs.io/en/latest/faq/faq.html#q-which-apis-have-been-implemented-in-op-tee) that says there is currently no TSL support in OPTEE. So, I want to ask whether there is any plan for implementing TSL? If not, do you have any suggestions about how to implement TSL?

Thanks,
Mingyuan

**Comment by xiangmingyuan** [comment]
Hi OPTEE group,

We are developing an application that requires TSL support, but I read from [here](https://optee.readthedocs.io/en/latest/faq/faq.html#q-which-apis-have-been-implemented-in-op-tee) that there is currently no TSL support in OPTEE. So, I want to ask whether there is any plan for implementing TSL support? If not, do you have any suggestions about how to implement TSL?

Thanks,
Mingyuan

**Comment by jenswi-linaro** [comment]
Hi Mingyuan,

We have thought about implementing it, but never committed to it. So if you need it you should probably implement it yourself. I can help reviewing and answer questions. What's needed to implementat GlobalPlatform TEE Sockets API is mostly a glue layer between mbedTLS (already available inside TAs, but will need to be configured with TLS support too) and the GP API provided.

This glue layer should probably be implemented in a separate library (`libuteetls` perhaps?) instead of the default `libutee` to avoid dependencies to `libmbedtls` from `libutee` directly.

**Comment by xiangmingyuan** [comment]
Hi @jenswi-linaro ,

Thanks for your help! We'll try to implement this feature.

Thanks,
Mingyuan

**Comment by xiangmingyuan** [comment]
Thanks for fixing my typo, @jforissier
