### ISSUE TITLE
Question about TA types and the corresponding build and load methods

### ISSUE THREAD

**Issue by ChiaweiW** [OP-TEE/optee_os#4092]
Hi All,
I am new to OP-TEE and would like to ask for your kind help to clarify my understanding of TA build, loading, and configuration.

1. In general, an user TA is loaded via tee-supplicant from REE
2. Pseudo TA is different from normal user TA and executes in the S-PL1 privilege with OP-TEE core
3. I found some TAs exist under the **ta/** folder in the optee_os repo. According to the Git log, these TAs are called **in-tree TA**. Is a in-tree TA built/linked with the CFG_EARLY_TA? If not, could you explain the flow to build and include a in-tree TA into the optee image.
For example, how can I make the hello_world example a in-tree TA?
4. Is adding in-tree TA not encouraged due to OPTEE image/memory/heap size?

If any of my understanding is wrong, please kindly point me the right direction.
Thanks

**Comment by ruchi393** [comment]
You can find more information at :
https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html

The in-tree TA's are the Early TA's

**Comment by etienne-lms** [comment]
Hello @ChiaweiW,

> 1. In general, an user TA is loaded via tee-supplicant from REE

Yes, in general TAs are loaded thanks to TEE supplicant. See [ree-filesystem-ta documentation](https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html?highlight=early#ree-filesystem-ta). But there are alternatives.

First is secure storage TAs. The scheme above can be used once to save a TA in OP-TEE secure storage so that it is later loaded from there. See [secure-storage-ta documenation](https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html?highlight=early#secure-storage-ta).

Last are the so-called early TAs. Early TAs are TAs which image file is stored striaght in OP-TEE Core binary itself. This allows for example such TAs can be invoked even before TEE supplicant is available. See [early-ta documentation](https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html?highlight=early#early-ta) and maybe also [mk/config.mk](https://github.com/OP-TEE/optee_os/blob/3.10.0/mk/config.mk#L284).

> 2. Pseudo TA is different from normal user TA and executes in the S-PL1 privilege with OP-TEE core

A pseudo TA is not a TA. It is rather an OP-TEE Core service (implemented in S-PL1 as you said) that can be invoked (called?) using a interface similar to how TAs are invoked: open session, invoked commands, close session.
See [pseudo-trusted-applications documentation](https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html?highlight=early#pseudo-trusted-applications).

> > 3. ... in-tree TA ...
> The in-tree TA's are the Early TA's

Sorry to contradict.

In-tree TAs are simply TAs which implementation (source files) are located inside optee_os source tree. They are not specifically built as early TAs, unless you ask for, using `CFG_IN_TREE_EARLY_TAS` configuration switch.
When optee_os is build, all in-tree TAs are also built but this does not mean there are embedded into the target. One can either copy the generated `*.ta` file(s) in the embedded filesystem or can be embedded as early TAs, as any TA built outside of optee_os source tree.

> For example, how can I make the hello_world example a in-tree TA?

**hello_world** is a TA from **optee_example.git** source tree, so it is not an in-tree TA. Note that in-tree TA and early TA refer to different features that are not inclusive or exclusive. You can embed both out-tree TAs and in-tree TAs either through REE filesystem or as early TAs, at your will.

> 4. Is adding in-tree TA not encouraged due to OPTEE image/memory/heap size?

No, it is not related, unless your platform as constraints on the OP-TEE Core binary image size itself.

In-tree TAs are rather general purpose TAs maintained by the OP-TEE project. To ease maintenance, such  TAs are released within **optee_os.git** rather than creating new repos which would make even more repo to maintain and synchronize.

**Comment by ChiaweiW** [comment]
Thank you for your prompt response!! Now I get a clearer picture of the TA placement.
I will keep exploring more for our demands
Once again thanks for your kind help.
