### ISSUE TITLE
Problem while signing with RSA-PSS

### ISSUE THREAD

**Issue by yaziza** [OP-TEE/optee_os#4102]
I am trying to sign some data with RSA.

While **TEE_ALG_RSASSA_PKCS1_V1_5_SHA256** works like a charm, i am having trouble using **TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA256**. 

I always get a TA Panic when calling **TEE_AsymmetricSignDigest**.

For the input i provide a digest of length 32 bytes, and i am expecting a signature of size key length:

```

    result = TEE_AsymmetricSignDigest(op_handle, NULL, 0, digest, digest_size,
                                      sig, &sig_size);
```

According to GPD Core API, the **TEE_ATTR_RSA_PSS_SALT_LENGTH** is optional, and op-tee uses digest bytes as default salt length ? 

Any hint's what i am doing wrong here ?

**Comment by jforissier** [comment]
Hi @yaziza ,



> I am trying to sign some data with RSA.
> 
> While **TEE_ALG_RSASSA_PKCS1_V1_5_SHA256** works like a charm, i am having trouble using **TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA256**.
> 
> I always get a TA Panic when calling **TEE_AsymmetricSignDigest**.
> 
> For the input i provide a digest of length 32 bytes, 

Correct.

> and i am expecting a signature of size key length:

Possibly, I don't know ;-) but whatever the size of the output, the function shouldn't panic due to the size. In case the supplied buffer is too small it should return `TEE_ERROR_SHORT_BUFFER`.

> ```
>     result = TEE_AsymmetricSignDigest(op_handle, NULL, 0, digest, digest_size,
>                                       sig, &sig_size);
> ```
> 
> According to GPD Core API, the **TEE_ATTR_RSA_PSS_SALT_LENGTH** is optional, and op-tee uses digest bytes as default salt length ?

Correct.

> Any hint's what i am doing wrong here ?

I see nothing obvious. I suggest you add a few debug traces to `syscall_asymm_operate()` or set a breakpoint there in GDB (if you're running QEMU).

**Comment by yaziza** [comment]
@jforissier , thank you for your reply !

The problem was with the RSA key size. 
TEE_ALG_RSASSA_PKCS1_PSS_MGF1_SHA256 requires an RSA key size >= 66byte  (hashLen + saltLen + 2)

so using 512 bit key, causes the TA panic.

**Comment by ademyankov** [comment]
Hey, @yaziza, have you figured out how to provide the actual salt to the GP crypto? Because I haven't found the way so far. There is an attribute to specify the salt length but there is nothing to provide the actual salt! Which is kinda odd to say at least. I have to implement a PSS algorithm where I have to generate a salt myself or get it from the user of my application, but there is no GP-way of doing it. It looks like GP spec is half-way-cooked in some parts!

**Comment by jforissier** [comment]
@ademyankov you're right, the salt is randomly generated. You can't pass it to the GP API.

**Comment by ademyankov** [comment]
@jforissier yeah, thanks, man. It should not be a big deal to implement it using mbedtls.
