### ISSUE TITLE
OP-TEE Context switching

### ISSUE THREAD

**Issue by lalzz** [OP-TEE/optee_os#4127]
Hi experts,
I am doing some research in the OP-TEE security and its implementation.I have started with implementing it in hikey960,and i was able to run a hello world sample app in hikey.
On the analysis i came across the following questions
1.Is the ATF that loads trusted OS?,If yes to which memory the trusted os is loaded?
2.By default does the REE and TEE runs in same core?If it is running in same core will there be any performance impact on the Rich OS during context switching?How the context switching affects the Rich OS

**Comment by lalzz** [comment]
Can anyone please help me understand the above scenarios?

Thank you in advance

**Comment by Emantor** [comment]
> 1.Is the ATF that loads trusted OS?,If yes to which memory the trusted os is loaded?

This depends on your platform, i.MX6 (32-bit ARMv7A) leaves the start of OP-TEE to the bootloader, i.MX8 (64-bit ARMv8) does start OP-TEE via the TF-A. TF-A is the route for every 64-bit platform AFAIK.
Which memory is used is also platform specific, additionally OP-TEE may run with `CFG_WITH_PAGER=y` which runs the core within SRAM and authenticates pages within DRAM. AFAIK all of the time DRAM is required, I don't know a platform which has enough SRAM to run a full OP-TEE OS + TAs within the SRAM.

> 2.By default does the REE and TEE runs in same core?If it is running in same core will there be any performance impact on the Rich OS during context switching?How the context switching affects the Rich OS

A core can only switch between the secure world (running the TEE) and the normal world (running the REE). Therefore cores running in the secure world can not be used by the normal world and vice versa. Note that OP-TEE does not permanently reserve a core for the secure world, since it only services requests from the normal world.

**Comment by lalzz** [comment]
Thank you for the reply.
sorry for not keeping the platform:ARMv8a
From the bootsequence provided by the soc vendor(r-car),what i understood is ATF is responsible for loading OP-TEE.so can please help me with more input on the bootsequence
On the first query,you mean that Core of optee os is running in SRAM and paging is in DRAM right?.on the memory aspect i am clear with your statement.


On query 2:
I have came across a statement that secure world is running on the same core which intializes the SMC.So from that statement does it mean that Rich OS and TEE OS running in the same core.So can you please help me in making clarity on this statement also

Thank you in advance


Thank you in advance

**Comment by etienne-lms** [comment]
> On query 2:
I have came across a statement that secure world is running on the same core which intializes the SMC....So from that statement does it mean that Rich OS and TEE OS running in the same core.So can you please help me in making clarity on this statement also

First about this:
> ... Rich OS and TEE OS running in the same core.

Yes, REE and TEE do run on the same CPUs. Trustzone make each CPU able to execute in secure or non-secure state.

Now, regarding the CPU that executes the secure sequence, it depends on the SMC function ID and its execution sequence.

For example, when invoking a TA from REE, secure world is entered on the executing CPU but at some point OP-TEE Core as an execution environment that allows REE timer interrupts to suspend the running OP-TEE thread and return in REE where execute REE scheduler. The suspended TEE thread can be scheduled back on any CPU by REE scheduler.

On contrary, there are SMC function IDs, as the PSCI functions, that are fully executed in secure world on the invoking CPU. This means that non-secure interrupts must be masked for that CPU while secure world executes which is what PSCI SMCs implementation do (PSCI implemented in TF-A on armv8 and OP-TEE on arvm7).
