### ISSUE TITLE
weak symbol function exclude from unpage area

### ISSUE THREAD

**Issue by soso7885** [OP-TEE/optee_os#4150]
Hi all

I have a question about the weak symbol, some patches just add the weak symbol
so that makes it possible to exclude from unpaged area.
e.g. 
core_init_mmu_map
thread_svc_handler

but why? I mean how to exclude from unpaged area just add the weak symbol?

**Comment by etienne-lms** [comment]
Hi @soso7885,

This is related, to the paging feature of optee Core, used when the secure RAM is relatively small (few hundreds of kbytes). `CFG_WITH_PAGER`. See also [pager doc](https://optee.readthedocs.io/en/latest/architecture/core.html?highlight=pager#pager).

With `CFG_WITH_PAGER=y` Core is built with a RAM resident part (unpaged sections) and a pageable part (memory paged sections). Due to to way Core boots up, there are also `init` sections that are pageable but shall be preloaded/mapped at boot-time as the resident (unpaged) sections.
The `__weak` attributes you mention are used by the build process  (together with source file **link_dummies_paged.c**) to ensure resources needed in the `init` sections (preloaded/mapped) are not linked in an unpaged section (which would overkill SRAM resident memory size in case the resource does not strictly need to be resident).

I tried to make short. In the hope that it helps.

**Comment by soso7885** [comment]
Hi @etienne-lms 

Thanks for your explanation.
I saw that **link_dummies_paged.c** declare few function symbol which is located in section **.text.dummt***** , not in unpaged area, also using the **weak** symbol be overwritten by **strong** symbol in link time, so that the real **core_init_mmu_map** is not in unpaged area, am I right ?
