### ISSUE TITLE
[QUERY]: optee nodes in Linux

### ISSUE THREAD

**Issue by prabhakarlad** [OP-TEE/optee_os#4183]
Hi All,

Currently I am in process of adding OPTEE support on Renesas RZ/G2x platforms. We have internally maintained code (we plan to upstream it). Currently we have tested and currently upstreaming the optee nodes in DTS [1].

I wanted to  check what is the correct/recommended way to add the optee nodes should they be coming from firmware stack (TFA ?) or should it be added in SoC dtsi ?

https://patchwork.kernel.org/project/linux-renesas-soc/list/?series=369199

Cheers,
Prabhakar

**Comment by jbech-linaro** [comment]
> I wanted to check what is the correct/recommended way to add the optee nodes should they be coming from firmware stack (TFA ?) or should it be added in SoC dtsi ?

I don't think there is a "correct way", both works. Some platforms, like NXP (i.MX ones) are adding the OP-TEE firmware node from U-Boot before passing it to the kernel. The pros by doing so is that there is no need to add anything to any dts file at all. However, that is also a "con" at the same time, since from kernel point of view there will be nodes during runtime that cannot be found in dts(i) files in the tree (i.e., a potential source for confusion for developers). In any case, whatever way is much better than keeping it maintainer internally. I would recommend doing what is best for your device and your build environments.

**Comment by jforissier** [comment]
To complement @jbech-linaro answer, also note that:
- OP-TEE can add itself to the DT or create an overlay, see https://optee.readthedocs.io/en/latest/architecture/device_tree.html
- If the dts(i) contains an OP-TEE node, the Linux kernel will try to probe for OP-TEE so the firmware must support that query (even if OP-TEE is not deployed) otherwise the boot may hang etc.

**Comment by prabhakarlad** [comment]
Thank you Joakim and Jérôme for your response (we have decided for now to go with firmware stack ie OP-TEE to  add itself to the DT.) and drop the nodes from Linux.
