### ISSUE TITLE
Possible bug in thread_get_id()?

### ISSUE THREAD

**Issue by tiger20081015** [OP-TEE/optee_os#4297]
Hi, recently we met a panic in secureos booting up stage when CFG_TEE_CORE_DEBUG is set to Y. The log and dump stack are:

_...
E/TC:0    thread_get_id:973 !!!!!!!!!!ct:-1 16
E/TC:0    assertion 'ct >= 0 && ct < CFG_NUM_THREADS' failed at core/arch/arm/kernel/thread.c:974 <thread_get_id>
E/TC:0    Panic at core/kernel/assert.c:28 <_assert_break>_

![image](https://user-images.githubusercontent.com/35290009/103610466-36816500-4f5b-11eb-9d4c-e29f052a1bb9.png)

I checked the code and found the default value of thread_get_core_local->curr_thread is -1 and it's set to 0 in init_primary. However, before init_primary(), core_init_mmu_map() is called and checks the value of curr_thread, which leads to the panic. 

Is it a possible bug as I analyzed above? Or did I miss something? Looking forward to your reply.

**Comment by jenswi-linaro** [comment]
`thread_get_id()` must only be called with an active thread.

When looking at `check_pa_matches_va()` I note that `thread_get_tsd()` is only called if `va` is in user space range. That suggests that there's an overlap between privileged mappings and user mode mappings.

**Comment by tiger20081015** [comment]
@jenswi-linaro , thanks for your reply.  
I checked core_mmu_get_user_va_range() in armv7 and found the user virtual address is fixed from 1M~32M. Our previous physical address for optee starts from 8M, after I changed it to 32M, the panic disappeared. So does it mean we can't put opteeos in physical address 1M~32M as it conflicts from the user space virtual address? Is there any configuration to eliminate the  limitation? We only have a ddr chip starts from 8M with 64M size.

**Comment by jenswi-linaro** [comment]
When configured with short translation tables (v7) we have a small per thread translation table for user mode mappings and a large common translation table for the privileged mode mappings which are shared between all CPUs.

When the per thread translation table is used it's programmed into TTBR0 while TTBR1 holds the large table. Given how the VA space is split between TTBR0 and TTBR1 we can only use low addresses in TTBR0. So currently we're restricted in the way that all privileged mappings goes into the large translation table and that the per thread mappings goes into the small translation table.

One way to avoid this problem is to use LPAE instead, but I guess that's not an option on your platform.

Back to short translation tables. The only part of the mappings that must be 1-to-1 the core part which initializes and enables mmu. The rest can reside anywhere. The large part which covers TA memory could for instance be located at a higher address. Isn't the part above 32M (physical address) large enough for OP-TEE Core? The memory below 32M (physical address) is still mappable as TA ram for instance.

**Comment by tiger20081015** [comment]
@jenswi-linaro , many thanks for your detailed explanation.  Sorry I still have 2 more questions:
1. So in secureos, even for armv7 both the TTBR0 and TTBR1 are used? In linux kernel it seems only TTBR0 is used for ARMV7;
2. I'm not familiar with LPAE, only know it can map physical address which is larger than 4G.  Just curious why it can avoid the limitation, could you give some more details? I scanned the code, it seems for LPAE the virtual address for user TA is allocated at last in core_init_mmu() but I don't understand why.

**Comment by jenswi-linaro** [comment]
> @jenswi-linaro , many thanks for your detailed explanation. Sorry I still have 2 more questions:
> 
> 1. So in secureos, even for armv7 both the TTBR0 and TTBR1 are used? In linux kernel it seems only TTBR0 is used for ARMV7;

Yes, that's a way of avoiding to allocate a 16kB level 1 translation table for each CPU in the system.

> 2. I'm not familiar with LPAE, only know it can map physical address which is larger than 4G.  Just curious why it can avoid the limitation, could you give some more details? I scanned the code, it seems for LPAE the virtual address for user TA is allocated at last in core_init_mmu() but I don't understand why.

It has a much smaller level 1 translation table, so we can (must in fact) have one for each CPU. Then we chose suitable entries for shared mappings and another for the per thread mappings depending on which addresses are required by OP-TEE OS when loaded.

**Comment by tiger20081015** [comment]
@jenswi-linaro Got it, thanks for your detailed reply.
