### ISSUE TITLE
Looking for a SoC development board

### ISSUE THREAD

**Issue by xlyu** [OP-TEE/optee_os#436]
Long time ago,we had purchased several  juno development boards and attended  ARM trustzone training.   
We(so far three people) prepare porting ATF(arm trusted firmware) and optee into a new Soc platform at next two months.if any time left, maybe will develop some new features likes key managment and  some new tee applcations.  
Now we are looking for a 64-bit SoC platform which  was not even ported at before.  
Do you have any recommend?

**Comment by jbech-linaro** [comment]
Hi @xlyu 

So you are looking for any 64bit device where OP-TEE hasn't been ported yet? Did I capture your question correctly? Unfortunately it seems like there aren't that many 64bit devices out there where people can do TrustZone development. For the 96boards program we have been using Hikey and since then there has been a few more boards coming from other vendors. Qualcomm released [Dragonboard](https://www.96boards.org/products/ce/dragonboard410c/), Actions Semiconductor released [Bubblegum-96](http://armdevices.net/2015/05/26/actions-bubblegum-96-linaro-96boards-org-development-board-on-quad-core-arm-cortex-a53/) and I think Freescale have something in the pipe (see [here](http://www.freescale.com/webapp/video_vault/videoSummary.sp?code=ARROW-IMX7-96BOARDS)).

I know that Qualcomm won't allow people to do TrustZone development on Dragonboard, so that board is unfortunately a no go. I have no idea whether Bubblegum or the Freescale boards are open enough to do TrustZone development.

If I understood your question wrong and you are only looking for 64bit platform for TrustZone development, then we recommend that you get the Hikey device (https://www.96boards.org/products/ce/hikey/). That is an ARMv8 board and we have OP-TEE running on it (see instructions [here](https://github.com/OP-TEE/manifest#5-hikey)).

// Joakim

**Comment by xlyu** [comment]
Thank you, Joakim.  
You are right we are trouble with SoC platform selection. There is few vendors  willing to  open  their platforms enough for doing  trustzone development.
The anothor way is to sign NDA with SoC vendors ,and it's a pity can't open the source.  That's last resort.

**Comment by photoszzt** [comment]
I think there're a lot more 64 bit boards since the question is asked. Is there any new information that can be provided? 

Is this a good board to try: https://libre.computer/products/boards/aml-s905x-cc/ ?

**Comment by jbech-linaro** [comment]
@photoszzt , indeed and as you can read from our [platforms supported](https://github.com/OP-TEE/optee_os#3-platforms-supported) page, there are support for a few more Armv8-A, AArch64 platforms in OP-TEE today. 

Is `AML-S905x-cc` a good board to try? I don't know. If you already have the board, then you could give it a try to add support for it in OP-TEE. If you are just looking for a board in general I would have picked any of the 64-bit boards already supported by OP-TEE.

**Comment by photoszzt** [comment]
@jbech-linaro Thanks for the reply. I brought a hikey 960 a few weeks ago. Haven't tried the trustzone functionality yet. Is there a good example to look at?

**Comment by jbech-linaro** [comment]
@photoszzt , yes the HiKey 960 is good for OP-TEE development, in fact that is @jforissier "go-to" device.
