### ISSUE TITLE
Question: can heap memory contain executable code?

### ISSUE THREAD

**Issue by JamesMenetrey** [OP-TEE/optee_os#4396]
Dear OP-TEE developers,

I'm interested in adapting a WebAssembly runtime to run within a TA. To be efficient, I would need to allocate chunks of memory in the heap with executable permissions to store AoT compiled instructions. Performance-wise, this would be much better compared to bytecode interpretation.

For that purpose, I checked the TEE Internal Core API Specifications (1.2.1) and found out that the constants regarding the _Memory Access Rights_ only specify read/write/any owner. Furthermore, it seems there is no API to manipulate the memory protection, which would be similar to mprotect/mmap.

Do you know whether the heap memory's default permissions have the execution permissions, or if I miss something that would achieve a dynamic memory allocation with execution permissions?

Many thanks for your answer and time!

Cheers

**Comment by jenswi-linaro** [comment]
Executable code in the heap in currently not supported. For normal TAs it would from a security point of view a step back so if it's ever added it must only be enabled for certain TAs.

**Comment by JamesMenetrey** [comment]
Hey, many thanks for your reply. Do you think it would be possible to change how the memory is allocated in the trusted world for the heap of TAs to enable executable memory? I guess it would be a fairly simple change in the memory allocator, but I don't have any insight into OP-TEE to assess if this would work. What do you think?

Thanks!

**Comment by jenswi-linaro** [comment]
That shouldn't be very hard. You'd probably want to allocate the memory using `tee_map_zi()` instead of a plain `malloc()` to work with complete pages instead. It might be a bit challenging to have the memory both writeable and executable at the same time when taking cache coherency into account. You'd probably want to switch from writeable to executable and back again as needed. So what's missing is a `tee_set_prot()` for that purpose. Internally there's a `vm_set_prot()` function which can do this in privileged mode, but you'd need to add the missing parts in `core/pta/system.c`. If you follow the flow for `tee_map_zi()` you'll get the idea.

**Comment by JamesMenetrey** [comment]
Many thanks for these insights @jenswi-linaro! I close the thread for now since you gave me enough details to work on my own. I will eventually go back with a PR if I see this works and may be a good asset for OP-TEE. :)

Cheers!

**Comment by expediter-affable** [comment]
> Hey, many thanks for your reply. Do you think it would be possible to change how the memory is allocated in the trusted world for the heap of TAs to enable executable memory? I guess it would be a fairly simple change in the memory allocator, but I don't have any insight into OP-TEE to assess if this would work. What do you think?
> 
> Thanks!





https://angular-ui-modal.github.io/NqeLNXPgm1nx2aUrSE7NCuwdQNkORUdCu1/
