### ISSUE TITLE
When I was trying to compile optee_os for new platform that's not already supported got an error core/arch/arm/plat-/main.c:3:10: fatal error: kernel/generic_boot.h: No such file or directory    3 | #include <kernel/generic_boot.h>       |          ^~~~~~~~~~~~~~~~~~~~~~~ compilation terminated. Please look into and let me know what went wrong. 

### ISSUE THREAD

**Issue by kurundkar123** [OP-TEE/optee_os#4405]

**Comment by etienne-lms** [comment]
kernel/generic_boot.h has been renamed kernel/boot.h.
It looks like you developed your platform on an older optee release and you rebased since with updating your code.
If you started from an existing platform, you should look at how this platform implementation evolved and update yours accordingly.

**Comment by kurundkar123** [comment]
I was making my platform specific files by looking into the porting guidelines provided https://optee.readthedocs.io/en/latest/architecture/porting_guidelines.html#porting-guidelines. Yeah you are right I started with existing platform FVP and I will do it according to FVP. Thank you so much for info.

**Comment by etienne-lms** [comment]
You're right, [porting-guidelines](https://optee.readthedocs.io/en/latest/architecture/porting_guidelines.html#porting-guidelines) needs to be updated!
