### ISSUE TITLE
Does TEE support multi threads?

### ISSUE THREAD

**Issue by janoslim** [OP-TEE/optee_os#4483]
Hello,
I am using optee and darknetZ which is TEE version of darknet including yolo, mobilenet, etc.
I wonder if I can utilize TEE with concurrent TEE threads.

what i tried is,
- invokeCommand with main thread & concurrently pthread_create in NA and invokeCommand
=> failed. Two threads works as a batch.
- set affinity with different cpu mask and run concurrently
=> failed.

I just read some docs that the inter-session multi threads is not available but, invoking TA function with different session would be possible(?).

I want to do parallel calculation through multi-threading in TEE, is there a good way?

Thank you!

**Comment by jforissier** [comment]
Hi @janoslim,

Multi-threading inside the same TA process is simply not possible at the moment. It is forbidden by the GlobalPlatform TEE Internal Core API specification. When several Normal World thread invoke the same TA process, they are serialized.

You can however have several threads executing the same TA binary simultaneously provided they do **not** share the same address space. This is called multiple instance TAs. Basically there is one TA process per client session. To do this you simply do **not** set the `TA_FLAG_SINGLE_INSTANCE` bit in `ta_head.flags` (i.e., typically when defining `TA_FLAGS` in `user_ta_header_defines.h`). Depending on your needs it might be OK to provide the processing power you need. But obviously it makes data sharing more complex since you have to go via Normal World. But again that's on purpose as per the GP spec for security/integrity reasons I suppose.

An example of this is the `aes-perf` application (`xtest --aes-perf`). The crypto TA is multiple instance and on a multi-CPU board you should see a speedup when running several instances of `xtest --aes-perf` in parallel.

Note that I have heard several requests for true multithreading support in TAs already, with `pthread_create()` etc. At some point I planned to work on it but I wanted to base this work on the OCALL feature (calling out to Normal World to start a new thread or perform synchronization), but OCALL has since stalled.

**Comment by jforissier** [comment]
One more thing, you may notice `TA_FLAG_CONCURRENT` in the OP-TEE source code but as mentioned in the comment it is only applicable to pseudo TAs at the moment (PTA = kernel mode code). More about the different kinds of TAs here: https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html. The GP spec can be helpful too to understand the terms (single instance vs. multiple instance, and single instance multiple sessions vs. single instance single session in particular).

**Comment by janoslim** [comment]
Thank you for your answer.
According to my understanding, NA create session of UUID.ta and Invoke TA functions -> this is not available to run concurrently.
if two NA threads create two session of UUID.ta, -> this could be run concurrently
Am I right to understand?
Thank you!

**Comment by jforissier** [comment]
@janoslim correct.

> if two NA threads create two session of UUID.ta, -> this could be run concurrently

yes, concurrently in two separate TA instances (processes in Secure World).
