### ISSUE TITLE
How do I make sure that only my OPTEE OS can access a certain physical memory region ?

### ISSUE THREAD

**Issue by tebina** [OP-TEE/optee_os#4580]
For example, I have an IP in the PL side and I want only my driver in optee to be able to communicate with it.
Is there a hardware authentification mechanism to be implemented ? Or is there already such mechanism in OPTEE ?

**Comment by lorc** [comment]
I don't believe that it is architecturally possible.

Your platform should provide mechanism that controls access to a memory from normal (non-secure world). And OP-TEE itself takes advantage of this mechanism to make sure its memory is protected. This is possible, because OP-TEE is running in secure mode. But problem is that optee driver is a part of non-secure world, so it is impossible to tell if optee driver accesses this memory or it is some other part of a kernel does thi access.
