### ISSUE TITLE
PKCS xtest fails after deleting TEE data in REE FS 

### ISSUE THREAD

**Issue by lenormandfranck** [OP-TEE/optee_os#4594]
When using the latest revision of OPTEE (3.13), I have a test performing the following sequence:
```
xtest
rm -rf /data/tee
xtest
```

When the second xtest run, I have only 1 test failing: pkcs11 1003:
```
E/TA: update_persistent_db:61 Failed to open token persistent db: 0xffff0008
```
I understand why the issue happens: DB inited when opening the TA, deleted due to the "rm" in the test, then the TA fails when trying to acccess it.

A simple fix would be to move the init of the DB to the handler for session opening:
```
diff --git a/ta/pkcs11/src/entry.c b/ta/pkcs11/src/entry.c
index a58f566d..f4b21477 100644
--- a/ta/pkcs11/src/entry.c
+++ b/ta/pkcs11/src/entry.c
@@ -17,7 +17,7 @@

 TEE_Result TA_CreateEntryPoint(void)
 {
-       return pkcs11_init();
+       return TEE_SUCCESS;
 }

 void TA_DestroyEntryPoint(void)
@@ -36,7 +36,7 @@ TEE_Result TA_OpenSessionEntryPoint(uint32_t __unused param_types,

        *tee_session = client;

-       return TEE_SUCCESS;
+       return pkcs11_init();
 }
 void TA_CloseSessionEntryPoint(void *tee_session)
```
I was wondering if it is feasible or a security issue. If it is I will the pull request for it.

If it is not a good option, I will modify my test to remove the "rm" but I wanted to bring up this behavior before doing further modifications.

**Comment by Emantor** [comment]
Deletion of data while the TA is still loaded should result in an error. AFAICS as soon as you restart OP-TEE/reload the TA by other means a new DB will be created. But IMO this is no bug in the TA.

**Comment by lenormandfranck** [comment]
@Emantor I also thinks it is not a bug and I wanted to know if the fix I am proposing could be integrated. I felt that a pull request where I cannot ensure the security of the TA was not the best way to propose the patch.

I can understand that deleting the data of the TA when a session is opened must result in an error. The idea of the patch is to init the DB whenever a session is opened. I am unsure about the security of such a modification so I am asking for input.

**Comment by etienne-lms** [comment]
Indeed erasing the full REE FS secure storage (at runtime or boot time) is not something expected on a product.
I think also this should be addressed at Core level, not at TA level (unless a TA has a specific "wipe my storage" feature).
I also strongly think that once OP-TEE Core has loaded some REE_FS content or references in (i.e. Core as accessed REE_FS since it has boot), then we can't delete REE_FS content without corrupting Core itself and I don't think it is desirable.

There are also so dependencies between REE_FS and RPMB_FS that makes deleting /data/tee difficult to work with when RPMB_FS stores the anti rollback hash of the REE_FS. 

All in one, i think we can find a way to allow REE_FS being reset, but only before op-tee boots. Something like boot then remove /data/tee content then reboot. I don't think we should ever support manipulations like `sh> xtest && rm -rf /data/tee && xtest`.

**Comment by lenormandfranck** [comment]
Thanks @etienne-lms for the clarification. I will close the ticket as the explanation is good: This use case should not be supported.
