### ISSUE TITLE
Question about core_mmu_create_user_map

### ISSUE THREAD

**Issue by jingdlu** [OP-TEE/optee_os#4598]
https://github.com/OP-TEE/optee_os/blob/a07b8a3907ca78f7a3007dd0c7623091ea1bbeea/core/kernel/user_ta.c#L155

Here, why do we need to create user map every time before entering user space? I think it should be time consuming operation. After open session, can we don't remove user space mapping and continue to use the user map for every invoke command operation? After close session, we finally remove user map then.

Is it because page table resources limit? or other concerns?

Thanks,
Jingdong

**Comment by etienne-lms** [comment]
There can be several TAs hosted by OP-TEE. Each time a TA is entered, we must restore its mapping and no mess with other TAs mapping.

Actually TA mapping tables are not rebuilt from scratch each time a TA is invoked. TA mapping is made of a static mapping (constructed when TA instance is initialized, from the TA image and preserved as long as TA instance is alive) and a dynamic mapping that are the memref params provided by TA client at each invocation. This part is rebuilt from scratch for each TA invocation since params can change from one invocation to another.

**Comment by etienne-lms** [comment]
In case my description is false, please feel free to comment.

**Comment by jingdlu** [comment]
Hi Jens,

Do you mean repopulating translation tables is done in core_mmu_populate_user_map function? Is there any TLB miss impact after repopulating page tables?

Thanks,
Jingdong

**Comment by jenswi-linaro** [comment]
> Do you mean repopulating translation tables is done in core_mmu_populate_user_map function?

Yes

> Is there any TLB miss impact after repopulating page tables?

It has never been measured.
