### ISSUE TITLE
Reboot might result in corrupted dirf.db

### ISSUE THREAD

**Issue by cgellner** [OP-TEE/optee_os#4619]
In case rebooting at a particular unlucky position during creation of the dirf.db it might be regarded as corrupted in the next power-cycle.
This situation won't heal itself.
To recover it is necessary to delete the dirf.db.

This issue seems to be related to
667b10f6f1b668c624a8d6f82cee63e27ec50803 tee_ree_fs: create dirfile only when it's not found

I believe the above commit is good as it avoid recreation of dirf.db in generic error situations, but it seems to have a weakness in the scenario described below.

The simple way to reproduce is to add a delay to _ree_fs_new_write_ in _tee-supplicant_.
As an alternative you could use GDB or similar to stop at _ree_fs_new_write_ and reboot before the second execution of _ree_fs_new_write_.

Simple patch adding delay to _ree_fs_new_write_ of _tee-supplicant_:
```
--- a/tee-supplicant/src/tee_supp_fs.c
+++ b/tee-supplicant/src/tee_supp_fs.c
@@ -332,6 +332,8 @@ static TEEC_Result ree_fs_new_write(size_t num_params,
        int fd = 0;
        ssize_t r = 0;
 
+       sleep(3);
+
        if (num_params != 2 ||
            (params[0].attr & TEE_IOCTL_PARAM_ATTR_TYPE_MASK) !=
                        TEE_IOCTL_PARAM_ATTR_TYPE_VALUE_INPUT ||
--
```

In order to reproduce in QEMU v7 I used the below sequence and above patch adding some delay to _ree_fs_new_write_.
````
rm -rf /tmp/qemu-data-tee && mkdir -p /tmp/qemu-data-tee && make QEMU_PSS_AUTOMOUNT=y run
````
Start using ```c``` in QEMU control console.
In normal-world run
```(optee_example_secure_storage &); sleep 4; echo "reboot"```
Execute ```system_reset``` in QEMU control console as soon as you see _reboot_ being printed in normal-world console.

After reboot you will see dirf.db having some data starting at offset 0x1042.
```
# hexdump /data/tee/dirf.db 
0000000 0000 0000 0000 0000 0000 0000 0000 0000
*
0001040 0000 4c09 3149 b2fd aff2 7c41 039e a922
0001050 6071 e806 1f21 01e9 677f c61a 25e3 0013
0001060 caac 0000 0000 0000 0000 0000 0000 0000
0001070 0000 0000 0000 0000 0000 0000 0000 0000
*
0001080 0000 0000                              
0001084
# 
```

Accessing dirf.db will fail with 0xf0100001 - TEE_ERROR_CORRUPT_OBJECT
```
# optee_example_secure_storage 
Prepare session with the TA
optee_example_secure_storage: TEEC_Opensession failed with code 0xf0100001 origin 0x3
```

When reverting 667b10f6f1b668c624a8d6f82cee63e27ec50803  I could see that the dirf.db has been recreated, which would fix the corrupted dirf.db. But as mentioned above this might also trigger unwanted recreation in generic error cases.

**Comment by cgellner** [comment]
Please note: the complicated reproduction steps are just needed to trigger the issue.
In theory it should also be possible to run into this race-condition without all this when rebooting while dirf.db is being created.

Could anybody reproduce this issue ?
Is it expected that OP-TEE is able to handle reboots etc. at any point in time ?
Does it make sense to fix this issue ?
If so I can have a look to check if I can identify a good position to fix.

**Comment by etienne-lms** [comment]
Hi @cgellner,
I wonder if this is a real issue. If system can crash/reboot at anytime, you expect filsystems to have some journal support to recover from such error and I would not expect _dirf.db_ creation or update failures to definitely corrupt OP-TEE's secure storage. Does that make sense? I may have missed something.

**Comment by jenswi-linaro** [comment]
If I've understood this correctly it's a problem that can only occur if `dirf.db` doesn't exist. Once it has been created and filled in properly it should be OK since each update is atomic. Is this correct?

**Comment by cgellner** [comment]
@etienne-lms
I don't think, this is an situation where journaling filesystems can help you.
tee_supplicant is opening the handle with O_SYNC
But there are multiple calls from OP-TEE OS to tee-supplicant to build the dirf.db step-by-step.
So there might be some time between the calls.
From my humble understanding, the intermediate states should be considered as valid from filesystem perspective.

@jenswi-linaro
Your understanding is correct. The reported error occurs during the very initial creation of dirf.db.
But I didn't test all the cases.

**Comment by jenswi-linaro** [comment]
> @jenswi-linaro
> Your understanding is correct. The reported error occurs during the very initial creation of dirf.db.
> But I didn't test all the cases.

Thanks for confirming. I believe the problem is that the `dirf.db` only becomes partially created. When creating the initial we should make sure that `dirf.db` is initialized so it can be successfully open in case we're interrupted. One way is to create it under a temporary name and then rename it in `open_dirh()` after `commit_dirh_writes()` has been called.

Given that there's more than just zeroes in you're example I suspect that `commit_dirh_writes()` has been called but it hasn't completed yet and since it started from an invalid file it's not atomic in the update.

If we can make sure to have the file in a valid state before `commit_dirh_writes()` is called the first time (at least under the name `dirf.db`) then we'd be safe.

**Comment by etienne-lms** [comment]
ok, I understand the issue now. thanks for the description.
 Can be quite tricky since how `dirf.db` management (_core/tee/fs_dirfile.c_) is separated from _tee_ree_fs.c_ implementation. I think we should load an initial content by a specific RPC right after we created the file (from [_tee_ree_fs.c_:501](https://github.com/OP-TEE/optee_os/blob/3.13.0/core/tee/tee_ree_fs.c#L501)) before returning from `open_dirh()`.
