### ISSUE TITLE
xtest regression_1024 Failed

### ISSUE THREAD

**Issue by zhengtf0963** [OP-TEE/optee_os#4666]
Hi,I encountered an error when running the xtest regression_1024 command using stm32. The error code is as follows:
`Test ID: regression_1024                                                        
RunD/TC:? 0 tee_ta_init_pseudo_ta_session:298 Lookup pseudo TA ee90d523-90ad-466
 test suite with level=0                                                        
                                                                                
TEE test application started over default TEE instance                          
D/TC:? 0 load_ldelf:719 ldelf load address 0x40004000                           
####################D/LD:  ldelf:134 Loading TA ee90d523-90ad-46a0-859d-8eea0b16
##################################                                              
#                                                                               
# regressionD/TC:? 0 tee_ta_init_pseudo_ta_session:298 Lookup pseudo TA 3a2f897c
                                                                                
#                                                                               
###############################D/TC:? 0 tee_ta_init_pseudo_ta_session:311 Open a
##D/TC:? 0 tee_ta_init_pseudo_ta_session:328 system.pta : 3a2f8978-5dc0-11e8-9cc
#####################                                                           
                                                                                
* regression_1024 Test PTA_SYSTEM_GET_TPM_EVENT_LOG Service                     
D/TC:? 0 system_open_ta_binary:256 Lookup user TA ELF ee90d523-90ad-46a0-859d-8)
D/TC:? 0 system_open_ta_binary:260 res=0xffff0008                               
D/TC:? 0 system_open_ta_binary:256 Lookup user TA ELF ee90d523-90ad-46a0-859d-8)
D/TC:? 0 system_open_ta_binary:260 res=0x0                                      
D/LD:  ldelf:168 ELF (ee90d523-90ad-46a0-859d-8eea0b150086) at 0x40068000       
D/TC:? 0 tee_ta_close_session:496 csess 0x2ffe2d48 id 1                         
D/TC:? 0 tee_ta_close_session:515 Destroy session                               
o regression_1024.1 TPM test service invocation                                 
Buffer Event log PA                                                             
Buffer Event log PA: 2048                                                       
D/TC:? 0 tee_ta_init_session_with_context:590 Re-open TA 3a2f8978-5dc0-11e8-9c2c
D/TC:? 0 tee_ta_init_session_with_context:590 Re-open TA 3a2f8978-5dc0-11e8-9c2c
D/TC:? 0 system_get_tpm_event_log:859 TPM Event log size: 2048 Bytes            
D/TC:? 0 system_get_tpm_event_log:860 aaa                                       
E/TC:? 0 tpm_get_event_log:114 TPM Event log size: 2048 Bytes                   
E/TC:? 0 tpm_get_event_log:115 TPM Event log size: 512 Bytes                    
D/TC:? 0 tpm_get_event_log:116 TPM Event log PA: 0x2d1f8d10                     
D/TC:? 0 tpm_get_event_log:133 tffff:0x40012000                                 
D/TC:? 0 system_get_tpm_event_log:864 tffff:0x40012000                          
D/TC:? 0 tee_ta_close_session:496 csess 0x2ffe2a40 id 1                         
D/TC:? 0 tee_ta_close_session:515 Destroy session                               
E/TA:  test_with_right_parameters:74 PCRIndex must be 0                         
D/TC:? 0 tee_ta_invoke_command:801 Error: ffff0000 of 4                         
regression_1000.c:1893: TEEC_InvokeCommand(&sesDs/TC:? 0 tee_ta_init_session_wic
Don, 1, ((void *)0), &ret_orig) has an unexpected value: 0xffff0000 = TEEC_ERROS
 /TC:? 0 system_get_tpm_event_log:859 TPM Event log size: 1 Bytes               
  D/TC:? 0 system_get_tpm_event_log:860 aaa                                     
reEg/TC:? 0 tpm_get_event_log:114 TPM Event log size: 1 Bytes                   
reE/TC:? 0 tpm_get_event_log:115 TPM Event log size: 512 Bytes                  
ssDi/TC:? 0 tpm_get_event_log:116 TPM Event log PA: 0x2d1f8d10                  
onE/TC:? 0 tpm_get_event_log:127 TPM: Not enough space for the log: 1, 512      
_1D0/TC:? 0 system_get_tpm_event_log:864 tffff:0x40012000                       
24.1 FAILED                                                                     
o regression_1024.2 TPM test passinDg/TC:? 0 tee_ta_close_session:496 csess 0x23
 sD/TC:? 0 tee_ta_close_session:515 Destroy session                             
hort buffer                                                                     
  regression_1024D/TC:? 0+-----------------------------+ 0x2ffe3358 id 1        
.2D /TC:? 0 tee_ta_close_|                             |                        
OK                       |  Cannot open /dev/ttyACM0!  |                        
D/TC:? 0 destroy_context:|                             |                        
D/TC:? 0 tee_ta_close_ses+-----------------------------+                        
D/TC:? 0 tee_ta_close_session:515 Destroy session                               
  regression_1024 FAILED                                                        
+-----------------------------------------------------                          
Result of testsuite regression filtered by "regression_1024":                   
regression_1024.1 FAILED first error at regression_1000.c:1893                  
regression_1024 FAILED                                                          
+-----------------------------------------------------                          
2 subtests of which 1 failed                                                    
1 test case of which 1 failed                                                   
91 test cases were skipped                                                      
TEE test application done!          `

I set up a global array in tf-a and accessed the address of this array so that I can get the content of this address. I used the tpm_get_event_log() function in tpm.c, and want to run the xtest 1024 command, but it seems to be unsuccessful,it looks like a pcr error and how to solve it?

**Comment by javieralso-arm** [comment]
Hi @zhengtf0963,

Sorry for the late reply, I've been on annual leave.

The error you are getting is caused because the buffer you are passing to PTA_SYSTEM_GET_TPM_EVENT_LOG doesn't have enough space to hold the whole event log passed to OPTEE at start-up. 

To give you a bit of background on PTA_SYSTEM_GET_TPM_EVENT_LOG, this system call should only be enabled if:

1. The underlying firmware (e.g TF-A) has been built with support for Measured Boot and it is able to generate an Event Log as specified in the [TCG EFI Protocol Specification](https://trustedcomputinggroup.org/wp-content/uploads/EFI-Protocol-Specification-rev13-160330final.pdf) and
2. If you are using a TA which needs to access the event log (e.g. https://github.com/microsoft/ms-tpm-20-ref which ARM32 port which has now support for Measured Boot).

PTA_SYSTEM_GET_TPM_EVENT_LOG was added to OPTEE in order to test and validate Measured Boot functionality on TF-A. At the moment, the latter has support for Measured Boot only for FVP platform, so if it were needed for your platform, you would need to enable Measured Boot support on your platform.

To get a reference on how this is done, I would suggest you to take a look at fvp_measured_boot.c on TF-A and also search for "MEASURED_BOOT" definition across the source code, to see how it is implemented for FVP. There is a driver which is generic so make it work on any platform should be straight forward. There is some [documentation on that driver](https://trustedfirmware-a.readthedocs.io/en/latest/components/measured_boot/index.html) on the TF-A project page which might be useful to you.

If you want an example on how to use PTA_SYSTEM_GET_TPM_EVENT_LOG, you can browse [this commit on ms-tpm-20-ref](https://github.com/microsoft/ms-tpm-20-ref/commit/98b60a44aba79b15fcce1c0d1e46cf5918400f6a) where the call is used. Specifically, you should review the changes on file fTPM.c

All that said, my recommendation is that if you don't need to use Measured Boot and/or an fTPM service based on OPTEE, you should disable PTA_SYSTEM_GET_TPM_EVENT_LOG call by setting CFG_CORE_TPM_EVENT_LOG to 0 at build time (it should be disabled by default anyway).

Hope you find this helpful.

Cheers,
Javier
