### ISSUE TITLE
standard libc headers not supported

### ISSUE THREAD

**Issue by jiangpeifu** [OP-TEE/optee_os#468]
I found the following libc headers are not supported in current version:
errno.h
time.h

Is there any plan to support these libc headers in OP-TEE ?

**Comment by jenswi-linaro** [comment]
So far we haven't seen the need for errno.h or time.h. What do you need them for, some software you're trying to put in a TA?

**Comment by jiangpeifu** [comment]
Yes, we are trying to do third-party DRM porting, it depends on these headers.

**Comment by jenswi-linaro** [comment]
Our TA environment aims to be Global Platform compliant, a portable TA can expect nothing more.

Some background, when we need another libc function/type/define that's part of a standard (real or de facto) we define it accordingly in the expected header file. Those will then be available to the TA also.

I don't think we'll ever add `errno.h` or `time.h` as they don't provide anything OP-TEE OS need. Especially `errno.h` since it's just normal world error codes that never finds its way into secure world (unless supplied as an argument to a TA but then it's part of that API/protocol instead). Concerning `time.h`, we're using the time related functions and types from Global Platform instead.

I think your best option is to supply those header files yourself inside the TA where you're using the third party software. You would then also be able to define the differed defines of `errno.h` with values that makes sense for your environment.
 
Regards,
Jens

**Comment by jiangpeifu** [comment]
Got it. Thx.
