### ISSUE TITLE
ta:  pkcs11: persistant object resource releasing

### ISSUE THREAD

**Issue by al1img** [OP-TEE/optee_os#4686]
The main issue is after creating few keys and importing few certificates it returns CKR_DEVICE_MEMORY error.

I see that creating persistent objects allocates memory for its attributes and doesn't free them. As result, PKCS11 TA runs out of memory. Looking through implementation I see that persistent object attributes cached on a persistent object creating and finding but they are never released. In the worst case, TA tries to allocate as much memory as all persistent objects occupy in the persistent DB. For example, find all persistent objects will cache all persistent objects attributes in RAM. Is it expected behavior?

Another issue: pkcs11_init fills token->object_list. I expect that pkcs11_deinit releases the list elements, but it doesn't. Shall the list be released somewhere?

Thanks.

**Comment by etienne-lms** [comment]
> I see that creating persistent objects allocates memory for its attributes and doesn't free them. 

That's true. The point is that objects created within a session are instanced in TA memory as object handles have been exported to client application. Closing the session once persistent object are created and using a new session for other operations should release memory pressure.

Should the TA offload object to persistent storage to release memory pressure?

I would rather think the pkcs11 TA heap size should be configurable. It's currently 16kB which may not always be sufficient.
What about adding config switch `CFG_PKCS11_TA_HEAP_SIZE`?

> Another issue: pkcs11_init fills token->object_list. I expect that pkcs11_deinit releases the list elements, but it doesn't. Shall the list be released somewhere?

`pkcs11_init()` is called from `TA_DestroyEntryPoint()` after which TA execution context is destroyed so there's no real need to release allocations in the heap. Note also that TA sets flags `TA_FLAG_INSTANCE_KEEP_ALIVE` which means `TA_DestroyEntryPoint()` is never called.

**Comment by al1img** [comment]
> That's true. The point is that objects created within a session are instanced in TA memory as object handles have been exported to client application. Closing the session once persistent object are created and using a new session for other operations should release memory pressure.

In the current implementation, it is not the case. Closing the session doesn't release persistent object resources.

**Comment by etienne-lms** [comment]
Looks you're right. Thanks for reporting. 
Do you have any correction in mind?

**Comment by etienne-lms** [comment]
Object handles are visible to all client's sessions so it is not clear when handles permanent objects should be released. For example, a session can _load_ an permanent object in memory through `C_FindObject()` and all sessions are free to use that handle. For a permanent object, when the initial session closes, the specs does not prevent another session from using the object handle.

A quick way out could be to unload from memory the attributes of permanent object when _all_ sessions are closed.

Another way would be keep valid handles for permanent objects but load/unload their attributes to RAM only when needed. ("only when needed" is not that easy to state...).

**Comment by al1img** [comment]
If there are no objections to load/unload attributes only when needed, I could try to work on the implementation.

**Comment by etienne-lms** [comment]
Hi @al1img, please, feel free to propose something.
`struct pkcs11_object` already informs when the object is persistent (`.uuid` not null). Could reload `.attributes` when `obj->attributes==NULL && obj->uuid != NULL`.
`entry_release_active_processing()` maybe a good place to release persistent objects for many of the API functions/commands.

**Comment by al1img** [comment]
Yes, caching everything works fast but consumes a lot of memory, allocation/releasing memory each time of accessing/modifying object attributes will decrease the performance. Some caching buffer with predefined configurable size could be the trade-off.

Increasing pkcs11 TA stack size works for me as well. But I still wonder if the current implementation with increasing TA stack size is the right one or the trade-off solution should be implemented?

**Comment by etienne-lms** [comment]
> Increasing pkcs11 TA stack size works for me as well. But I still wonder if the current implementation with increasing TA stack size is the right one or the trade-off solution should be implemented?

PKCS11 TA current stack and heap sizes were set quite arbitrarily, they may need some adjustment.
I think we should be able to consider a generic stack size but the TA heap size will be to be customized by platforms that expect to manipulate many objects. Maybe the reference implementation should use bigger sizes to be generic and let platform lower them if applicable.

**Comment by vesajaaskelainen** [comment]
Actually it was heap that we enlarged.

```patch
diff --git a/ta/pkcs11/src/user_ta_header_defines.h b/ta/pkcs11/src/user_ta_header_defines.h
index a9b84a56..2841e46d 100644
--- a/ta/pkcs11/src/user_ta_header_defines.h
+++ b/ta/pkcs11/src/user_ta_header_defines.h
@@ -15,7 +15,7 @@
                                         TA_FLAG_INSTANCE_KEEP_ALIVE)
 
 #define TA_STACK_SIZE                  (4 * 1024)
-#define TA_DATA_SIZE                   (16 * 1024)
+#define TA_DATA_SIZE                   (64 * 1024)
 
 #define TA_DESCRIPTION                 "PKCS#11 trusted application"
 #define TA_VERSION                     TO_STR(PKCS11_TA_VERSION_MAJOR) "." \

```

In our case we need to allocate quite a lot of secure memory due to memory partitioning configuration to OP-TEE. This leaves quite a bit of secure memory "unused". And in our case the PKCS#11 is more or less the only secure memory user in OP-TEE so adding more heap for the PKCS#11 was not a problem at all. We did sanity test to create sufficient amount of keys we could ever imagine and then we hit the barrier. Also noticed that heap needs to be about twice the needed memory for the keys due to internal usage. I believe the current PKCS#11 is a bit more easier on memory pressure than what we were using at a time.

With this increase we have more than enough memory for keys for the use cases we have. When comparing it to overall OP-TEE memory allocation this is not in same scale at all -- eg. not a problem at all. In theory default could even be larger but we wanted to capture possible memory leaks so did not go for too large one.

In example following key counts are supported by some commercial economy offering:

Product | RSA key pairs | EC key pairs | Other limit
--------|---------|---------|--------
Nitrokey HSM 2 | 38 | 300 |
YubiHSM 2 | - | - | All data stored as objects. 256 object slots, 128KB (base 10) max total

Commercial professional offering do not have much storage limits (they are more or less speed capped). With "cheaper models" the speed can be extremely slow when switching the key (and even more when generating one).

I would assume most often OP-TEE's PKCS#11 use case would be more like "IoT device" when you go to authenticate your device or so to the cloud offering. You may have web server (Web UI) or so within your device so those also need space. For Android type of device IF the OP-TEE's PKCS#11 would be in use then FIDO2 or such user authentication could be added to the list. Nothing limits one to create a own (cheap) HSM with OP-TEE :grin: -- then the comparison would most likely to be other economy offerings.

That being said -- looking at that list I suppose heap limit like 256 KiB (eg. I suppose that would make about 64 KiB for objects) could be reasonable. Supporting key counts like 256 (or 128 pairs) sounds a bit overkill for expected use cases. What then eats more memory is that if one imports X.509 certificates to the storage then those could easily be 1-2 KiB per piece -- you are likely to import the whole chain (expect the root) so they take a bit more per key pair.

Then the real thing is I don't think those ALL keys that memory allows would be in use all the time -- and it might even be better that not all keys would be unencrypted in secure memory all the time. But as the cache logic is a bit more to complex to implement so perhaps it would be good start to have a bit larger default and then if someone really hits the limit then consider implementing the cache. I suppose only reason why one would like to have them all in memory is to have `C_Find*` -- otherwise only opened (or recently accessed) keys could be in memory. I suppose one option could be to leave secret material in storage until someone really asks for them to save a bit -- but that itself increases the complexity which may not be a good thing -- in this formula I suppose the possibility for secret material exposure due to software bug would be more critical factor.

Then there is also used storage space query (`C_GetTokenInfo`) in PKCS#11 so I suppose it would be a good idea to report some kind of estimate how much memory is left.

**Comment by etienne-lms** [comment]
Thanks @vesajaaskelainen for sharing your experience. 

IMO this shows how devices will likely need a customized heap size. A configuration switch `CFG_PKCS11_TA_HEAP_SIZE` would greatly help.

> Then there is also used storage space query (C_GetTokenInfo) in PKCS#11 so I suppose it would be a good idea to report some kind of estimate how much memory is left.

When OP-TEE OS libs are built with `CFG_WITH_STATS=y`, we can use  `malloc_get_stats()` to retrieve heap status. However, OS releases tend to disable debug resources among which `CFG_WITH_STATS` and here ta/pkcs11 would need a specific **libutils** built with that option.

**Comment by jforissier** [comment]
> Thanks @vesajaaskelainen for sharing your experience.
> 
> IMO this shows how devices will likely need a customized heap size. A configuration switch `CFG_PKCS11_TA_HEAP_SIZE` would greatly help.

Even better perhaps, OP-TEE could expand the TA heap dynamically. We already have `tee_map_zi()` so we could use it with `malloc_add_pool()`. The downside however is it could allow DoS from a TA eating up all the memory.

**Comment by etienne-lms** [comment]
OP-TEE usually tends to provision the memory so that the secure service can be called in reasonable conditions (I.e. no intentional heap allocation DoS attacks). GPD TEE spec expects TA property "gpd.ta.dataSize" has a reasonable guaranty of the heap size the TA can rely on.

Yet, extending with `tee_map_zi` is a nice idea. Note that such heap extensions would never be released to the OS (the TA is KeepAlive).

I still think device should be able to customize its pkcs11 TA heap size, being at TA build time or from the OP-TEE OS (i.e. a max allowed extra `tee_map_zi` size for that TA).

**Comment by etienne-lms** [comment]
IMO this pkcs11 TA heap size configuration has not been addressed but ideas are there.
Could this issue be reopened and tagged enhancement or like for the pkcs11 TA?
