### ISSUE TITLE
ta: pkcs11: wrong type sizes

### ISSUE THREAD

**Issue by al1img** [OP-TEE/optee_os#4689]
Attributes CKA_CLASS, CKA_CERTIFICATE_TYPE, CKA_KEY_TYPE, CKA_HW_FEATURE_TYPE, CKA_MECHANISM_TYPE, CKA_KEY_GEN_MECHANISM, CKA_VALUE_LEN, CKA_MODULUS_BITS are defined as CK_ULONG which is 8 bytes length. However, they are mostly defined as uint32_t which 4 bytes length.

There is an approach to retrieve attributes if the size is unknown: send empty (null) buffer in TLV. In this case, TA returns the actual attribute size in the length field. Then ask for the attribute again with preallocated buffer. But this approach fails due to the following check in the client library (libckteec):
```c
if (ck_attr_is_ulong(attr->type)) {
	CK_ULONG ck_ulong = 0;

	if (attr->ulValueLen < sizeof(CK_ULONG))
		return CKR_ATTRIBUTE_TYPE_INVALID;
```

Q1: shall the above type's sizes be set to CK_ULONG?
Q2: why CK_ULONG type is handled differently and has separate path in libckteec?

**Comment by etienne-lms** [comment]
CK_ULONG attributes have an attribute value that should be 'unsigned int' large, hence 32bit on 32bit machines (as armv7-a) and 64bit on 64bit machines (as AArch64).
In PKCS11 TA space, such attributes are always 32bit sized attributes, so that the API match both 32bit and 64bit clients.
Therefore we explicitly convert such attribute values from CK_ULONG (32b or 64b) into explicit `uint32_t` in libckteec when seruializing data passed to the TA. We must do that only for CK_ULONG typed attributes, not for all 8-byte large attributes of course.

**Comment by al1img** [comment]
Then it is the bug in libckteec and should be fixed there? CK_ULONG should be defined as uint32_t explicitly to match TA implementation?

**Comment by etienne-lms** [comment]
`CK_ULONG` can be 64bit as per Cryptoki spec so libckteec has to make the conversion when passing data from/to client data since TA uses a fixed 32bit to comply with both architecture. Forcing `CK_ULONG` to `uint32_t` in libckteec would break the lib compatibility IMO.

**Comment by vesajaaskelainen** [comment]
If I understood the question above, this should now be fixed by:
https://github.com/OP-TEE/optee_client/pull/274

And no we cannot fix Cryptoki interface size for `CK_ULONG` to be anything else than what applications expect them to be as @etienne-lms above mentioned.

**Comment by al1img** [comment]
I confirm that OP-TEE/optee_client#274 fixed the issue.
