### ISSUE TITLE
OpenSSL dependency run

### ISSUE THREAD

**Issue by rafagameiro** [OP-TEE/optee_os#4712]
Hi!

I'm trying to make use of the openSSL library to decrypt in my CA, some information I received from TA, in Secure World.
The library I used is this one, https://github.com/OP-TEE/optee_test/tree/master/host/openssl
, and currently my Makefile is this one:
![image](https://user-images.githubusercontent.com/48484516/123815925-ca226580-d8ee-11eb-9958-8bcde1642c1a.png)
and I'm using this directory displacement:
![image](https://user-images.githubusercontent.com/48484516/123816454-3f8e3600-d8ef-11eb-8e09-1f4ec9c2506f.png)

However, whenever I try to run the CA in OP-TEE I get the following message
![image](https://user-images.githubusercontent.com/48484516/123814290-7a8f6a00-d8ed-11eb-8a75-21bca65388be.png)
preventing me to run the CA.
Does anyone know if I missed something or might be doing something wrong?

Best Regards

**Comment by jforissier** [comment]
Hi @rafagameiro,

What makes you think the error is related to OpenSSL? That being said, the pre-compiled libraries in `optee_test/host/openssl/lib` were used for testing back when we didn't have Buildroot and I wouldn't recommend using them because there is no guarantee they are compatible with your target environment. How do you build your target root filesystem?

https://optee.readthedocs.io/en/latest/building/devices/qemu.html#qemu-v8

https://github.com/OP-TEE/optee_test/blob/3.13.0/host/xtest/CMakeLists.txt#L13-L17

**Comment by rafagameiro** [comment]
Hi!

I think its related because before I tried to include the openSSL files, it compiled and run perfectly well. But after I added the following error started showing up. In that case, should I just use the normal openSSL package, after installing it on my machine?

I don't know if it helps, but I'm currently using a RPI3 where I run the OP-TEE environment.
To build the CA I'm using the command:
`
 make \
    CROSS_COMPILE=aarch64-linux-gnu- \
    TEEC_EXPORT=<optee_client>/out/export/usr \
    --no-builtin-variables
`
