### ISSUE TITLE
aarch64-linux-gnu-gcc: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by JustAnotherArchetype** [OP-TEE/optee_os#4739]
I've been trying to get OP-TEE to work on WSL, but encountered  a strange problem, but forsome reason I keep getting the same error:

aarch64-linux-gnu-gcc: cannot execute binary file: Exec format error

Google search brought me to this issue: https://github.com/OP-TEE/build/issues/224, which unfortunately didn't  help due to uname -m returning x86_64. Does anybody  have any ideas on how to fix this? I am really confused.

**Comment by jforissier** [comment]
Hi @JustAnotherArchetype,

Are you building only `optee_os` or are you using a full environment from https://github.com/OP-TEE/manifest? The later should work out of the box, although I have never tried on WSL. Is it WSL1 or WSL2? WSL1 could quite possibly have limitations, not exposing a "true" and "complete" Linux environment.

Please try to build with `V=1` so that you can see the actual command and know for sure the full path to the cross compiler. If you see a path with directory components then you have it, if it is only `aarch64-linux-gnu-gcc` then you can use `which aarch64-linux-gnu-gcc` to get the full path. Then you may use the `file` and `ldd` commands to identify the file format and the shared libraries that it needs.

**Comment by JustAnotherArchetype** [comment]
Apparently, switching to WSL2 works in this case. I consider the issue closed, thanks for help, @jforissier!
