### ISSUE TITLE
OP-TEE TAs :some problems encountered when TA runs on rpi3

### ISSUE THREAD

**Issue by SyNgnath1** [OP-TEE/optee_os#4795]
When I try to write a TA implementation to decrypt encrypted data, I need to link the libcrypto.so dynamic library of OpenSSL. After the successful compilation, some problems are encountered when running on rpi3. The Ca and Ta session cannot be established. I don't know why.

D/TC:? 0 tee_ta_init_pseudo_ta_session:299 Lookup pseudo TA 6aaaf210-2450-11e4-b
D/TC:? 0 ldelf_load_ldelf:91 ldelf load address 0x40006000                      
D/LD:  ldelf:134 Loading TS 6aaaf210-2450-11e4-abe2-0002a5d5c51b                
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF 6aaaf210-2450-11e4-abe2-)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff0008                              
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF 6aaaf210-2450-11e4-abe2-)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0                                       
D/TC:? 0 ldelf_syscall_open_bin:142 Lookup user TA ELF 00000000-0000-0000-0000-)
D/TC:? 0 ldelf_syscall_open_bin:146 res=0xffff0000                              
E/LD:  init_elf:437 sys_open_ta_bin(00000000-0000-0000-0000-000000000000)       
E/TC:? 0 ldelf_init_with_ldelf:126 ldelf failed with res: 0xffff0000            
D/TC:? 0 tee_ta_open_session:718 init session failed 0xffff0000                 
optee_example_zxq_test: TEEC_Opensession failed with code 0xffff0000 origin 0x3

**Comment by jforissier** [comment]
Hi @SyNgnath1,

You can't use OpenSSL in a TA.

**Comment by SyNgnath1** [comment]
@jforissier thanks for your reply.If I want to implement some functions in Ta, which is need to use the library encapsulated by others.Is this method not allowed?

**Comment by jforissier** [comment]
@SyNgnath1 sorry for the short response -- I was interrupted and decided to send it anyways ;)

Libraries for TAs need to be compiled from source using the "TA dev kit" environment. You cannot used a shared library that is built for Linux (like the `libcrypto.so` you mentioned, I suppose).

For some simple libraries it is easy to do. For example libraries that have very few external dependencies (like, only C library functions which are provided in OP-TEE's `libutils`) can easily be recompiled for OP-TEE. For other libraries it is almost impossible due to dependencies on things that do not exist in OP-TEE such as POSIX files, pthreads or other external libraries. I think OpenSSL is one of them, probably not impossible to port but certainly not very easy. The secure side is a different environment compared to Linux, it is like comparing Linux and Windows, obviously you can't link a Windows application against a Linux library. Same goes for OP-TEE.

If you want to understand more about how to create a library for TAs, please check https://github.com/OP-TEE/optee_test/tree/master/ta/os_test (the TA) and https://github.com/OP-TEE/optee_test/tree/master/ta/os_test_lib (the shared library).

For crypto needs in your TA you should probably use the GlobalPlatform TEE Internal Core API instead. For things not supported by GP, you may use MBedTLS which is built as a static library by default when you build OP-TEE (`libmbedtls.a`). A rather simple example of how to use the GP API for AES is in https://github.com/linaro-swg/optee_examples/blob/master/aes/ta/aes_ta.c.
