### ISSUE TITLE
JSON Parser in TA

### ISSUE THREAD

**Issue by vinethak** [OP-TEE/optee_os#4851]
Hello,
I need to use a JSON parser in my TA. I have chosen cJSON parser which consists of a header and a source file.
The problem is that this parser uses C89 standard. The OPTEE & TA build uses C99 standard.
I am having following specific issues merging the cJSON library in TA-
1. The library needs math.h file which is not generated as part of the **export-user_ta/include** after building OPTEE OS.
2. If I provide the system math.h file, the compilation goes forward but the linker gives folloiwng issues-
**ta/cJSON/cJSON.c:145: undefined reference to `__ctype_tolower_loc'
ta/cJSON/cJSON.c:571: undefined reference to `__isoc99_sscanf'
ta/cJSON/cJSON.c:353: undefined reference to `strtod'**

I think the problems are due to the different C standards with cJSON and OPTEE.
Can you please suggest me how can one overcome this problem?
Do you have any suggestion for any other compatible JSON parser?

Many thanks.

**Comment by jenswi-linaro** [comment]
It should be noted that the only standardized environment for TAs is what's specified by GlobalPlatform TEE Internal Core API. However, we do follow other standards internally to make it easier to use third party libraries or code.
`libutils` which is the libc of OP-TEE only has a subset of a full fledged libc. Over the years we've added stuff when needed to support some third party library we're using (mbedTLS for instance).

The `__ctype_tolower_loc` error looks like a configuration error because we have the `tolower()` function in `<ctype.h>`. sscanf() and strtod() are missing in libutils. Do you need floating point support? Would it be possible to configure cJSON without support for floating point?

**Comment by vinethak** [comment]
I think you are right about the __ctype_tolower_loc(). I think this issue was there because I was trying to mix the libraries partly from the sdk of my board and partly from optee. 
I was able to use a dummy strtod() implemenation. I need float number for my application.
I have removed sscanf() from cJSON source. I think I would not need this at the moment.
