### ISSUE TITLE
How to solve "winscard.h is missing" when I was installing qemu optee on my ubantu?

### ISSUE THREAD

**Issue by EmbarrassedKing** [OP-TEE/optee_os#4853]
When I was compiling the qemu_v8.mk,  this error **"configure: error: winscard.h is required for pcsc"** always exist so that I can't compile qemu_optee, and I check the folder , the 'winscard.h' is exist. I really do not  know how to solve this problem. Thank you for telling me how to solve this problem please.

**Comment by etienne-lms** [comment]
Looks like a _libpcsclite-dev_ dependency. Check if `apt-get install libpcsclite-dev` fixes your issue.

**Comment by EmbarrassedKing** [comment]
>But I have installed 'libpcsclite-dev','libpcsclite1' and 'pcscd.' but it still didn't work. Do you know how to solve it?

**Comment by etienne-lms** [comment]
Sorry, no idea. On which package does build fail?

**Comment by andrade** [comment]
I was having the same error (`configure: error: winscard.h is required for pcsc`) in Ubuntu 24.04 with OP-TEE build 6ba8a37 when following the instructions at https://optee.readthedocs.io/en/latest/building/devices/qemu.html#qemu-v8.

I have `libpcsclite-dev` installed and `winscard.h` is available.

Turns out the problem were the latin characters in my directory name. Build fails at `~/pão/optee/` but works at `~/tmp/optee/`.
