### ISSUE TITLE
question about hardware crypto framework

### ISSUE THREAD

**Issue by onlinedj** [OP-TEE/optee_os#4889]
in optee crypto framework, all tee requests forward to "core/crypto" , it will call "core/driver/crypto/crypto_api/" to try to get a hardware context. 
I have 2 questions about the crypto:

hash & cipher has different way to do so in core/driver/crypto/crypto_api/, what's the intention or benefit? 
hash implements only a drvcrypt_hash_alloc_ctx api. ops implemented in vendor layer
cipher implements drvcrypt_cipher_alloc_ctx & all ops function.

acipher doesn't has such hardware ctx allocation and choose to implements same function as libtomcrypt 
which may lead conflicts. what's the design concern?

@cneveux can you help me on it? thanks in advance.

**Comment by cneveux** [comment]
> 
> 
> in optee crypto framework, all tee requests forward to "core/crypto" , it will call "core/driver/crypto/crypto_api/" to try to get a hardware context. I have 2 questions about the crypto:
> 
> hash & cipher has different way to do so in core/driver/crypto/crypto_api/, what's the intention or benefit? hash implements only a drvcrypt_hash_alloc_ctx api. ops implemented in vendor layer cipher implements drvcrypt_cipher_alloc_ctx & all ops function.
> 
The intention is to use a structure to pass argument to the cipher function. It simplifies the functions calls using one parameter and in addition if we would like to add (or unused) parameter it's simpler.

> acipher doesn't has such hardware ctx allocation and choose to implements same function as libtomcrypt which may lead conflicts. what's the design concern?
> 
acipher is for asymmetric cipher, there is no context to handle in case of asymmetric operation. Operation is one oneshot not multipart operation. Otherwise I don't understand the question "what's the design concern?". Acipher driver is already in place and working.

**Comment by onlinedj** [comment]
> > in optee crypto framework, all tee requests forward to "core/crypto" , it will call "core/driver/crypto/crypto_api/" to try to get a hardware context. I have 2 questions about the crypto:
> > hash & cipher has different way to do so in core/driver/crypto/crypto_api/, what's the intention or benefit? hash implements only a drvcrypt_hash_alloc_ctx api. ops implemented in vendor layer cipher implements drvcrypt_cipher_alloc_ctx & all ops function.
> 
> The intention is to use a structure to pass argument to the cipher function. It simplifies the functions calls using one parameter and in addition if we would like to add (or unused) parameter it's simpler.
> 
Got it, that makes sense.
> > acipher doesn't has such hardware ctx allocation and choose to implements same function as libtomcrypt which may lead conflicts. what's the design concern?
> 
> acipher is for asymmetric cipher, there is no context to handle in case of asymmetric operation. Operation is one oneshot not multipart operation. Otherwise I don't understand the question "what's the design concern?". Acipher driver is already in place and working.
I mean rsa is not good designed as hash alg. look the following code for example,
when try to cfg a hardware accelerator algrithm, you have to known the macro which disable libtomcrypt coresponding algrithm.
hash is good designed, hardware has higher priority, if drv exist, use it instead of tomcrypt.
ifeq ($(CFG_NXP_SE05X_RSA_DRV),y)
$(call force,CFG_CRYPTO_DRV_RSA,y)
CFG_CRYPTO_RSASSA_NA1 ?= y
_CFG_CORE_LTC_RSA = n
endif

**Comment by cneveux** [comment]
> I mean rsa is not good designed as hash alg. look the following code for example,
when try to cfg a hardware accelerator algrithm, you have to known the macro which disable libtomcrypt coresponding algrithm.
hash is good designed, hardware has higher priority, if drv exist, use it instead of tomcrypt.
ifeq ($(CFG_NXP_SE05X_RSA_DRV),y)
$(call force,CFG_CRYPTO_DRV_RSA,y)
CFG_CRYPTO_RSASSA_NA1 ?= y
_CFG_CORE_LTC_RSA = n
endif

Ah, ok I got your point.
The core implementation must be reworked in the same way than ECC driver to call a common function in core/crypto/crypto.c `crypto_acipher_XXX_rsa_YYY` and redesign a bit the RSA driver (same for DH, DSA, ...).

Then in case of CAAM driver the RSA tomcrypt flag `_CFG_CORE_LTC_RSA` don't need to be disabled. 
But I agree with you that if we want to use tomcrypt to do RSA operation not supported by a HW driver, current implementation doesn't allow it.

**Comment by onlinedj** [comment]
Appreciate your detailed explain of my questions, i will try to rework on it in my project.
Thanks for your help!

**Comment by cneveux** [comment]
@onlinedj
Could you submit the crypto enhancement thru OPTEE github PR process in order to initiate a process review and integrate it in to the database?

cc: @clementfaure
