### ISSUE TITLE
Open and Close session timing issue

### ISSUE THREAD

**Issue by ZheTing815** [OP-TEE/optee_os#4926]
Hi,

We encounter an issue on open/close session. In our situation, There are two session with TA0(S1 and S2).
In our TA0, we declare a pointer in TA_CreateEntryPoint() and free it in TA_DestroyEntryPoint().
S1 is opened finished, now the ctx->ref_count is one and the session is added to session list.
S2 is not finished. It only increase cts->ref_count but the session is not added to session list.
https://github.com/OP-TEE/optee_os/blob/6fd1b42843021e38bb526bcae0611ee120616c63/core/kernel/tee_ta_manager.c#L716-L749

In the same time, S1 is closed. OS decrease ctx->ref_count, now it is one. And removes session from session list then call uninit_instance because S2 is not added in session list.
https://github.com/OP-TEE/optee_os/blob/6fd1b42843021e38bb526bcae0611ee120616c63/lib/libutee/arch/arm/user_ta_entry.c#L232-L233
But OS will not destroy the context(line 562) because the ctx->ref_count is not zero.
https://github.com/OP-TEE/optee_os/blob/6fd1b42843021e38bb526bcae0611ee120616c63/core/kernel/tee_ta_manager.c#L545-L564

After S1 is closed,the S2 is added to session list.
So, some one invoke command with S2, will access null pointer, but it has been released when S1 is closed. 

I think that these problem is because open/close session will increase context refcount in kernel space and add session in list in user space. But these two actions are not atomic.

Do you have any suggestion in our case?

**Comment by jenswi-linaro** [comment]
I I understand this correctly there's a race.
1. S1 has been opened and TA0 notified it has a new session.
2. S2 has been opened and waits to notify TA0 of a new session. 
3. S1 is closed and TA0 is notified that the session is gone.
4. Since TA0 isn't aware of any more sessions it believes that it's about to be destroyed.
5. S2 is finally able to notify TA0 of a new session, while TA0 instead believed it was to be destroyed.

Does this happen all the time or only occasionally? I mean would it be possible to create a solid test case based on your pattern?

It seems that we need to keep track of how many thread are waiting to notify a TA of a new session. Before notifying the TA of a closed session we must make sure that all open session notifications has been delivered. Sadly this will make the logic in `tee_ta_set_busy()` and friends even more complicated.

**Comment by ZheTing815** [comment]
> I I understand this correctly there's a race.
> 
> 1. S1 has been opened and TA0 notified it has a new session.
> 2. S2 has been opened and waits to notify TA0 of a new session.
> 3. S1 is closed and TA0 is notified that the session is gone.
> 4. Since TA0 isn't aware of any more sessions it believes that it's about to be destroyed.
> 5. S2 is finally able to notify TA0 of a new session, while TA0 instead believed it was to be destroyed.
> 
> Does this happen all the time or only occasionally? I mean would it be possible to create a solid test case based on your pattern?
> 
> It seems that we need to keep track of how many thread are waiting to notify a TA of a new session. Before notifying the TA of a closed session we must make sure that all open session notifications has been delivered. Sadly this will make the logic in `tee_ta_set_busy()` and friends even more complicated.

**Comment by ZheTing815** [comment]
I think that if there are two application open and close to a TA, it can be reporduced.
It may happen at times depends on system schedule when TA is single instance and not keep alive.

**Comment by jenswi-linaro** [comment]
It might be worth a shot to try to create a test case. It doesn't have to be 100%. The reason why we'd like to have a test case is that this synchronization where we have the problem is quite complicated already. So it would help a lot in making sure that the error is well understood and also that it isn't reintroduced later after the fix is in place.
