### ISSUE TITLE
Running two or more TA simultaneously ?

### ISSUE THREAD

**Issue by louisyang1977** [OP-TEE/optee_os#496]
Hi,
We have use case to run two or more TA simultaneously.
In the Q&A, it said this will support this feature on 2015, does optee os support this feature now ??
If it doesn't, when will we have this feature??

Thanks !!

**Comment by jbech-linaro** [comment]
Hi @louisyang1977 , we still have this in the pipe and some work has been done (see [this](https://github.com/jenswi-linaro/optee_os/commits/concurrent_ta) branch). However, other activities have higher priority for the moment so the multi core TA work is currently pending. My best guess is maybe at the end of this year. I would like to give a better estimation, but since none is working with it right now it could slip. If you need it sooner, then feel free to implement a proposal. If this is something you would consider doing, then we should probably sync up first, so it is somewhat in line with our ideas.

// Joakim

**Comment by louisyang1977** [comment]
Hi jbech,
We don't have plan to implement this feature right now.
I will check at the end of this year to see the better estimation.
If we plan to do it, we will sync you up first.

Thanks for your feedback !!

**Comment by jbech-optee-adm** [comment]
Hi again @louisyang1977 , the patch set you're looking for has been merged, see [here](https://github.com/OP-TEE/optee_os/commit/888cc4826f68ec5920b5b512e5483fb4299cbd80) and therefore I'll close this issue. Please feel free to re-open it again in case you have more questions about it.

// Joakim

**Comment by louisyang1977** [comment]
Hi @jbech-optee-adm :
Thanks for your quickly response, it's good news for us, we will enable this function in our project.
If we encounter the problem, we will let you know or even re-open.

Thanks again !!
