### ISSUE TITLE
[Question] Minimalist build / core

### ISSUE THREAD

**Issue by maroueneboubakri** [OP-TEE/optee_os#4998]
Dear team, 

I was wondering, if there is any way letting building a very minimalist OP-TEE core, without components that I really don't want. For example, disabling crypto still makes building crypto related sources.
```
/core/crypto/rng_fortuna.o
core/crypto/rng_fortuna.c:14:10: fatal error: kernel/spinlock.h: No such file or directory
```
What I want to have is just building a dummy kernel file for another architecture which does nothing.

Is there any way to do that ?

Regards
Maro

**Comment by jforissier** [comment]
Hello @maroueneboubakri,

It is true that some files may be compiled although they are not needed. In the end it doesn't matter much because unused symbols are eliminated at link time (`-ffunction-sections -fdata-sections` / `--gc-sections`). That being said, I'm sure some `CFG_*` are missing in some places, such as `srcs-y += foo.c` should be `srcs-$(CFG_FOO) += foo.c` and things like that. If you find such occurrences please feel free to propose patches.

Regarding the example you give: `rng_fortuna.o` should not be built if `CFG_WITH_SOFTWARE_PRNG != y`.

**Comment by maroueneboubakri** [comment]
Hi @jforissier,

Thank you for the quick reply. 

The issue is more at build time not in the generated tee core file and if it embeds unused symbols or not.

Maybe `rng_fortuna.c` was not the best example. Let's consider `console.c` which has some important dependencies.  `kernel/thread.h`, `mm/core_mmu.h`, `kernel/boot.h` and much more. 

We made few trials towards having an easier review process, but the task seems complicated, meaning that one needs to manage many source files to be able to build a dummy core. Was hoping that there is a quicker way. We will try to propose some patchs though.

Thanks again, I close this for now.
Maro
