### ISSUE TITLE
S-EL2 vs. OPTEE

### ISSUE THREAD

**Issue by huhrenfeldt** [OP-TEE/optee_os#5055]
I wonder if an up-to-date reference exists implementing OPTEE on top of an S-EL2 secure partition manager as outlined in https://linaro.atlassian.net/browse/TS-100?

A PoC exists here: https://github.com/arugan02/manifest/blob/sel2_spmc/fvp.xml, but it hasn't been updated for some time....

Can anyone shed some light?

Best regards,
Henrik

**Comment by jenswi-linaro** [comment]
I expect that upstream OP-TEE is pretty close to what you need. But the problem is to get all the other components in place. Last time (around the time of that prototype, but not with that prototype) I tried it I had stability issues with Hafnium on FVP that was supposed to be fixed by some DT patch for the PSCI node, but I never got it to work as intended.

The FF-A patches for the OP-TEE driver in the Linux kernel will be available in the next kernel release. So we now have a good opportunity to put together a new setup the may not even need to be a prototype, but based on upstream. However, I can't spare the time to do that at the moment.
