### ISSUE TITLE
Explanations for performance overhead

### ISSUE THREAD

**Issue by krstn42** [OP-TEE/optee_os#5082]
Dear OP-TEE maintainers,

do you have any pointers or know of any papers regarding the performance overhead of using OP-TEE, especially concerning different cryptographic operations? Are there any specific reasons for operations inside trusted applications being slower?

I have modified and compiled the [mbed TLS benchmark](https://github.com/ARMmbed/mbedtls/blob/development/programs/test/benchmark.c) for the "normal world" and for use inside an OP-TEE trusted application and noticed that operations inside the trusted application seem to generally be a lot slower and that this also appears to vary a lot depending on the specific operation/algorithms used.

For example, running the mbed TLS benchmark on an i.MX 7Dual SABRE Board results in the majority of tests being approximately 2-5 times as slow inside the TA, but some tests are slowed down a lot more (more than 50 times as slow). You can find a comparison of results in [this Gist](https://gist.github.com/krstn42/202e6c300962b7490db8318649df9cd3). As you can see, the results differ a lot depending on the algorithms/elliptic curves/key sizes used.

Do you have any pointers for possible explanations and/or any suggestions on how this overhead could be reduced? Thanks in advance!

**Comment by jenswi-linaro** [comment]
This question has popped up from time to time, but we have never been able to find the root of the problem. I suspect that there might be more than one root cause. The figures are quite interesting. Did you use the same optimization options when compiling in both cases?

I would very much like to understand and minimize this performance problem. Do we have the same problem when executing in AArch64 on some ARMv8 platform? It would be a good start to be able to rule out the __aeabi functions used in ARMv7/AArch32.
