### ISSUE TITLE
Unknown relocation type 7

### ISSUE THREAD

**Issue by Hussain1811** [OP-TEE/optee_os#5088]
I have a library within my TA folder in the test-code structure
Then i have a TA which links to this shared library.
Finally, I invoke this TA via some test

But i get the following error:
```
I/TC: >tee_entry_std  0x32000004
I/TC: arg->cmd 0x0
D/TC:? 0 tee_ta_init_pseudo_ta_session:288 Lookup pseudo TA cbcf9c6c-a65c-4f2e-ba23-f75970de5d30
D/TC:? 0 load_elf:833 Lookup user TA ELF cbcf9c6c-a65c-4f2e-ba23-f75970de5d30 (Secure Storage TA)
D/TC:? 0 load_elf:833 Lookup user TA ELF cbcf9c6c-a65c-4f2e-ba23-f75970de5d30 (REE)
D/TC:? 0 load_elf_from_store:802 ELF load address 0x7fc0003000
D/TC:? 0 tee_ta_init_user_ta_session:930 Processing relocations in cbcf9c6c-a65c-4f2e-ba23-f75970de5d30
E/TC:? 0 e64_process_rel:491 Unknown relocation type 7
D/TC:? 0 tee_ta_open_session:542 init session failed 0xffff0005
```

Actually i am using an x86 based OPTEE. So, i am wondering if this is a x86 OPTEE kernel issue.
i have also seen https://github.com/OP-TEE/optee_os/issues/1399 which seems to be related to what i am facing.

Am i missing something here?

**Comment by jforissier** [comment]
Hello @Hussain1811,

> `E/TC:? 0 e64_process_rel:491 Unknown relocation type 7`
>
> Actually i am using an x86 based OPTEE. So, i am wondering if this is a x86 OPTEE kernel issue.

Yes it seems to be an issue with the implementation of your TA loader (ldelf). Relocation type 7 is `R_386_JMP_SLOT` which seems to be equivalent to [this case](https://github.com/OP-TEE/optee_os/blob/[master](https://github.com/OP-TEE/optee_os/blob/3.15.0/ldelf/ta_elf_rel.c#L369)/ldelf/ta_elf_rel.c#L369) (for Aarch32) or [this case](https://github.com/OP-TEE/optee_os/blob/3.15.0/ldelf/ta_elf_rel.c#L590) (for Aarch64). Unfortunately since x86 is not upstream I can't provide a fix or give more details, but hopefully you should be able to figure out a solution based on the Arm code.

**Comment by Hussain1811** [comment]
Thanks a lot for the pointer @jforissier 
Shall look into it
