### ISSUE TITLE
Xilinx Zynq MPSoC does not boot anymore with new DDR configurations

### ISSUE THREAD

**Issue by vesajaaskelainen** [OP-TEE/optee_os#5144]
Using latest versions Xilinx ZCU102 devkit (nor our own board) does not boot.

During the boot gives following error on trace:
```
E/TC:0 0 std_smc_entry:183 Bad arg address 0x803989000
```

Seems that this commit causes the issue -- if we revert this then zcu102 once again boots:
[a7474d1](https://github.com/OP-TEE/optee_os/commit/a7474d1d0b780fc4f8a93883ae3f21320b155998) - plat: zynqmp: register ddr for dyn shm support

Xilinx Zynq MPSoC does have two DDR bases:
- First 2 GiB of DRAM (DDR Low): 0x0000_0000 .. 0x8000_0000
- And then rest of memory (DDR High):  0x0008_0000_0000 .. 0x000F_FFFF_FFFF

Real memory size is either detected from DDR DIMM or hard coded in device tree. There could also be aliasing so perhaps the right course of action would be to get this detail from device tree assuming previous stages has detected the memory size or has fixed size.

**Comment by ricardosalveti** [comment]
How much memory do you have in your devkit? The board I test with has 2GB, which is enough for the hardcoded values, and enough for dyn shm to work (optee needs to register the entire memory region otherwise with dyn shm the kernel might use a region that is unknown to optee and cause the error you're getting).

**Comment by vesajaaskelainen** [comment]
On this ZCU102 where we did testing it had 4 GiB of memory.

**Comment by ricardosalveti** [comment]
OP-TEE can also identify based on what gets provided by the device tree, can you check if the one given to optee also contain the 4GBs described there?

**Comment by vesajaaskelainen** [comment]
Our current bootflow is:
FSBL->ATF->OP-TEE->u-boot...

And currently we do not have device tree in Xilinx image blob containing ATF. We will see what effect adding device tree to the Xilinx image blob has.

**Comment by ricardosalveti** [comment]
Without dtb I think it worked before for you because optee was probably disabling dyn_shm. If you build with CFG_CORE_DYN_SHM=n you should get it to boot with latest rev.

To fix this properly (and enable dyn_shm) you can either provide a dtb or extend plat-zynqmp/main.c to register DRAM1_BASE (via another CFG), as done with other targets, e.g.:

```
core/arch/arm/plat-stm/main.c:register_ddr(DRAM0_BASE, DRAM0_SIZE);
core/arch/arm/plat-stm/main.c:register_ddr(DRAM1_BASE, DRAM1_SIZE);
```

**Comment by vesajaaskelainen** [comment]
Made a deluxe version of that :grin: -- see the PR
