### ISSUE TITLE
openssl pkeyutl -decrypt failure

### ISSUE THREAD

**Issue by fhsuman** [OP-TEE/optee_os#5219]
Created a RSA key using pkcs11-tool and tried to encrypt and decrypt a symmetric key using openssl, but it always fails to decrypt the key

$ pkcs11-tool --module /lib/libckteec.so --init-token --label token_slot0 --slot 0 --so-pin 1234  // initialize the token on slot 0
$ pkcs11-tool --module /lib/libckteec.so --label token_slot0 --slot 0 --so-pin 1234 --login --init-pin --pin ABCD // set user pin

$ pkcs11-tool --module /lib/libckteec.so --token-label token_slot0 --slot 0 --pin ABCD --keypairgen --usage-decrypt --usage-sign --key-type RSA:2048 --id 1 --label rsa-key  // created the RSA key

// Encrypt the key in /data/plain.key
$ openssl pkeyutl -engine pkcs11 -keyform engine -encrypt -pubin -inkey "pkcs11:token=token_slot0;object=rsa-key;type=public;pin-value=ABCD" -pkeyopt rsa_padding_mode:oaep -in /data/plain.key -out /data/encrypted.key

// Decrypt the key in /data/encrypted.key
$ openssl pkeyutl -engine pkcs11 -keyform engine -decrypt -inkey "pkcs11:token=token_slot0;object=rsa-key;type=private;pin-value=ABCD" -pkeyopt rsa_padding_mode:oaep -in /data/encrypted.key -out /data/dec.key
Public Key operation error
4159504400:error:82079070:PKCS#11 module:pkcs11_private_decrypt:Mechanism invalid:p11_rsa.c:150:

The question is, can we not use the private portion of RSA key to decrypt the contents?

**Comment by ruchi393** [comment]
@fhsuman , it seems like the issue is with the mechanism you are using. At my end I removed the option -pkeyopt rsa_padding_mode:oaep in the command above. Encryption with public key and decryption works fine for me.

openssl pkeyutl -engine pkcs11 -keyform engine -encrypt -pubin -inkey "pkcs11:
token=token_slot0;object=rsa-key;type=public;pin-value=ABCD" -in /data/plain.key
 -out /data/encrypted.key
engine "pkcs11" set.
# openssl pkeyutl -engine pkcs11 -keyform engine -decrypt -inkey "pkcs11:token=t
oken_slot0;object=rsa-key;type=private;pin-value=ABCD" -in /data/encrypted.key -
out /data/dec.key
engine "pkcs11" set.

**Comment by etienne-lms** [comment]
Encrypting data with an RSA public and decrypting with a private key is a valid use.
I'm surprised you get a "Public Key operation error" error trace on an operation that involves the private key.
Do you get any error traces from the pkcs11 TA itself?  (build it with `CFG_TEE_TA_LOG_LEVEL=3`).
