### ISSUE TITLE
kernel5.10 optee_shutdown

### ISSUE THREAD

**Issue by klcib508** [OP-TEE/optee_os#5221]
for android device ,tee-supplicant will be killed first  when device reboot/shutdown,then kernel drivers shutdown ,optee_driver goto optee_shutdown->optee->rpc,than the device will hang.any goog idea for this Question?]

kernel add optee_shutdown on
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/drivers/tee/optee/core.c?h=v5.10.105&id=2a879ff9719fdb75bdedfca029a381105aea6d72

**Comment by jenswi-linaro** [comment]
This is better discussed at the mailing lists. By the way, there is already a fix in stable for that commit.

**Comment by klcib508** [comment]
@jenswi-linaro  thanks for your quick reply. but I  still don't sure how to solve this problem

**Comment by jenswi-linaro** [comment]
This may relate to your issue https://lists.trustedfirmware.org/archives/list/op-tee@lists.trustedfirmware.org/thread/DJDGN3HLV5J53QSNTQWGY3R42QIDFREK/

**Comment by klcib508** [comment]
thank you，this patch patch is I need

**Comment by jenswi-linaro** [comment]
Please note that that patch isn't upstream. If it helps in your case please reply on the list to get more attention to that patch or it may never reach upstream.

**Comment by ZheTing815** [comment]
HI @jenswi-linaro 

We also meet this problem. It can easy reproduce this issue when running "xtest 1010" and  immediately "reboot".
It will hang. Maybe the reason is that thread is not free. We print log here https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/kernel/thread_optee_smc.c#L314. It will print only once.

We also apply this patch https://lists.trustedfirmware.org/archives/list/op-tee@lists.trustedfirmware.org/thread/DJDGN3HLV5J53QSNTQWGY3R42QIDFREK/, but it seems not work.

Do you have any other suggestions?

Thanks!

**Comment by jenswi-linaro** [comment]
I'm not sure this is the same problem to be honest.

**Comment by lxxstone** [comment]
Hi @ZheTing815 @jenswi-linaro ，
We have  also meet this when we reboot while doing optee_open_session. It looks like optee_shutdown needs to do more, such as optee_supp_release to abort all queued reuests.
