### ISSUE TITLE
Random failures in xtest 2002.1 (Xen)

### ISSUE THREAD

**Issue by jforissier** [OP-TEE/optee_os#5288]
The CI job "Run regression tests (xtest) in QEMUv8" fails from time to time in the Xen part of the run. For example: https://dev.azure.com/OPTEE/optee_os/_build/results?buildId=2827&view=logs&j=705748f3-7146-5e86-79af-1c0266d20a8c&t=d3458a7d-1a81-5639-8e63-8927d807e53a&l=7812.

**Comment by jenswi-linaro** [comment]
I'll take a closer look.

**Comment by jenswi-linaro** [comment]
I've been running this locally now a few time without any error.
Could it be something with the environment. Perhaps I should try it in one of the containers. Can you help me with instructions on how to do that?

**Comment by jforissier** [comment]
You can run the CI image like so:
```
$ docker run -it jforissier/optee_os_ci:qemuv8_check 
# cd $SHOME/optee_repo_qemu_v8/build
# make -j$(nproc) CFG_TEE_CORE_LOG_LEVEL=0 check XEN_BOOT=y
```
That will not be the exact same environment as the Azure build though but hopefully close enough... (for example Azure sets some environments variables and [it has bitten us in the past](https://github.com/OP-TEE/optee_os/blob/3.17.0/.azure-pipelines.yml#L239-L241)).

**Comment by jenswi-linaro** [comment]
It seems to be an error in normal world, possibly the hypervisor. I'm investigating further.

**Comment by jenswi-linaro** [comment]
I think I've found the root cause. It seems there's a window after a cookie for an shm has been freed in the kernel but before it's unregistered in Xen. This means that another core can by chance allocate a new shm with the same cookie and try to register it before Xen has freed it. If this happens then the registration will fail and OP-TEE will see it as a failed RPC allocate.

I'll try to change so Xen unregisters before the kernel to close that window, but there may have been a reason why it was done in this way from the beginning. We'll see. By the way, @lorc does this ring any bells?

**Comment by lorc** [comment]
Well, I'll take a deeper look later. But I believe, I have faced very similar issue and upstreamed a fix.

Which version of Xen are you using?

**Comment by jforissier** [comment]
> Which version of Xen are you using?

4.14.3 from Buildroot 2021.11.

**Comment by jenswi-linaro** [comment]
I have something that seems to work here https://github.com/jenswi-linaro/xen/tree/optee-shm-fix

**Comment by jenswi-linaro** [comment]
Thank you @lorc.
