### ISSUE TITLE
Cross compiling an executable with optee client libraries for QEMU OP-TEE

### ISSUE THREAD

**Issue by verd1c** [OP-TEE/optee_os#5376]
I have successfully set up my QEMU OP-TEE environment, and can run all the pre-existing executables by following the [instructions](https://optee.readthedocs.io/en/latest/building/devices/qemu.html). However, I am specifically trying to get the following [project ](https://github.com/mofanv/PPFL) running under the QEMU OP-TEE environment and thus I have to build it. Since the OP-TEE QEMU build uses buildroot as a filesystem, I can not compile it on the guest system that has all the libraries that are needed (teec, etc.) since buildroot does not come with a compiler and is not intended to have one in the first place.

Since I can't compile on guest, I tried cross compiling on host using the toolchain ARM compiler. However, my issue is that on my host I am missing all the required headers (tee_client_api.h) and libraries (teec) that are only present in the guest. One of the errors I am getting is:

```/home/user/toolchains/aarch64/bin/../lib/gcc/aarch64-none-linux-gnu/10.2.1/../../../../aarch64-none-linux-gnu/bin/ld: cannot find -lteec```

How should I go ahead in doing this? 

Thanks

**Comment by jforissier** [comment]
Hi @verd1c,

In order to build your project in the OP-TEE QEMU environment, I think the best option is to create a Buildroot external package similar to `optee_example`. See in particular the following in the `build/` directory:
- `br-ext/Config.in`
- `br-ext/package/optee_examples_ext/*`
- `git grep OPTEE_EXAMPLES_EXT`

You could for instance copy everything from `optee_examples`, change 'example' for 'pplf' everywhere, and adjust as needed to build the code in the PPFL top-level checkout.

That being said, maybe you can find some more documentation and/or help in the PPFL project?

**Comment by verd1c** [comment]
Thanks, worked perfectly.
