### ISSUE TITLE
STM32MP1 Hardware Unique Key (follow up for #5448)

### ISSUE THREAD

**Issue by ldts** [OP-TEE/optee_os#5554]
justa follow up of  #5448 (I cant re-open it)
@etienne-lms do you plan to propose your HUK driver?

**Comment by mstjohns** [comment]
On the STM32MP13x series, the way to do this is via the DHUK/BHK functionality of the SAES unit as the DHUK is derived off of an RHUK which ST writes into OTP at chip manufacture.    The STM32MP15x series lacks that peripheral.    Keep that in mind when proposing an approach labeled for STM32MP1.  

For the MP15x, generating a seed could be done as part of the first boot of the signed TF-A once the part is closed, rather than requiring it to be done as part of TFA-SSP process.    What I'd suggest is to generate a 32byte or longer seed value and write that to OTP. Then have TF-A use that as the master secret for a couple of KDF calls - one of which would be a HUK which would then be retained in SYSRAM through the next reset.  The OTP shadow registers should be cleared after the KDFs are run, and the 4 words of OTP marked as not-reloadable.  That will prevent retrieving the seed value from trusted applications.

**Comment by ldts** [comment]
> On the STM32MP13x series, the way to do this is via the DHUK/BHK functionality of the SAES unit as the DHUK is derived off of an RHUK which ST writes into OTP at chip manufacture.    The STM32MP15x series lacks that peripheral.    Keep that in mind when proposing an approach labeled for STM32MP1.  
> 
> 
> 
> For the MP15x, generating a seed could be done as part of the first boot of the signed TF-A once the part is closed, rather than requiring it to be done as part of TFA-SSP process.    What I'd suggest is to generate a 32byte or longer seed value and write that to OTP. Then have TF-A use that as the master secret for a couple of KDF calls - one of which would be a HUK which would then be retained in SYSRAM through the next reset.  The OTP shadow registers should be cleared after the KDFs are run, and the 4 words of OTP marked as not-reloadable.  That will prevent retrieving the seed value from trusted applications.
> 
> 

Would you mind help reviewing #5555. I am certainly not aware of all variants so your contribution is welcomed.
