### ISSUE TITLE
TEE_AEDecryptFinal panics when destData/destLen is NULL

### ISSUE THREAD

**Issue by hoiho-amzn** [OP-TEE/optee_os#5683]
In the GPD Internal Core API specification, it says:

> `destData`, `destLen`: Output buffer. Can be omitted if the output is to be discarded, e.g. because it is known to be empty.

However when I tried to call `TEE_AEDecryptFinal` with `destData` and `destLen` as `NULL`, it panics. Is this a known bug?

**Comment by jforissier** [comment]
Hi @hoiho-amzn, no it is not an know issue. And we don't seem to have a test for that in `xtest`. Patches welcome :)

**Comment by hoiho-amzn** [comment]
Ack - will try to submit a PR.

**Comment by matlimatli** [comment]
It seems like the title of this issue is wrong. I'm assuming that you refer to **TAA_AEEncryptFinal**, which exhibits this behavior and has the destData marked as outbufopt in the spec, which is not the case for TAA_AEDecryptFinal.

I also noticed that it is actually mentioned in https://github.com/OP-TEE/optee_os/pull/5688 
> TEE_AEEncryptFinal(), OP-TEE doesn't treat destData as optional, this should be fixed.

**Comment by hoiho-amzn** [comment]
The title is right - I am referring to `TEE_AEDecryptFinal`. Both the v1.2.1 and v1.3.1 spec say the same about `destData` and `destLen`:

> Can be omitted if the output is to be discarded, e.g. because it is known to be empty.

**Comment by matlimatli** [comment]
Ah, sorry, you are right. (The difference is that for `TEE_AEEncryptFinal`, the parameter  is `[outbufopt]`, while for `TEE_AEDecryptFinal` it is `[outbuf]`.)
