### ISSUE TITLE
Questions about shared memory between worlds

### ISSUE THREAD

**Issue by SangsubLim** [OP-TEE/optee_os#5741]
Hello,
I am inquiring about the data sharing method between CA and TA.

In order to share data between worlds, the following methods seem to exist.

1) TEEC_RegisterSharedMemory
```
TEEC_SharedMemory shm = { };
shm.flags = TEEC_MEM_INPUT | TEEC_MEM_OUTPUT;
shm.buffer = buffer; // Buffer in use by application
shm.size = 1024;
TEEC_RegisterSharedMemory(&ctx, &shm)))
op.paramTypes = (uint32_t)TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INOUT, NONE, TEEC_NONE, TEEC_NONE);
op.params[0].memref.parent = shm;
op.params[0].memref.size = 1024;
op.params[0].memref.offset = 0;

TEEC_InvokeCommand(&sess, cmd, &op, &err_origin);
```

2) TEEC_AllocateSharedMemory
```
TEEC_SharedMemory shm = { };
shm.size = 1024;
shm.flags = TEEC_MEM_INPUT | TEEC_MEM_OUTPUT;
TEEC_AllocateSharedMemory(&ctx, &shm))

op.paramTypes = (uint32_t)TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INOUT, NONE, TEEC_NONE, TEEC_NONE);
op.params[0].memref.parent = shm;
op.params[0].memref.size = 1024;
op.params[0].memref.offset = 0;
TEEC_InvokeCommand(&sess, cmd, &op, &err_origin);
```

3) temp memory?
```
paramTypes = (uint32_t)TEEC_PARAM_TYPES(TEEC_MEMREF_TEMP_INOUT, NONE, TEEC_NONE, TEEC_NONE);
op.params[0].tmpref.buffer = (void*)buffer; // Buffer in use by application
op.params[0].tmpref.size   = 1024;
TEEC_InvokeCommand(&sess, cmd, &op, &err_origin);
```

1) is to use the buffer used by the application,
2) allocates a buffer within the TEEC.
3) Use without calling TEEC function for shared mem.
 
I know the difference between 1 and 2.
But I wonder what the difference is between 3 and 1.
And all three methods above know that shared memory is mapped in TEE (secure OS?) at the time of invocation. What's the difference in performance?

What I'm developing is roughly like this.
My CA receives requests from several services.
The request requires world shared memory of at least 2KB and at most 10MB depending on the situation.
As far as I know, the maximum size of shared memory is related to the TA heap size. is that right? 

If the data size to be sent to TA is large, I will try to send it in units of 1MB and then receive an intermediate processing value.
I saw that there seemed to be a question similar to my situation, but I have a question.
 - https://github.com/OP-TEE/optee_os/issues/2285

Is there such a thing as static shared memory?
As far as I understand this article, memory alloc for a large buffer, and register it as world shared memory using the TEEC_RegisterSharedMemory function.
After that, it seems to call invoke by adjusting the size or offset of op params after copying the data from the service to the buffer.

In my case, there is only one CA, so only one session is being created.
The purpose is to solve the performance problem when the size of data coming from various services is different.

I know that memory mapping takes place in TEE (optee-os?) when invoke command is called. If invoke for large-size shared mem is called frequently, system overhead is likely to occur.

So, I thought that if static shared memory was used in the link above, mapping would be performed only once and would have a performance advantage.

Just a simple idea, I thought that if the invoke requesting 1MB of shared mem is continuously called in the worst case, it would be faster to copy the data received from the service to the static shared buffer rather than the overhead of memory mapping each time. Please let me know if there is something I am thinking wrong.

As a final question, how is memory sharing between worlds internally performed?
Looking at the link below, it seems to be using the DMA method.
 - https://optee.readthedocs.io/en/latest/architecture/core.html#shared-memory-chunk-allocation

That means optee-os maps the buffer physical address received from the normal world, I understand. Am I right?

**Comment by jenswi-linaro** [comment]
> I know the difference between 1 and 2.
> But I wonder what the difference is between 3 and 1.

It's more of a convenience thing when you're only using the buffer a few times or where you're not overly concerned with performance.

> And all three methods above know that shared memory is mapped in TEE (secure OS?) at the time of invocation. What's the difference in performance?

3 will register the memory before doing invoke and then unregister the memory after the invoke, so there's some overhead with additional round trips to the secure world.

> The request requires world shared memory of at least 2KB and at most 10MB depending on the situation.
As far as I know, the maximum size of shared memory is related to the TA heap size. is that right?

No, it's independent from the TA heap size. It's limited by how many translation tables are set aside for mapping TAs (`PGT_CACHE_SIZE`).

> Is there such a thing as static shared memory?

Yes, but it's not likely to have a noticeable impact on performance since it's mapped for TAs in a similar manner.

> I know that memory mapping takes place in TEE (optee-os?) when invoke command is called. If invoke for large-size shared mem is called frequently, system overhead is likely to occur.

Have you measured a noticeable overhead or is this speculation?

> So, I thought that if static shared memory was used in the link above, mapping would be performed only once and would have a performance advantage.

That wouldn't help here. Static shared memory is just a fixed carveout of physical memory used as shared memory. TAs are still only able to access memory as indicated in the invoke command.


> As a final question, how is memory sharing between worlds internally performed? Looking at the link below, it seems to be using the DMA method.
> 
> * https://optee.readthedocs.io/en/latest/architecture/core.html#shared-memory-chunk-allocation
> 
> That means optee-os maps the buffer physical address received from the normal world, I understand. Am I right?

There's no DMA involved. Nonsecure memory is mapped as non-secure physical memory by OP-TEE, quite similar to how two processes in Linux user space might share a chunk of shared memory. So memory caches are also used to avoid memory coherency issues. However, if the memory would have been mapped as secure memory there would be coherency issues since entries in caches would be tagged differently.
