### ISSUE TITLE
Bad Linux ARM64 Image magic! on Raspberry Pi 3 

### ISSUE THREAD

**Issue by joke2512** [OP-TEE/optee_os#5891]
Hey! 
I'm getting an error when booting a Raspberry pi 3 saying `Bad Linux ARM64 Image magic!`.

I followed the build instructions in the [documentation](https://optee.readthedocs.io/en/latest/building/devices/rpi3.html#build-instructions) and everything seems to be working, but when reaching step 5 after running `picocom -b 115200 /dev/ttyUSB0` the Pi gives the `Bad Linux ARM64 Image magic!` error and is stuck in the U-Boot interface. 

I've attached the output of the boot sequence here:
[dump.txt](https://github.com/OP-TEE/optee_os/files/10981030/dump.txt)

Can anyone help me figure out what is happening and why?
Cheers!

**Comment by jbech-linaro** [comment]
Never seen that before on the  RPi3 and I've been the one that most often verifies this when doing releases. It did work as [expected during the 3.20 release earlier this year](https://github.com/OP-TEE/optee_os/pull/5751#issuecomment-1377274813). However, I think I've seen similar issues elsewhere and in those cases it's been when trying to run 32 bit binaries on 64 bit system. Having said, that I don't know how that will happen in our build, IIRC we build only 64 bit code for it. I know there are other unofficial guides for OP-TEE out there, that leverage the 32-bit Raspian, but since you refer to our instructions that shouldn't be the issue. If not sooner I'll check it again for the 3.21 [release that will take place April 14th](https://optee.readthedocs.io/en/latest/general/releases.html).

**Comment by joke2512** [comment]
Hey thanks for the reply, we got it working with the 3.20 release!

**Comment by jbech-linaro** [comment]
Re-opening the issue, since we need to fix this sooner or later. As already indicated, I'm onto this as we're speaking. What I've seen so far is that the Image and kernel8.img gets corrupted or so during/later in the build process. If I manually copy the kernel image (Image) to kernel8.img on the SD card, then it boots up as it should. But I'll refer to this ticket for this particular issue.

**Comment by jbech-linaro** [comment]
With this:
```
+-----------------------------------------------------
27040 subtests of which 0 failed
104 test cases of which 0 failed
0 test cases were skipped
TEE test application done!
```
