### ISSUE TITLE
Can anyone provides an optee version that can use the benchmark tool?

### ISSUE THREAD

**Issue by Xisaname** [OP-TEE/optee_os#5909]
I have installed the latest optee version and everything is fine when I run `xtest -l 15` which means I pass all the test.
**But** when I wanted to use benchmark tools, it throws error like :
```
[Benchmark] ERROR: TEEC_InvokeCommand: 0xffff000c

alloc_benchmark_buffer:72 Benchmark: can't create mobj for timestamp buffer
```
so I followed the official OP-TEE documentation in https://optee.readthedocs.io/building/gits/optee_benchmark.html. I installed [optee-3.15.0](https://github.com/linaro-swg/linux/commits/optee-3.15.0) and I set `CFG_TEE_BENCHMARK = y` in `build/common.mk`.

I pass the build process but got the same error when I run the command: 
```
benchmark ../usr/bin/optee_example_hello_world
```

So I wonder if there are any other optee version that can use benchmark tool?

Thanks!

**Comment by etienne-lms** [comment]
OP-TEE benchmark requires kernel patches that were not maintained since OP-TEE 3.16.0. Latest patches available based on Linux v5.14 : https://github.com/linaro-swg/linux/commit/527d88b5e5c88f1be35a38554a71f949d7f5d266 and https://github.com/linaro-swg/linux/commit/ae76d86c64628a99c2137dd39a922c658402ccfb. Restoring the feature with recent kernels can be tricky, the memory allocation scheme used by OP-TEE benchmark for benchmark data shared buffer is no more supported and should be changed.
