### ISSUE TITLE
[QEMU] aarch64 Host and TA Compiling. Compiles with aarch32 but TA fails.

### ISSUE THREAD

**Issue by lordqwerty** [OP-TEE/optee_os#591]
Hello,

I updated my toolchains by running `make toolchains` in the build project. Since I have done this it appears that when trying to compile applications with aarch64 compiler I get:

```
aarch64-linux-gnu-gcc -lteec -L/home/jwhitefield/devel/TEE/optee/dev/optee_client/out/export/lib -o comcast_crypto_demo comcast_crypto_gp_client.o sec_security_openssl.o sec_security_common.o
/home/jwhitefield/devel/TEE/optee/dev/toolchains/aarch64/bin/../lib/gcc/aarch64-linux-gnu/4.9.1/../../../../aarch64-linux-gnu/bin/ld: skipping incompatible /home/jwhitefield/devel/TEE/optee/dev/optee_client/out/export/lib/libteec.so when searching for -lteec
/home/jwhitefield/devel/TEE/optee/dev/toolchains/aarch64/bin/../lib/gcc/aarch64-linux-gnu/4.9.1/../../../../aarch64-linux-gnu/bin/ld: cannot find -lteec
collect2: error: ld returned 1 exit status
```
As such I changed `HOST_CROSS_COMPILE` to `arm-linux-gnueabihf-` which then compiles fine. 

Then for the [Hello World](https://github.com/jenswi-linaro/lcu14_optee_hello_world) and [Comcast crypto example](https://github.com/jbech-linaro/comcast_cryptoapi_ta_example) I get a `0xdeadbeef` errors. Is this because it has not been built using the aarch64 toolchain? I am running this on QEMU.  

Build shell:
```
#!/bin/bash
export PATH=$HOME/devel/TEE/optee/dev/toolchains/aarch32/bin:$PATH
export PATH=$HOME/devel/TEE/optee/dev/toolchains/aarch64/bin:$PATH

export TA_DEV_KIT_DIR=$HOME/devel/TEE/optee/dev/optee_os/out/arm-plat-vexpress/export-user_ta
export TEEC_EXPORT=$HOME/devel/TEE/optee/dev/optee_client/out/export

cd $HOME/devel/TEE/TAs/comcast_cryptoapi_ta_example
make O=./out-client-aarch64 \
                HOST_CROSS_COMPILE=aarch64-linux-gnu- \
                TA_CROSS_COMPILE=arm-linux-gnueabihf- \
                $@
```
This works when `HOST_CROSS_COMPILE` is changed as described above. 

You can see more details of my issue https://github.com/jbech-linaro/comcast_cryptoapi_ta_example/issues/2 and this includes screenshots and terminal output. 

I felt this is probably a better place to ask this question since it is happening for both the examples. That being said all of the `xtest` examples run and I am struggling to understand the difference as to why one runs and not the other. 

Provided I can get all of this running I am more than happy to contribute back and write documentation, to help others get up and running with OP-TEE. 

Thanks for taking time to look at this. I really appreciate it. 
Best,

![screenshot from 2015-12-14 17-17-05](https://cloud.githubusercontent.com/assets/1949133/11807317/099ae60c-a311-11e5-8abe-50274d229380.png)
![screenshot from 2015-12-14 17-17-06](https://cloud.githubusercontent.com/assets/1949133/11807320/0b11753c-a311-11e5-9c87-96e3a84d03ca.png)

**Comment by jbech-linaro** [comment]
Hi,

As written here: https://github.com/jbech-linaro/comcast_cryptoapi_ta_example/issues/2 I've updated the comcast demo TA project this morning and now it builds fine and runs fine on both QEMU and FVP. Please update the git and try again.

**Comment by jbech-linaro** [comment]
And also a little bit more clarification:

__Toolchains__
Depending on the target you will need to setup different toolchains. For example QEMU is a plain 32-bit build and there everything uses the same 32-bit compiler, which can be seen [here](https://github.com/OP-TEE/build/blob/master/qemu.mk#L12-L15). But if we compare to FVP that runs 64-bit normal world code and either 64- or 32-bit in secure world. In our default setup it is configured for 64-bit for normal world builds and 32-bit for secure world build. This can be seen [here](https://github.com/OP-TEE/build/blob/master/fvp.mk#L8-L11).

__Projects not included in the repo setup__
Having that said, everything is pre-configured and is tested both by [Travis](https://travis-ci.org/OP-TEE/optee_os) (QEMU enviroment) and by us manually for other platforms. So, for a default setup you shouldn't have to face __any__ problems. But when trying things not included by default in the repo setup, then we have to be a bit more careful. The project(s) might be dated, which is the case with the `hello world` and was until this morning with `comcast demo TA`. Both of those we're created quite early on when `xtest` wasn't available. I.e, there were no other place to find out how to write a TA. But when we published xtest, we more or less just forgot about the hello world and comcast TA. This, since xtest contains quite a few Trusted Applications and with a bit more useful implementation.

So, summary, if you are building things separately, please pay attention to the "arch" on secure and normal world side. Also make sure that the "root fs" are updated accordingly so that the TA and the binary actually are includeded in the root fs (this is a bit complicated if you have to do it manually).

I appreciate the you consider updating instructions etc, that is always welcome.

**Comment by lordqwerty** [comment]
Hello Joakim,

Thank you for your time and support I really appreciate it. Everything is working perfectly now and I can compile and run applications. 

Many thanks for the clarification I am now going to have a play around and make a few examples. I will make them public so can reference if wanted. 

If there is anything specific you want documented please let me know, it's the least I can do :+1:

**Comment by jbech-optee-adm** [comment]
Issue has been solved, closing it.
