### ISSUE TITLE
How to flash/build OP-TEE with own application to Raspberry Pi 3b?

### ISSUE THREAD

**Issue by LZYHHHHH** [OP-TEE/optee_os#5967]
Hi,

I successfully build the OP-TEE on Raspberry Pi 3 with an SD card according to the [Youtube video]((https://www.youtube.com/watch?v=-IcC2b3AJdA)) and followed the [rpi3](https://optee.readthedocs.io/en/latest/building/devices/rpi3.html)  and [build](https://optee.readthedocs.io/en/latest/building/gits/build.html#get-and-build-the-solution) instructions. The xtext and the hello world example both succeeded on board. 

When I tried to build my own application by modifying the "hello world" example,  I followed the [optee_examples](https://optee.readthedocs.io/en/latest/building/gits/optee_examples/optee_examples.html) to build host application and trusted application using make command and then put the file inside the SD card. However, I met some problems when I tried to build a host application. 
I run:
make     CROSS_COMPILE=aarch64-linux-gnu-     TEEC_EXPORT=/home/lzy/devel/optee/optee_client/out/export/usr     --no-builtin-variables

I noticed that there is no "out" folder under the "optee_client" and the error showed me that: 
![IMG_4147](https://user-images.githubusercontent.com/113720727/232956901-fccadb5a-93a9-43e5-8fb4-66f163f91ce8.png)

Even if I copy the head file, I still met another problem. **Is this the correct track to build an application on Rpi3**?

Furthermore, upon searching, I discovered that both the {UUID}.sh file and the application file exist somewhere in the folder. Subsequently, I copied them onto the SD card using the following command:

sudo cp /home/lzy/devel/optee/out-br/build/optee_examples_ext-1.0/first_app/ta/out/37701efc-26c0-4ca7-b811-cea962d1d920.ta /media/lzy/rootfs/lib/optee_armtz
sudo cp /home/lzy/devel/optee/out-br/target/usr/bin/optee_example_first_app /media/lzy/rootfs/usr/bin

The implementation was successful. However, when I tried to implement this [darknetz](https://github.com/mofanv/darknetz) project, I am unsure about **where to store the dataset** and how to verify if the application was built correctly.

I apologize for the unclear question, and I would greatly appreciate any assistance.

**Comment by jbech-linaro** [comment]
The most straight forward way is to re-run "make" from the build.git, that will rebuild examples and put the onto the root filesystem. Running the makefiles directly "works" in some cases, if you know what you are doing. In short, you need to point to TA-dev kit, libteec etc and make sure that those has been built. This can be a bit tricky if you're not used to the environment. Personally, when I do that, I tend to wrap things into shell-script and with that I can just easily recompile a TA for example. Having said that, you'd still need to figure out how to get the TA to the device itself. That could be done in several ways depending on the device. Mount rootfs and copy, scp files, host mount folder, adb push etc. [Here](https://github.com/jbech-linaro/locki/blob/main/build.sh) is a shell-script is wrote and used not that long ago that wraps things. That is for QEMU v8, where I host mount folders to be able to re-run TA's after compiling them without having to reboot QEMU. If I would have tried the same for RPi3, then I would have used [NFS boot](https://optee.readthedocs.io/en/latest/building/devices/rpi3.html#nfs-boot) to avoid having to fiddle with the uSD-card again and again.  So, in short

1. you have linker errors, because it cannot find libteec.so
2. You can call Makefiles directly, see my wrapper shell script as an example
3. You need to figure out how to best move TA's to the device. I suggest NFS for Rpi3 (I have a [branch](https://github.com/jbech-linaro/build/tree/rpi_nfs) for build.git with my own customization for syncing files via NFS)

And please, try to use plain text log files instead of screenshots if possible!

**Comment by LZYHHHHH** [comment]
Apologies for my delayed reply. I'll try the script and implement NFS boot. Thank you so much for your help!
