### ISSUE TITLE
OPTEE with Android on QEMU

### ISSUE THREAD

**Issue by hybridNeo** [OP-TEE/optee_os#605]
It would be great if there was support to run Android on QEMU with OPTEE as the secure kernel. I am free for the next 6 months and I am willing to work on this if I get some guidance.

**Comment by jbech-linaro** [comment]
Hi @hybridNeo ,

Thanks for reaching out. In Linaro we are working side by side with the people maintaining QEMU. We have discussed this a couple of times but we haven't really tested out the things together. As such I don't think it would be that complicated to get it up and running. As you probably already know, we can run OP-TEE in QEMU today in plain Linux and as I understand my colleagues you can run Android (emulator) in QEMU today (see this [blog](http://www.linaro.org/blog/core-dump/running-64bit-android-l-qemu/) post). Having that said, ARMv8-A TrustZone extension are being implemented for QEMU as we're speaking, so we must use ARMv7-A to start with. So in the end it's more or less a job of getting the already working pieces to play together. Please let me ask a few questions internally and then I'll get back to you again.

// Joakim

**Comment by hybridNeo** [comment]
Thank you, I am interested on working on it , so if you can get back to me.
It would be great !

**Comment by chazy** [comment]
Hi @hybridNeo ,

I run the virtualization team which works with QEMU in Linaro.

Are you looking to run Android with OPTEE on ARMv7 or ARMv8 AArch64?

In any case I'll be happy to connect you with the right people and help you get set up for development.  I assume that one of the first steps would be getting AOSP running on a fairly upstream QEMU for some limited capacity?

**Comment by hybridNeo** [comment]
Hello ,
I am looking to run Android with OPTEE on armv7 and more specifically
cortex A-15 . Yes I think first I need to run AOSP on QEMU, Is there a
particular version I need to look into?

**Comment by stsquad** [comment]
It all depends on how you define "run" ;-)

The specific Android branch we worked on mostly consists of support for the Android Pipe device as well as a couple of emulated devices* and the plumbing required for triggering things like display rotations through the emulator console. The display itself in that case is actually a standard linux framebuffer with the AOSP code doing a soft-GPU implementation which is just enough to run the home screen and the basic apps.

If you don't care about having those frills (which includes adb and the adb shell) then you can use the plain QEMU mainline build with the correct kernel** and a normal AOSP arm64 build.

That said our branch was fairly careful not to be overly invasive so you could re-base it if you really needed that functionality. I can't speak for the current state of the Google branch which has had slightly more major surgery on it to support their GPU solution***.

* Google have since added stuff to https://android.googlesource.com/platform/external/qemu-android (mostly additional platforms AFAICT & GPU)
** The ranchu_defconfig kernel with virtio disks and all the jazz
*** Other GPU solutions are about, I've seen people playing with Mesa/Virgl3D stuff, all pretty alpha ATM.

**Comment by hybridNeo** [comment]
My main goal is to run a demo quiz application which delegates certain
functions to OPTEE . I won't be using anything fancy with that so the
branch you worked on should be sufficient right .

**Comment by stsquad** [comment]
@hybridNeo if you do find you need better graphics and don't want to go down the Google route you can look at: https://github.com/robherring/generic_device/wiki/Android-with-DRM-mesa-graphics

As you can see it uses vanilla QEMU (with some light patching of AOSP for Mesa/3D)

**Comment by hybridNeo** [comment]
Thank you very much. I will try it out and let you know.

**Comment by pascal-brand-st-dev** [comment]
@hybridNeo Could you close this issue if answers are suitable?

**Comment by yingkailiang** [comment]
Hi, @stsquad 

I want to test TEE feature in qemu which running android. 
You mentioned in this post that we can use plain qemu to run AOSP. Suppose  I have following image file: ramdisk.img, system.img, cache.img, userdata.img in AOSP out folder. 

Do you know what command should I use to run AOSP images in plain qemu? 

Thanks in advance.
