### ISSUE TITLE
how to check TA memory usage

### ISSUE THREAD

**Issue by SangsubLim** [OP-TEE/optee_os#6124]
I often encounter out of memory while working on a TA development project.
There are times when a lot of memory is used for the purpose of improving performance, and I always want to know how much heap memory I have used so far.
So I'm wondering if there is a way to check this.

Also, inquire about the following features.
When I checked the config.mk file, the following two entries exist.
CFG_TEE_CORE_MALLOC_DEBUG = y
CFG_TEE_TA_MALLOC_DEBUG = y

Should this be added to the TA build as well as optee-os?
If I add it to TA, can I write it in sub.mk?

And is the purpose of the above feature only for memory leak detection?

Finally, if I use "TEE_GenerateKey" function for key generation, memory will be used internally.
Is the memory used at this time also included in TA memory? Or is it using kernel (optee-os) memory?

BR,

**Comment by jforissier** [comment]
Hello @SangsubLim,

> I often encounter out of memory while working on a TA development project. There are times when a lot of memory is used for the purpose of improving performance, and I always want to know how much heap memory I have used so far. So I'm wondering if there is a way to check this.
> 
> Also, inquire about the following features. When I checked the config.mk file, the following two entries exist. CFG_TEE_CORE_MALLOC_DEBUG = y CFG_TEE_TA_MALLOC_DEBUG = y
> 
> Should this be added to the TA build as well as optee-os?

Yes, as mentioned in the [comment](https://github.com/OP-TEE/optee_os/blob/9a54d4848dae866aa3f1e79fd4203dfda3c30cd9/mk/config.mk#L89).

> If I add it to TA, can I write it in sub.mk?

Yes.
 
> And is the purpose of the above feature only for memory leak detection?

Mainly, yes. Although I believe it may help detect some memory corruption because it adds some checks relative to the debug header.

> Finally, if I use "TEE_GenerateKey" function for key generation, memory will be used internally. Is the memory used at this time also included in TA memory? Or is it using kernel (optee-os) memory?

Kernel memory. The TEE_* functions are implemented in the TEE core (kernel), the functions in libutee are essentially wrappers around the system calls.

**Comment by SangsubLim** [comment]
@jforissier 

Thanks for your reply.
I tried to inquire about what CFG_TA_STATS is.
Based on what you've told me, I think I'll get it right with a few more things.

One curious thing is "xtest --stats --ta".
This seems to output information about the loaded TA.

f04a0fe7-1f5d-4b9b-abf7619b85b4ce8c said Trusted Keys TA. Is this static TA?

I want to see the memory usage of the TA I wrote, not the xtest 4006.
So I tested it like this:

```
# optee_example_hello_world & sleep 10; xtest --stats --ta
Invoking TA to increment 42
TA incremented value to 43
ta(f04a0fe7-1f5d-4b9b-abf7619b85b4ce8c)
         panicked(0) -- True if TA has panicked
         session number(1)
         Heap Status:
                 Bytes allocated: 128
                 Max bytes allocated: 256
                 Size of pool: 16368
                 Number of failed allocations: 0
                 Size of larges allocation failure: 0
                 Total bytes allocated at that failure: 0
[1]+ Done optee_example_hello_wor
#
```

The output TA information is not optee_example_hello_world information, but Trusted Keys TA information.
Is there anything to be aware of when using xtest --stats --ta?

Finally, where can I find TA's memory map? For example, what is the address of the TA Stack and what is the starting address of the heap?

A very useful feature seems to be included in optee.
awesome!

BR,

**Comment by jforissier** [comment]
> @jforissier
> 
> Thanks for your reply. I tried to inquire about what CFG_TA_STATS is. Based on what you've told me, I think I'll get it right with a few more things.
> 
> One curious thing is "xtest --stats --ta". This seems to output information about the loaded TA.
> 
> f04a0fe7-1f5d-4b9b-abf7619b85b4ce8c said Trusted Keys TA. Is this static TA?

It is an "early TA", see https://optee.readthedocs.io/en/latest/architecture/trusted_applications.html#early-ta.
 
> I want to see the memory usage of the TA I wrote, not the xtest 4006. So I tested it like this:
> 
> ```
> # optee_example_hello_world & sleep 10; xtest --stats --ta
> Invoking TA to increment 42
> TA incremented value to 43
> ta(f04a0fe7-1f5d-4b9b-abf7619b85b4ce8c)
>          panicked(0) -- True if TA has panicked
>          session number(1)
>          Heap Status:
>                  Bytes allocated: 128
>                  Max bytes allocated: 256
>                  Size of pool: 16368
>                  Number of failed allocations: 0
>                  Size of larges allocation failure: 0
>                  Total bytes allocated at that failure: 0
> [1]+ Done optee_example_hello_wor
> #
> ```
> 
> The output TA information is not optee_example_hello_world information, but Trusted Keys TA information. Is there anything to be aware of when using xtest --stats --ta?

The TA has to be running when you invoke `xtest --stats --ta` or it will not be shown. You may need to change the code a bit to make sure the session is still open. For example add `TEE_Wait()`.

> Finally, where can I find TA's memory map? For example, what is the address of the TA Stack and what is the starting address of the heap?

One way of showing the memory map is to cause a crash or a panic. Just call `TEE_Panic(0)` and you will get a dump on the secure console (but of course the TA will stop running at that point).
You may want to build optee_os with `CFG_TA_ASLR=n` so that virtual addresses remain the same from one run to another.

The TA heap starts at `ta_heap` (see [here](https://github.com/OP-TEE/optee_os/blob/660463d38a55d65ba9aa7b8e503ac48367edda26/ta/user_ta_header.c#L119)), so you should be able to print it with `printf("heap at %p", (void *)ta_heap);` in the TA.

> A very useful feature seems to be included in optee. awesome!

Thanks! This is the result of hard work from many contributors :wink:
