### ISSUE TITLE
Older Optee versions vs Latest Optee versions

### ISSUE THREAD

**Issue by dhruv77777** [OP-TEE/optee_os#6240]
Hey Team,

I have gone through the Web to check out the differences between the older Optee versions and the latest Optee versions, but I am not able to get good resources for that.

Are there any resources available, where I can find the difference between versions on features level?

Thanks

**Comment by jbech-linaro** [comment]
You won't find it explicitly mentioned, but you can get the information via a couple of different routes:
- Via the [CHANGELOG](https://github.com/OP-TEE/optee_os/blob/master/CHANGELOG.md), which can be a bit cumbersome. But recently there has been [blog posts](https://www.trustedfirmware.org/blog/) about the changes. 
- Via https://optee.readthedocs.io, press the `v: latest" down to the left and browse an older copy of the documentation.
- Via the Linaro YouTube channel, from time to time we've given "[lightning talks](https://www.youtube.com/@LinaroOrg/search?query=lightning%20talk)" where we've described recent changes. The Youtube in general is a good resource, since that is often where our generic talks end up as well.

**Comment by dhruv77777** [comment]
Thanks for the response....
