### ISSUE TITLE
Best way to set-up a crypto Hardware block

### ISSUE THREAD

**Issue by Amit-Radur** [OP-TEE/optee_os#6388]
I have a HW accelerator on my platform that can be used to encrypt/decrypt an Image file, Now need to set it up as crypto block, and wanted to check what is the best way to do it.

I see there is this "crypto_mac_ops" structure with various call backs , is it just for some software crypto Implementation? or can it be used to register HW accelerator as crypto block?

Can some one explain what these callback do?

static const struct crypto_mac_ops sm3_hmac_ops = {
        .init = op_sm3_hmac_init,
        .update = op_sm3_hmac_update,
        .final = op_sm3_hmac_final,
        .free_ctx = op_sm3_hmac_free_ctx,
        .copy_state = op_sm3_hmac_copy_state,
};

**Comment by jenswi-linaro** [comment]
There are a few examples to copy or take inspiration from in the source tree, one example in `core/drivers/crypto/caam/hash/caam_hash_mac.c`.

**Comment by Amit-Radur** [comment]
@jenswi-linaro , While checking examples, came across core/drivers/stm32mp15_huk.c that suits my requirement well.
Will get the HUK from "tee_otp_get_hw_unique_key", and use it for purpose of encryption/decryption though I have follow-up question 

https://github.com/OP-TEE/optee_os/blob/master/core/drivers/stm32mp15_huk.c#L110
crypto_authenc_init(ctx, TEE_MODE_ENCRYPT, key, key_len, nonce,
				  nonce_len, TEE_AES_BLOCK_SIZE, 0, uid_len);

Is this callback registered here , https://github.com/OP-TEE/optee_os/blob/master/core/drivers/crypto/stm32/stm32_cryp.c#L623 ?

**Comment by jenswi-linaro** [comment]
I suspect that yes, but I'm not sure. @etienne-lms do you know?

**Comment by etienne-lms** [comment]
Yes Jens, you're right.
stm32_crypt driver supports AES operations. It registers to AE (Authenticated Encryption) (with `drvcrypt_register_authenc()`) and symmetric ciphering (with `drvcrypt_register_cipher()`). stm32mp15_huk driver calls the generic core crypto API which is it charge to calling registered stm32_crypt handlers.

@Amit-Radur, as @jenswi-linaro pointed out above, the best way to use HW accelerated crypto with OP-TEE is to register your driver in the `drvcrypt` framework so that is it used for all related OP-TEE crypto operations. You can look at how the several crypto drivers (_core/driver/crypto/..._) register to drvcrypt using `drvcrypt_register_xxx()` functions. Drvcrypt framework API function are declared in _core/drivers/crypto/crypto_api/include/drvcrypt.h_.
 
Regarding how to use OP-TEE core crypto framework, the crypto APIs are declared in _core/include/crypto/crypto.h_. These API will call drvcrypt crypto drivers if found or will fallback to the default software crypto implementation, based on libtomcrypt or libmbedtls.
