### ISSUE TITLE
PKCS11: Checksum Attribute Is Not Supported

### ISSUE THREAD

**Issue by moose-rivieh** [OP-TEE/optee_os#6431]
It seems the checksum attribute is not supported, and some common application requires it (example: Amazon Voice Assistance, see [this link](https://github.com/alexa/avs-device-sdk/blob/b32be0a1139be1aa22f1df5f59ba394d3b6a9697/core/Crypto/Pkcs11/src/PKCS11Key.cpp#L116) for reference). Are there plans to support this attribute? Thank you.

**Comment by etienne-lms** [comment]
You mean `CKA_CHECK_VALUE`  attribute? Indeed it's not supported. I think it could be and should not be too hard to implement. I can add that to my todo list but contributions are warmly welcome, as always (I'm sorry to say it won't be in my top priority tasks).

**Comment by moose-rivieh** [comment]
Yes. That is correct. I'd love to commit the change, but this is my first interaction with optee and PKCS11 so not really sure what I am doing. If you point me to some documentation, I am happy to look it over and see if I can add support for `CKA_CHECK_VALUE`

**Comment by etienne-lms** [comment]
We'll be please to help you. It seems you need `CKA_CHECK_VALUE` for symmetric key objects.

As a start point, you can look he PKCS#11 base spec [latest 3.0 is fine](https://docs.oasis-open.org/pkcs11/pkcs11-base/v3.0/os/pkcs11-base-v3.0-os.html) section 4.10, last paragraph for for an overview of the attribute. 
Especially _"Unless otherwise specified for the object definition, the value of this attribute is derived from the key object by taking the first three bytes of an encryption of a single block of null (0x00) bytes, using the default cipher and mode (e.g. ECB) associated with the key type of the secret key object."_
For object of type `CKK_GENERIC_SECRET`: see PKCS#11 current mechanism spec [3.0](https://docs.oasis-open.org/pkcs11/pkcs11-curr/v3.0/pkcs11-curr-v3.0.html) sec

**Comment by moose-rivieh** [comment]
Thank you, @etienne-lms, for the detailed info. I got caught up with something urgent and just got time to get back to this. We have been able to address this issue on our end using a shortcut, but I am still going to review the info shared and attempt a pull request.

**Comment by etienne-lms** [comment]
> It seems that CKA_CHECK_VALUE  can be created from template ? should this case be handled ? even if the template value would conflict with the exepcted/correct value ?

I think yes. When the attribute is supported, we should conform to the specification.

> For when C_SetAttributeValue() is called CKR_ACTION_PROHIBITED should be returned. Once CKA_CHECK_VALUE cannot be changed once it has been set.

The specs (both v2.40 and v3.0) say that for CKO_SECRET_KEY objects, C_SetAttributeValue can destroy the attribute. The spec does not say that once destroyed it cannot be created back, it only says that if created, it must match the value recomputed inside the token.
