### ISSUE TITLE
Proposal for implementing TEE_ALG_RSASSA_PKCS1_V1_5 with mbedtls

### ISSUE THREAD

**Issue by larper2axis** [OP-TEE/optee_os#6433]
Hi

For us the ability to support PKCS11 mechanism CKM_RSA_PKCS together with mbedtls was critical. After a study of the PKCS11 spec it seems all sensible use-cases of this mechanism for signing will pass a DigestInfo-formatted hash. Thus the idea to strip the DigestInfo ASN.1 stuff and reconstruct the hash identifier needed to call the RSA signing API in mbedtls. We end up with a CKM_RSA_PKCS that can support all hashes implemented by mbedtls.

Is upstream interested in this work ? The commit message I attached below explains it in more detail.

> 
>     Implement TEE_ALG_RSASSA_PKCS1_V1_5 with mbedtls
>     
>     TEE_ALG_RSASSA_PKCS1_V1_5 is a signing scheme designed to be
>     compatible with PKCS11 mechanism CKM_RSA_PKCS. It is odd in the sense
>     that the scheme does not prepend the DigestInfo structure from RFC
>     8017 in the EMSA-PKCS1-v1_5 formatting. Instead it must be supplied by
>     the caller as part of the input message, if the caller intends to
>     create or verify a PKCS1 v1.5 signature.
>     
>     It is reasonable to believe that the caller always uses the mechanism
>     to manage a PKCS1 v1.5 RSA signature and the message will therefore
>     always contain a DigestInfo followed by the hash to be signed. Thus we
>     can reconstruct the arguments needed to create a PKCS1 v1.5 signature
>     with mbedtls. The hash algorithm is deduced from the OID stored in the
>     DigestInfo.
>     
>     The implementation will reject DigestInfos encoded using BER encoding
>     rules so it may reject input that was compliant with RFC 2313.
>

**Comment by jenswi-linaro** [comment]
If it implements something missing in PKCS#11 it should be interesting. I'm still not sure what the patch does so I can't promise anything except that I will look at it.

**Comment by etienne-lms** [comment]
It's all fine using mbedTLS in the pkcs11 TA. It's already used for `CKM_RSA_AES_KEY_WRAP` (45d40bda652aece0c348d316b0170992f781c99a) and  EC key import (7c24332175d8a3a60264f9de2929fd16591a0e0e).

Patches are welcome, in the TA and in optee_test (_host/xtest/pkcs11_1000.c_ test [`pkcs11_1021`](https://github.com/OP-TEE/optee_test/blob/4.0.0/host/xtest/pkcs11_1000.c#L6752)).

> For us the ability to support PKCS11 mechanism CKM_RSA_PKCS together with mbedtls was critical (...)

You mean you prefer having the TA to use mbedTLS rather than crypto library from OP-TEE core? 
Note that core crypto lib can leverage HW assistance (perf and/or side-channel attacks resistance) when the platform provides one.

`CKM_RSA_PKCS` for signing is already supported in the pkcs11 TA. Do you mean is the current implementation is too restrictive regarding the hash algorithm used? I think I'm missing something here.

**Comment by larper2axis** [comment]
@etienne-lms  this is about using mbedtls in the core. CKM_RSA_PKCS in the TA depends on the core providing the algorithm TEE_ALG_RSASSA_PKCS1_V1_5 which was not the case for a core built with mbedtls. The APIs provided by mbedtls can only perform the full  EMSA-PKCS1-v1_5 formatting,
