### ISSUE TITLE
Unexpected Session Termination

### ISSUE THREAD

**Issue by YaelAv** [OP-TEE/optee_os#6437]
When a session is closed by the client using TEEC_CloseSession, the expected cleanup process occurs. 
However, what happens when the session is unexpectedly terminated? 
If the TA retains data per session, this data should be cleared when a client voluntarily closes the session. Yet, how is this managed in the event of an unexpected session closure? Is there any built-in TA infrastructure to detect such closures and eliminate all storage related to that particular session?

**Comment by etienne-lms** [comment]
If a session unexpectedly terminates due to Linux userland cient application (for example a segmentation fault, client application is killed, ...), then Linux kernel simply acts as if the client application called `TEEC_CloseSession()` to terminate the session.

If a session unexpectedly terminates due to the callee TA (for example a TA segmentation fault or a TA panic case), then TEE core simply destroys the TA instance. The next time a client invokes the TA from it's still opened session, it will be reported the `TEEC_ERROR_TARGET_DEAD` error code.

**Comment by YaelAv** [comment]
Thanks
