### ISSUE TITLE
Unable to use printf in the kernel 

### ISSUE THREAD

**Issue by niteshnarayanlal** [OP-TEE/optee_os#647]
I tried to add a printf statement in ./core/lib/libtomcrypt/src/tee_ltc_provider.c but got the error saying 
out/arm-plat-ls/core/lib/libtomcrypt/libtomcrypt.a(tee_ltc_provider.o): In function `gen_rsa_key':
/home/B44382/Work/OPTEE/optee-os-clean/core/lib/libtomcrypt/src/tee_ltc_provider.c:858: undefined reference to `puts'.
In other places of libtomcrypto all the printf are commented, does that mean: we can not use printf within kernel?

**Comment by jforissier** [comment]
Indeed you are not supposed to use `printf()` in TEE kernel code. You should use the `*MSG` macros instead: `DMSG`, `IMSG`, `EMSG` as well as their `_RAW` variants. Just `#include <trace.h>` and they will be available.
Now I am a bit surprised by the error message you're getting, I would have expected undefined reference to `printf` rather than `puts`. Even better I think we should not declare the `printf` prototype when building the TEE kernel (i.e., when `__KERNEL__` is defined). Feel free to submit a PR if you think you can clean this a bit ;-) improvements are always welcome.
Anyway, hope this helps.
