### ISSUE TITLE
Question about mobj and fobj

### ISSUE THREAD

**Issue by NewDwarf** [OP-TEE/optee_os#6559]
What are the main purposes of `mobj` and `fobj` abstraction from the OP-TEE design perspective? 
It is interesting to know how they help to orginize the OP-TEE design and how difficult/inconvenient would be developing of OP-TEE in the case of missed `mobj` and `fobj` abstraction.

**Comment by etienne-lms** [comment]
A `mobj` is an abstraction of a memory object: shared memory, TA exec or read/write memory, FFA memory reference, etc... It is a convenient way to bind operations (map/unmap w/ refcount, get phys. addr./memroy type, ...) under a common API: consumers manipulate a `mobj` reference instead of a virtual address reference.

An `fobj` is a file abstraction for the content represented by a memory object. It is mainly designed for OP-TEE pager, for the page swapping mechanism. Elfloader also uses the `fobj` abstraction for ELF content loading of secure userland code/data (unless i missed somthing).

Due to pager constraint on the system, OP-TEE core needs a specific sequence to allocate external secure memory that you will find at several places (_ldelf_loader.c_, _ldelf_syscalls.c_, _stmm_sp.c_, _secure_partition.c_):
* allocate in `tee_mm_sec_ddr`/TA_RAM using `fobj = fobj_ta_mem_alloc(page_count)`;
* get a memory object for it and drop the fobj: `mobj = mobj_with_fobj_alloc(fobj, ...); fobj_put(fobj);`;
* map the buffer and drop the mobj: `va = vm_map(..., mobj, ...); mobj_put(mobj);`;
* The buffer can be accessed, and will be released after `vm_unmap(..., va, ...)` (unless there are several users).
