### ISSUE TITLE
Is ROCK Pi 4 implementation really secure?

### ISSUE THREAD

**Issue by guilhermeeec** [OP-TEE/optee_os#6568]
The documentation states that the [Raspberry Pi 3](https://optee.readthedocs.io/en/latest/building/devices/rpi3.html) implementation of OP-TEE is not secure due to processor limitations. The same is not stated for ROCK Pi 4 [ROCK Pi 4](https://optee.readthedocs.io/en/latest/building/devices/rockpi4.html). Could someone please help me confirm if the ROCK Pi 4 implementation presents the same problem as the Raspberry Pi 3 implementation?

**Comment by NewDwarf** [comment]
The Rock Pi 4 board has much better memory isolation due to using kind of TZASC to enable hardware isolation of the specific memory regions. Please, check [this source file](https://github.com/OP-TEE/optee_os/blob/master/core/arch/arm/plat-rockchip/platform_rk3399.c)
Also, the Rock Pi 4 has the TEE support on the DMA level.

**Comment by guilhermeeec** [comment]
Thank you :)
