### ISSUE TITLE
boot_init_memtag is called before mmu is enabled.

### ISSUE THREAD

**Issue by sichunqin** [OP-TEE/optee_os#6649]
Memory tag is associated with VA (mmu), so I understand that the boot_init_memtag should be called after mmu is enabled. 
If it is called before mmu is enabled, the OPTEE would panic on some platforms. Can someone explains why it is called early? Thanks!

**Comment by jenswi-linaro** [comment]
> Memory tag is associated with VA (mmu), so I understand that the boot_init_memtag should be called after mmu is enabled.

Could you tell me how you came to that conclusion? 

> If it is called before mmu is enabled, the OPTEE would panic on some platforms. Can someone explains why it is called early? Thanks!


Please see the comment in `core/arch/arm/kernel/entry_a64.S` where `boot_init_memtag()` is called:
``` C
        /*
         * If FEAT_MTE2 is available, initializes the memtag callbacks.
         * Tags for OP-TEE core memory are then cleared to make it safe to
         * enable MEMTAG below.
         */
        bl      boot_init_memtag
```
The tags must be cleared before they are used. I can't remember why we do that early except that it's likely to avoid potential coherency problems. You may want to consult the Arm ARM for further details.

**Comment by sichunqin** [comment]
Thanks for the reply!
The panic happens on ARMV9. I am afraid that it might be ARMv9 specific problem. BTW, How can I consult ARM?

**Comment by sichunqin** [comment]
BTW, during reset, memory could be cleared up. I guess it also include tag cleap up. It seems that bl32 tag clearing up behavior seems not be required.

**Comment by jenswi-linaro** [comment]
This is the Arm ARM I was talking about https://developer.arm.com/documentation/ddi0487/ja/?lang=en

**Comment by sichunqin** [comment]
Thanks for the share The panic happens on “”dc gva” instruction which is called by boot_init_memtag on ARMv9 platform. The MTE uses virtual address TBI, it is why I think enabled MMU is necessary.

**Comment by jenswi-linaro** [comment]
So do the other `dc` instructions and we all know we should clear the cache before enabling MMU.
Have you looked at ESR when you get the exception? https://esr.arm64.dev/ is quite handy to interpret the value.

**Comment by sichunqin** [comment]
@jenswi-linaro Thanks for the info!
According to the ARM reference document, dc gva instructions seems not relate to cache maintenance, but allocate tag. The reference doc doesn't explain clearly how it work, and how it to be useed. dc I see the dc gva is used to tag or untag memory in OPTEE. 
![image](https://github.com/OP-TEE/optee_os/assets/15395572/b9e6bc12-567a-4f25-8dc5-3116de8e9004)
It seems that DC GZVA is more suitable to clear memory. But the two instruction are almost same except zero memory. I guess it would not work as dc gzva. Any other dc instruction can be used? 

Has the OPTEE memtag feature been tested on other platform than Qemu? It can work well on QemuV8, I am afraid that it might break on non-simulator platform. 

@odeprez thanks for providing the information. Seems that the memtag does not work on FVP as well. It would help a lot if you could retry with FVP.

**Comment by jenswi-linaro** [comment]
If it's wrong to clear the tags with MMU disabled, then we'll need to do it a bit later. We don't want to rely on the previous boot stage to clear the tags for the memory used by OP-TEE.

**Comment by odeprez** [comment]
Hi noticed boot_init_memtag called before mmu enable:
DC GZA gives an alignment fault, I assume this is because when mmu is off all accesses are made of device type and Arm ARM says: "If the memory region being modified is any type of Device memory, this instruction can give an alignment fault [...]."

Moving boot_init_memtag after mmu enable behaves differently:
DC GZA gives a permission fault, I assume this is because the range given by core_mmu_get_secure_memory consists of pages mapped RO (op-tee text section?) and then RW (data sections?). DC GZA is a write instruction towards an RO page leading to a fault.

I progressed it by specifying only the RW section range. But then hitting a tag check panic a bit later. Tbc.

**Comment by odeprez** [comment]
Hi, it ends up working for me on FVP , after applying below change. The commit message contains the details.
The way to calculate RW section in boot_clear_memtag may require revisit.

`From 7a569d73df719de377fd2a4015f37edcb5ca14dd Mon Sep 17 00:00:00 2001
From: Olivier Deprez <olivier.deprez@arm.com>
Date: Thu, 1 Feb 2024 15:04:23 +0100
Subject: [PATCH] fix: memory tagging boot time init

Baed on following observations on FVP:
With boot_init_memtag called before MMU enable, DC GZA hits an alignment
fault. This is because all accesses are of device type when MMU is off.
Arm ARM states for DC GZA: "If the memory region being modified is any
type of Device memory, this instruction can give an alignment fault."
Moving boot_init_memtag after MMU enable, DC GZA hits a permission
fault, this is because the range returned by core_mmu_get_secure_memory
consists of pages mapped RO (text sections) and then RW (data sections)
consecutively. DC GZA is a write instruction executed towards an RO page
leading to a fault.

To fix this, split boot_init_memtag into two halves:
Setup memtag operations before MMU is enabled such that MAIR_EL1 is
properly configured for normal tagged memory.
Clear core TEE RW sections after MMU is enabled.

Signed-off-by: Olivier Deprez <olivier.deprez@arm.com>
---
 core/arch/arm/kernel/boot.c      | 12 ++++++++++--
 core/arch/arm/kernel/entry_a64.S |  5 +++++
 core/include/kernel/boot.h       |  1 +
 3 files changed, 16 insertions(+), 2 deletions(-)

diff --git a/core/arch/arm/kernel/boot.c b/core/arch/arm/kernel/boot.c
index d7cbe5998..705139538 100644
--- a/core/arch/arm/kernel/boot.c
+++ b/core/arch/arm/kernel/boot.c
@@ -321,12 +321,20 @@ static void init_asan(void)
 #if defined(CFG_MEMTAG)
 /* Called from entry_a64.S only when MEMTAG is configured */
 void boot_init_memtag(void)
+{
+	memtag_init_ops(feat_mte_implemented());
+}
+
+/* Called from entry_a64.S only when MEMTAG is configured */
+void boot_clear_memtag(void)
 {
 	paddr_t base = 0;
 	paddr_size_t size = 0;
 
-	memtag_init_ops(feat_mte_implemented());
-	core_mmu_get_secure_memory(&base, &size);
+	base = (paddr_t) __data_start;
+	size = (paddr_size_t)TEE_RAM_VA_SIZE;
+	size -= (paddr_size_t)((paddr_t)__data_start - (paddr_t)__text_start);
+
 	memtag_set_tags((void *)(vaddr_t)base, size, 0);
 }
 #endif
diff --git a/core/arch/arm/kernel/entry_a64.S b/core/arch/arm/kernel/entry_a64.S
index 480ba7060..14210e964 100644
--- a/core/arch/arm/kernel/entry_a64.S
+++ b/core/arch/arm/kernel/entry_a64.S
@@ -344,6 +344,11 @@ clear_nex_bss:
 
 	bl	__get_core_pos
 	bl	enable_mmu
+
+#ifdef CFG_MEMTAG
+	bl	boot_clear_memtag
+#endif
+
 #ifdef CFG_CORE_ASLR
 	/*
 	 * Reinitialize console, since register_serial_console() has
diff --git a/core/include/kernel/boot.h b/core/include/kernel/boot.h
index bf78d5c38..279053290 100644
--- a/core/include/kernel/boot.h
+++ b/core/include/kernel/boot.h
@@ -45,6 +45,7 @@ extern const struct core_mmu_config boot_mmu_config;
 void boot_init_primary_early(void);
 void boot_init_primary_late(unsigned long fdt, unsigned long manifest);
 void boot_init_memtag(void);
+void boot_clear_memtag(void);
 void boot_save_args(unsigned long a0, unsigned long a1, unsigned long a2,
 		    unsigned long a3, unsigned long a4);
 
-- 
2.34.1
`

**Comment by sichunqin** [comment]
@odeprez Thanks a lot! I will try the patch. BTW, I think the patch is generic and could applicable to all platforms, and would be merged to the master branch of OPTEE. @jenswi-linaro

**Comment by jenswi-linaro** [comment]
Yes, I agree. I'll pick up the patch and turn it into a pull request.

**Comment by sichunqin** [comment]
@odeprez @jenswi-linaro , we encounter another crash when enable ASLR on ARMv9 platform. Since the platform has not debug capability, so we can't find more information which cause the crash. 

Seems it crashes on enable_mmu function on entry_a64.S. I doubt that ARMv9 MMU can't support memory overlapping? Enable ASLR, two different VAs would map same PAs. I am afraid that it may be generic ARMv9 issue. 

Sorry, it is not related to the topic.

**Comment by etienne-lms** [comment]
> Sorry, it is not related to the topic.

I think you should rather create another issue for that, if you don't mind. It would be more convenient for people interested by your finding.

**Comment by sichunqin** [comment]
OK, I will create new issue for it.
