### ISSUE TITLE
Accessing tee_common_otp.h from TA

### ISSUE THREAD

**Issue by mardyr** [OP-TEE/optee_os#6658]
Hi, 

Is it possible to include directly `tee_common_otp.h` inside TA(hello world example) ? Now only OPTEE_OS libs are accessible from TA which are in export-ta* directory. I would like to make dirty solution for test purposes and for that I need to have access to the tee_common_otp.h and its source from TA. I believe that for this purpose I have to change ta_dev_kit.mk, but I am not sure. Do you have any recommendations this problem?

BR, 
Martin

**Comment by jforissier** [comment]
Hi @mardyr, no, it is not possible. `tee_common_otp.h` contains declarations for functions that are in the OP-TEE kernel (OS running at S-EL1). These functions are not accessible from user space applications (TAs, which are running at S-EL0).

One common way of giving access to a kernel service is by writing a pseudo-TA (PTA). See for example[ `core/pta/system.c`](https://github.com/OP-TEE/optee_os/blob/4.1.0/core/pta/system.c) which exposes a few kernel functions via the GlobalPlatform API. For instance `huk_subkey_derive()` is wrapped by `system_derive_ta_unique_key()` so that can be called by user space TAs via the `PTA_SYSTEM_DERIVE_TA_UNIQUE_KEY` command. An example is in [`optee_os/ta/crypt/derive_key_taf.c`](https://github.com/OP-TEE/optee_test/blob/4.1.0/ta/crypt/derive_key_taf.c).

Speaking of derived keys, I think that fundamentally you do NOT want to expose the hardware unique key to applications (even Trusted ones). Derivation is what is normally done to protect the unique key upon which many secrets depend.

**Comment by mardyr** [comment]
Niceee, will give it a shot, thanks. I will leave it open for now, if any other questions related arise

**Comment by mardyr** [comment]
Ok, I have some ground question about PTA. I treat it as statically compiled service in core blob which works on behalf TA which works in S-EL0. I found a lot of questions related to that, but still would like to confirm. It works only this way : CA -> TA -> PTA , right? I see this correlation in trusted_keys example when REE driver requests TA for the work which is delegated to S-EL1 , but I am also looking on stats PTA which is triggered by MMI `xtest --stats --<action>` and I cannot see there delegation to TA, I mean usage of Global Platform Core API which is common for TA, in trusted keys it is defined in `entry.c`

**Comment by jforissier** [comment]
> Ok, I have some ground question about PTA. I treat it as statically compiled service in core blob which works on behalf TA which works in S-EL0. I found a lot of questions related to that, but still would like to confirm. It works only this way : CA -> TA -> PTA , right? I see this correlation in trusted_keys example when REE driver requests TA for the work which is delegated to S-EL1 , 

Correct.

> but I am also looking on stats PTA which is triggered by MMI `xtest --stats --<action>` and I cannot see there delegation to TA, I mean usage of Global Platform Core API which is common for TA, in trusted keys it is defined in `entry.c`

The CA may also call the PTA directly, because both TAs and PTAs expose a GlobalPlatform-compliant API. PTAs may add checks to impose restrictions on the caller, such as being called from a TA, or a TA with a given UUID.

**Comment by mardyr** [comment]
_PTAs may add checks to impose restrictions on the caller, such as being called from a TA, or a TA with a given UUID._
Like this?
```
static TEE_Result open_session(uint32_t param_types __unused,
			       TEE_Param params[TEE_NUM_PARAMS] __unused,
			       void **sess_ctx __unused)
{
	struct ts_session *s = ts_get_calling_session();

	/* Check that we're called from a user TA */
	if (!s)
		return TEE_ERROR_ACCESS_DENIED;
	if (!is_user_ta_ctx(s->ctx))
		return TEE_ERROR_ACCESS_DENIED;

	return TEE_SUCCESS;
}
```

**Comment by jforissier** [comment]
> _PTAs may add checks to impose restrictions on the caller, such as being called from a TA, or a TA with a given UUID._ Like this?
> 
> ```
> static TEE_Result open_session(uint32_t param_types __unused,
> 			       TEE_Param params[TEE_NUM_PARAMS] __unused,
> 			       void **sess_ctx __unused)
> {
> 	struct ts_session *s = ts_get_calling_session();
> 
> 	/* Check that we're called from a user TA */
> 	if (!s)
> 		return TEE_ERROR_ACCESS_DENIED;
> 	if (!is_user_ta_ctx(s->ctx))
> 		return TEE_ERROR_ACCESS_DENIED;
> 
> 	return TEE_SUCCESS;
> }
> ```

Exactly.
