### ISSUE TITLE
including libtomcrypt

### ISSUE THREAD

**Issue by shirinebadi** [OP-TEE/optee_os#6688]
Hello. I'm trying to include libtomcrypt in my normal world application. I know client app is a normal c program, so I assume there should I be no problem. However, I'm keep getting no such file error. I'm using QEMU and libtomcrypt is installed on my system.

Thank you in advance.

**Comment by jforissier** [comment]
Hi @shirinebadi,

If you are building your app with Buildroot (like `optee_test` and `optee_examples`) then you need to add `libtomcrypt` to your package dependencies. For example with `optee_test`:
```diff
diff --git a/br-ext/package/optee_test_ext/optee_test_ext.mk b/br-ext/package/optee_test_ext/optee_test_ext.mk
index 8037789..cfd9a4d 100644
--- a/br-ext/package/optee_test_ext/optee_test_ext.mk
+++ b/br-ext/package/optee_test_ext/optee_test_ext.mk
@@ -3,7 +3,7 @@ OPTEE_TEST_EXT_SOURCE = local
 OPTEE_TEST_EXT_SITE = $(BR2_PACKAGE_OPTEE_TEST_EXT_SITE)
 OPTEE_TEST_EXT_SITE_METHOD = local
 OPTEE_TEST_EXT_INSTALL_STAGING = YES
-OPTEE_TEST_EXT_DEPENDENCIES = optee_client_ext openssl host-python-cryptography
+OPTEE_TEST_EXT_DEPENDENCIES = optee_client_ext openssl host-python-cryptography libtomcrypt
 OPTEE_TEST_EXT_SDK = $(BR2_PACKAGE_OPTEE_TEST_EXT_SDK)
 OPTEE_TEST_EXT_CONF_OPTS = -DOPTEE_TEST_SDK=$(OPTEE_TEST_EXT_SDK)
 # os_test has dependencies, this enforces a valid build order
```

If you are using a different build system, then it depends. Note that you need an Arm build of LibTomCrypt, so it doesn't help that LibTomCrypt is installed on your (presumably x86-based) build host.

**Comment by oldoldcoder** [comment]
@jforissier Excuse me, I would like to know if we have an explanation diagram of the directory structure under the build folder

<img width="280" alt="image" src="https://github.com/OP-TEE/optee_os/assets/83199123/df80ff08-02a3-4534-9f53-c1c0356b57d8">

Just like this in document

> https://optee.readthedocs.io/en/3.14.0/architecture/file_structure.html

However, I did not find any similar explanation of the directory structure of the build folder. Is there any such information? Thank you.

**Comment by oldoldcoder** [comment]
@jforissier At the same time, because my Normal World program uses MBEDTLS, I will ask me to add libmbedtls to OPTEE_EXAMPLE_EXT, but it is prompted to tell me that this is not a feasible target

<img width="553" alt="image" src="https://github.com/OP-TEE/optee_os/assets/83199123/9b2bedbb-d26e-4f04-9c16-c95cd636110f">

<img width="651" alt="image" src="https://github.com/OP-TEE/optee_os/assets/83199123/99c65d91-97c7-437f-add5-24807b486960">

**Comment by jforissier** [comment]
Hi @oldoldcoder,

There is no documentation about the structure of the `build/` folder. `br-ext` means `Buildroot extensions`, it is where we store Buildroot package definitions for the projects we check out locally. For example, instead of telling Buildroot to build the official `optee-client` which is defined in `$(TOP)/buildroot/package/optee-client`, we build a package called  `optee_client_ext` which points to the local checkout in `$(TOP)/optee_client`.

In order to add MBed TLS to `optee_examples_ext`, you need to add `mbedtls` to `OPTEE_EXAMPLES_EXT_DEPENDENCIES` (**not** `libmbedtls`). As you can see in `$(TOP)/buildroot/package/`, MBed TLS is in `$(TOP)/buildroot/package/mbedtls/`.

**Comment by oldoldcoder** [comment]
Hi@jforissier 
LOL!!!I now know

Thank you and I hope to add introductions to other directories in the FILE structure in the future.
