### ISSUE TITLE
Question about panic of TA2 in TA1-TA2 connection.

### ISSUE THREAD

**Issue by ydonghyuk** [OP-TEE/optee_os#6701]
- Testing process
1/ TA1 -> TA2 open session (TA_FLAGS: single instance, multi session flag)
2/ Force TEE_Panic on TA2
3/ TA1->TA2 invoke command (TEE_InvokeTACommand)

- Result
No response from TA1.

- Additional test
TA panic situation when connecting CA-TA through the same process

- Result
When invoke command is performed from CA to TA, TEE_ERROR_TARGET_DEAD is immediately returned.

- Inquiry
Is there any way for TA1 to know if TA2 is experiencing a panic or abnormal termination?
Also, in this situation, would it be meaningful to use the cancellationRequestTimeout parameter of TEE_InvokeTACommand?

**Comment by etienne-lms** [comment]
> Testing process
1/ TA1 -> TA2 open session (TA_FLAGS: single instance, multi session flag)
2/ Force TEE_Panic on TA2
3/ TA1->TA2 invoke command (TEE_InvokeTACommand)

I would guess at stage 3 `TEE_InvokeTACommand()` (from TA1) returns `TEE_ERROR_TARGET_DEAD`. This is how TA1 knows TA2 is dead.

> Also, in this situation, would it be meaningful to use the cancellationRequestTimeout parameter of TEE_InvokeTACommand

There is no API function for a TA to request cancellation of a request it has sent to another TA. Actually there can't be as the client TA is still busy waiting its request to the other TA completes.

**Comment by etienne-lms** [comment]
step 1: TA1 invokes TA2 using calls `TEE_InvokeTAComment()`.
step 2: TA2 panics
end of step 2: I expect TA1 gets return code `TEE_ERROR_TARGET_DEAD` from `TEE_InvokeTAComment()`.

Is that the scenario your are testing?

If so, TA1 is not expected to call `TEE_InvokeTAComment()` since the related session was closed when TA2 died.
That said, TEE core should not panic in such case, this is not good. I'm a bit surprised it does. I'll try that this usecase with Qemu.

**Comment by etienne-lms** [comment]
I've setup a quick test with OP-TEE qemu_virt env, playing and hacking with xtest regression_1016 and os_test TA and I see that OP-TEE behaves as expected:

1. xtest opens a session to TA1 and invokes TA1 that in turn opens a session to TA2
   (note: xtest is of corse a CA: a non-secure client application)
   (note: TA1 keeps its session to TA2 opened so that it can use it later)
   (note: TA2 is single instance/multi session, so that it can be invoked from both xtest and TA1)
2. xtest invokes TA1 that invokes TA2 (using the already opened session) for some dummy processing: all good.
3. xtest invokes TA2 to make TA2 instance to panic: TA2 panics.
4. xtest invokes TA1 that invokes TA2 (using the already opened session): TA1 is informed that TA2 is dead.
    (TEE core behaves as expected and does not panic, only TA2 has panicked where expected)

I've tested this using latest OP-TEE (4.10.) but I strong think this behavior can be reproduced on OP-TEE tags 3.1x.0 and 3.2x.0.

**Comment by etienne-lms** [comment]
My bad! I've run my test on OP-TEE 3.19.0 and... indeed OP-TEE OS crashes when TA1 invokes TA2 after CA has made TA2 to panic. TEE core trace message looks a lot like the trace message you found:
```
E/TC:0 0 
E/TC:0 0 Core data-abort at address 0x10 (translation fault)
E/TC:0 0  fsr 0x00000005  ttbr0 0x0e1b786a  ttbr1 0x0e1b006a  cidr 0x4
E/TC:0 0  cpu #0          cpsr 0xa0000133
E/TC:0 0  r0 0x00000000      r4 0x00000000    r8 0x93868c90   r12 0x00272104
E/TC:0 0  r1 0x00000000      r5 0x00116e08    r9 0x937f4fdb    sp 0x93868b20
E/TC:0 0  r2 0xffffffff      r6 0x00000001   r10 0x00000000    lr 0x937f489b
E/TC:0 0  r3 0x00000000      r7 0x93868b20   r11 0x00000000    pc 0x937be5e0
E/TC:0 0 TEE load address @ 0x937aa000
E/TC:0 0 Call stack:
E/TC:0 0  0x937be5e0
E/TC:0 0  0x937f489b
E/TC:0 0  0x937f50eb
E/TC:0 0  0x937b1a48
```

I have not bisect to find where this situation got fixed between 3.19.0 tag and 4.1.0 tag.

**Comment by etienne-lms** [comment]
After some investigation, the issue you face is related to https://github.com/OP-TEE/optee_os/issues/6226 (that issue deals with a deadlock case). The issue was addressed though https://github.com/OP-TEE/optee_os/pull/6281 (commit c10e3fa93d24) with an added fixup (https://github.com/OP-TEE/optee_os/pull/6378 / commit 0a75d4083e2e). A regression test was added to cover the case, see https://github.com/OP-TEE/optee_test/pull/693).

**Comment by ydonghyuk** [comment]
@etienne-lms 

Thank you so much for your help.
I will check and comment.

**Comment by ydonghyuk** [comment]
@etienne-lms 

I applied the 4 commits below. Is this correct?
0a75d4083 core: fix data abort during ftrace
c10e3fa93 core: fix race in handling TA panic
5a5d1173d core: add release_state to struct ts_ops
1a6043750 core: vm_info_final(): clear vm_info.asid only

After application, it was confirmed that it operates as follows.
When calling TEE_InvokeTACommand in TA1, TEEC_ERROR_TARGET_DEAD error is returned without stuck phenomenon.

**Comment by etienne-lms** [comment]
Yes, I think you made it right. I think there is a conflict to resolve but IMHO it's quite obvious to sort it out.

**Comment by ydonghyuk** [comment]
I applied the above 4 patches on optee 3.22,
It was applied well without any conflict issues.
Thank you so much for your help.
