### ISSUE TITLE
Does OPTEE support NPU (Neural Processing Unit)?

### ISSUE THREAD

**Issue by sungkeunsong** [OP-TEE/optee_os#6761]
Hi experts,

I want to know if optee side can utilize NPU and for this, SoC has to support SDK for NPU.

Thanks

**Comment by jbech-linaro** [comment]
Hi, in theory yes I suppose, in practice I would say no, since it's a memory constrained environment. From what I know there are no SoC's out there who have tried to do this via OP-TEE. Storing models security is an area of interest though. But having said that, I have no deep understanding in the NPU area, so please read my advice and comment based on that.

**Comment by jforissier** [comment]
Not much more to add to @jbech-linaro, I do not know NPU environments very well either. Regarding running AI in a memory-constrained environment (and with minimal code/dependencies which is also a thing to consider when developing for a secure environment), I remember reading a paper about splitting models in two parts and having a small piece in secure world while the rest is in normal world. IIRC secure world only has one layer of the model or something like that. I will post a link if I can find it.

**Comment by jforissier** [comment]
The paper I had in mind is https://dl.acm.org/doi/10.1145/3386901.3388946.

**Comment by sungkeunsong** [comment]
Your assistance was very helpful. Thank you for your comments
