### ISSUE TITLE
 How to build sdp environment base on linux 6.6

### ISSUE THREAD

**Issue by wayne110** [OP-TEE/optee_os#6777]
I have a question about optee driver on linux 6.6.

I want to use dma-buf to register sharememory to optee,

But I have not found the tee_shm_register_fd in linux 6.6.
 853 static long tee_ioctl(struct file *filp, unsigned int cmd, unsigned long arg)
 854 {           
 855 >...struct tee_context *ctx = filp->private_data;
 856 >...void __user *uarg = (void __user *)arg;
 857             
 858 >...switch (cmd) {
 859 >...case TEE_IOC_VERSION:
 860 >...>...return tee_ioctl_version(ctx, uarg);
 861 >...case TEE_IOC_SHM_ALLOC:
 862 >...>...return tee_ioctl_shm_alloc(ctx, uarg);
 863 >...case TEE_IOC_SHM_REGISTER:
 864 >...>...return tee_ioctl_shm_register(ctx, uarg);
 865 >...case TEE_IOC_SHM_REGISTER_FD:
 866 >...>...return tee_ioctl_shm_register_fd(ctx, uarg);
 867 >...case TEE_IOC_OPEN_SESSION:
 868 >...>...return tee_ioctl_open_session(ctx, uarg);
 869 >...case TEE_IOC_INVOKE:
 870 >...>...return tee_ioctl_invoke(ctx, uarg);
 871 >...case TEE_IOC_CANCEL:
 872 >...>...return tee_ioctl_cancel(ctx, uarg);
 873 >...case TEE_IOC_CLOSE_SESSION:
 874 >...>...return tee_ioctl_close_session(ctx, uarg);
 875 >...case TEE_IOC_SUPPL_RECV:
 876 >...>...return tee_ioctl_supp_recv(ctx, uarg);
 877 >...case TEE_IOC_SUPPL_SEND:
 878 >...>...return tee_ioctl_supp_send(ctx, uarg);
 879 >...default:                                                                                                                                       
 880 >...>...return -EINVAL;
 881 >...}       
 882 }           

Did linaro use another way to support Secure media path between REE and TEE on the newest linux?

Or whether linaro maintain the shm APIs to use dma-buf in other branches?

**Comment by jenswi-linaro** [comment]
SDP is not supported (yet?). I ran across this https://github.com/OP-TEE/optee_test/issues/716 though.

**Comment by jenswi-linaro** [comment]
I guess https://github.com/linaro-swg/linux/issues/118 is the same question.

**Comment by jbech-linaro** [comment]
Hi, like Jens said, since ION was removed from the Linux kernel, we haven't been able to re-enable SDP. Work has been done (and is ongoing) trying to get that up and running again with dma-buf. You'll find patches on the kernel mailinglist for this. In addition to that we've been a couple of people from Linaro, Google, Arm, Qualcomm etc who have met a couple of times to discuss this. You can find more about that here:
- [Meeting notes](https://docs.google.com/document/d/1rWNDr4OGyvyQ1-phUsnNryYHohd-IltMZHnUZAh9WYg/edit)
- [LTF meeting with recording](https://linaro.atlassian.net/wiki/spaces/LTF/pages/29111451760/2024-01-17+LTF+-+dma+buf+Secure+Heaps)

If you just want to play around with SDP on a somewhat recent OP-TEE setup, then you can try a setup I did a couple of months ago, however, this is based on older patches from NXP, so likely if we ever end up with a getting this supported in kernel, it will likely look a lot different to this setup. But with this, I've re-enabled SDP and SDP test etc in OP-TEE.
```bash
mkdir optee-sdp && cd optee-sdp
repo init -u https://github.com/jbech-linaro/manifest.git -m qemu_v8.xml -b nxp-sdp
repo sync -j12
cd build
make toolchains
make -j24 CFG_SECURE_DATA_PATH=y CFG_CORE_ASLR=n CFG_TA_ASLR=n run
When reaching the shell, type: xtest --sdp-basic
```

**Comment by wayne110** [comment]
@jenswi-linaro @jbech-linaro Many thanks.
I will get the code and verify it.
