### ISSUE TITLE
Is bluetooth low energy / classic bluetooth fully supported in the op-tee build

### ISSUE THREAD

**Issue by jamesxyzzy** [OP-TEE/optee_os#6809]

**Comment by jbech-linaro** [comment]
Impossible to give a 100% accurate answer, since it depends on the the hardware where you intend to run it, as well as if that hardware has support for drivers etc. Without checking, I believe that you can enable Bluetooth tools etc via Buildroot (see my answer in your other issue). For Lilnux kernel, you probably have to various drivers and frameworks as well. On secure side OP-TEE, there is no support for this at all.
