### ISSUE TITLE
Is it possible to pass pointer fields in the structure to TA

### ISSUE THREAD

**Issue by pluto-llf** [OP-TEE/optee_os#6924]
Description:

I have two structures defined as follows:
```c
typedef struct {
    int dim;
    int hidden_dim;
    int n_layers;
    int n_heads;
} Config;

typedef struct {
    float* wq;
    float* wk;
    float* wv;
    float* wo;
    float* w1;
    float* w2;
    float* w3;
} Weights;
```
Firstly, the structures have been properly initialized, and the same structure definitions exist both in CA and TA. I attempted to pass the values of these structures to the TA using the following method:
```c
size_t weights_size = sizeof(Weights);
uint8_t *weights_buffer = (uint8_t *)malloc(weights_size);
memcpy(weights_buffer, &weights, weights_size);
op.params[0].tmpref.buffer = weights_buffer;
op.params[0].tmpref.size = weights_size;
```
And then receive them in the TA:
```c
Weights *weights = (Weights *)malloc(params[0].memref.size);
memcpy(weights, params[0].memref.buffer, params[0].memref.size);
```
It seems that the data pointed to by the pointer variables in the Weights structure cannot be successfully transmitted, leading to incorrect output results. I used the same method for the `Config` structure and was able to correctly output the values of its parameters.

Is there a way to transmit such a structure with pointer fields to the TA?

**Comment by etienne-lms** [comment]
> Is there a way to transmit such a structure with pointer fields to the TA?

No. The GP TEE spec OP-TEE is based on allows only 4 TA invocation parameters which can each be either a value (2x32bit values) or memory references (memref). You may need to serialize you data into 1 to 4 memory buffers so that they can be passed to the TA.

Another comment: I think you should check whether `float` type really has the same representation between the CA and the TA. You may need to formalize that in your TA interface.

**Comment by pluto-llf** [comment]
Thank you for clarifying the constraints. I'll do some testing later
