### ISSUE TITLE
build error when cloning with depth of 1

### ISSUE THREAD

**Issue by vchong** [OP-TEE/optee_os#703]
`git clone --depth 1 https://github.com/OP-TEE/optee_os.git` will cause an error during build like:

`mk/config.mk:95 *** Could not parse TEE_IMPL_VERSION (8a933cc), expected format: <major>.<minor>[anything else]. Stop.`

because `git describe --always --dirty=-dev` returns something like `8a933cc` instead of `1.1.0-79-8a933cc`.

**Comment by jforissier** [comment]
The only fix I can think of would be to hard-code the current version in the main Makefile instead of trying to get it from Git. Which means duplicating some information, but it may be preferable for better flexibility -- it would allow building from a tarball also. Actually this is the kernel's way so it must be good ;)
Opinions?

**Comment by pascal-brand-st** [comment]
#705 solves it
