### ISSUE TITLE
make run not launching qemu when GDBSERVER flag is set in QEMU v8 build

### ISSUE THREAD

**Issue by abhishekiitm** [OP-TEE/optee_os#7035]
Hi,

I am trying to set up the `GDB normal world` section present in the [docs](https://optee.readthedocs.io/en/latest/building/devices/qemu.html) 

I have followed the following steps 
```
$ mkdir optee
$ cd optee
$ repo init -u https://github.com/OP-TEE/manifest.git -m qemu_v8.xml
$ repo sync
$ cd build
$ make toolchains
$ make -j8 run GDBSERVER=y
```

After running the command `make -j8 run GDBSERVER=y`, the QEMU console doesn't start. Instead, the build process finishes without any error. I have attached the [logs.txt](https://github.com/user-attachments/files/16968424/logs.txt) that I see on running this command.

I am running this on an Ubuntu 20.04.

Would you have any ideas on how to get this working? Please let me know if I should share any additional info that might be useful to debug this.

**Comment by jbech-linaro** [comment]
I can reproduce the error and took a quick look. It's related to a) [BUILDROOT_TOOLCHAIN](https://github.com/OP-TEE/build/blob/master/common.mk#L249) which in turn set's [these](https://github.com/OP-TEE/build/blob/master/br-ext/configs/toolchain-br). Most likely the information in there needs to be updated to match more recent versions of Buildroot. I did a quick test, but no success. But still, I'm pretty sure that this is where the issue is.
