### ISSUE TITLE
tee_mm_init issues with MMU shift value

### ISSUE THREAD

**Issue by hemanth-puranik** [OP-TEE/optee_os#723]
In tee_mm_init() function there is an issue on ARM v8 with LPAE. For L1 table the shift value is 30 in which case pool->hi and pool->lo values are not right.

For eg if hi is 0x4000000 and low is 0x2000000 (which is the case while we init tee_mmu_virt_kmap) after : 

lo = ROUNDUP(lo, 1 << shift);
hi = ROUNDDOWN(hi, 1 << shift);

pool->hi and pool->lo will end up with wrong values which results in an assert while running xtest 100x.

**Comment by pascal-brand-st-dev** [comment]
On FVP, tee_mmu_virt_kmap() is initialized with L2 table, that is with a shift 21. Everything went fine in my experiments.

**Comment by hemanth-puranik** [comment]
Just to elaborate on this, I faced this issue while running xtest but clearly when the page shift is 30 the lines 

lo = ROUNDUP(lo, 1 << shift);
hi = ROUNDDOWN(hi, 1 << shift);

wont work as expected, we need to change the above right ?

**Comment by jenswi-linaro** [comment]
@hemanth-puranik, I suspect that you're not testing this on one of our supported platforms as we haven't noticed the problem there.

I think `tee_mmu_kmap_init()`, `TEE_MMU_KMAP_START_VA`, and `TEE_MMU_KMAP_END_VA` is the problem here. `tee_mmu_kmap_init()` depends on kmap va range to be represented by translation tables that have a fine enough granularity.

One way around the problem is if `tee_mmu_kmap_init()` would take a dynamic approach similar to the one used to find a suitable va range to map user TAs in.

**Comment by hemanth-puranik** [comment]
@jenswi-linaro Yes we are testing this on our v8 platform. Ya but as you mention currently `TEE_MMU_KMAP_START_VA` and `TEE_MMU_KMAP_END_VA` are fixed as below which is causing the issue :

`#define TEE_MMU_KMAP_START_VA       (32 * 1024 * 1024)
#define TEE_MMU_KMAP_END_VA     (64 * 1024 * 1024)`

`tee_mmu_kmap_init()` needs to be smart enough to find the valid range depending on the 'shift' value rather than hard coding this.

**Comment by MrVan** [comment]
You need to remap your device address to avoid conflicts work kmap address space.

**Comment by jenswi-linaro** [comment]
In this case I suspect that there's nothing mapped at all in 0..0x40000000, that would explain the large shift value.

**Comment by jbech-optee-adm** [comment]
@hemanth-puranik did the answer from people here answer your questions? If you have more questions, please re-open the issue.
