### ISSUE TITLE
Inter-TA IPC

### ISSUE THREAD

**Issue by hoihochan** [OP-TEE/optee_os#780]
Are there any thoughts on how to implement IPC between TAs?

For example:

- TA1 sends an encrypted message to TA2, and only TA2 can decrypt the message
- The message is also authenticated: TA2 knows the message comes from TA1 and not anybody else.

**Comment by jenswi-linaro** [comment]
The *GlobalPlatform TEE Internal Core API* specification describes a way for TAs to communicate with each other via `TEE_OpenTASession()` and `TEE_InvokeTACommand()`.

**Comment by hoihochan** [comment]
Thanks. This is not encrypted, but depends on the fact that TZ RAM is protected by TZASC. Do we also allocate another thread for the receiving TA and set up translation tables?

**Comment by hoihochan** [comment]
Is there an xtest case for this already or something I can help contribute?

**Comment by jenswi-linaro** [comment]
There's no point in encrypting when doing `TEE_InvokeTACommand()` because if we can't trust the translation tables then we can't trust what's encrypted any way.

This kind of communication is synchronous so they use the same thread, but we change translation tables as part of changing active TA.

Test case 1006 and 1011 does some `TEE_InvokeTACommand()`, but I guess there's corner cases which aren't covered. I suspect that timeout of chained invokes doesn't have proper tests, if any.

If you're looking for something else to improve you could look into dividing test case 1006 (TA_OS_TEST_CMD_BASIC) into several sub tests as that has become a bit of a kitchen sink with lots of unrelated tests.

**Comment by hoihochan** [comment]
Thanks. If we send a large chunk of data between two TAs using `TEE_InvokeTACommand()`, what would be the best param type to use to ensure only the two TAs are allowed to access?

**Comment by jenswi-linaro** [comment]
It doesn't matter, all of them are supposed to be equally secure as long as it's not references to non-secure shared memory.

**Comment by hoihochan** [comment]
Because during the TA->TA call it won't get interrupted?

**Comment by jenswi-linaro** [comment]
No, they can be interrupted (interrupt delivered to normal world, the operation is resumed when normal world returns from the interrupt) but the memory can't be mapped for something else in the meantime.

**Comment by hoihochan** [comment]
Thanks, so between the TA1 -> TA2 IPC call, the memory used by TA1 can't be mapped for another TA's use.

**Comment by jenswi-linaro** [comment]
Correct
