### ISSUE TITLE
What is the best way to interface with OPTEE from a non-linux normal world?

### ISSUE THREAD

**Issue by dsblue** [OP-TEE/optee_os#793]
Is there a bare-metal library in place that enables interaction with OPTEE from the normal world, but does not require Linux?  I hope that this request makes sense.  I have a static TA running in OPTEE and I can currently hand-craft packets and call SMC to pass data to OPTEE, but I'd like to leverage the OPTEE API for this.  
My current approach is to pull the low-level functionality for interfacing OPTEE from optee_linuxdriver, however I was wondering if anyone had run in to this before, and may have a better approach?  Maybe a build option that would be useful for me?

Note:  I don't necessarily need full GlobalPlatform API support at this point

**Comment by jenswi-linaro** [comment]
Hi,

I'm not aware of anyone doing the client part in bare-metal. It's been done in the prehistory of OP-TEE, but that code is neither available nor applicable any longer.

When doing a bare-metal implementation of the client lib, the critical part is to map the shared memory correctly. As you have a static TA you can hopefully avoid implementing parts of a bare-metal supplicant.

Another thing to keep in mind is to make sure that OP-TEE is ready to make a fresh start on shared memory allocation when Linux is booting (some RPC objects may otherwise be cashed etc).

**Comment by dsblue** [comment]
Thanks for that info, i thought there might be a repo somewhere that I was missing, but I guess not. 

As a related side question, is there resource that you know of that list the platforms/SoCs for which Linux supports booting within normal world? I would like to look at some of them to see how they handle things like PLL configuration from the normal world as that stuff seems to be locked down on the TrustZone enabled SoCs I have looked at.

**Comment by jenswi-linaro** [comment]
No, I'm not aware of any such list.

**Comment by dsblue** [comment]
Thanks
