### ISSUE TITLE
OP-TEE and hypervisor in normal world

### ISSUE THREAD

**Issue by helen-fornazier** [OP-TEE/optee_os#807]
Hi!

I would like to know if I can have optee running in the secure world and an hypervisor with several guest OSes in the normal world.
If so, how doesn't optee knows to which guest OS a request came from? Does the hypervisor need to be aware of optee?

Thank you

**Comment by jenswi-linaro** [comment]
Hi,

Yes, that should possible but is untested. One thing I know need to be fixed is to tie the open sessions to a specific guest to avoid guests interfering/interacting with each other.

The hypervisor need to be aware of OP-TEE in order to translate intermediate physical addresses from the guest into real physical addresses used by OP-TEE and vice versa. There's also `r7`, the *Hypervisor Client ID register* which need to be assigned by the hypervisor for each `smc`.

Regards,
Jens

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
