### ISSUE TITLE
ramdisk.img size

### ISSUE THREAD

**Issue by Miraje** [OP-TEE/optee_os#822]
Hi,

I recently tried to update my OP-TEE files using `repo sync` and in the end it showed that the current `ramdisk.img` size was `29.15 MB` as shown below:
```
Image Type:   AArch64 Linux RAMDisk Image (gzip compressed)
Data Size:    30563157 Bytes = 29846.83 kB = 29.15 MB
Load Address: 00000000
Entry Point:  00000000
```

As the `/JUNO/SITE1/HBI0262B/images.txt` limits it to `8.3 MB` I am guessing that I should update `NOR4ADDRESS` , is that right? 

The increased size comes from the lib folder, could it be because of the use of gcc5?

Note: I tried in downloading all files again but got the same thing. I compiled for the juno board.

**Comment by Miraje** [comment]
Update: I tried to compile the files with a previous version of the `build` repository to the gcc5 update, more specifically to the `Fix conditional include of driver module (cfb99cf)` and the size of `ramdisk.img` went to `7.6 MB` again.

**Comment by jbech-linaro** [comment]
@Miraje yes, we've noticed that too for other platforms. You're right, this comes from the use of GCC5, the reason seems to be that we get quite a few more files copied into the root fs [here](https://github.com/linaro-swg/gen_rootfs/blob/master/generate-cpio-rootfs.sh#L37-L41).

If it's possible to increase the `/JUNO/SITE1/HBI0262B/images.txt`, then yes, please do so. Would you mind investigate if that is possible and if yes, please provide a fix?

**Comment by Miraje** [comment]
@jbech-linaro Yes of course, I will look into it, as soon as I find something I will let you know.

**Comment by Miraje** [comment]
@jbech-linaro Good news, I modified the `NORXADDRESS` addresses on the `images.txt` file and increased the size available for `ramdisk.img` to `32MB` so now everything works fine :)

As I modified `/JUNO/SITE1/HBI0262D/images.txt` how should I provide a fix? 
I can create a patch for the file? or do you think there is a better way?

**Comment by Miraje** [comment]
@jbech-linaro  What do you think?

**Comment by jbech-linaro** [comment]
@Miraje , thanks for verifying that it worked when increasing the size. A fix for it? Yeah, that's a good question since that isn't something directly included in something coming from us. But we already mention this in the README ([here](https://github.com/OP-TEE/optee_os#572-globalplatform-testsuite-support)), so I guess the best way to fix it is to update the README.md.

Would you mind create a patch and pull request for it ([instructions](https://github.com/OP-TEE/optee_os/blob/master/documentation/github.md#contributing))? If not, we will pick it up / fix it sooner or later (when depends on how important it is).

**Comment by Miraje** [comment]
@jbech-linaro Done :)
