### ISSUE TITLE
Unable to flash debian_system.img with OPTEE on Hikey

### ISSUE THREAD

**Issue by Machiry** [OP-TEE/optee_os#832]
I followed all the instructions (using repo) for building debian for Hikey.
There are 2-issues I faced:

1) Errors while building edk2:

I fixed this by changing hikey_debian.mk: GCC49_AARCH64_PREFIX=$(AARCH64_CROSS_COMPILE) to GCC49_AARCH64_PREFIX=$(**LEGACY_**AARCH64_CROSS_COMPILE)

2) make flash fails to flash system.img:

fastboot flash system ../out/debian_system.img
target reported max download size of 268435456 bytes
sending sparse 'system' (262140 KB)...
OKAY [ 14.893s]
writing 'system'...
FAILED (remote: Error flashing partition.)
finished. total time: 14.895s
make: *** [flash] Error 1

Did anyone successfully flashed debian/optee on Hikey?

**Comment by jbech-linaro** [comment]
@Machiry ,

Thanks for reporting the issue and a fix for the compiler errors. If you want too, feel free to submit a patch for it via a pull request ([instructions](https://github.com/OP-TEE/optee_os/blob/master/documentation/github.md#contributing)). If not, then we will pick it up rather soon.

**Did anyone successfully flashed debian/optee on Hikey?**
Yes, it's still an "experimental" build with lots of small things to be fixed. Having that said I was running it successfully multiple times when I pushed that particular build. Also a colleague of mine used it ~2 weeks ago when he participated in a joint test session with GlobalPlatform.

We will make the OP-TEE 2.1.0 release by the end of this month. Hopefully we will have at least sorted out any eventual issue by then. If you in the interim however find a solution for the issue, then we would be more than happy to hear about it.

**Comment by jbech-linaro** [comment]
@Machiry with your proposed fix, all builds fine and it also flashes fine for me. No issues there. However, when I install my own build kernel (the *.deb packages), then it fails during boot complaining about initramfs. I've rebuilt a couple of times today (takes forever to rebuild stuff), but no success. So, build + flash works, boot does not. I'm not sure when I can find more time to try this again, since I have a few other things I'm working with right now.

**Comment by Machiry** [comment]
@jbech-linaro ,
I forgot to update. Yes, I was able to flash too and debian works without op-tee .deb packages. 
But, after I install the debs, it fails to boot.

**Comment by jbech-linaro** [comment]
@Machiry , some good news! I gave it a last try and looked more into the error messages. It seems like it's a known issue that comes with GCC5 (relocation error) on older kernel versions. A patch has been provided in later kernel revisions.

I took that patch and applied it manually on the kernel tree used in hikey_debian.xml and voila! It works! (Your patch is of course also still needed). Since I now know how to get it working again. I'll do some updates tomorrow.

The patch you need is this one:
https://github.com/torvalds/linux/commit/67dfa1751ce71e629aad7c438e1678ad41054677

**Comment by jbech-linaro** [comment]
So, all should work now. The edk2 fix has been merged and I've just cherry-picked the Linux kernel fix and pushed that to the https://github.com/linaro-swg/linux/commits/experimental/96b_rpb_1603_optee_debian branch.

**Comment by jbech-linaro** [comment]
I'll try to build using the official 96boards 16.06 RPB branch. It seems like that already have that fix included. If that is working, then I'm gonna update the manifest to point to that branch instead. In the end, that is an official branch, while our is a fork and a bit experimental.

**Comment by Machiry** [comment]
Thanks @jbech-linaro. It works with the relocation patch.
