### ISSUE TITLE
Usage "native" bitmapfonts

### ISSUE THREAD

**Issue by d3zd3z** [OP-TEE/optee_os#837]
The python-wand dependency pulls in a _lot_ of code. For environments such as OE or even travis, it pulls in a few hundred MB of additional packages (cairo, imagemagick, etc.). When building OE, these dependencies end up getting built.

Instead, perhaps we should consider using a pre-defined bitmap font, such as one of the kernel console fonts. Another option would be to just convert the fonts manually, and check in the bitmap version.

**Comment by jenswi-linaro** [comment]
My first proposal was indeed converting the fonts in advance and check them in.

**Comment by jforissier** [comment]
@d3zd3z it was me who asked for the `.h` files to be generated at build time. It's funny that you're asking to remove this due to the OE build, I mean, OE and BitBake follow the "always build everything from source" philosophy, don't they? That's what we're doing, too ;)
As for Travis, I don't see any problem, installing the required dependencies takes 65 KB and 1 second (https://travis-ci.org/OP-TEE/optee_os/builds/135845983#L1523). Probably because most deps are already installed and it's just the Python package that's being pulled.

This said, we could move the generated files into the source tree and commit them (but still keep the build rules). Not a very good option IMO because the build rules would be subject to bitrot. But still acceptable I think.

**Comment by d3zd3z** [comment]
Actually, my suggestion was more along the lines of finding fonts that are already represented as bitmaps.

**Comment by jbech-linaro** [comment]
Do we want to do something about this as of now? I see this as a future improvement / enhancement. Is it worth keeping this as an open issue or should we simply close it? Comment? @d3zd3z @jforissier ?

**Comment by jbech-linaro** [comment]
TUI stuff was removed in #1844.

**Comment by jbech-optee-adm** [comment]
We are closing this issue/question, why?
 - We believe the question has been answered.
 - Quite often when we have answered the questions, the issuer forget to close the issue which results in many open issues for us which makes it hard to keep track of the ones actually waiting for an answer.
 - In some cases we ask follow-up questions, but do not hear back from the one creating the issue.

If you however feel that you have additional questions or still thinks this is an issue, then please feel free to re-open the issue again. When closing issues we will only show this entire message once.

// OP-TEE admins
