### ISSUE TITLE
 error 7000: Failed to execute command 	make tbuild 

### ISSUE THREAD

**Issue by symu1818** [OP-TEE/optee_os#842]
I am trying to use the Hikey with the debian option, however when I perform "make all" I got the next errors:

Do you know how can be solved?

error 7000: Failed to execute command
	make tbuild [/home/develdeb/optee/edk2/Build/HiKey/RELEASE_GCC49/AARCH64/ArmPlatformPkg/PrePi/PeiMPCore]

Thanks!

**Comment by jbech-linaro** [comment]
@symu1818 ,

I haven't checked hikey_debian experimental build since we stepped up to GCC5.x, so it might be that there is some issue. One of the open questions (which makes this build experimental) is the way we're dealing with EDK2. Basically we pick the edk2, prebuilt ([here](https://github.com/OP-TEE/build/blob/master/hikey_debian.mk#L27)). But at the same time we anyhow build EDK2 from source as we do on the other targets (see [here](https://github.com/OP-TEE/build/blob/master/hikey_debian.mk#L118) and [here](https://github.com/OP-TEE/build/blob/master/hikey_debian.mk#L125-L148)). That is simply wrong. Having that said, it worked fine when I initially created and added the experimental HiKey debian patch. But, I'm a bit worried that something might have sneaked in with the GCC5.3 update.

As you can read on the [commit message](https://github.com/OP-TEE/build/commit/a40320b1cf8d2daa42e295ba4659e5561477b606), there is still quite a lot to do regarding the Debians builds until we can remove the "experimental" part from that particular build.

We will make the OP-TEE 2.1.0 release by the end of this month. Hopefully we will have at least sorted out any eventual build issue. But I don't think we have time to do a fix that properly handle edk2.

**Comment by symu1818** [comment]
OK thank you. 

My main problem is that I tried Hikey Initramfs based first. However, I do not know how to transfer files (as trusted applications executable files), since no USB or SD is detected by the Hikey board using Initramfs version.

Do you know how can I tranfer files to Hikey after flashing it?

**Comment by jbech-linaro** [comment]
When I'm using initramfs, I'm only relying on rebuilding the rootfs. I haven't tried it, but I'm pretty sure it would be possible to setup the WiFi and then install [Dropbear SSH](https://matt.ucc.asn.au/dropbear/dropbear.html) for example and then after having that up running you could use SSH instead of having to root fs when you update the TA's. I have no idea how much work it'd be to get it working, but I imagine that you'd need to enable some flags and rebuild the Linux kernel and then compile and put some user space tools dealing with the WiFi.

**Comment by jbech-linaro** [comment]
@symu1818 it seems like @Machiry found out why it failed, see the first part of his question in #832.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.

**Comment by ademyankov** [comment]
I am having the similar problem building EDK2 for OPTEE qemu_v8 in Windows 10 WSL.
**Is there a trick I can try to fix that?**
> 4.4.0-43-Microsoft GNU/Linux
> Distributor ID: Ubuntu
> Release: 16.04
> Codename: xenial
> 

```
Architecture(s)  = AARCH64
Build target     = DEBUG
Toolchain        = GCC49

Active Platform          = /mnt/c/projects/optee/edk2/ArmVirtPkg/ArmVirtQemuKernel.dsc
Flash Image Definition   = /mnt/c/projects/optee/edk2/ArmVirtPkg/ArmVirtQemuKernel.fdf

Processing meta-data ...... done!
Building ... /mnt/c/projects/optee/edk2/MdePkg/Library/DxePcdLib/DxePcdLib.inf [AARCH64]
Building ... /mnt/c/projects/optee/edk2/MdePkg/Library/BaseMemoryLibOptDxe/BaseMemoryLibOptDxe.inf [AARCH64]
Building ... /mnt/c/projects/optee/edk2/MdePkg/Library/BaseLib/BaseLib.inf [AARCH64]
Building ... /mnt/c/projects/optee/edk2/MdePkg/Library/BaseIoLibIntrinsic/BaseIoLibIntrinsic.inf [AARCH64]
make[2]: Entering directory '/mnt/c/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/BaseMemoryLibOptDxe/BaseMemoryLibOptDxe'
make[2]: Leaving directory '/mnt/c/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/BaseMemoryLibOptDxe/BaseMemoryLibOptDxe'
make[2]: Entering directory '/mnt/c/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/DxePcdLib/DxePcdLib'
make[2]: Leaving directory '/mnt/c/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/DxePcdLib/DxePcdLib'
Building ... /mnt/c/projects/optee/edk2/ArmVirtPkg/Library/ArmVirtDxeHobLib/ArmVirtDxeHobLib.inf [AARCH64]
make[2]: *** No rule to make target '/home/ademyankov/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/BaseMemoryLibOptDxe/BaseMemoryLibOptDxe/GNUmakefile', needed by '/home/ademyankov/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/BaseMemoryLibOptDxe/BaseMemoryLibOptDxe/OUTPUT/AArch64/ScanMem.obj'.  Stop.
make[2]: *** No rule to make target '/home/ademyankov/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/DxePcdLib/DxePcdLib/GNUmakefile', needed by '/home/ademyankov/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/DxePcdLib/DxePcdLib/OUTPUT/DxePcdLib.obj'.  Stop.
make[2]: Entering directory '/mnt/c/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/BaseLib/BaseLib'
make[2]: Leaving directory '/mnt/c/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/BaseLib/BaseLib'
Building ... /mnt/c/projects/optee/edk2/ArmPlatformPkg/Drivers/PL011Uart/PL011Uart.inf [AARCH64]
make[2]: *** No rule to make target '/home/ademyankov/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/BaseLib/BaseLib/GNUmakefile', needed by '/home/ademyankov/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/BaseLib/BaseLib/OUTPUT/CheckSum.obj'.  Stop.


build.py...
 : error 7000: Failed to execute command
        make tbuild [/mnt/c/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/BaseMemoryLibOptDxe/BaseMemoryLibOptDxe]


build.py...
 : error 7000: Failed to execute command
        make tbuild [/mnt/c/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/DxePcdLib/DxePcdLib]


build.py...
 : error 7000: Failed to execute command
        make tbuild [/mnt/c/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/BaseLib/BaseLib]


build.py...
 : error 7000: Failed to execute command
        make tbuild [/mnt/c/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/BaseIoLibIntrinsic/BaseIoLibIntrinsic]


build.py...
 : error 7000: Failed to execute command
        make tbuild [/mnt/c/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/BaseDebugPrintErrorLevelLib/BaseDebugPrintErrorLevelLib]


build.py...
 : error 7000: Failed to execute command
        make tbuild [/mnt/c/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/ArmVirtPkg/Library/ArmVirtDxeHobLib/ArmVirtDxeHobLib]


build.py...
 : error 7000: Failed to execute command
        make tbuild [/mnt/c/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/ArmPlatformPkg/Drivers/PL011Uart/PL011Uart]


build.py...
 : error F002: Failed to build module
        /mnt/c/projects/optee/edk2/MdePkg/Library/BaseMemoryLibOptDxe/BaseMemoryLibOptDxe.inf [AARCH64, GCC49, DEBUG]

- Failed -
Build end time: 15:28:00, Dec.15 2017
Build total time: 00:00:08

ArmPlatformPkg/Scripts/Makefile:58: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/mnt/c/projects/optee/edk2'
common.mk:218: recipe for target 'edk2-common' failed
make: *** [edk2-common] Error 2
```

**Comment by jbech-linaro** [comment]
Hi,

This might not be the answer, but in the last three weeks, I faced at least two issues when trying to update our "build.git" to use upstream EDK2 instead of running an older version from the ARM Landing team in Linaro. Both of them has been resolved and the [cron job running last night passed](https://travis-ci.org/OP-TEE/build/builds/317868664) on all platforms. So, what I'm trying to say is that, please try to update so you are sure you are running latest. Other than that I'm afraid you are a bit on your own, since no-one in the OP-TEE team are building this using Windows, all of us are native Linux environments. Also our experience with EDK2 is a bit limited, since we are mainly just using it where needed and we do not do any development (in our team) for it.

**Comment by ademyankov** [comment]
Ok, I tried to update the repo and rebuild. It didn't help. Anyway, thanks for the replay, and I'll keep digging...

**Comment by Poojakumari-git** [comment]
> I am having the similar problem building EDK2 for OPTEE qemu_v8 in Windows 10 WSL. **Is there a trick I can try to fix that?**
> 
> > 4.4.0-43-Microsoft GNU/Linux
> > Distributor ID: Ubuntu
> > Release: 16.04
> > Codename: xenial
> 
> ```
> Architecture(s)  = AARCH64
> Build target     = DEBUG
> Toolchain        = GCC49
> 
> Active Platform          = /mnt/c/projects/optee/edk2/ArmVirtPkg/ArmVirtQemuKernel.dsc
> Flash Image Definition   = /mnt/c/projects/optee/edk2/ArmVirtPkg/ArmVirtQemuKernel.fdf
> 
> Processing meta-data ...... done!
> Building ... /mnt/c/projects/optee/edk2/MdePkg/Library/DxePcdLib/DxePcdLib.inf [AARCH64]
> Building ... /mnt/c/projects/optee/edk2/MdePkg/Library/BaseMemoryLibOptDxe/BaseMemoryLibOptDxe.inf [AARCH64]
> Building ... /mnt/c/projects/optee/edk2/MdePkg/Library/BaseLib/BaseLib.inf [AARCH64]
> Building ... /mnt/c/projects/optee/edk2/MdePkg/Library/BaseIoLibIntrinsic/BaseIoLibIntrinsic.inf [AARCH64]
> make[2]: Entering directory '/mnt/c/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/BaseMemoryLibOptDxe/BaseMemoryLibOptDxe'
> make[2]: Leaving directory '/mnt/c/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/BaseMemoryLibOptDxe/BaseMemoryLibOptDxe'
> make[2]: Entering directory '/mnt/c/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/DxePcdLib/DxePcdLib'
> make[2]: Leaving directory '/mnt/c/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/DxePcdLib/DxePcdLib'
> Building ... /mnt/c/projects/optee/edk2/ArmVirtPkg/Library/ArmVirtDxeHobLib/ArmVirtDxeHobLib.inf [AARCH64]
> make[2]: *** No rule to make target '/home/ademyankov/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/BaseMemoryLibOptDxe/BaseMemoryLibOptDxe/GNUmakefile', needed by '/home/ademyankov/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/BaseMemoryLibOptDxe/BaseMemoryLibOptDxe/OUTPUT/AArch64/ScanMem.obj'.  Stop.
> make[2]: *** No rule to make target '/home/ademyankov/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/DxePcdLib/DxePcdLib/GNUmakefile', needed by '/home/ademyankov/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/DxePcdLib/DxePcdLib/OUTPUT/DxePcdLib.obj'.  Stop.
> make[2]: Entering directory '/mnt/c/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/BaseLib/BaseLib'
> make[2]: Leaving directory '/mnt/c/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/BaseLib/BaseLib'
> Building ... /mnt/c/projects/optee/edk2/ArmPlatformPkg/Drivers/PL011Uart/PL011Uart.inf [AARCH64]
> make[2]: *** No rule to make target '/home/ademyankov/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/BaseLib/BaseLib/GNUmakefile', needed by '/home/ademyankov/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/BaseLib/BaseLib/OUTPUT/CheckSum.obj'.  Stop.
> 
> 
> build.py...
>  : error 7000: Failed to execute command
>         make tbuild [/mnt/c/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/BaseMemoryLibOptDxe/BaseMemoryLibOptDxe]
> 
> 
> build.py...
>  : error 7000: Failed to execute command
>         make tbuild [/mnt/c/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/DxePcdLib/DxePcdLib]
> 
> 
> build.py...
>  : error 7000: Failed to execute command
>         make tbuild [/mnt/c/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/BaseLib/BaseLib]
> 
> 
> build.py...
>  : error 7000: Failed to execute command
>         make tbuild [/mnt/c/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/BaseIoLibIntrinsic/BaseIoLibIntrinsic]
> 
> 
> build.py...
>  : error 7000: Failed to execute command
>         make tbuild [/mnt/c/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/MdePkg/Library/BaseDebugPrintErrorLevelLib/BaseDebugPrintErrorLevelLib]
> 
> 
> build.py...
>  : error 7000: Failed to execute command
>         make tbuild [/mnt/c/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/ArmVirtPkg/Library/ArmVirtDxeHobLib/ArmVirtDxeHobLib]
> 
> 
> build.py...
>  : error 7000: Failed to execute command
>         make tbuild [/mnt/c/projects/optee/edk2/Build/ArmVirtQemuKernel-AARCH64/DEBUG_GCC49/AARCH64/ArmPlatformPkg/Drivers/PL011Uart/PL011Uart]
> 
> 
> build.py...
>  : error F002: Failed to build module
>         /mnt/c/projects/optee/edk2/MdePkg/Library/BaseMemoryLibOptDxe/BaseMemoryLibOptDxe.inf [AARCH64, GCC49, DEBUG]
> 
> - Failed -
> Build end time: 15:28:00, Dec.15 2017
> Build total time: 00:00:08
> 
> ArmPlatformPkg/Scripts/Makefile:58: recipe for target 'all' failed
> make[1]: *** [all] Error 1
> make[1]: Leaving directory '/mnt/c/projects/optee/edk2'
> common.mk:218: recipe for target 'edk2-common' failed
> make: *** [edk2-common] Error 2  GOT SAME ERROR

**Comment by jforissier** [comment]
qemu_v8.xml does not use EDK2 anymore since commit https://github.com/OP-TEE/manifest/commit/2b88dac3114b05db21e7d562343c13e243270e3d (27-Jul-2023). Please use a more recent version of the manifest, and upgrade your Linux distribution as well (Ubuntu 16.04 will likely not work, I recommend 22.04 or 24.*).
Build instructions: https://optee.readthedocs.io/en/latest/building/devices/qemu.html#qemu-v8
