### ISSUE TITLE
Having trouble putting AOSP + OP-TEE on the HiKey board

### ISSUE THREAD

**Issue by jsherman3** [OP-TEE/optee_os#845]
Hello, I'm currently trying to follow the instructions at: https://github.com/jforissier/hikey_optee/tree/aosp
I cloned the repository and followed the instructions and when I type
make -j8

I get an error in the makefile:

GRUB2 will be compiled with following components:
Platform: arm64-efi
With devmapper support: No (need libdevmapper header)
With memory debugging: No
With disk cache statistics: No
With boot time statistics: Yes
efiemu runtime: No (not available on efi)
grub-mkfont: No (need freetype2 library)
grub-mount: No (need FUSE library)
starfield theme: No (No build-time grub-mkfont)
With libzfs support: No (need zfs library)
Build-time grub-mkfont: No (need freetype2 library)
Without unifont (no build-time grub-mkfont)
Without liblzma (no support for XZ-compressed mips images) (need lzma library)
*******************************************************
make[1]: Leaving directory `/home/jsherman/Documents/AOSP/hikey_optee'
make: *** [_all] Error 2
I was wondering if anyone else was getting this error?

**Comment by jforissier** [comment]
Hello @jsherman3,

I can't tell what is wrong with your setup, because due to `-j8` the text you copied does not contain the actual error message that cause make to stop. But, please note that the repository and branch you have cloned is outdated. It was meant for initial porting work only. Please consider using this instead: https://github.com/linaro-swg/optee_android_manifest.

**Comment by jsherman3** [comment]
Thank you for your response, 
I noticed in the instructions you gave me, it said there were two different builds for a 8 gb and a 4 gb board.  The only difference between the HiKey boards I noticed was the amount of ram ( 1 or 2 gb ).  I was curious if you could clarify.

**Comment by jforissier** [comment]
4 and 8 GB refer the the amount of flash, 1 and 2 to the amount of RAM. I think the 2 GB boards have 8 GB of flash but I'm not 100% sure.

**Comment by jsherman3** [comment]
Okay thank you. How come the android + optee is not on the official optee github ?

**Comment by jbech-linaro** [comment]
> Okay thank you. How come the android + optee is not on the official optee github ?
I think I can answer that. It's because a couple of things. First we started out building it as Jerome did. But now later on we've started to use the whole tree (AOSP from Google) for the builds since HiKey since a while back has been officially supported. Having that said we have the 96Boards team and LMG (Mobile) team in Linaro that both are the ones mainly dealing with AOSP builds. We (Security Working Group) that owns and maintain OP-TEE mainly supports "stripped" down builds to be used for daily development.

As we're speaking we're in the process of a transition/merging our OP-TEE / AOSP instructions to those two teams. We haven't decided yet, but eventually we will remove all AOSP instructions from the OP-TEE pages (including linaro-swg) when the merge is done and instead just give a URL to the 96Boards or LMG pages containing their build. Simply to avoid duplicating information.

But the best and most accurate instructions for running OP-TEE and AOSP as of today are the ones that Jerome linked to just above. I haven't written those instructions myself. But I've verified that they indeed are working just a couple of weeks ago.

**Comment by jsherman3** [comment]
Thank you for all of your responses. I used the link: https://github.com/linaro-swg/optee_android_manifest and I just got done downloading the android source code, however I can't complete the step after the lunch and which is running the get tool chains script because I don't see a optee folder. Can someone shed some insight on this ?
