### ISSUE TITLE
Implementing TUI for Hikey Platform

### ISSUE THREAD

**Issue by radheshkrishnan** [OP-TEE/optee_os#852]
Hi,

I am willing to work on implementing TUI for Hikey platform and I am looking for guidance. 
Could someone please help me with this?

I did a bit of research on how to go about this and following is my understanding, let me know if I got this wrong:

Going through TUI work done for FVP Base platform, I understand that to implement TUI:
- First, we need to port frame buffer driver to secure world.
- Secondly, port the LCD display controller to secure world. Initialise this LCD controller such a way it reads from secure frame buffer. 
- Finally, when the control is handed over to secure world (i.e, when TUI session is initiated), save the state of LCD controller of normal
  world and pass the control to secure world LCD controller driver.
- Restore the state of normal world display controller driver when the TUI session ends.

First I tried to figure out which is Hikey display controller:
- Hikey board uses Direct Rendering Manager ([DRM](https://github.com/LeMaker/linux-96boards/blob/lemaker-hikey-mainline/drivers/gpu/drm/hisilicon/)) subsystem of the Linux kernel to render images to display/monitor
-  [ADE](https://github.com/LeMaker/linux-96boards/blob/lemaker-hikey-mainline/drivers/gpu/drm/hisilicon/hisi_drm_ade.c)  is the display controller.

So I guess to implement TUI for Hikey platform, I first have to port [DRM](https://github.com/LeMaker/linux-96boards/blob/lemaker-hikey-mainline/drivers/gpu/drm/hisilicon/) to secure world (optee_os/core/drivers). Is that the right way to go? I need a expert advice on this :)

Few more things are not so clear to me yet:  (May be this one is a silly question, but I would like to know the answer)
1. Without porting/adding DRM to optee_os , is it possible to render a image or just a color on LCD monitor from secure world (trusted app)? I know then it won't be a Trusted UI, but still was wondering whether it is possible. If so, how do I do that? Any pointers?  

Thank you so much for your time,
Radhesh

**Comment by jbech-linaro** [comment]
Hi @radheshkrishnan ,

Great news that you are interested in this. The things is that it's hard for us to give any advice here, since dealing with graphics is unfortunately an area where we lack experience. The work done on FVP so far, is working "ok" for a secure side rough demo/proof of concept (follow GP TUI v1.0). The big remaining issue is how to share the framebuffer with normal world. We haven't figured out how to do that. We've started to ask some graphics people for advice, but currently that is a pending activity.

To get somewhere, I think as you suggested it would be a good idea to just try to replicate what has been done on FVP, so the same works on HiKey. That would be a good start. How are you going to display things? Hooking it up to the HDMI? We've been thinking about using a LCD for 96boards ([this one](http://www.lenovator.com/product/102.html)), from rumors I've heard that should be a touch display and that would be ideal when working with TUI.

When we can render stuff on HiKey from secure world, then I think we can start attacking the framebuffer sharing issue.

Also, if you're writing code, you're always welcome to send a "Request For Comment" pull request. I.e, something that might not be meant for merging as of now, just something that you'd like to discuss.

**Comment by jbech-linaro** [comment]
Just an update, we haven't been working with TUI lately, it's currently blocked because of other activities with higher priority and we still haven't been able to find a suitable hardware. Have you @radheshkrishnan been able to look into this on your side? Anything you'd like to share?

**Comment by radheshkrishnan** [comment]
@jbech-linaro, The  LCD for 96boards wasn't available to buy till 2 weeks ago. So I couldn't do much  research on this till now. Last week I ordered LCD for 96boards, ([this one](http://www.lenovator.com/product/102.html)). As soon as I get this on hand, I will update you on this.

**Comment by jbech-linaro** [comment]
This isn't something prioritized on our side as of now. Having that said, it's not the same as saying that we won't do it. But, meanwhile we're involved in other implementations we leave this open for other people. I.e, i.e., we would be more than happy if someone else would champion this issue.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
