### ISSUE TITLE
OP-TEE installation issues on JUNO

### ISSUE THREAD

**Issue by aminusamine** [OP-TEE/optee_os#867]
Hello, 

I have an ARM JUNO card and i want to install OP-TEE on it. 

I'm using the Linaro last deliverable to boot up. Then i installed a Debian on it. However the packages like libc6:i386 are not available on it which make the setup impossible. 

Can anyone help me on it ? Is it better to use an other Linux distribution ? If the response is yes, can you please indicate me the necessary steps to install OP-TEE on Juno starting from the scratch.

Best Regards.

**Comment by jbech-optee-adm** [comment]
@aminusamine, we released OP-TEE 2.1.0 stable yesterday and that was tested OK on Juno. Note however that it's a bare bone setup using a simple [initramfs based root fs](https://github.com/OP-TEE/build/blob/master/juno.mk#L131-L164). We've never tried to use Debian with OP-TEE on Juno, so I don't dare to say anything about that setup and currently we have no plans to look into that. If you however manage to get it working, we'd be more than happy receive and merge patches that would enable that particular setup.

Since this was OP-TEE + Juno was tested OK on the [official setup](https://github.com/OP-TEE/optee_os#57-juno) yesterday I'm closing this. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
