### ISSUE TITLE
optee-os compilation error with: make PLATFORM=hikey CFG_ARM64_core=y

### ISSUE THREAD

**Issue by chinnabha** [OP-TEE/optee_os#875]
Hi all,

I have aarch64 tool chain only (no aarch32 tool chain). And then I have compiled the optee_os for hikey with following command:
make PLATFORM=hikey CFG_ARM64_core=y

**The build has ended with the following error:**
       .    .    .      
  GEN     out/arm-plat-hikey/core/tee-init_load_addr.txt
  GEN     out/arm-plat-hikey/core/tee-init_mem_usage.txt
  **GEN     out/arm-plat-hikey/core/tee.bin**
  GEN     out/arm-plat-hikey/core/tee.symb_sizes
  CC      out/arm-plat-hikey/ta_arm32-lib/libutee/tee_api_property.o
/bin/bash: arm-linux-gnueabihf-gcc: command not found
mk/compile.mk:146: recipe for target 'out/arm-plat-hikey/ta_arm32-lib/libutee/tee_api_property.o' failed
make: *** [out/arm-plat-hikey/ta_arm32-lib/libutee/tee_api_property.o] Error 127

The build error is happening as I don't have aarch32 tool chain. But the tee_bin is already formed. 
1. Does it imply only 32-bit TAs are not supported? 
2. Can I use the output tee.bin to run 64-bit TAs irrespective of the above build error?
3. Is the above error expected with the above build command for Hikey?

Regards,
Chinnabha

**Comment by vchong** [comment]
Along with tee.bin, the development kit for both 64- and 32-bit TAs are generated as part of the optee_os build, hence the need to for both aarch64 and arm toolchain. Even if you only care about 64-bit, the build unfortunately generates the 32-bit dev kit first, and stopped with an error because it couldn't find the arm toolchain, so the 64-bit dev kit was never generated, which you will need if you want to build 64-bit TAs. You can probably hack the makefiles to just ignore the 32-bit dev kit build and jump to the 64-bit one, but probably much simpler to just download the arm toolchain.

If you build tee.bin as a 32-bit binary, obviously only 32-bit TAs are supported. If 64-bit, then both 32- and 64-bit TAs are supported.

**Comment by jforissier** [comment]
The build of the TA libraries is controlled by `ta-targets`, defined in the platform `conf.mk`. You may try `make PLATFORM=... ta-targets=ta_arn64` to override the value.

**Comment by chinnabha** [comment]
Thanks for the help. ta-target=ta_arm64 has solved my issue. I have couple more questions:

1. Along with tee.bin, the aarch64 compilation has also produced core-lib, ta_arm64-lib and export_ta-arm64 folders. Are these libraries needed in the final production build when integrating secure-os (tee.bin) with normal os via Arm Trusted Firmware? 

2. The ATF Secure-EL1 Payloads and dispatchers notes @https://github.com/ARM-software/arm-trusted-firmware/blob/master/docs/firmware-design.md#5--secure-el1-payloads-and-dispatchers says that ATF firmware will locate, load and execute the secure-os (BL32 image). Just the entry-point function of the secure-os needs to be registered via the function bl31_register_bl32_init( ). 
      A. Please tell me what is this entry function for aarch64 secure OS? 
      B. How to integrate the above libraries (core-lib and ta_arm64-lib) that were compiled as part of secure os with ATF?
      
Thanks,
Chinnabha
