### ISSUE TITLE
Does OPTEE have aarch64 support for the zynqmp platform?

### ISSUE THREAD

**Issue by dsblue** [OP-TEE/optee_os#889]
It is my understanding that ARMv8 CPUs can only support aarch64  execution if higher exception levels are also running at aarch64.  So, if OPTEE is running at EL3, then it should be running in aarch64 to support 64bit OSes.  Is this correct?

Does OPTEE support running in aarch64 mode on the zynqmp platform (looks like it is aarch32 by default)?

**Comment by sorenb-xlnx** [comment]
On ARMv8 platforms OP-TEE doesn't run in *EL3* but *secure EL1*. The secure monitor (ATF) runs in EL3.
I haven't tested running OP-TEE in aarch64 mode much since the ATF was handing off to EL1-S in aarch32 mode. That changed recently in upstream and I did some quick test, and AFAICT everything works in aarch64 mode too.

**Comment by jbech-linaro** [comment]
Hi @dsblue, besides OP-TEE not running in EL3 as pointed out by @sorenb-xlnx, you are right. I think a general answer to the first question could be found [here](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0500f/CHDDAHFB.html), which describes the different combinations possible on ARMv8-A.

**Comment by dsblue** [comment]
Thanks for the replies, that makes perfect sense.  I am used to OPTEE being the secure monitor and the secure OS on ARMv7.

**Comment by dsblue** [comment]
Sören, is adding CFG_ARM64_core=y the only change you had to make to enable a 64 bit build?

**Comment by sorenb-xlnx** [comment]
On Tue, 2016-07-05 at 14:14:46 -0700, Nathan Palmer wrote:
> Sören, is adding CFG_ARM64_core=y the only change you had to make to enable a 64 bit build?  

Yes, that's all I did. Depending on your build commandline/environment
you might have to specify ```CROSS_COMPILE64``` now additionally
to the 32-bit cross toolchain.
I use
```
make -rRj 16 \
      DEBUG=1 \
      O=${BUILDDIR}debug \
      CFG_TEE_CORE_LOG_LEVEL=2 \
      CROSS_COMPILE=${ARMV7A_TC_PATH}${ARMV7A_TC_PRFX} \
      CROSS_COMPILE64=${AARCH64_TC_PATH}${AARCH64_TC_PRFX} \
      CROSS_COMPILE32=${ARMV7A_TC_PATH}${ARMV7A_TC_PRFX} \
      CFG_TEE_TA_LOG_LEVEL=2 \
      CFG_TEE_CORE_LOG_LEVEL=2 \
      ARCH=arm \
      PLATFORM=zynqmp-zc1751_dc1 \
      CFG_ARM64_core=y \
      all cscope
```
to build OP-TEE.

	Sören

**Comment by dsblue** [comment]
Great, thanks.  That's similar to what I have but I am still unable to load OPTEE as the BL32 secure payload for the ATF boot process.  Could you also post the build command you used to build the ARM Trusted Firmware for the zynqmp platform?

**Comment by sorenb-xlnx** [comment]
The below command should do it. But, you need a version of the ATF that hands off in aarch64 mode. The [Xilinx tree still hands off in aarch32 mode](https://github.com/Xilinx/arm-trusted-firmware/blob/master/services/spd/opteed/opteed_main.c#L147). That [changed in upstream](https://github.com/ARM-software/arm-trusted-firmware/commit/29464f13f6f940abf7fb6218df05e38b0bb3f80f) recently. but we haven't pulled that in yet.
```
make -rR -j16   PLAT=zynqmp \
                        ERROR_DEPRECATED=1 \
                        RESET_TO_BL31=1 \
                        SPD=opteed \
                        cscope bl31 bl32
```

**Comment by dsblue** [comment]
That is pretty much the command that I am using and I am using the upstream ATF, (git master as of today).  So it is probably an issue somewhere else in my test flow, thanks for the info!

**Comment by vchong** [comment]
@dsblue See if your ATF has this [1] patch. If not, maybe try it and see if it helps.

https://github.com/linaro-swg/arm-trusted-firmware/commit/b287d5d71b604e7bb964302bb7053e46c1b9ebf7

**Comment by sorenb-xlnx** [comment]
@dsblue, do you mind me asking, what platform you're running on and what bootmode you use?
In general, there is not much QEMU testing as the Xilinx QEMU is quite diverged from upstream and doesn't have the needed support for EL1-S yet (especially not in aarch32 mode). I'm primarily running on silicon platforms.

Furthermore, since commit [b96f77c65ba5ce91091044b43704562e622a353b "zynqmp: FSBL->ATF handover"](https://github.com/ARM-software/arm-trusted-firmware/commit/b96f77c65ba5ce91091044b43704562e622a353b), the boot image needs to provide correct partition attributes (does not apply if you use JTAG bootmode).
