### ISSUE TITLE
Why is only HMACSHA256 based Key Derivation used?

### ISSUE THREAD

**Issue by elektrischermoench** [OP-TEE/optee_os#907]
Hi,

is there a special reason why only HMACSHA256 based KDF is used by OPTEE? Why not use
PBKDF2 or newer approaches like Argon2 (the winner of password hasing competition https://password-hashing.net/). Is it because the input for SSK generation is already an key, and for minimal boot-time?

Thanks Kai

**Comment by jbech-linaro** [comment]
Hi Kai, I guess you're talking about the derivation of the SSK? Because there are a few more [KDF's supported in OP-TEE](https://github.com/OP-TEE/optee_os/tree/master/documentation/extensions).

Regarding SSK and HMAC, we thought it was a good choice at the time and as you said, this is coming from a key and static string, so I'm not sure whether we gain much by using another KDF for that key. Using something like PBKDF2 would of course make brute much force harder, but at the same time it'd increase boot time. That is something that probably is negligible for the end user, but in production it could matter. Anyhow, it's easy to change if someone needs another KDF. But people/vendors having devices already in use needs to be careful and think twice before doing a change (so they don't end up with bricked devices).

Related ... the overall main concern I have regarding the SSK is that it's not well protected in case of a flaw in OP-TEE which eventually could give secure side kernel access. I.e, what I'm saying is that with only ARM TrustZone building blocks it's hard to make/derive write-only keys. One would like to have some kind of support similar to HSM and such (and that is something a lot of vendors add on top of TrustZone solutions).

**Comment by elektrischermoench** [comment]
Hi Joakim, you're right i'm talking about the derivation of the SSK. Sorry for the confusing. 

> I'm not sure whether we gain much by using another KDF for that key. Using something like PBKDF2 would of course make brute much force harder, but at the same time it'd increase boot time.

That was my conclusion after some thinking about it :). So if I would like to change the KDF for SSK I'm free to fork it and make a pull request. Maybe a compile flag could be a good solution for not brick up existing devices. 

> Related ... the overall main concern I have regarding the SSK is that it's not well protected in case of a flaw in OP-TEE which eventually could give secure side kernel access. I.e, what I'm saying is that with only ARM TrustZone building blocks it's hard to make/derive write-only keys.

So a good idea would be to modify the code and make use of a vendor specific HSM if availabe? Or are their any other ways to improve SSK-Security in general?

**Comment by elektrischermoench** [comment]
I think we can close this issue. Thanks a lot!
