### ISSUE TITLE
Increasing HEAP_SIZE of OS cause compile error on 64bit build

### ISSUE THREAD

**Issue by bradlin** [OP-TEE/optee_os#942]
Hi,

I want to increase the heap size of optee_os. I think it can modified by change HEAP_SIZE in platform_config.h. When I change it to a larger value(for example 512KB), the following compile error occurs.
optee_os/core/arch/arm/kernel/generic_entry_a64.S:109:(.text.boot+0x70): relocation truncated to fit: R_AARCH64_ADR_PREL_LO21 against symbol `_end' defined in .nozi section in out/arm-plat-kylin/core/tee.elf_
The Line 109 in generic_entry_a64.S is  "adr	x1, _end"

I use the same config in 32bit build and it is fine.
Do I  misunderstand anything for the 64bit build ?

**Comment by d3zd3z** [comment]
The 'adr' instruction loads a pc-relative address, and the way the instruction is encoded, the code must be within +/- 1MB of where the instruction is. By increasing the stack size, you've just moved the `_end` label further away, so that it can't load the address.

Can you try replacing the "`adr x1, _end`" with:
```
        adrp    x1, _end
        add     x1, :lo12:_end
```

if this works, we should probably incorporate this fix, since there isn't any inherent reason the code has to be within +/- 1MB of the `_end` label.

**Comment by bradlin** [comment]
Hi,
It works in my platform.
Thanks a lot.

**Comment by d3zd3z** [comment]
It seems to work fine at 512K, if I make the heap too large (say 2MB), the boot fails. Unsure if it is worth investigating, and probably not part of this issue.

**Comment by bradlin** [comment]
For your reference:
I try to enlarge it to 3MB, and it can boot on my platform.
