### ISSUE TITLE
Adding header files to TA source code

### ISSUE THREAD

**Issue by SimonWan** [OP-TEE/optee_os#943]
Hi there,

I just wanted to use some functions of `<sched.h>` and it could work for the client application easily while when I'm adding this file into TA's source code I got "error: sched.h: No such file or directory".

Could you please give me some advice for solving this issue?

Thanks.

**Comment by jforissier** [comment]
`<sched.h>` is a Linux header which defines functions/syscalls exported by the Linux libc/kernel. Therefore, it is not available to Trusted Applications, which run in a separate environment.

What are you trying to do that makes you think you need `<sched.h>` in the TA?

**Comment by SimonWan** [comment]
Hi jforissier,

Sorry I posted the question twice since I'm not sure I can get response.

Yesterday I was trying to use "sched_getcpu()" to get which CPU the TA is running on so I want to include the header file.

Furthermore, after I posted question I also tried the function sleep and it's fail too. Including the header file <unistd.h> is okay for the compiling while the function sleep is implicit declaration for the compiler. 

Does that means the unistd.h for TA is different from normal unistd.h?

Thank you very much for your help.

**Comment by d3zd3z** [comment]
The TAs run, in a sense, "below" the Linux kernel. None of the functionality available to normal Linux applications is available to them. However, it does provide some basic functionality (such as the unistd.h, and other headers) that are useful for writing basic apps. But, other concepts, such as threads, are not available.

It might be helpful if you could explain what problem you're having, instead of a possible solution (see the [XY Problem](http://www.perlmonks.org/?node=XY+Problem)). It's possible additional functionality to the TA would be useful, or there may be a better way of solving the problem you have.

**Comment by SimonWan** [comment]
Hi d3zd3z,

Thank you for the reply and the link for asking question. 

The problem I meet is I want to hold one CPU core in "secure state" as long as possible and I want to know which core it is.

Any suggestion is appreciated!

**Comment by d3zd3z** [comment]
> The problem I meet is I want to hold one CPU core in "secure state" as long as possible and I want to know which core it is.
Not to sound too nit-picky, but this still sounds like a description of a solution rather than the problem.

When this CPU core is held in the &ldquo;secure state&rdquo;, what will it be doing? After knowing which core is in this state, what will the system do with this knowledge?

The reason I'm trying to dig deeper into the problem is because OP-TEE doesn't really have a scheduler to handle this kind of thing.
