### ISSUE TITLE
An error about building the test code of libtomcrypt.

### ISSUE THREAD

**Issue by longyu1987** [OP-TEE/optee_os#95]
Hello everyone,
     I'm sorry to bother you again.I try to embed the libtomcrypt test code that locate in the directory 
core/lib/libtomcrypt/test/ to the TA.What my aim is to test the internal API of libtomcrypt in the OP-TEE.But,in the link stage,there is an error listed in the following. 
" gcc-linaro-arm-linux-gnueabihf-4.9-2014.05_linux/bin/../lib/gcc/arm-linux-gnueabihf/4.9.1/libgcc.a(_dvmd_lnx.o): In function `__aeabi_ldiv0':  (.text+0x6): undefined reference to `raise'  "
I don't know what I use the compiler is correct? Maybe this error is result from other reasons.I can't find the real reasons. So,I'm hope to get you help.Thanks.
    Best regards

**Comment by savage0** [comment]
there is a error——Rootfs copy cannot be done because ROOTFS_DIR is not defined
anyone know how to fix it？thanks！

**Comment by vchong** [comment]
Is it an error or just a warning? I've seen this before but the rootfs works just fine, i.e. the filesystem.cpio.gz file is actually being generated, just that the copy operation has failed due to ROOTFS_DIR being undefined. If you see filesystem.cpio.gz, then you can probably just use it. The build script might have to be updated though to resolve the error/warning.

**Comment by pascal-brand-st-dev** [comment]
This "warning" was emitted when compiling optee_client. It has been removed in https://github.com/OP-TEE/optee_client/pull/34. Is it this one, or something else?

**Comment by pascal-brand-st-dev** [comment]
@savage0 let me know if I can close the issue. Without any answer, I'll close it.
