### ISSUE TITLE
HiKey Kernel driver debugging

### ISSUE THREAD

**Issue by peterfeifanchen** [OP-TEE/optee_os#969]
I added some changes to the linux driver and also added an interceptor to intercept system calls for my project. I was wondering, is there a core dump that is generated when the kernel panics which would contain the printk statements I have in my driver (maybe even the printouts in the Trusted World too)? 

Right now it just flips to a blank screen and I have to restart the device. I have an idea what is wrong but would like a way to debug through some log of the dmesg before the kernel crashed (and even better, if I can get the printouts in the Trusted World too). 

Unluckily I burnt my UART adaptor board accidentally. Is the console suppose to give me output from both Trusted World and Normal World kernel? 

Thanks.

**Comment by vchong** [comment]
As far as UART is concerned, yes the console is supposed to give you output from both worlds.
The UART adaptor board is UART3, the default output port for both worlds. You can rebuild to use UART0. Just change https://github.com/OP-TEE/build/blob/master/hikey.mk#L12-L13 to 0s instead of 3s. The only catch is that you'll need a TTL-232RG-VREG1V8-WE cable, which costs more than the adaptor board, and also solder a 4-pin header to the board. See http://www.96boards.org/forums/topic/uart0-use-on-hikey-lemaker/ for more info.

**Comment by peterfeifanchen** [comment]
Thanks. I got a spare one so that works now. Just wondering, how does UART3 output both printk from Normal and Secure World? Is the device intermittently switched between the worlds or is it under a single world's control (I am assuming Secure World) and somehow the normal world writes to some shared memory that is actually the UART buffer?

**Comment by d3zd3z** [comment]
As far as I know, they just step on each other. It isn't the ideal situation, but the UART device is simple enough it tends to at least output everything properly.

**Comment by etiennec-linaro** [comment]
There is a constrains with uart tracing from optee. traces are slowly flushed. This can dramatically impact test setups where performance is critical and when verbose trace are expected to track some hidden issue. In such situation, having traces output using a RAM buffer give far better responsiveness of the optee.
[PR810]( https://github.com/OP-TEE/optee_os/pull/810) deals with such setup.

**Comment by peterfeifanchen** [comment]
Okay I'll look into that. Thanks!
