### ISSUE TITLE
[RPMB] About RPMB key 

### ISSUE THREAD

**Issue by airbak** [OP-TEE/optee_os#975]
As RPMB key can only be written one time, we will do it in a trusted environment like factory.
But tee_rpmb_init() is called in read and write each time,  it will be  leaked to REE when malicious attack.
Please give me some advise to avoid it, thanks.

**Comment by etiennec-linaro** [comment]
You could use a dedicated optee image for factory provisionning, including rpmb key write support, and use a specific optee image for end product with `tee_rpmb_write_key` support disabled (optee_os must be hacked for this).

If using the very same optee image for factory and end product, them your optee image must have some platform specific means to detect it operates in a trusted environment and can safely expose the rpmb key to the non-secure world.

**Comment by airbak** [comment]
Is there plan to write RPMB KEY directly in the secure word?

**Comment by etienne-lms** [comment]
I don't think so. It would need integration of an emmc driver inside optee core.
Actually, a firmware dedicated to factory provisionning could be used to program the RPMB, completely outside of optee and even tz. It would only need to run the same derivation scheme to generate the key (as optee core will generate it) and program the emmc.

**Comment by bzhu5** [comment]
I assumed that the Key programming should be done by a Trusted firmware, whenever it detects that the RPMB key is not yet programmed, then the trusted firmware will attempt to generate a key and program the key (in plaintext) into RPMB device. Also, we need to consider programming a new different key into a new device if the eMMC (or UFS, or NVMe SSD storage) is replaced in the field due to device malfunction. If we only do it in factory (safe environment), then the key re-programming cannot happen in the field after replacement.

How do you think? and what's the best practice nowadays?

By the way, see this link for my experience on RPMB, welcome feedback and further discussion.
https://lsseu2018.sched.com/event/G3LG

**Comment by jenswi-linaro** [comment]
If you program the key into every device that doesn't yet have a key programmed there's a risk of leaking the key. Even if you base the key on the serial number of the device, that serial number can be faked.

**Comment by bzhu5** [comment]
@jenswi-linaro 
not quite understanding this, did you mean "program the same key"? but actually, we attempts to programming the different key into different device.
> If you program the key into every device that doesn't yet have a key programmed there's a risk of leaking the key


if we're using the alg. like this: RPMB key = KDF (unique device base key, "serial number") to generate the key, my understanding is that someone solders a new "faked" emmc with the "faked serial number", which is programed with the same "serial number" of the previous eMMC device that is to be attacked?
> Even if you base the key on the serial number of the device, that serial number can be faked.

is this in the scope of threat model?

how do you solve this? in other words, the question is what things are required to bind with RPMB key? i assumed that 1). the RPMB device programed in one device cannot be used in another device, 2). in the same device, if an old RPMB device is replaced, then the new RPMB device should be programmed with a new different Key.  anything else? do you want to bind the RPMB key with the CPU?

**Comment by jenswi-linaro** [comment]
In the design used with OP-TEE we're accessing eMMC via non-secure world in order to avoid other synchronization problems when accessing the shared resource. This means that non-secure world easily can emulate an unprogrammed RPMB, in fact we're even using that setup to during test.

Let's say that you have a programmed RPMB with a serial number 12345, the key used for that device will be a generated with a function taking Hardware unique key and the serial number 12345 as input.

Now you replace non-secure world with software that will emulate and unprogrammed RPMB device with serial number 12345. If OP-TEE tries to write a new key into that device the key is revealed.

Programming the key into RPMB has to be something that's only done in a controlled environment. Unless there's another way of trusting the device.

**Comment by bzhu5** [comment]
accessing eMMC over non-secure world driver does make sense, our project uses the same approach: https://github.com/trusty-ia/trusty_app_storage 

However, in our case, Trusty (TEE) on x86 platform won't send RPMB key to non-secure world, which means that Trusty is not designed to program the RPMB Key no matter for RPMB emulation or physical/real RPMB device. we're trying to figure out other ways for our platform to program the RPMB key in a controlled/safe environment.

Also, in our case, we're using RPMB emulation too in non-secure world for testing/validation on development stage.

**Comment by bzhu5** [comment]
on ARM platform, can ARM Trusted Firmware (ATF: https://github.com/ARM-software/arm-trusted-firmware) be responsible for programming the RPMB key even before OP-TEE starts? since I assumed that ATF is in trusted path, and it should have eMMC driver.

**Comment by jenswi-linaro** [comment]
I guess it's possible extend ARM Trusted Firmware to program the key. However, there's still the problem with replacing the RPMB, either by soldering or by other means. It will be a bit harder for an attacker to obtain the key, but I don't suppose it's that hard to sniff the communication with the eMMC .

**Comment by bzhu5** [comment]
right. Advanced hardware attack like "sniff the communication with the eMMC" is always a threat unless we can ensure 100% safe environment for key programming.

@jenswi-linaro  by the way, i just dropped you an email, if you're interested in, please let me know. thanks.

**Comment by jenswi-linaro** [comment]
"pretty small" is in the eye of the beholder. It could be a preferred attack path compared to other options like side channel attacks etc. It is better than nothing though.

**Comment by dashemsec** [comment]
Hi for avoid creating two set of OPTEE image for rpmb, i have introduced a concept here https://github.com/OP-TEE/optee_os/issues/2887
