### ISSUE TITLE
About CryptoCell

### ISSUE THREAD

**Issue by fanguannan0706** [OP-TEE/optee_os#987]
Hi,
I find something about CryptoCell from [ARM](http://www.arm.com/zh/products/processors/technologies/trustzone/index.php). It seems like a hardware component for crypto support. But I read the docs in optee_os, it says crypto algorithms are based on LibTomCrypt. So do OPTEE use CryptoCell? And Is there a CryptoCell on Hikey?

**Comment by d3zd3z** [comment]
CryptoCell looks like it covers multiple components that can be included in an SoC.

As far as HiKey goes, we should be using the HW support for AES and SHA1/SHA256. This support is part of the included LibTomCrypt. Look at `core/lib/libtomcrypt/src/ciphers/aes_arm64_ce.c` and the neighboring assembly file. Some of this is changed a bit with some recent patches to also support 32-bit builds as well.

**Comment by fanguannan0706** [comment]
Thank you for answer!
And I have another question."During OP-TEE initialization, a 128-bit AES Secure Storage Key (SSK) is derived from a Hardware Unique Key (HUK). It is kept in secure memory and never written to disk. " So every time OP-TEE inits, the SSK is same ? If I know the board's HUK, I can predict the SSK?

**Comment by jforissier** [comment]
@fanguannan0706 yes. The SSK has to be the same each time OP-TEE inits, otherwise it would be impossible to decrypt the file keys.
If your platform has a crypto accelerator capable of using a HUK without ever revealing it to software (which is quite common), it's better, because leaking the HUK could compromise many keys derived from it. But currently we don't support any such accelerator upstream so the SSK derivation is not written with this in mind.

**Comment by fanguannan0706** [comment]
So the SSK is not enough safe now, right? @jforissier

**Comment by jforissier** [comment]
In my opinion, the SSK is safe enough. It is the HUK that is not safe enough.
Suppose an attacker finds a way to hack into the TEE and read the secure memory. Then he can read the SSK, no matter how it was derived (either as we do know, or with a crypto accelerator instead). But, with our current implementation the attacker could probably also read the HUK. This would not be possible with a HW accelerator that does not reveal the key to SW. Revealing the HUK is a problem because the attacker can conduct offline attacks on the device (such as: dictionary-based attacks on passwords for applications that derive their key from a password and the HUK).

**Comment by d3zd3z** [comment]
I think the only way that is secure is to have the HUK that is never revealed to software, and is also not used to derive another key. This would be a bit of a change, because even file data would have to be encrypted by this hardware using the HUK.

The next best is if the HUK is not readable through normal means. I would guess a compromise that is able to read the SSK from secure memory (say jtag) would also be able to read this HUK.

**Comment by jbech-linaro** [comment]
David and Jerome more or less already answered it, but I just want to chime in. In OP-TEE today we use a stubbed HUK, which is totally unsecure and therefore the SSK is also unsecure. The idea is of course that the OEM shall replace the stubbed HUK with a proper implementation that ideally never ever reveal the HUK to software. There exist hardware solutions that are capable of that. I.e, you could derive new keys by calling a function in dedicated hardware that derives a new key based on a HUK that never ever is visible to software.

Even though there are quite a few devices and platforms supported in OP-TEE as of now, we who are running the project haven't had access to hardware with such capabilities as mentioned above. If we had one, then we could re-work the HUK handling and SSK derivation. But until then, that is something that is left to the OEM (actually HiKey has CryptoCell, but currently we have no access to it, but we're trying to work with a few companies trying to get that access, but I cannot promise anything). Having that said, we should create a porting guideline that explains things like this.

**Comment by jbech-optee-adm** [comment]
We're closing this issue since the question has been answered. If you however feel that you have additional questions or still thinks this is an issue, please feel free to re-open the issue again.
